-- A3 FINANCE 1.3.1 - COMPLETE DATABASE INSTALLER
-- Fixes ERROR 42P01: relation "public.driver_signup_links" does not exist.
--
-- Use this file when migrations 020/021/023 were not previously installed.
-- It installs, in order:
--   020 Driver Network and company-locked signup
--   021 Driver vehicle-document uploads
--   023 Driver login-link repair
--   024 Company-scoped administrators and short signup links
--
-- Safe to run after migrations 000-019. The included migrations are designed
-- to be repeatable. Run this entire file in Supabase SQL Editor.

-- ------------------------------------------------------------
-- BASE DATABASE PREFLIGHT
-- ------------------------------------------------------------
do $$
begin
  if to_regclass('public.companies') is null
     or to_regclass('public.profiles') is null
     or to_regclass('public.user_company_access') is null
     or to_regclass('public.drivers') is null
     or to_regclass('public.customers') is null then
    raise exception 'A3 Finance base tables are missing. Install migrations 000-019 before this complete installer.';
  end if;

  if to_regprocedure('public.set_updated_at()') is null
     or to_regprocedure('public.is_app_administrator()') is null then
    raise exception 'A3 Finance Phase 10 functions are missing. Install migration 019 before this complete installer.';
  end if;
end;
$$;

-- ============================================================
-- MIGRATION 020
-- ============================================================
-- A3 MANAGEMENT - PHASE 11
-- DRIVER NETWORK, MULTI-COMPANY LINKS, CLIENT/CUSTOMER LINKS AND COMPANY-LOCKED SIGNUP
-- Run after migration 019. Safe to run more than once.

begin;

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- 1. DRIVER TO LIMOUSINE COMPANY NETWORK
-- ------------------------------------------------------------
create table if not exists public.driver_company_links (
  id bigint generated by default as identity primary key,
  driver_id bigint not null references public.drivers(id) on delete cascade,
  company_id bigint not null references public.companies(id) on delete restrict,
  is_primary boolean not null default false,
  membership_status text not null default 'active'
    check (membership_status in ('active', 'inactive', 'suspended')),
  joined_at date not null default current_date,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (driver_id, company_id)
);

create index if not exists driver_company_links_company_idx
  on public.driver_company_links(company_id, membership_status, driver_id);
create index if not exists driver_company_links_driver_idx
  on public.driver_company_links(driver_id, membership_status, company_id);
create unique index if not exists driver_company_links_one_primary_uidx
  on public.driver_company_links(driver_id)
  where is_primary = true and membership_status = 'active';

create or replace function public.validate_driver_company_link()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  selected_company_type text;
  selected_company_status text;
begin
  select company_type, status
    into selected_company_type, selected_company_status
  from public.companies
  where id = new.company_id;

  if selected_company_type is null then
    raise exception 'Selected company was not found.';
  end if;

  if selected_company_type <> 'limousine' then
    raise exception 'Drivers can only be linked through the Driver Network to limousine companies.';
  end if;

  if selected_company_status <> 'active' then
    raise exception 'The selected limousine company is inactive.';
  end if;

  if new.is_primary and new.membership_status = 'active' then
    update public.driver_company_links
       set is_primary = false,
           updated_at = now()
     where driver_id = new.driver_id
       and id <> coalesce(new.id, 0)
       and is_primary = true;
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists driver_company_links_validate on public.driver_company_links;
create trigger driver_company_links_validate
before insert or update on public.driver_company_links
for each row execute function public.validate_driver_company_link();

create or replace function public.sync_primary_driver_company()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.is_primary and new.membership_status = 'active' then
    update public.drivers
       set company_id = new.company_id,
           updated_at = now()
     where id = new.driver_id
       and company_id is distinct from new.company_id;
  end if;
  return new;
end;
$$;

drop trigger if exists driver_company_links_sync_primary on public.driver_company_links;
create trigger driver_company_links_sync_primary
after insert or update on public.driver_company_links
for each row execute function public.sync_primary_driver_company();

drop trigger if exists driver_company_links_set_updated_at on public.driver_company_links;
create trigger driver_company_links_set_updated_at
before update on public.driver_company_links
for each row execute function public.set_updated_at();

-- Backfill each existing driver whose current company is a limousine company.
insert into public.driver_company_links (
  driver_id,
  company_id,
  is_primary,
  membership_status,
  joined_at,
  notes
)
select
  driver.id,
  driver.company_id,
  true,
  case when driver.status = 'active' then 'active' else 'inactive' end,
  coalesce(driver.created_at::date, current_date),
  'Migrated from the original driver company assignment.'
from public.drivers driver
join public.companies company on company.id = driver.company_id
where company.company_type = 'limousine'
on conflict (driver_id, company_id) do update
set is_primary = excluded.is_primary,
    membership_status = excluded.membership_status,
    updated_at = now();

-- ------------------------------------------------------------
-- 2. DRIVER TO CLIENT / CUSTOMER LINKS
-- Company-type customers are shown as Clients. Individual customers are
-- shown as Customers. The relationship type is assigned automatically.
-- ------------------------------------------------------------
create table if not exists public.driver_customer_links (
  id bigint generated by default as identity primary key,
  driver_id bigint not null references public.drivers(id) on delete cascade,
  company_id bigint not null references public.companies(id) on delete restrict,
  customer_id bigint not null references public.customers(id) on delete cascade,
  relationship_type text not null default 'client'
    check (relationship_type in ('client', 'customer')),
  link_status text not null default 'active'
    check (link_status in ('active', 'inactive')),
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (driver_id, customer_id)
);

create index if not exists driver_customer_links_driver_idx
  on public.driver_customer_links(driver_id, link_status, company_id);
create index if not exists driver_customer_links_customer_idx
  on public.driver_customer_links(customer_id, link_status, driver_id);
create index if not exists driver_customer_links_company_idx
  on public.driver_customer_links(company_id, link_status, driver_id);

create or replace function public.validate_driver_customer_link()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  selected_customer_company bigint;
  selected_customer_type text;
begin
  select company_id, customer_type
    into selected_customer_company, selected_customer_type
  from public.customers
  where id = new.customer_id;

  if selected_customer_company is null then
    raise exception 'Selected client or customer was not found.';
  end if;

  if selected_customer_company <> new.company_id then
    raise exception 'The selected client or customer does not belong to this company.';
  end if;

  if not exists (
    select 1
    from public.driver_company_links link
    where link.driver_id = new.driver_id
      and link.company_id = new.company_id
      and link.membership_status = 'active'
  ) then
    raise exception 'The driver must first be linked to this limousine company.';
  end if;

  new.relationship_type := case
    when selected_customer_type = 'individual' then 'customer'
    else 'client'
  end;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists driver_customer_links_validate on public.driver_customer_links;
create trigger driver_customer_links_validate
before insert or update on public.driver_customer_links
for each row execute function public.validate_driver_customer_link();

drop trigger if exists driver_customer_links_set_updated_at on public.driver_customer_links;
create trigger driver_customer_links_set_updated_at
before update on public.driver_customer_links
for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- 3. COMPANY-SPECIFIC PUBLIC DRIVER SIGNUP LINKS
-- The public token determines the company. Applicants cannot choose or alter it.
-- ------------------------------------------------------------
create table if not exists public.driver_signup_links (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public.companies(id) on delete cascade,
  public_token uuid not null default gen_random_uuid() unique,
  link_name text not null default 'Driver Recruitment',
  status text not null default 'active'
    check (status in ('active', 'inactive')),
  expires_at timestamptz,
  max_applications integer check (max_applications is null or max_applications > 0),
  application_count integer not null default 0 check (application_count >= 0),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists driver_signup_links_company_idx
  on public.driver_signup_links(company_id, status, created_at desc);
create index if not exists driver_signup_links_token_idx
  on public.driver_signup_links(public_token);

create or replace function public.validate_driver_signup_link()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  selected_company_type text;
  selected_company_status text;
begin
  select company_type, status
    into selected_company_type, selected_company_status
  from public.companies
  where id = new.company_id;

  if selected_company_type is null then
    raise exception 'Selected company was not found.';
  end if;
  if selected_company_type <> 'limousine' then
    raise exception 'Driver signup links can only be created for limousine companies.';
  end if;
  if (tg_op = 'INSERT' or new.company_id is distinct from old.company_id)
     and selected_company_status <> 'active' then
    raise exception 'Driver signup links require an active limousine company.';
  end if;

  new.link_name := coalesce(nullif(btrim(new.link_name), ''), 'Driver Recruitment');
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists driver_signup_links_validate on public.driver_signup_links;
create trigger driver_signup_links_validate
before insert or update on public.driver_signup_links
for each row execute function public.validate_driver_signup_link();

drop trigger if exists driver_signup_links_set_updated_at on public.driver_signup_links;
create trigger driver_signup_links_set_updated_at
before update on public.driver_signup_links
for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- 4. DRIVER SIGNUP APPLICATIONS
-- ------------------------------------------------------------
create table if not exists public.driver_signup_applications (
  id bigint generated by default as identity primary key,
  application_no text unique,
  signup_link_id uuid not null references public.driver_signup_links(id) on delete restrict,
  company_id bigint not null references public.companies(id) on delete restrict,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'withdrawn')),
  driver_id bigint references public.drivers(id) on delete set null,

  full_name text not null,
  phone text not null,
  contact_email text not null,
  address text,
  nric_passport text,
  nationality text,
  date_of_birth date,
  licence_no text,
  licence_class text,
  licence_expiry date,
  emergency_contact_name text,
  emergency_contact_phone text,
  vehicle_make text,
  vehicle_model text,
  vehicle_plate text,
  vehicle_type text,
  bank_name text,
  bank_account_name text,
  bank_account_no text,
  paynow_type text check (paynow_type is null or paynow_type in ('mobile', 'nric', 'uen', 'other')),
  paynow_no text,
  notes text,
  consent_confirmed boolean not null default false,

  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  review_notes text,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists driver_signup_applications_company_idx
  on public.driver_signup_applications(company_id, status, submitted_at desc);
create index if not exists driver_signup_applications_link_idx
  on public.driver_signup_applications(signup_link_id, status, submitted_at desc);
create unique index if not exists driver_signup_applications_pending_email_uidx
  on public.driver_signup_applications(company_id, lower(contact_email))
  where status = 'pending';

create or replace function public.prepare_driver_signup_application()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  selected_link public.driver_signup_links%rowtype;
begin
  select * into selected_link
  from public.driver_signup_links
  where id = new.signup_link_id;

  if selected_link.id is null then
    raise exception 'Driver signup link was not found.';
  end if;

  if tg_op = 'INSERT' then
    if selected_link.status <> 'active' then
      raise exception 'This driver signup link is inactive.';
    end if;
    if selected_link.expires_at is not null and selected_link.expires_at <= now() then
      raise exception 'This driver signup link has expired.';
    end if;
    if selected_link.max_applications is not null
       and selected_link.application_count >= selected_link.max_applications then
      raise exception 'This driver signup link has reached its application limit.';
    end if;
  end if;

  new.company_id := selected_link.company_id;
  new.full_name := btrim(new.full_name);
  new.phone := btrim(new.phone);
  new.contact_email := lower(btrim(new.contact_email));
  new.vehicle_plate := nullif(upper(btrim(coalesce(new.vehicle_plate, ''))), '');
  new.updated_at := now();

  if new.full_name = '' or new.phone = '' or new.contact_email = '' then
    raise exception 'Name, phone and email are required.';
  end if;
  if not new.consent_confirmed then
    raise exception 'Consent confirmation is required.';
  end if;

  return new;
end;
$$;

drop trigger if exists driver_signup_applications_prepare on public.driver_signup_applications;
create trigger driver_signup_applications_prepare
before insert or update on public.driver_signup_applications
for each row execute function public.prepare_driver_signup_application();

create or replace function public.assign_driver_application_number()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.application_no is null or btrim(new.application_no) = '' then
    new.application_no := 'DRVAPP-' || lpad(new.id::text, 6, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists driver_signup_applications_assign_number on public.driver_signup_applications;
create trigger driver_signup_applications_assign_number
before insert on public.driver_signup_applications
for each row execute function public.assign_driver_application_number();

create or replace function public.count_driver_signup_application()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  update public.driver_signup_links
     set application_count = application_count + 1,
         updated_at = now()
   where id = new.signup_link_id;
  return new;
end;
$$;

drop trigger if exists driver_signup_applications_count on public.driver_signup_applications;
create trigger driver_signup_applications_count
after insert on public.driver_signup_applications
for each row execute function public.count_driver_signup_application();

drop trigger if exists driver_signup_applications_set_updated_at on public.driver_signup_applications;
create trigger driver_signup_applications_set_updated_at
before update on public.driver_signup_applications
for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- 5. SECURITY
-- Public signup is handled only through the server API using the service role.
-- No anonymous table access is granted.
-- ------------------------------------------------------------
alter table public.driver_company_links enable row level security;
alter table public.driver_customer_links enable row level security;
alter table public.driver_signup_links enable row level security;
alter table public.driver_signup_applications enable row level security;

grant select, insert, update, delete on
  public.driver_company_links,
  public.driver_customer_links,
  public.driver_signup_links,
  public.driver_signup_applications
  to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Driver company links: administrators manage; drivers can see their own network.
drop policy if exists driver_company_links_select_admin_or_self on public.driver_company_links;
create policy driver_company_links_select_admin_or_self on public.driver_company_links
for select to authenticated
using (
  public.is_app_administrator()
  or exists (
    select 1 from public.drivers driver
    where driver.id = driver_company_links.driver_id
      and driver.auth_user_id = auth.uid()
  )
);

drop policy if exists driver_company_links_manage_admin on public.driver_company_links;
create policy driver_company_links_manage_admin on public.driver_company_links
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

-- Driver customer links: administrators manage; drivers can see their own links.
drop policy if exists driver_customer_links_select_admin_or_self on public.driver_customer_links;
create policy driver_customer_links_select_admin_or_self on public.driver_customer_links
for select to authenticated
using (
  public.is_app_administrator()
  or exists (
    select 1 from public.drivers driver
    where driver.id = driver_customer_links.driver_id
      and driver.auth_user_id = auth.uid()
  )
);

drop policy if exists driver_customer_links_manage_admin on public.driver_customer_links;
create policy driver_customer_links_manage_admin on public.driver_customer_links
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

-- Signup links and applications are administrator-only inside the authenticated app.
drop policy if exists driver_signup_links_admin on public.driver_signup_links;
create policy driver_signup_links_admin on public.driver_signup_links
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

drop policy if exists driver_signup_applications_admin on public.driver_signup_applications;
create policy driver_signup_applications_admin on public.driver_signup_applications
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());


-- Phase 10 permission matrix extension for the new administrator module.
insert into public.finance_module_permissions(
  role_name,
  module_name,
  can_view,
  can_create,
  can_edit,
  can_approve
)
select
  role_name,
  'driver_network',
  role_name = 'administrator',
  role_name = 'administrator',
  role_name = 'administrator',
  role_name = 'administrator'
from (values ('administrator'), ('finance'), ('viewer'), ('user')) roles(role_name)
on conflict (role_name, module_name) do update
set can_view = excluded.can_view,
    can_create = excluded.can_create,
    can_edit = excluded.can_edit,
    can_approve = excluded.can_approve,
    updated_at = now();

notify pgrst, 'reload schema';
commit;

-- ============================================================
-- MIGRATION 021
-- ============================================================
-- A3 Finance Phase 11.1
-- Secure vehicle-document uploads for company-locked driver recruitment.
-- Run after 020_driver_network_and_company_signup.sql.

begin;

-- ------------------------------------------------------------
-- 1. APPLICATION UPLOAD SESSION SUPPORT
-- ------------------------------------------------------------
alter table public.driver_signup_applications
  add column if not exists submission_token uuid not null default gen_random_uuid(),
  add column if not exists upload_completed_at timestamptz;

create unique index if not exists driver_signup_applications_submission_token_uidx
  on public.driver_signup_applications(submission_token);

-- Email is useful but the recruitment requirement is contact number first.
alter table public.driver_signup_applications
  alter column contact_email drop not null;

-- Replace the old status constraint so a private upload session can exist before
-- the completed application is released to the administrator inbox.
do $$
declare
  constraint_row record;
begin
  for constraint_row in
    select constraint_name
    from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'driver_signup_applications'
      and constraint_type = 'CHECK'
      and constraint_name in (
        select conname
        from pg_constraint
        where conrelid = 'public.driver_signup_applications'::regclass
          and contype = 'c'
          and pg_get_constraintdef(oid) ilike '%status%'
      )
  loop
    execute format(
      'alter table public.driver_signup_applications drop constraint if exists %I',
      constraint_row.constraint_name
    );
  end loop;
end;
$$;

alter table public.driver_signup_applications
  add constraint driver_signup_applications_status_check
  check (status in ('uploading', 'pending', 'approved', 'rejected', 'withdrawn'));

-- Prevent duplicate active applications when an email is supplied, while still
-- allowing applicants who only provide a contact number.
drop index if exists public.driver_signup_applications_pending_email_uidx;
create unique index driver_signup_applications_pending_email_uidx
  on public.driver_signup_applications(company_id, lower(contact_email))
  where status in ('uploading', 'pending') and contact_email is not null;

update public.driver_signup_applications
set upload_completed_at = coalesce(upload_completed_at, submitted_at)
where status <> 'uploading';

-- ------------------------------------------------------------
-- 2. VEHICLE DOCUMENT REGISTER
-- ------------------------------------------------------------
create table if not exists public.driver_application_documents (
  id uuid primary key default gen_random_uuid(),
  application_id bigint not null
    references public.driver_signup_applications(id) on delete cascade,
  company_id bigint not null references public.companies(id) on delete restrict,
  driver_id bigint references public.drivers(id) on delete set null,
  document_type text not null default 'vehicle_document'
    check (document_type in (
      'vehicle_document',
      'vehicle_log_card',
      'vehicle_insurance',
      'vehicle_inspection',
      'vehicle_photo',
      'other'
    )),
  storage_bucket text not null default 'driver-documents'
    check (storage_bucket = 'driver-documents'),
  storage_path text not null unique,
  original_filename text not null,
  mime_type text not null
    check (mime_type in ('image/png', 'image/jpeg', 'image/webp', 'application/pdf')),
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 10485760),
  upload_status text not null default 'pending'
    check (upload_status in ('pending', 'uploaded', 'verified', 'rejected')),
  uploaded_at timestamptz,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  review_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists driver_application_documents_application_idx
  on public.driver_application_documents(application_id, created_at);
create index if not exists driver_application_documents_driver_idx
  on public.driver_application_documents(driver_id, created_at desc)
  where driver_id is not null;
create index if not exists driver_application_documents_company_idx
  on public.driver_application_documents(company_id, created_at desc);

create or replace function public.prepare_driver_application_document()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  selected_application public.driver_signup_applications%rowtype;
  required_prefix text;
begin
  select * into selected_application
  from public.driver_signup_applications
  where id = new.application_id;

  if selected_application.id is null then
    raise exception 'Driver application was not found.';
  end if;

  new.company_id := selected_application.company_id;
  new.driver_id := coalesce(new.driver_id, selected_application.driver_id);
  new.original_filename := btrim(new.original_filename);
  new.storage_path := btrim(new.storage_path);
  new.updated_at := now();

  required_prefix := format(
    'applications/%s/%s/',
    selected_application.company_id,
    selected_application.id
  );

  if new.original_filename = '' then
    raise exception 'The original vehicle document filename is required.';
  end if;
  if new.storage_path = '' or position(required_prefix in new.storage_path) <> 1 then
    raise exception 'Vehicle document path does not match the locked application company.';
  end if;

  return new;
end;
$$;

drop trigger if exists driver_application_documents_prepare
  on public.driver_application_documents;
create trigger driver_application_documents_prepare
before insert or update on public.driver_application_documents
for each row execute function public.prepare_driver_application_document();

drop trigger if exists driver_application_documents_set_updated_at
  on public.driver_application_documents;
create trigger driver_application_documents_set_updated_at
before update on public.driver_application_documents
for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- 3. EXACT PUBLIC APPLICATION REQUIREMENTS
-- ------------------------------------------------------------
create or replace function public.prepare_driver_signup_application()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  selected_link public.driver_signup_links%rowtype;
  requires_submission_validation boolean := false;
begin
  select * into selected_link
  from public.driver_signup_links
  where id = new.signup_link_id
  for update;

  if selected_link.id is null then
    raise exception 'Driver signup link was not found.';
  end if;

  requires_submission_validation := tg_op = 'INSERT';
  if tg_op = 'UPDATE' then
    requires_submission_validation :=
      new.status = 'pending' and old.status is distinct from 'pending';
  end if;

  if requires_submission_validation then
    if selected_link.status <> 'active' then
      raise exception 'This driver signup link is inactive.';
    end if;
    if selected_link.expires_at is not null and selected_link.expires_at <= now() then
      raise exception 'This driver signup link has expired.';
    end if;
    if selected_link.max_applications is not null
       and selected_link.application_count >= selected_link.max_applications then
      raise exception 'This driver signup link has reached its application limit.';
    end if;
  end if;

  new.company_id := selected_link.company_id;
  new.full_name := btrim(coalesce(new.full_name, ''));
  new.phone := btrim(coalesce(new.phone, ''));
  new.contact_email := nullif(lower(btrim(coalesce(new.contact_email, ''))), '');
  new.vehicle_model := nullif(btrim(coalesce(new.vehicle_model, '')), '');
  new.vehicle_plate := nullif(upper(btrim(coalesce(new.vehicle_plate, ''))), '');
  new.emergency_contact_name := nullif(btrim(coalesce(new.emergency_contact_name, '')), '');
  new.emergency_contact_phone := nullif(btrim(coalesce(new.emergency_contact_phone, '')), '');
  new.bank_name := nullif(btrim(coalesce(new.bank_name, '')), '');
  new.bank_account_name := nullif(btrim(coalesce(new.bank_account_name, '')), '');
  new.bank_account_no := nullif(btrim(coalesce(new.bank_account_no, '')), '');
  new.paynow_no := nullif(btrim(coalesce(new.paynow_no, '')), '');
  new.updated_at := now();

  -- Enforce the requested recruitment fields when the application is first
  -- created or when an upload session is finalized into the review inbox.
  if requires_submission_validation then
    if new.full_name = '' then
      raise exception 'Name is required.';
    end if;
    if new.phone = '' then
      raise exception 'Contact number is required.';
    end if;
    if new.vehicle_model is null then
      raise exception 'Car model is required.';
    end if;
    if new.vehicle_plate is null then
      raise exception 'Car plate is required.';
    end if;
    if new.emergency_contact_name is null or new.emergency_contact_phone is null then
      raise exception 'Emergency contact name and number are required.';
    end if;
    if new.bank_name is null
       or new.bank_account_name is null
       or new.bank_account_no is null then
      raise exception 'Bank name, account name and account number are required.';
    end if;
    if new.paynow_type is null or new.paynow_no is null then
      raise exception 'PayNow type and number are required.';
    end if;
    if not new.consent_confirmed then
      raise exception 'Consent confirmation is required.';
    end if;
  end if;

  return new;
end;
$$;

-- Count only complete applications. Upload sessions do not consume a link's
-- application limit unless they are successfully finalized.
create or replace function public.count_driver_signup_application()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.status = 'pending' then
    update public.driver_signup_links
       set application_count = application_count + 1,
           updated_at = now()
     where id = new.signup_link_id;
  end if;
  return new;
end;
$$;

drop trigger if exists driver_signup_applications_count
  on public.driver_signup_applications;
create trigger driver_signup_applications_count
after insert on public.driver_signup_applications
for each row execute function public.count_driver_signup_application();

create or replace function public.count_finalized_driver_signup_application()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if old.status <> 'pending' and new.status = 'pending' then
    update public.driver_signup_links
       set application_count = application_count + 1,
           updated_at = now()
     where id = new.signup_link_id;
  end if;
  return new;
end;
$$;

drop trigger if exists driver_signup_applications_count_finalized
  on public.driver_signup_applications;
create trigger driver_signup_applications_count_finalized
after update of status on public.driver_signup_applications
for each row execute function public.count_finalized_driver_signup_application();

-- ------------------------------------------------------------
-- 4. PRIVATE STORAGE AND ACCESS
-- ------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'driver-documents',
  'driver-documents',
  false,
  10485760,
  array['image/png', 'image/jpeg', 'image/webp', 'application/pdf']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

alter table public.driver_application_documents enable row level security;

drop policy if exists driver_application_documents_admin_all
  on public.driver_application_documents;
create policy driver_application_documents_admin_all
on public.driver_application_documents
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

drop policy if exists driver_application_documents_driver_read
  on public.driver_application_documents;
create policy driver_application_documents_driver_read
on public.driver_application_documents
for select to authenticated
using (
  exists (
    select 1
    from public.drivers driver
    where driver.id = driver_application_documents.driver_id
      and driver.auth_user_id = auth.uid()
  )
);

-- The original driver-document policy covers paths under drivers/<id>/... .
-- Recruitment uploads use applications/<company>/<application>/..., so this
-- additional private policy follows the metadata link established on approval.
drop policy if exists driver_application_vehicle_documents_select_self
  on storage.objects;
create policy driver_application_vehicle_documents_select_self
on storage.objects
for select to authenticated
using (
  bucket_id = 'driver-documents'
  and exists (
    select 1
    from public.driver_application_documents document
    join public.drivers driver on driver.id = document.driver_id
    where document.storage_path = storage.objects.name
      and driver.auth_user_id = auth.uid()
  )
);

grant select, insert, update, delete
  on public.driver_application_documents to authenticated;

notify pgrst, 'reload schema';
commit;

select
  '021 driver vehicle document uploads installed' as result,
  (select count(*) from public.driver_application_documents) as registered_documents;

-- ============================================================
-- MIGRATION 023
-- ============================================================
-- A3 FINANCE - DRIVER LOGIN LINK REPAIR V2
-- Safe to run more than once.
-- Fixes: ON CONFLICT DO UPDATE command cannot affect row a second time.
-- Only exact, unambiguous email matches are linked. Privileged accounts are
-- never converted into driver accounts.

begin;

-- Ensure each auth user has a profile row. Skip an email update only when the
-- same normalized email is already owned by a different profile.
insert into public.profiles (id, email, full_name)
select
  auth_user.id,
  lower(btrim(auth_user.email)),
  coalesce(
    nullif(btrim(auth_user.raw_user_meta_data ->> 'full_name'), ''),
    split_part(auth_user.email, '@', 1)
  )
from auth.users auth_user
where auth_user.email is not null
  and not exists (
    select 1
    from public.profiles other_profile
    where other_profile.id <> auth_user.id
      and other_profile.email is not null
      and lower(btrim(other_profile.email)) = lower(btrim(auth_user.email))
  )
on conflict (id) do update
set email = excluded.email,
    updated_at = now();

-- Capture only one-to-one email matches. Ambiguous duplicate emails are left
-- untouched instead of assigning one login to several driver records.
create temporary table _driver_login_repair
on commit drop
as
with auth_candidates as (
  select
    auth_user.id as auth_user_id,
    lower(btrim(auth_user.email)) as email_key,
    count(*) over (
      partition by lower(btrim(auth_user.email))
    ) as email_match_count
  from auth.users auth_user
  where auth_user.email is not null
    and btrim(auth_user.email) <> ''
),
driver_candidates as (
  select
    driver.id as driver_id,
    driver.company_id,
    lower(btrim(driver.login_email)) as email_key,
    count(*) over (
      partition by lower(btrim(driver.login_email))
    ) as email_match_count
  from public.drivers driver
  where driver.auth_user_id is null
    and driver.login_email is not null
    and btrim(driver.login_email) <> ''
)
select
  driver.driver_id,
  driver.company_id,
  auth_user.auth_user_id,
  driver.email_key
from driver_candidates driver
join auth_candidates auth_user
  on auth_user.email_key = driver.email_key
left join public.profiles profile
  on profile.id = auth_user.auth_user_id
where driver.email_match_count = 1
  and auth_user.email_match_count = 1
  and coalesce(profile.role, 'user') in ('user', 'driver')
  and not exists (
    select 1
    from public.drivers linked_driver
    where linked_driver.auth_user_id = auth_user.auth_user_id
  );

-- Link the selected driver rows.
update public.drivers driver
set auth_user_id = repair.auth_user_id,
    login_email = repair.email_key,
    login_enabled = true,
    updated_at = now()
from _driver_login_repair repair
where driver.id = repair.driver_id
  and driver.auth_user_id is null;

-- Synchronize each linked login from exactly one driver row. DISTINCT ON also
-- protects older databases that may contain duplicate auth_user_id values.
with selected_driver as (
  select distinct on (driver.auth_user_id)
    driver.auth_user_id,
    driver.login_email,
    driver.full_name,
    driver.phone,
    driver.status,
    driver.company_id
  from public.drivers driver
  where driver.auth_user_id is not null
    and driver.login_email is not null
  order by driver.auth_user_id, driver.updated_at desc nulls last, driver.id desc
)
update public.profiles profile
set email = lower(btrim(driver.login_email)),
    full_name = driver.full_name,
    phone = driver.phone,
    job_title = 'Driver',
    role = 'driver',
    status = driver.status,
    active_company_id = driver.company_id,
    updated_at = now()
from selected_driver driver
where profile.id = driver.auth_user_id
  and profile.role in ('user', 'driver');

-- Grant company access. GROUP BY guarantees only one source row for each
-- conflict key, so PostgreSQL never updates the same row twice in one upsert.
insert into public.user_company_access (
  user_id,
  company_id,
  can_view,
  can_create,
  can_edit,
  can_delete
)
select
  driver.auth_user_id,
  driver.company_id,
  true,
  false,
  false,
  false
from public.drivers driver
join public.profiles profile
  on profile.id = driver.auth_user_id
where driver.auth_user_id is not null
  and profile.role = 'driver'
group by driver.auth_user_id, driver.company_id
on conflict (user_id, company_id) do update
set can_view = true,
    updated_at = now();

notify pgrst, 'reload schema';
commit;

-- Result summary shown by Supabase SQL Editor.
select
  count(*) filter (where driver.auth_user_id is not null) as linked_driver_logins,
  count(*) filter (
    where driver.login_email is not null
      and driver.auth_user_id is null
  ) as still_unlinked_driver_logins
from public.drivers driver;

-- ============================================================
-- MIGRATION 024 / A3 FINANCE 1.3
-- ============================================================
-- A3 FINANCE 1.3
-- Company-scoped administrator visibility, short driver signup links,
-- and safer company selection.
-- Run once after migration 023.

begin;

create extension if not exists pgcrypto;

-- ------------------------------------------------------------------
-- 1. SHORT DRIVER SIGNUP CODES
-- ------------------------------------------------------------------
alter table public.driver_signup_links
  add column if not exists short_code text;

create or replace function public.assign_driver_signup_short_code()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  candidate text;
begin
  if new.short_code is null or btrim(new.short_code) = '' then
    loop
      candidate := upper(substr(encode(gen_random_bytes(8), 'hex'), 1, 10));
      exit when not exists (
        select 1
        from public.driver_signup_links link
        where upper(link.short_code) = candidate
          and link.id is distinct from new.id
      );
    end loop;
    new.short_code := candidate;
  else
    new.short_code := upper(regexp_replace(btrim(new.short_code), '[^A-Za-z0-9]', '', 'g'));
  end if;

  if length(new.short_code) < 6 then
    raise exception 'Driver signup short code must contain at least 6 letters or numbers.';
  end if;

  return new;
end;
$$;

update public.driver_signup_links
set short_code = upper(substr(replace(public_token::text, '-', ''), 1, 10))
where short_code is null or btrim(short_code) = '';

create unique index if not exists driver_signup_links_short_code_uidx
  on public.driver_signup_links(upper(short_code));

alter table public.driver_signup_links
  alter column short_code set not null;

drop trigger if exists driver_signup_links_assign_short_code on public.driver_signup_links;
create trigger driver_signup_links_assign_short_code
before insert or update of short_code on public.driver_signup_links
for each row execute function public.assign_driver_signup_short_code();

-- ------------------------------------------------------------------
-- 2. ENSURE EVERY ADMINISTRATOR HAS AN EXPLICIT COMPANY SCOPE
-- Existing administrators receive explicit access to their current active company.
-- ------------------------------------------------------------------
insert into public.user_company_access(
  user_id,
  company_id,
  can_view,
  can_create,
  can_edit,
  can_delete
)
select
  profile.id,
  profile.active_company_id,
  true,
  true,
  true,
  true
from public.profiles profile
where profile.role = 'administrator'
  and profile.status = 'active'
  and profile.active_company_id is not null
  and not exists (
    select 1
    from public.user_company_access access
    where access.user_id = profile.id
      and access.company_id = profile.active_company_id
  )
on conflict (user_id, company_id) do update
set can_view = true,
    can_create = true,
    can_edit = true,
    can_delete = true;

-- ------------------------------------------------------------------
-- 3. COMPANY-SCOPED ADMINISTRATOR HELPERS
-- Security-definer functions prevent policy recursion.
-- ------------------------------------------------------------------
create or replace function public.current_user_is_active_administrator()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles profile
    where profile.id = auth.uid()
      and profile.role = 'administrator'
      and profile.status = 'active'
  );
$$;

create or replace function public.current_user_company_permission(
  p_company_id bigint,
  p_permission text default 'view'
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
      select 1
      from public.profiles profile
      where profile.id = auth.uid()
        and profile.status = 'active'
    )
    and exists (
      select 1
      from public.user_company_access access
      where access.user_id = auth.uid()
        and access.company_id = p_company_id
        and case p_permission
          when 'delete' then access.can_delete
          when 'edit' then access.can_edit
          when 'create' then access.can_create
          else access.can_view
        end = true
    );
$$;

create or replace function public.current_user_shares_company(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select p_user_id = auth.uid()
    or (
      public.current_user_is_active_administrator()
      and exists (
        select 1
        from public.user_company_access actor_access
        join public.user_company_access target_access
          on target_access.company_id = actor_access.company_id
        where actor_access.user_id = auth.uid()
          and actor_access.can_view = true
          and target_access.user_id = p_user_id
      )
      and not exists (
        select 1
        from public.user_company_access target_access
        where target_access.user_id = p_user_id
          and not exists (
            select 1
            from public.user_company_access actor_access
            where actor_access.user_id = auth.uid()
              and actor_access.company_id = target_access.company_id
              and actor_access.can_view = true
          )
      )
    );
$$;

grant execute on function public.current_user_is_active_administrator() to authenticated;
grant execute on function public.current_user_company_permission(bigint, text) to authenticated;
grant execute on function public.current_user_shares_company(uuid) to authenticated;

-- ------------------------------------------------------------------
-- 4. COMPANY-SCOPED COMPANY SELECTOR AND USER MANAGEMENT POLICIES
-- ------------------------------------------------------------------
drop policy if exists companies_select_accessible on public.companies;
create policy companies_select_accessible on public.companies
for select to authenticated
using (public.current_user_company_permission(id, 'view'));

drop policy if exists companies_insert_admin on public.companies;
create policy companies_insert_admin on public.companies
for insert to authenticated
with check (public.current_user_is_active_administrator());

drop policy if exists companies_update_admin on public.companies;
create policy companies_update_admin on public.companies
for update to authenticated
using (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(id, 'edit')
)
with check (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(id, 'edit')
);

drop policy if exists companies_delete_admin on public.companies;
create policy companies_delete_admin on public.companies
for delete to authenticated
using (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(id, 'delete')
);

drop policy if exists profiles_select_own_or_admin on public.profiles;
create policy profiles_select_own_or_admin on public.profiles
for select to authenticated
using (public.current_user_shares_company(id));

drop policy if exists access_select_own_or_admin on public.user_company_access;
create policy access_select_own_or_admin on public.user_company_access
for select to authenticated
using (
  user_id = auth.uid()
  or (
    public.current_user_is_active_administrator()
    and public.current_user_company_permission(company_id, 'view')
  )
);

drop policy if exists access_insert_admin on public.user_company_access;
create policy access_insert_admin on public.user_company_access
for insert to authenticated
with check (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'edit')
);

drop policy if exists access_update_admin on public.user_company_access;
create policy access_update_admin on public.user_company_access
for update to authenticated
using (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'edit')
)
with check (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'edit')
);

drop policy if exists access_delete_admin on public.user_company_access;
create policy access_delete_admin on public.user_company_access
for delete to authenticated
using (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'edit')
);

-- Newly created companies are automatically assigned to their administrator creator.
create or replace function public.grant_company_creator_access()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is not null and public.current_user_is_active_administrator() then
    insert into public.user_company_access(
      user_id, company_id, can_view, can_create, can_edit, can_delete
    )
    values (auth.uid(), new.id, true, true, true, true)
    on conflict (user_id, company_id) do update
    set can_view = true,
        can_create = true,
        can_edit = true,
        can_delete = true;
  end if;
  return new;
end;
$$;

drop trigger if exists companies_grant_creator_access on public.companies;
create trigger companies_grant_creator_access
after insert on public.companies
for each row execute function public.grant_company_creator_access();

-- Administrators may only activate a company explicitly assigned to them.
create or replace function public.set_active_company(p_company_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'You must be signed in.';
  end if;

  if not exists (
    select 1
    from public.companies company
    where company.id = p_company_id
      and company.status = 'active'
  ) then
    raise exception 'The selected company is unavailable or inactive.';
  end if;

  if not exists (
    select 1
    from public.user_company_access access
    where access.user_id = auth.uid()
      and access.company_id = p_company_id
      and access.can_view = true
  ) then
    raise exception 'You do not have access to this company.';
  end if;

  update public.profiles
  set active_company_id = p_company_id,
      updated_at = now()
  where id = auth.uid();

  if not found then
    raise exception 'User profile was not found.';
  end if;

  return p_company_id;
end;
$$;

grant execute on function public.set_active_company(bigint) to authenticated;

-- ------------------------------------------------------------------
-- 5. COMPANY-SCOPED DRIVER NETWORK POLICIES
-- ------------------------------------------------------------------
create or replace function public.current_user_can_access_driver(p_driver_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.drivers driver
    where driver.id = p_driver_id
      and (
        driver.auth_user_id = auth.uid()
        or public.current_user_company_permission(driver.company_id, 'view')
        or exists (
          select 1
          from public.driver_company_links link
          where link.driver_id = driver.id
            and link.membership_status = 'active'
            and public.current_user_company_permission(link.company_id, 'view')
        )
      )
  );
$$;

grant execute on function public.current_user_can_access_driver(bigint) to authenticated;

drop policy if exists drivers_select_admin_or_self on public.drivers;
create policy drivers_select_admin_or_self on public.drivers
for select to authenticated
using (public.current_user_can_access_driver(id));

drop policy if exists drivers_insert_administrator on public.drivers;
create policy drivers_insert_administrator on public.drivers
for insert to authenticated
with check (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'create')
);

drop policy if exists drivers_update_administrator on public.drivers;
create policy drivers_update_administrator on public.drivers
for update to authenticated
using (
  public.current_user_is_active_administrator()
  and public.current_user_can_access_driver(id)
)
with check (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'edit')
);

drop policy if exists drivers_delete_administrator on public.drivers;
create policy drivers_delete_administrator on public.drivers
for delete to authenticated
using (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'delete')
);

drop policy if exists driver_company_links_select_admin_or_self on public.driver_company_links;
create policy driver_company_links_select_admin_or_self on public.driver_company_links
for select to authenticated
using (
  public.current_user_company_permission(company_id, 'view')
  or exists (
    select 1 from public.drivers driver
    where driver.id = driver_company_links.driver_id
      and driver.auth_user_id = auth.uid()
  )
);

drop policy if exists driver_company_links_manage_admin on public.driver_company_links;
create policy driver_company_links_manage_admin on public.driver_company_links
for all to authenticated
using (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'edit')
)
with check (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'edit')
);

drop policy if exists driver_customer_links_select_admin_or_self on public.driver_customer_links;
create policy driver_customer_links_select_admin_or_self on public.driver_customer_links
for select to authenticated
using (
  public.current_user_company_permission(company_id, 'view')
  or exists (
    select 1 from public.drivers driver
    where driver.id = driver_customer_links.driver_id
      and driver.auth_user_id = auth.uid()
  )
);

drop policy if exists driver_customer_links_manage_admin on public.driver_customer_links;
create policy driver_customer_links_manage_admin on public.driver_customer_links
for all to authenticated
using (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'edit')
)
with check (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'edit')
);

drop policy if exists driver_signup_links_admin on public.driver_signup_links;
create policy driver_signup_links_admin on public.driver_signup_links
for all to authenticated
using (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'view')
)
with check (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'edit')
);

drop policy if exists driver_signup_applications_admin on public.driver_signup_applications;
create policy driver_signup_applications_admin on public.driver_signup_applications
for all to authenticated
using (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'view')
)
with check (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'edit')
);

drop policy if exists driver_application_documents_admin_all on public.driver_application_documents;
create policy driver_application_documents_admin_all on public.driver_application_documents
for all to authenticated
using (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'view')
)
with check (
  public.current_user_is_active_administrator()
  and public.current_user_company_permission(company_id, 'edit')
);

notify pgrst, 'reload schema';
commit;

-- ------------------------------------------------------------
-- FINAL INSTALLATION CHECK
-- ------------------------------------------------------------
select
  to_regclass('public.driver_signup_links') is not null as driver_signup_links_ready,
  to_regclass('public.driver_signup_applications') is not null as driver_signup_applications_ready,
  to_regclass('public.driver_application_documents') is not null as driver_documents_ready,
  exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'driver_signup_links'
      and column_name = 'short_code'
  ) as short_signup_codes_ready;
