"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useSearchParams} from "next/navigation";
import {formatDate} from "@/lib/format-date";

type Kind="invoice"|"receipt"|"payout"|"booking"|"job-sheet";
const cash=(n:any,c="SGD")=>new Intl.NumberFormat("en-SG",{style:"currency",currency:c||"SGD"}).format(Number(n||0));
const date=(v:any)=>formatDate(v);
const val=(v:any)=>v||"—";

export default function PrintDocument({kind}:{kind:Kind}){
 const search=useSearchParams();
 if(kind==="booking" && search.get("mode")==="sheet") kind="job-sheet";
 const id=search.get("id"),[data,setData]=useState<any>(null),[branding,setBranding]=useState<any>({}),[error,setError]=useState("");
 const apiType=kind==="receipt"?"invoice":kind==="booking"||kind==="job-sheet"?"job":kind;
 useEffect(()=>{if(!id){setError("Missing document ID.");return;}fetch(`/api/admin/documents?type=${apiType}&id=${id}`,{cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to load document.");setData(p.document);setBranding(p.branding||{});}).catch(e=>setError(e.message));},[id,apiType]);
 const company=data?.companies||{},currency=company.base_currency||"SGD";
 const title=kind==="invoice"?"TAX INVOICE":kind==="receipt"?"PAYMENT RECEIPT":kind==="payout"?"DRIVER PAYOUT SLIP":kind==="booking"?"BOOKING CONFIRMATION":"DRIVER JOB SHEET";
 const number=kind==="invoice"?data?.invoice_no:kind==="receipt"?`RCT-${data?.invoice_no||data?.id}`:kind==="payout"?data?.payout_no:data?.job_reference;
 const invoiceItems=data?.customer_invoice_items||[];
 const payoutItems=data?.driver_payout_items||[];
 const totals=useMemo(()=>({balance:Math.max(0,Number(data?.total_amount||0)-Number(data?.amount_paid||0)),net:Math.max(0,Number(data?.gross_earnings||0)-Number(data?.deductions||0)-Number(data?.advances||0))}),[data]);
 if(error)return <main className="document-state"><h1>Unable to open document</h1><p>{error}</p><Link href={`/${apiType}s`}>Return</Link></main>;
 if(!data)return <main className="document-state"><p>Preparing document...</p></main>;
 return <div className="document-screen"><div className="document-toolbar"><Link href={`/${apiType}s`}>← Back</Link><strong>{title}</strong><button onClick={()=>window.print()}>Print / Save PDF</button></div>
 <main className="a4-document" style={{"--doc-primary":company.primary_color||company.primary_colour||"#17365d"} as React.CSSProperties}>
  <header className="document-header"><div className="company-identity">{branding.logo_url?<img src={branding.logo_url} alt="Company logo"/>:<div className="logo-placeholder">{String(company.name||"A3").slice(0,2).toUpperCase()}</div>}<div><h1>{company.name||"Company"}</h1><p>{val(company.address)}</p><p>{company.phone||""}{company.phone&&company.email?" · ":""}{company.email||""}</p></div></div><div className="document-title"><span>{title}</span><strong>{number||`#${data.id}`}</strong><em className={`document-status ${data.status||""}`}>{data.status||data.payment_status||"issued"}</em></div></header>
  <section className="document-meta"><div><small>UEN</small><b>{val(company.uen)}</b></div><div><small>GST Registration</small><b>{val(company.gst_no)}</b></div>{kind==="invoice"||kind==="receipt"?<><div><small>{kind==="receipt"?"Receipt Date":"Invoice Date"}</small><b>{date(kind==="receipt"?(data.payment_date||data.invoice_date):data.invoice_date)}</b></div><div><small>{kind==="receipt"?"Invoice Reference":"Due Date"}</small><b>{kind==="receipt"?val(data.invoice_no):date(data.due_date)}</b></div></>:kind==="payout"?<><div><small>Pay Period</small><b>{date(data.period_start)} – {date(data.period_end)}</b></div><div><small>Payment Date</small><b>{date(data.payment_date)}</b></div></>:<><div><small>Service Date</small><b>{date(data.job_date)}</b></div><div><small>Pickup Time</small><b>{val(data.pickup_time?.slice?.(0,5)||data.pickup_time)}</b></div></>}</section>
  {(kind==="invoice"||kind==="receipt")&&<section className="document-parties"><div><h3>Bill To</h3><strong>{data.customer_name}</strong><p>{val(data.billing_address)}</p><p>{data.customer_phone||""}{data.customer_phone&&data.customer_email?" · ":""}{data.customer_email||""}</p></div><div><h3>Payment Details</h3><p><b>Method:</b> {val(data.payment_method)}</p><p><b>Reference:</b> {val(data.payment_reference)}</p></div></section>}
  {kind==="payout"&&<section className="document-parties"><div><h3>Driver</h3><strong>{data.drivers?.full_name}</strong><p>Driver No.: {val(data.drivers?.driver_no)}</p><p>Vehicle: {val(data.drivers?.vehicle_plate)}</p></div><div><h3>Payment</h3><p><b>Method:</b> {val(data.payment_method)}</p><p><b>Status:</b> {val(data.status)}</p></div></section>}
  {(kind==="booking"||kind==="job-sheet")&&<section className="document-parties"><div><h3>{kind==="booking"?"Passenger":"Customer"}</h3><strong>{val(data.customer_name)}</strong><p>{val(data.customer_phone)}</p><p>{val(data.service_type)}</p></div><div><h3>Assigned Driver</h3><strong>{val(data.drivers?.full_name)}</strong><p>{val(data.drivers?.phone)}</p><p>{val(data.drivers?.vehicle_plate)}</p></div></section>}
  {kind==="invoice"&&<table className="document-table"><thead><tr><th>#</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Amount</th></tr></thead><tbody>{invoiceItems.map((x:any,i:number)=><tr key={x.id||i}><td>{i+1}</td><td>{x.description}</td><td>{Number(x.quantity||0)}</td><td>{cash(x.unit_price,currency)}</td><td>{cash(x.line_total,currency)}</td></tr>)}</tbody></table>}
  {kind==="payout"&&<table className="document-table"><thead><tr><th>#</th><th>Job Reference</th><th>Date</th><th>Service</th><th>Driver Amount</th></tr></thead><tbody>{payoutItems.map((x:any,i:number)=><tr key={x.id||i}><td>{i+1}</td><td>{val(x.driver_jobs?.job_reference)}</td><td>{date(x.driver_jobs?.job_date)}</td><td>{val(x.driver_jobs?.service_type)}</td><td>{cash(x.amount||x.driver_jobs?.driver_amount,currency)}</td></tr>)}</tbody></table>}
  {(kind==="booking"||kind==="job-sheet")&&<section className="route-card"><div><small>PICKUP</small><strong>{val(data.pickup_location)}</strong></div><span>→</span><div><small>DROP-OFF</small><strong>{val(data.dropoff_location)}</strong></div></section>}
  {(kind==="booking"||kind==="job-sheet")&&<section className="job-detail-grid"><div><small>Vehicle Requirement</small><b>{val(data.vehicle_requirement)}</b></div><div><small>Pricing Source</small><b>{String(data.pricing_source||"manual").replaceAll("_"," ")}</b></div><div><small>Matched Rate</small><b>{val(data.matched_rate_name)}</b></div><div><small>Booking Status</small><b>{val(data.status)}</b></div><div><small>Payment Status</small><b>{val(data.payment_status)}</b></div><div><small>Payment Method</small><b>{val(data.payment_method)}</b></div>{kind==="job-sheet"&&<><div><small>Customer Fare</small><b>{cash(Number(data.gross_amount)+Number(data.extra_charges),currency)}</b></div><div><small>Driver Payout</small><b>{cash(data.driver_amount,currency)}</b></div></>}</section>}
  {kind==="invoice"&&<section className="document-summary"><div><span>Subtotal</span><b>{cash(data.subtotal,currency)}</b></div><div><span>Service Charge ({Number(data.service_charge_rate||0)}%)</span><b>{cash(data.service_charge_amount,currency)}</b></div><div><span>GST ({Number(data.gst_rate||0)}%)</span><b>{cash(data.gst_amount,currency)}</b></div><div className="grand"><span>Total</span><b>{cash(data.total_amount,currency)}</b></div><div><span>Paid</span><b>{cash(data.amount_paid,currency)}</b></div><div className="balance"><span>Balance Due</span><b>{cash(totals.balance,currency)}</b></div></section>}
  {kind==="receipt"&&<section className="receipt-hero"><small>AMOUNT RECEIVED</small><strong>{cash(data.amount_paid,currency)}</strong><p>Balance remaining: <b>{cash(totals.balance,currency)}</b></p></section>}
  {kind==="payout"&&<section className="document-summary"><div><span>Gross Earnings</span><b>{cash(data.gross_earnings,currency)}</b></div><div><span>Deductions</span><b>- {cash(data.deductions,currency)}</b></div><div><span>Advances</span><b>- {cash(data.advances,currency)}</b></div><div className="grand"><span>Net Payout</span><b>{cash(totals.net,currency)}</b></div><div><span>Amount Paid</span><b>{cash(data.amount_paid,currency)}</b></div><div className="balance"><span>Outstanding</span><b>{cash(Math.max(0,totals.net-Number(data.amount_paid||0)),currency)}</b></div></section>}
  {data.notes&&<section className="document-notes"><h3>Notes</h3><p>{data.notes}</p></section>}
  <footer className="document-footer"><div><h3>Payment / Bank Details</h3><p>{[company.bank_name,company.bank_account_name,company.bank_account_no,company.paynow_details].filter(Boolean).join(" · ")||"Please contact the company for payment details."}</p></div>{branding.chop_url?<img src={branding.chop_url} alt="Company chop"/>:<div className="signature-line">Authorised Signature</div>}</footer>
 </main></div>;
}
