"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { formatDate } from "@/lib/format-date";

type Company = { id:number; name:string; status:string; company_type:string };
type Job = { id:number; company_id:number; job_reference:string|null; job_date:string; customer_name:string|null; customer_phone:string|null; gross_amount:number; extra_charges:number; status:string; payment_status:string };
type Item = { id?:number; job_id:number|null; description:string; quantity:number; unit_price:number; line_total?:number };
type Invoice = { id:number; company_id:number; invoice_no:string|null; invoice_date:string; due_date:string|null; customer_name:string; customer_phone:string|null; customer_email:string|null; billing_address:string|null; subtotal:number; service_charge_rate:number; service_charge_amount:number; gst_rate:number; gst_amount:number; total_amount:number; amount_paid:number; status:string; payment_method:string|null; payment_reference:string|null; notes:string|null; companies:{name:string}|null; customer_invoice_items:Item[] };
type Form = Omit<Invoice,"id"|"companies"|"customer_invoice_items"|"subtotal"|"service_charge_amount"|"gst_amount"|"total_amount"> & { items:Item[] };
const today = new Date().toISOString().slice(0,10);
const emptyItem:Item={job_id:null,description:"Transport service",quantity:1,unit_price:0};
const emptyForm:Form={company_id:0,invoice_no:"",invoice_date:today,due_date:"",customer_name:"",customer_phone:"",customer_email:"",billing_address:"",service_charge_rate:0,gst_rate:9,amount_paid:0,status:"draft",payment_method:"",payment_reference:"",notes:"",items:[{...emptyItem}]};
const currency=(n:number)=>new Intl.NumberFormat("en-SG",{style:"currency",currency:"SGD"}).format(Number(n||0));
const round=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;

export default function InvoicesPage(){
 const [invoices,setInvoices]=useState<Invoice[]>([]),[companies,setCompanies]=useState<Company[]>([]),[jobs,setJobs]=useState<Job[]>([]);
 const [selectedId,setSelectedId]=useState<number|null>(null),[form,setForm]=useState<Form>(emptyForm);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const availableJobs=useMemo(()=>jobs.filter(j=>j.company_id===Number(form.company_id)&&!invoices.some(inv=>inv.id!==selectedId&&inv.customer_invoice_items.some(i=>i.job_id===j.id))),[jobs,invoices,form.company_id,selectedId]);
 const totals=useMemo(()=>{const subtotal=round(form.items.reduce((s,i)=>s+Number(i.quantity||0)*Number(i.unit_price||0),0));const service=round(subtotal*Number(form.service_charge_rate||0)/100);const gst=round((subtotal+service)*Number(form.gst_rate||0)/100);return{subtotal,service,gst,total:round(subtotal+service+gst),balance:round(subtotal+service+gst-Number(form.amount_paid||0))}},[form]);
 const summary=useMemo(()=>({count:invoices.length,total:invoices.reduce((s,i)=>s+Number(i.total_amount||0),0),paid:invoices.reduce((s,i)=>s+Number(i.amount_paid||0),0),outstanding:invoices.reduce((s,i)=>s+Math.max(0,Number(i.total_amount||0)-Number(i.amount_paid||0)),0)}),[invoices]);
 useEffect(()=>{void load();},[]);
 async function load(preferred?:number|null){setLoading(true);const r=await fetch("/api/admin/invoices",{cache:"no-store"});const p=await r.json();if(!r.ok){setError(p.error||"Unable to load invoices.");setLoading(false);return;}setInvoices(p.invoices||[]);setCompanies(p.companies||[]);setJobs(p.jobs||[]);const found=(p.invoices||[]).find((x:Invoice)=>x.id===preferred);if(found)select(found);else createNew(p.companies||[]);setLoading(false);}
 function select(i:Invoice){setSelectedId(i.id);setForm({company_id:i.company_id,invoice_no:i.invoice_no||"",invoice_date:i.invoice_date,due_date:i.due_date||"",customer_name:i.customer_name,customer_phone:i.customer_phone||"",customer_email:i.customer_email||"",billing_address:i.billing_address||"",service_charge_rate:Number(i.service_charge_rate||0),gst_rate:Number(i.gst_rate||0),amount_paid:Number(i.amount_paid||0),status:i.status,payment_method:i.payment_method||"",payment_reference:i.payment_reference||"",notes:i.notes||"",items:(i.customer_invoice_items||[]).map(x=>({...x,quantity:Number(x.quantity),unit_price:Number(x.unit_price) }))});setError("");setNotice("");}
 function createNew(cs=companies){const c=cs.find((x:Company)=>x.status==="active");setSelectedId(null);setForm({...emptyForm,company_id:c?.id||0,items:[{...emptyItem}]});setError("");setNotice("Enter the new invoice details.");}
 function update<K extends keyof Form>(key:K,value:Form[K]){setForm(f=>({...f,[key]:value}));}
 function updateItem(index:number,key:keyof Item,value:string|number|null){setForm(f=>({...f,items:f.items.map((item,i)=>i===index?{...item,[key]:value}:item)}));}
 function addJob(jobId:number,index:number){const job=jobs.find(j=>j.id===jobId);if(!job)return;setForm(f=>({...f,customer_name:f.customer_name||job.customer_name||"",customer_phone:f.customer_phone||job.customer_phone||"",items:f.items.map((item,i)=>i===index?{...item,job_id:job.id,description:`${job.job_reference||`JOB-${job.id}`} — Transport service (${formatDate(job.job_date)})`,quantity:1,unit_price:Number(job.gross_amount||0)+Number(job.extra_charges||0)}:item)}));}
 async function save(){setSaving(true);setError("");setNotice("");const r=await fetch("/api/admin/invoices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:selectedId?"update":"create",invoice_id:selectedId,...form})});const p=await r.json();if(!r.ok){setError(p.error||"Unable to save invoice.");setSaving(false);return;}await load(p.invoice_id);setNotice(selectedId?"Invoice updated successfully.":"Invoice created successfully.");setSaving(false);}
 async function remove(){if(!selectedId||!confirm("Delete this invoice permanently?"))return;const r=await fetch("/api/admin/invoices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete",invoice_id:selectedId})});const p=await r.json();if(!r.ok){setError(p.error||"Unable to delete invoice.");return;}await load();setNotice("Invoice deleted.");}
 return <div className="shell">
 <main className="container"><div className="page-heading-row"><div><h1 className="page-title">Customer Invoices</h1><p className="subtitle">Create invoices from completed jobs. Use Accounts Receivable for payment receipts, allocations and ageing.</p></div><button className="button primary" onClick={()=>createNew()}>+ New Invoice</button></div>{notice?<div className="notice success">{notice}</div>:null}{error?<div className="notice error">{error}</div>:null}
 <section className="invoice-summary-grid"><article className="card metric"><span>Invoices</span><strong>{summary.count}</strong></article><article className="card metric"><span>Total Billed</span><strong>{currency(summary.total)}</strong></article><article className="card metric"><span>Collected</span><strong>{currency(summary.paid)}</strong></article><article className="card metric"><span>Outstanding</span><strong>{currency(summary.outstanding)}</strong></article></section>
 <section className="invoice-management-grid"><article className="card invoice-list-card"><h2>Invoice List</h2>{loading?<p>Loading...</p>:invoices.length===0?<p className="muted">No invoices yet.</p>:<div className="invoice-list">{invoices.map(i=><button key={i.id} className={`invoice-list-item ${selectedId===i.id?"active":""}`} onClick={()=>select(i)}><strong>{i.invoice_no||`INV-${i.id}`}</strong><span>{formatDate(i.invoice_date)} · {i.customer_name}</span><span>{i.companies?.name||"Company"}</span><span className="job-list-bottom"><em>{i.status}</em><b>{currency(i.total_amount)}</b></span></button>)}</div>}</article>
 <article className="card"><div className="section-title-row"><h2>{selectedId?"Edit Invoice":"New Invoice"}</h2>{selectedId?<span className="badge">#{selectedId}</span>:null}</div><div className="form-grid"><label>Company<select value={form.company_id} onChange={e=>update("company_id",Number(e.target.value))}><option value={0}>Select company</option>{companies.filter(c=>c.status==="active").map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Invoice number<input value={form.invoice_no||""} onChange={e=>update("invoice_no",e.target.value)} placeholder="Auto-generated when blank"/></label><label>Invoice date<input type="date" value={form.invoice_date} onChange={e=>update("invoice_date",e.target.value)}/></label><label>Due date<input type="date" value={form.due_date||""} onChange={e=>update("due_date",e.target.value)}/></label><label>Customer name<input value={form.customer_name} onChange={e=>update("customer_name",e.target.value)}/></label><label>Customer phone<input value={form.customer_phone||""} onChange={e=>update("customer_phone",e.target.value)}/></label><label>Customer email<input type="email" value={form.customer_email||""} onChange={e=>update("customer_email",e.target.value)}/></label><label>Status<select value={form.status} onChange={e=>update("status",e.target.value)}><option value="draft">Draft</option><option value="issued">Issued</option><option value="partial">Partial</option><option value="paid">Paid</option><option value="overdue">Overdue</option><option value="cancelled">Cancelled</option></select></label><label className="span-2">Billing address<textarea rows={2} value={form.billing_address||""} onChange={e=>update("billing_address",e.target.value)}/></label></div>
 <h3>Invoice Items</h3><div className="invoice-items">{form.items.map((item,index)=><div className="invoice-item-row" key={index}><label>Completed job<select value={item.job_id||0} onChange={e=>addJob(Number(e.target.value),index)}><option value={0}>Manual item</option>{availableJobs.map(j=><option key={j.id} value={j.id}>{j.job_reference||`JOB-${j.id}`} — {j.customer_name||"Customer"} — {currency(Number(j.gross_amount)+Number(j.extra_charges))}</option>)}</select></label><label className="item-description">Description<input value={item.description} onChange={e=>updateItem(index,"description",e.target.value)}/></label><label>Qty<input type="number" min="0.01" step="0.01" value={item.quantity} onChange={e=>updateItem(index,"quantity",Number(e.target.value))}/></label><label>Unit price<input type="number" min="0" step="0.01" value={item.unit_price} onChange={e=>updateItem(index,"unit_price",Number(e.target.value))}/></label><button className="button danger" type="button" disabled={form.items.length===1} onClick={()=>update("items",form.items.filter((_,i)=>i!==index))}>Remove</button></div>)}</div><button className="button secondary" type="button" onClick={()=>update("items",[...form.items,{...emptyItem}])}>+ Add Item</button>
 <div className="form-grid payout-money-grid"><label>Service charge %<input type="number" min="0" step="0.01" value={form.service_charge_rate} onChange={e=>update("service_charge_rate",Number(e.target.value))}/></label><label>GST %<input type="number" min="0" step="0.01" value={form.gst_rate} onChange={e=>update("gst_rate",Number(e.target.value))}/></label><label>Amount paid<input type="number" min="0" step="0.01" value={form.amount_paid} onChange={e=>update("amount_paid",Number(e.target.value))}/></label><label>Payment method<input value={form.payment_method||""} onChange={e=>update("payment_method",e.target.value)} placeholder="Cash, PayNow, bank..."/></label><label>Payment reference<input value={form.payment_reference||""} onChange={e=>update("payment_reference",e.target.value)}/></label><label className="span-2">Notes<textarea rows={3} value={form.notes||""} onChange={e=>update("notes",e.target.value)}/></label></div>
 <div className="invoice-totals"><span>Subtotal <b>{currency(totals.subtotal)}</b></span><span>Service charge <b>{currency(totals.service)}</b></span><span>GST <b>{currency(totals.gst)}</b></span><span>Total <b>{currency(totals.total)}</b></span><span>Balance <b>{currency(totals.balance)}</b></span></div><div className="actions"><button className="button primary" disabled={saving} onClick={save}>{saving?"Saving...":"Save Invoice"}</button>{selectedId?<><Link className="button secondary" href={`/invoices/print?id=${selectedId}`} target="_blank">Print Invoice</Link><Link className="button secondary" href={`/invoices/receipt?id=${selectedId}`} target="_blank">Print Receipt</Link><Link className="button secondary" href="/receivables">Record Payment</Link><button className="button danger" onClick={remove}>Delete Invoice</button></>:null}</div></article></section></main></div>;
}
