"use client";
import { useEffect, useMemo, useState } from "react";
import { LayoutDashboard, CarFront, UtensilsCrossed, WalletCards, Percent, Network, Settings2, BarChart3, ReceiptText, FileText, Search, Bell, Menu, X, ChevronRight, Plus, TrendingUp, Users, Clock3, ShieldCheck, Globe2 } from "lucide-react";
import { bookings, rates, Role, services, vehicleTypes } from "@/lib/data";

type Item={id:string;label:string;roles:Role[];icon:any};
const nav: {label:string;items:Item[]}[]=[
 {label:"Workspace",items:[{id:"overview",label:"Executive Overview",roles:["ADMIN","OPERATIONS","DRIVER"],icon:LayoutDashboard}]},
 {label:"Booking",items:[{id:"limousine",label:"Website Limousine Bookings",roles:["ADMIN","OPERATIONS"],icon:CarFront},{id:"sakura",label:"Website Sakura Table Bookings",roles:["ADMIN","OPERATIONS"],icon:UtensilsCrossed}]},
 {label:"Driver Only",items:[{id:"payout",label:"Driver Report Payout",roles:["DRIVER"],icon:WalletCards},{id:"rebate",label:"Driver 10% Rebate",roles:["DRIVER"],icon:Percent},{id:"network",label:"Driver Network",roles:["DRIVER"],icon:Network}]},
 {label:"Fleet & Setting · Admin",items:[{id:"rates",label:"Vehicle & Rate",roles:["ADMIN"],icon:CarFront},{id:"driverfix",label:"Driver Fix Rate",roles:["ADMIN"],icon:Settings2},{id:"clientfix",label:"Client Fix Rate",roles:["ADMIN"],icon:Settings2},{id:"drivers",label:"Driver Management",roles:["ADMIN"],icon:Users},{id:"catalogue",label:"Website Catalogue Rate",roles:["ADMIN"],icon:Globe2},{id:"company",label:"Company Setting",roles:["ADMIN"],icon:Settings2},{id:"access",label:"User Access",roles:["ADMIN"],icon:ShieldCheck}]},
 {label:"Report",items:[{id:"reports",label:"Income / Expense / P&L",roles:["ADMIN","OPERATIONS"],icon:BarChart3},{id:"invoice",label:"Invoice · EN / 中文 A4",roles:["ADMIN","OPERATIONS"],icon:ReceiptText},{id:"quotation",label:"Quotation · EN / 中文 A4",roles:["ADMIN","OPERATIONS"],icon:FileText}]}
];
const money=(n:number)=>new Intl.NumberFormat("en-SG",{style:"currency",currency:"SGD",maximumFractionDigits:0}).format(n);
export function ManagementApp(){
 const [role,setRole]=useState<Role>("ADMIN"); const [active,setActive]=useState("overview"); const [mobile,setMobile]=useState(false); const [query,setQuery]=useState("");
 const allowed=useMemo(()=>nav.map(g=>({...g,items:g.items.filter(i=>i.roles.includes(role))})).filter(g=>g.items.length),[role]);
 const allowedIds=useMemo(()=>new Set(allowed.flatMap(group=>group.items.map(item=>item.id))),[allowed]);
 useEffect(()=>{ if(!allowedIds.has(active)) setActive("overview"); },[active,allowedIds]);
 useEffect(()=>{
  const closeOnEscape=(event:KeyboardEvent)=>{ if(event.key==="Escape") setMobile(false); };
  window.addEventListener("keydown",closeOnEscape);
  return ()=>window.removeEventListener("keydown",closeOnEscape);
 },[]);
 const selectPage=(id:string)=>{ setActive(id); setMobile(false); };
 return <div className={mobile?"shell menu-open":"shell"}>
  <button className={mobile?"sidebarbackdrop show":"sidebarbackdrop"} aria-label="Close navigation" onClick={()=>setMobile(false)}/><aside className={mobile?"sidebar open":"sidebar"} aria-label="Main navigation">
   <div className="brand"><div className="brandmark">A3</div><div><strong>A3 MANAGEMENT</strong><span>Business Operating System</span></div><button className="close" aria-label="Close navigation" onClick={()=>setMobile(false)}><X/></button></div>
   <nav>{allowed.map(g=><div className="navgroup" key={g.label}><p>{g.label}</p>{g.items.map(i=>{const Icon=i.icon;return <button key={i.id} className={active===i.id?"navitem active":"navitem"} onClick={()=>selectPage(i.id)}><Icon size={17}/><span>{i.label}</span><ChevronRight size={15}/></button>})}</div>)}</nav>
   <div className="sidebarfoot"><span>Connected services</span><div><i></i> Vercel ready</div><div><i></i> Speed Insights</div></div>
  </aside>
  <main>
   <header><button className="menu" aria-label="Open navigation" aria-expanded={mobile} onClick={()=>setMobile(true)}><Menu/></button><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search bookings, drivers, documents..."/></div><button className="iconbtn"><Bell size={19}/><b></b></button><select value={role} onChange={e=>{setRole(e.target.value as Role);setActive("overview")}}><option value="ADMIN">Administrator</option><option value="OPERATIONS">Operations</option><option value="DRIVER">Driver</option></select><div className="avatar">AT</div></header>
   <section className="content">
    {active==="overview"&&<Overview role={role}/>} {active==="limousine"&&<Bookings query={query}/>} {active==="sakura"&&<Sakura/>} {active==="rates"&&<RateMatrix/>}
    {["reports","invoice","quotation","payout","rebate","network","driverfix","clientfix","drivers","catalogue","company","access"].includes(active)&&<Module id={active}/>} 
   </section>
  </main>
 </div>
}
function Heading({eyebrow,title,copy,action,onAction}:{eyebrow:string;title:string;copy:string;action?:string;onAction?:()=>void}){return <div className="heading"><div><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{action&&<button className="primary" onClick={onAction}><Plus size={17}/>{action}</button>}</div>}
function Overview({role}:{role:Role}){return <><Heading eyebrow="A3 GROUP · LIVE OPERATIONS" title="Executive Overview" copy={`A focused command centre for ${role.toLowerCase()} operations across A3 Group.`}/><div className="metrics"><Metric icon={TrendingUp} label="Revenue this month" value={money(128420)} note="+12.4% vs last month"/><Metric icon={CarFront} label="Active bookings" value="48" note="12 require attention"/><Metric icon={Users} label="Drivers online" value="27" note="84% network coverage"/><Metric icon={Clock3} label="On-time performance" value="96.8%" note="+1.9% this month"/></div><div className="grid2"><div className="panel"><div className="panelhead"><div><span>Revenue performance</span><h2>Monthly operating trend</h2></div><select><option>Last 6 months</option></select></div><div className="chart">{[42,55,51,67,74,88,82,96,100,112,105,126].map((h,i)=><div key={i} style={{height:`${h}px`}}><span></span></div>)}</div><div className="months"><span>Aug</span><span>Oct</span><span>Dec</span><span>Feb</span><span>Apr</span><span>Jul</span></div></div><div className="panel"><div className="panelhead"><div><span>Today</span><h2>Operational pulse</h2></div></div><div className="pulse"><div><strong>18</strong><span>Trips completed</span></div><div><strong>7</strong><span>Upcoming pickups</span></div><div><strong>3</strong><span>Pending confirmations</span></div><div><strong>1</strong><span>Driver issue</span></div></div></div></div><div className="panel"><div className="panelhead"><div><span>Latest activity</span><h2>Website limousine bookings</h2></div><button className="ghost">View all</button></div><BookingTable rows={bookings}/></div></>}
function Metric({icon:Icon,label,value,note}:{icon:any;label:string;value:string;note:string}){return <div className="metric"><div className="metricicon"><Icon size={20}/></div><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function Bookings({query}:{query:string}){const rows=bookings.filter(r=>r.join(" ").toLowerCase().includes(query.toLowerCase()));return <><Heading eyebrow="LIMOUSINE.A3GROUP.SG" title="Website Limousine Bookings" copy="Confirm rates, assign drivers and monitor every website booking from one operational queue." action="New booking"/><div className="panel"><BookingTable rows={rows}/></div></>}
function BookingTable({rows}:{rows:string[][]}){return <div className="tablewrap"><table><thead><tr>{["Reference","Customer","Pickup","Service","Vehicle","Status","Amount"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r[0]}>{r.map((x,i)=><td key={i}>{i===5?<span className={`status ${x.toLowerCase().replace(" ","")}`}>{x}</span>:x}</td>)}</tr>)}</tbody></table></div>}
function Sakura(){return <><Heading eyebrow="SAKURA.A3GROUP.SG" title="Website Sakura Table Bookings" copy="Manage online reservations, guest counts, deposits and seating allocation." action="New reservation"/><div className="panel empty"><UtensilsCrossed size={34}/><h2>Restaurant booking workspace</h2><p>Connect the Sakura booking API to replace demonstration records with live reservations.</p><button className="primary">Configure integration</button></div></>}
type RateRule={service:string;tripType:string;values:string[]};
function RateMatrix(){
 const defaults:RateRule[]=services.map(([service,tripType])=>({service,tripType,values:rates[service].map(String)}));
 const [rules,setRules]=useState<RateRule[]>(()=>{if(typeof window==="undefined")return defaults;try{const saved=window.localStorage.getItem("a3-rate-rules");return saved?JSON.parse(saved):defaults}catch{return defaults}});
 const [open,setOpen]=useState(false);
 const [service,setService]=useState("");
 const [tripType,setTripType]=useState("Per Trip");
 const [values,setValues]=useState<string[]>(vehicleTypes.map(()=>"0"));
 useEffect(()=>{try{window.localStorage.setItem("a3-rate-rules",JSON.stringify(rules))}catch{}},[rules]);
 const updateValue=(row:number,col:number,value:string)=>setRules(current=>current.map((rule,index)=>index===row?{...rule,values:rule.values.map((rate,i)=>i===col?value:rate)}:rule));
 const addRule=()=>{const name=service.trim();if(!name)return;setRules(current=>[...current,{service:name,tripType,values:values.map(value=>value||"0")}]);setService("");setTripType("Per Trip");setValues(vehicleTypes.map(()=>"0"));setOpen(false)};
 return <><Heading eyebrow="ADMIN · PRICING CONTROL" title="Vehicle, Service & Trip Type Rates" copy="One authoritative rate matrix for vehicle classes, service rules and per-hour or per-trip pricing." action="Add rate rule" onAction={()=>setOpen(true)}/><div className="panel"><div className="tablewrap"><table className="rate"><thead><tr><th>Rate rule</th><th>Trip type</th>{vehicleTypes.map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{rules.map((rule,row)=><tr key={`${rule.service}-${row}`}><td><strong>{rule.service}</strong></td><td><span className="pill">{rule.tripType}</span></td>{rule.values.map((value,col)=><td key={col}><input value={value} inputMode="decimal" aria-label={`${rule.service} ${vehicleTypes[col]} rate`} onChange={event=>updateValue(row,col,event.target.value)}/></td>)}</tr>)}</tbody></table></div></div>{open&&<div className="modalbackdrop" role="presentation" onMouseDown={()=>setOpen(false)}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="rate-rule-title" onMouseDown={event=>event.stopPropagation()}><div className="modalhead"><div><span>PRICING CONTROL</span><h2 id="rate-rule-title">Add rate rule</h2></div><button className="modalclose" aria-label="Close" onClick={()=>setOpen(false)}><X size={19}/></button></div><label>Rule / service name<input value={service} onChange={event=>setService(event.target.value)} placeholder="Example: Additional stop" autoFocus/></label><label>Trip type<select value={tripType} onChange={event=>setTripType(event.target.value)}><option>Per Trip</option><option>Per Hour</option></select></label><div className="rulegrid">{vehicleTypes.map((vehicle,index)=><label key={vehicle}>{vehicle}<input value={values[index]} inputMode="decimal" onChange={event=>setValues(current=>current.map((value,i)=>i===index?event.target.value:value))}/></label>)}</div><div className="modalactions"><button className="ghost" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" onClick={addRule} disabled={!service.trim()}>Save rate rule</button></div></div></div>}</>}

const names:Record<string,[string,string,string]>={reports:["REPORTING","Financial Reports","Income, expense, balance sheet, daily/monthly/yearly, profit and loss, and GST reporting."],invoice:["DOCUMENTS","Invoice · English / 中文 A4 PDF","Create bilingual A4 invoices and print or save them as PDF."],quotation:["DOCUMENTS","Quotation · English / 中文 A4 PDF","Create bilingual A4 quotations using your company identity and approved rates."],payout:["DRIVER PRIVATE","Driver Report Payout","Review trip earnings, deductions, incentives and payout status."],rebate:["DRIVER PRIVATE","Driver 10% Rebate","Track qualifying revenue and automatic 10% rebate calculations."],network:["DRIVER PRIVATE","Driver Network","View active drivers, coverage, availability and fleet capability."],driverfix:["ADMIN","Driver Fix Rate","Maintain contract payout rates for drivers."],clientfix:["ADMIN","Client Fix Rate","Maintain client-specific contracted prices."],drivers:["ADMIN","Driver Management","Manage onboarding, documents, vehicles and account status."],catalogue:["ADMIN","Website Catalogue Rate","Publish rates to FOOD.A3GROUP.SG, SAKURA.A3GROUP.SG and LIMOUSINE.A3GROUP.SG."],company:["ADMIN","Company Setting","Configure company identity, GST, currency and document preferences."],access:["ADMIN","User Access","Manage role-based access for administrators, operations staff and drivers."]};
function Module({id}:{id:string}){const n=names[id];return <><Heading eyebrow={n[0]} title={n[1]} copy={n[2]} action="Create record"/><div className="grid3"><div className="panel mini"><span>Current records</span><strong>128</strong><small>Across active entities</small></div><div className="panel mini"><span>Pending action</span><strong>7</strong><small>Requires review</small></div><div className="panel mini"><span>Last synchronised</span><strong>Just now</strong><small>System healthy</small></div></div><div className="panel empty"><ShieldCheck size={34}/><h2>{n[1]} workspace ready</h2><p>The interface and permissions are ready for database and API integration.</p></div></>}
