"use client";
import {useEffect,useMemo,useState} from "react";
type Company={id:number;name:string;status:string};
type Customer={id:number;company_id:number;customer_no:string|null;customer_type:string;customer_name:string;contact_person:string|null;phone:string|null;email:string|null;billing_address:string|null;uen_tax_id:string|null;payment_terms_days:number;credit_limit:number;preferred_language:string;default_currency:string;contract_reference:string|null;contract_start_date:string|null;contract_end_date:string|null;status:string;notes:string|null};
type Job={id:number;company_id:number;customer_name:string|null;customer_phone:string|null;job_date:string;gross_amount:number;extra_charges:number;status:string};
type Invoice={id:number;company_id:number;customer_name:string|null;total_amount:number;amount_paid:number;balance_due:number;invoice_date:string;status:string};
const empty={company_id:0,customer_no:"",customer_type:"company",customer_name:"",contact_person:"",phone:"",email:"",billing_address:"",uen_tax_id:"",payment_terms_days:0,credit_limit:0,preferred_language:"en",default_currency:"SGD",contract_reference:"",contract_start_date:"",contract_end_date:"",status:"active",notes:""};
const money=(n:number)=>new Intl.NumberFormat("en-SG",{style:"currency",currency:"SGD"}).format(Number(n||0));
export default function CustomersPage(){const [customers,setCustomers]=useState<Customer[]>([]),[companies,setCompanies]=useState<Company[]>([]),[jobs,setJobs]=useState<Job[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[selected,setSelected]=useState<number|null>(null),[form,setForm]=useState<any>(empty),[search,setSearch]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[saving,setSaving]=useState(false);useEffect(()=>{void load()},[]);
async function load(id?:number){const r=await fetch('/api/admin/customers',{cache:'no-store'}),p=await r.json();if(!r.ok){setError(p.error);return}setCustomers(p.customers||[]);setCompanies(p.companies||[]);setJobs(p.jobs||[]);setInvoices(p.invoices||[]);const c=(p.customers||[]).find((x:Customer)=>x.id===id);if(c)pick(c);else if(!selected)newOne(p.companies||[])}
function pick(c:Customer){setSelected(c.id);setForm({...c,preferred_language:'en'});setError('');setNotice('')}
function newOne(cs=companies){setSelected(null);setForm({...empty,company_id:cs.find((c:Company)=>c.status==='active')?.id||0});setNotice('Enter the customer details.');setError('')}
function u(k:string,v:any){setForm((f:any)=>({...f,[k]:v}))}
async function save(){setSaving(true);const r=await fetch('/api/admin/customers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:selected?'update':'create',customer_id:selected,...form})}),p=await r.json();setSaving(false);if(!r.ok){setError(p.error);return}await load(p.customer_id);setNotice(selected?'Customer updated successfully.':'Customer created successfully.')}
async function remove(){if(!selected||!confirm('Delete this customer?'))return;const r=await fetch('/api/admin/customers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',customer_id:selected})}),p=await r.json();if(!r.ok){setError(p.error);return}await load();setNotice('Customer deleted.')}
const list=useMemo(()=>customers.filter(c=>`${c.customer_no} ${c.customer_name} ${c.phone} ${c.email}`.toLowerCase().includes(search.toLowerCase())),[customers,search]);const current=customers.find(c=>c.id===selected);const cj=current?jobs.filter(j=>j.company_id===current.company_id&&((j.customer_name||'').toLowerCase()===current.customer_name.toLowerCase()||(current.phone&&j.customer_phone===current.phone))):[];const ci=current?invoices.filter(i=>i.company_id===current.company_id&&(i.customer_name||'').toLowerCase()===current.customer_name.toLowerCase()):[];const outstanding=ci.reduce((s,i)=>s+Number(i.balance_due||0),0);
return <main className="container"><div className="page-heading-row"><div><h1 className="page-title">Customers & CRM</h1><p className="subtitle">Profiles, booking history and account balances.</p></div><button className="button primary" onClick={()=>newOne()}>+ New Customer</button></div>{notice&&<div className="notice success">{notice}</div>}{error&&<div className="notice error">{error}</div>}
<section className="driver-summary-grid"><article className="card metric"><span>Total Customers</span><strong>{customers.length}</strong></article><article className="card metric"><span>Active</span><strong>{customers.filter(c=>c.status==='active').length}</strong></article><article className="card metric"><span>Total Bookings</span><strong>{jobs.length}</strong></article><article className="card metric"><span>Outstanding</span><strong>{money(invoices.reduce((s,i)=>s+Number(i.balance_due||0),0))}</strong></article></section>
<section className="job-management-grid"><article className="card job-list-card"><div className="section-title-row"><h2>Customer Directory</h2></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, phone or email"/>
<div className="job-list">{list.map(c=><button key={c.id} className={`job-list-item ${selected===c.id?'active':''}`} onClick={()=>pick(c)}><strong>{c.customer_name}</strong><span>{c.customer_no||`CUS-${c.id}`} · {c.customer_type}</span><span>{c.phone||'No phone'} · {c.email||'No email'}</span><span className="job-list-bottom"><em>{c.status}</em><b>{companies.find(x=>x.id===c.company_id)?.name}</b></span></button>)}</div></article>
<article className="card"><div className="section-title-row"><h2>{selected?'Customer Profile':'New Customer'}</h2>{selected&&<span className="badge">{current?.customer_no}</span>}</div>{selected&&<div className="crm-kpi-row"><div><small>Bookings</small><strong>{cj.length}</strong></div><div><small>Invoices</small><strong>{ci.length}</strong></div><div><small>Outstanding</small><strong>{money(outstanding)}</strong></div></div>}
<div className="form-grid"><label>Company<select value={form.company_id} onChange={e=>u('company_id',Number(e.target.value))}><option value={0}>Select company</option>{companies.filter(c=>c.status==='active').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Customer Type<select value={form.customer_type} onChange={e=>u('customer_type',e.target.value)}><option value="company">Company</option><option value="individual">Individual</option></select></label><label>Customer Name<input value={form.customer_name} onChange={e=>u('customer_name',e.target.value)}/></label><label>Contact Person<input value={form.contact_person||''} onChange={e=>u('contact_person',e.target.value)}/></label><label>Phone<input value={form.phone||''} onChange={e=>u('phone',e.target.value)}/></label><label>Email<input type="email" value={form.email||''} onChange={e=>u('email',e.target.value)}/></label><label>UEN / Tax ID<input value={form.uen_tax_id||''} onChange={e=>u('uen_tax_id',e.target.value)}/></label><label>Preferred Language<select value={form.preferred_language} onChange={e=>u('preferred_language',e.target.value)}><option value="en">English</option></select></label><label>Default Currency<input maxLength={3} value={form.default_currency||'SGD'} onChange={e=>u('default_currency',e.target.value.toUpperCase())}/></label><label>Contract Reference<input value={form.contract_reference||''} onChange={e=>u('contract_reference',e.target.value)}/></label><label>Contract Start<input type="date" value={form.contract_start_date||''} onChange={e=>u('contract_start_date',e.target.value)}/></label><label>Contract End<input type="date" value={form.contract_end_date||''} onChange={e=>u('contract_end_date',e.target.value)}/></label><label>Payment Terms (Days)<input type="number" min="0" value={form.payment_terms_days} onChange={e=>u('payment_terms_days',Number(e.target.value))}/></label><label>Credit Limit<input type="number" min="0" step="0.01" value={form.credit_limit} onChange={e=>u('credit_limit',Number(e.target.value))}/></label><label>Status<select value={form.status} onChange={e=>u('status',e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label className="span-2">Billing Address<textarea rows={2} value={form.billing_address||''} onChange={e=>u('billing_address',e.target.value)}/></label><label className="span-2">Notes<textarea rows={3} value={form.notes||''} onChange={e=>u('notes',e.target.value)}/></label></div><div className="actions"><button className="button primary" disabled={saving} onClick={save}>{saving?'Saving...':'Save Customer'}</button>{selected&&<button className="button danger" onClick={remove}>Delete</button>}</div></article></section></main>}
