import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
export const runtime="nodejs";export const dynamic="force-dynamic";
const APPLICATION_KEY="a3-driver-applications-v1";const MODEL_KEY="a3-vehicle-model-map";
const fallbackModels=[{id:"VM-018",model:"Toyota Alphard",vehicleType:"7 Seater Premium",active:true},{id:"VM-019",model:"Toyota Vellfire",vehicleType:"7 Seater Premium",active:true},{id:"VM-017",model:"Hyundai Staria",vehicleType:"7 Seater",active:true},{id:"VM-020",model:"Mercedes-Benz V-Class",vehicleType:"7 Seater Premium",active:true},{id:"VM-011",model:"Toyota Noah",vehicleType:"7 Seater",active:true},{id:"VM-012",model:"Toyota Voxy",vehicleType:"7 Seater",active:true},{id:"VM-013",model:"Toyota Sienta",vehicleType:"7 Seater",active:true},{id:"VM-015",model:"Honda Freed",vehicleType:"7 Seater",active:true},{id:"VM-007",model:"Mercedes-Benz E-Class",vehicleType:"5 Seater Premium",active:true},{id:"VM-001",model:"Toyota Camry",vehicleType:"5 Seater",active:true}];
function cleanEnv(value:string|undefined){return String(value||"").trim().replace(/^['"]|['"]$/g,"")}
function client(){
 let url=cleanEnv(process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL);
 const key=cleanEnv(process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY);
 if(!url||!key)throw new Error("Driver sign-up cloud configuration is missing.");
 if(!/^https?:\/\//i.test(url))url=`https://${url}`;
 try{url=new URL(url).origin}catch{throw new Error("The Finance Supabase URL is invalid. Update NEXT_PUBLIC_SUPABASE_URL in Vercel without quotes or spaces.")}
 return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})
}
async function ownerId(s:ReturnType<typeof client>){const preferred=(process.env.PRIMARY_ADMIN_EMAIL||"").toLowerCase();const {data,error}=await s.auth.admin.listUsers({page:1,perPage:100});if(error)throw error;const user=(preferred?data.users.find(item=>item.email?.toLowerCase()===preferred):undefined)||data.users[0];if(!user)throw new Error("No cloud owner account exists.");return user.id}
export async function GET(){try{const s=client();const uid=await ownerId(s);const {data,error}=await s.from("a3_app_storage").select("value").eq("user_id",uid).eq("storage_key",MODEL_KEY).maybeSingle();if(error)throw error;const models=Array.isArray(data?.value)?data.value:fallbackModels;return NextResponse.json({ok:true,models:models.filter((item:any)=>item&&item.active!==false&&item.model&&item.vehicleType)});}catch{return NextResponse.json({ok:true,models:fallbackModels});}}
export async function POST(req:NextRequest){try{const body=await req.json();for(const key of ["name","mobile","address","carModel","vehicleType","carPlate"])if(!String(body[key]||"").trim())return NextResponse.json({ok:false,message:`${key} is required.`},{status:400});for(const key of ["licence","pdvl","vehicleFront","phvDecal"])if(!body.documents?.[key]?.data)return NextResponse.json({ok:false,message:`Required document missing: ${key}.`},{status:400});if(!body.consent)return NextResponse.json({ok:false,message:"Declaration consent is required."},{status:400});const s=client();const uid=await ownerId(s);const {data}=await s.from("a3_app_storage").select("value").eq("user_id",uid).eq("storage_key",APPLICATION_KEY).maybeSingle();const current=Array.isArray(data?.value)?data.value:[];const id=`APP-${Date.now().toString(36).toUpperCase()}`;const clean={...body,nric:undefined,dob:undefined,phvCompany:undefined,id,status:"Pending Review",submittedAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const {error}=await s.from("a3_app_storage").upsert({user_id:uid,storage_key:APPLICATION_KEY,value:[clean,...current],updated_at:new Date().toISOString()},{onConflict:"user_id,storage_key"});if(error)throw error;return NextResponse.json({ok:true,applicationId:id})}catch(error){return NextResponse.json({ok:false,message:error instanceof Error?error.message:String(error)},{status:500})}}
