"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { formatDate } from "@/lib/format-date";

type Company={id:number;name:string;status:string};
type Driver={id:number;driver_no:string;full_name:string;company_id:number;status:string;vehicle_plate:string|null};
type Job={id:number;company_id:number;driver_id:number;job_reference:string|null;job_date:string;service_type:string|null;driver_amount:number;status:string};
type Item={id:number;payout_id:number;job_id:number;amount:number};
type Payout={id:number;company_id:number;driver_id:number;payout_no:string|null;period_start:string|null;period_end:string|null;gross_earnings:number;deductions:number;advances:number;net_payout:number;amount_paid:number;outstanding_amount:number;payment_date:string|null;payment_method:string|null;status:string;notes:string|null;drivers:{driver_no:string;full_name:string;vehicle_plate:string|null}|null;companies:{name:string}|null};
type Form={company_id:number;driver_id:number;payout_no:string;period_start:string;period_end:string;deductions:number;advances:number;amount_paid:number;payment_date:string;payment_method:string;status:string;notes:string;job_ids:number[]};
const today=new Date().toISOString().slice(0,10);
const empty:Form={company_id:0,driver_id:0,payout_no:"",period_start:today,period_end:today,deductions:0,advances:0,amount_paid:0,payment_date:"",payment_method:"",status:"draft",notes:"",job_ids:[]};
const money=(n:number)=>new Intl.NumberFormat("en-SG",{style:"currency",currency:"SGD"}).format(Number(n||0));

export default function PayoutsPage(){
 const [payouts,setPayouts]=useState<Payout[]>([]),[drivers,setDrivers]=useState<Driver[]>([]),[companies,setCompanies]=useState<Company[]>([]),[jobs,setJobs]=useState<Job[]>([]),[items,setItems]=useState<Item[]>([]);
 const [selectedId,setSelectedId]=useState<number|null>(null),[form,setForm]=useState<Form>(empty),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
 useEffect(()=>{void load();},[]);
 const assignedJobIds=useMemo(()=>new Set(items.filter(i=>i.payout_id!==selectedId).map(i=>i.job_id)),[items,selectedId]);
 const availableDrivers=useMemo(()=>drivers.filter(d=>d.company_id===form.company_id&&d.status==="active"),[drivers,form.company_id]);
 const eligibleJobs=useMemo(()=>jobs.filter(j=>j.company_id===form.company_id&&j.driver_id===form.driver_id&&!assignedJobIds.has(j.id)&&j.job_date>=form.period_start&&j.job_date<=form.period_end),[jobs,assignedJobIds,form]);
 const gross=useMemo(()=>jobs.filter(j=>form.job_ids.includes(j.id)).reduce((s,j)=>s+Number(j.driver_amount||0),0),[jobs,form.job_ids]);
 const net=Math.max(gross-form.deductions-form.advances,0), outstanding=Math.max(net-form.amount_paid,0);
 const summary=useMemo(()=>({total:payouts.length,approved:payouts.filter(p=>p.status==="approved").length,paid:payouts.reduce((s,p)=>s+Number(p.amount_paid||0),0),outstanding:payouts.filter(p=>p.status!=="cancelled").reduce((s,p)=>s+Number(p.outstanding_amount||0),0)}),[payouts]);
 async function load(preferred?:number|null){setLoading(true);const r=await fetch("/api/admin/payouts",{cache:"no-store"});const p=await r.json();if(!r.ok){setError(p.error||"Unable to load payouts.");setLoading(false);return;}setPayouts(p.payouts||[]);setDrivers(p.drivers||[]);setCompanies(p.companies||[]);setJobs(p.jobs||[]);setItems(p.items||[]);const found=(p.payouts||[]).find((x:Payout)=>x.id===preferred);if(found)select(found,p.items||[]);else makeNew(p.companies||[],p.drivers||[]);setLoading(false);}
 function select(p:Payout,allItems=items){setSelectedId(p.id);setForm({company_id:p.company_id,driver_id:p.driver_id,payout_no:p.payout_no||"",period_start:p.period_start||today,period_end:p.period_end||today,deductions:Number(p.deductions||0),advances:Number(p.advances||0),amount_paid:Number(p.amount_paid||0),payment_date:p.payment_date||"",payment_method:p.payment_method||"",status:p.status,notes:p.notes||"",job_ids:allItems.filter(i=>i.payout_id===p.id).map(i=>i.job_id)});setNotice("");setError("");}
 function makeNew(cs=companies,ds=drivers){const c=cs.find((x:Company)=>x.status==="active");const d=ds.find((x:Driver)=>x.company_id===c?.id&&x.status==="active");setSelectedId(null);setForm({...empty,company_id:c?.id||0,driver_id:d?.id||0,period_start:today,period_end:today});setNotice("Select completed jobs for the payout.");setError("");}
 function update<K extends keyof Form>(k:K,v:Form[K]){setForm(f=>({...f,[k]:v,...(k==="company_id"?{driver_id:drivers.find(d=>d.company_id===Number(v)&&d.status==="active")?.id||0,job_ids:[]}:{}),...(k==="driver_id"||k==="period_start"||k==="period_end"?{job_ids:[]}:{})}));}
 function toggleJob(id:number){setForm(f=>({...f,job_ids:f.job_ids.includes(id)?f.job_ids.filter(x=>x!==id):[...f.job_ids,id]}));}
 async function save(){setSaving(true);setError("");setNotice("");const r=await fetch("/api/admin/payouts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:selectedId?"update":"create",payout_id:selectedId,...form})});const p=await r.json();if(!r.ok){setError(p.error||"Unable to save payout.");setSaving(false);return;}await load(p.payout_id);setNotice(selectedId?"Payout updated successfully.":"Payout created successfully.");setSaving(false);}
 async function remove(){if(!selectedId||!confirm("Delete this payout permanently? The jobs will become available for another payout."))return;const r=await fetch("/api/admin/payouts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete",payout_id:selectedId})});const p=await r.json();if(!r.ok){setError(p.error||"Unable to delete payout.");return;}await load();setNotice("Payout deleted.");}
 return <div className="shell">
 <main className="container"><div className="page-heading-row"><div><h1 className="page-title">Driver Payouts</h1><p className="subtitle">Group completed jobs, calculate driver earnings and track payments.</p></div><button className="button primary" onClick={()=>makeNew()}>+ New Payout</button></div>{notice?<div className="notice success">{notice}</div>:null}{error?<div className="notice error">{error}</div>:null}
 <section className="payout-summary-grid"><article className="card metric"><span>Total Payouts</span><strong>{summary.total}</strong></article><article className="card metric"><span>Approved</span><strong>{summary.approved}</strong></article><article className="card metric"><span>Amount Paid</span><strong>{money(summary.paid)}</strong></article><article className="card metric"><span>Outstanding</span><strong>{money(summary.outstanding)}</strong></article></section>
 <section className="payout-management-grid"><article className="card payout-list-card"><h2>Payout Records</h2>{loading?<p>Loading...</p>:payouts.length===0?<p className="muted">No payouts yet.</p>:<div className="payout-list">{payouts.map(p=><button key={p.id} className={`payout-list-item ${selectedId===p.id?"active":""}`} onClick={()=>select(p)}><strong>{p.payout_no||`PAY-${p.id}`}</strong><span>{p.drivers?.full_name||"Unknown driver"}</span><span>{formatDate(p.period_start)} to {formatDate(p.period_end)}</span><span className="job-list-bottom"><em>{p.status}</em><b>{money(p.outstanding_amount)}</b></span></button>)}</div>}</article>
 <article className="card"><div className="section-title-row"><h2>{selectedId?"Edit Payout":"New Payout"}</h2>{selectedId?<span className="badge">#{selectedId}</span>:null}</div><div className="form-grid"><label>Company<select value={form.company_id} onChange={e=>update("company_id",Number(e.target.value))}><option value={0}>Select company</option>{companies.filter(c=>c.status==="active").map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Driver<select value={form.driver_id} onChange={e=>update("driver_id",Number(e.target.value))}><option value={0}>Select driver</option>{availableDrivers.map(d=><option key={d.id} value={d.id}>{d.driver_no} — {d.full_name}</option>)}</select></label><label>Payout number<input value={form.payout_no} onChange={e=>update("payout_no",e.target.value)} placeholder="Auto-generated when blank"/></label><label>Status<select value={form.status} onChange={e=>update("status",e.target.value)}><option value="draft">Draft</option><option value="approved">Approved</option><option value="partial">Partial</option><option value="paid">Paid</option><option value="cancelled">Cancelled</option></select></label><label>Period start<input type="date" value={form.period_start} onChange={e=>update("period_start",e.target.value)}/></label><label>Period end<input type="date" value={form.period_end} onChange={e=>update("period_end",e.target.value)}/></label></div>
 <h3>Completed Jobs</h3><div className="payout-job-list">{eligibleJobs.length===0?<p className="muted">No unassigned completed jobs in this period.</p>:eligibleJobs.map(j=><label key={j.id} className="payout-job-option"><input type="checkbox" checked={form.job_ids.includes(j.id)} onChange={()=>toggleJob(j.id)}/><span><strong>{j.job_reference||`JOB-${j.id}`}</strong><small>{formatDate(j.job_date)} · {j.service_type||"Service"}</small></span><b>{money(j.driver_amount)}</b></label>)}</div>
 <div className="form-grid payout-money-grid"><label>Gross earnings<input value={gross.toFixed(2)} readOnly/></label><label>Deductions<input type="number" min="0" step="0.01" value={form.deductions} onChange={e=>update("deductions",Number(e.target.value))}/></label><label>Advances<input type="number" min="0" step="0.01" value={form.advances} onChange={e=>update("advances",Number(e.target.value))}/></label><label>Net payout<input value={net.toFixed(2)} readOnly/></label><label>Amount paid<input type="number" min="0" step="0.01" value={form.amount_paid} onChange={e=>update("amount_paid",Number(e.target.value))}/></label><label>Outstanding<input value={outstanding.toFixed(2)} readOnly/></label><label>Payment date<input type="date" value={form.payment_date} onChange={e=>update("payment_date",e.target.value)}/></label><label>Payment method<input value={form.payment_method} onChange={e=>update("payment_method",e.target.value)} placeholder="PayNow, bank transfer, cash..."/></label><label className="span-2">Notes<textarea rows={3} value={form.notes} onChange={e=>update("notes",e.target.value)}/></label></div><div className="actions"><button className="button primary" disabled={saving||form.job_ids.length===0} onClick={save}>{saving?"Saving...":"Save Payout"}</button>{selectedId?<><Link className="button secondary" href={`/payouts/print?id=${selectedId}`} target="_blank">Print Payout Slip</Link><button className="button danger" onClick={remove}>Delete Payout</button></>:null}</div></article></section></main></div>;
}
