-- A3 MANAGEMENT COMPANY - PHASE 0 FOUNDATION
-- Run this once in Supabase SQL Editor.
-- Safe for a new project. It does not create any auth user.

begin;

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'user' check (role in ('administrator', 'finance', 'viewer', 'user')),
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  name text not null,
  company_type text not null default 'general' check (company_type in ('general', 'limousine', 'entertainment', 'food', 'other')),
  address text,
  uen text,
  gst_no text,
  gst_enabled boolean not null default false,
  gst_rate numeric(7,4) not null default 9 check (gst_rate between 0 and 100),
  phone text,
  email text,
  bank_name text,
  bank_account_name text,
  bank_account_no text,
  paynow_details text,
  base_currency text not null default 'SGD' check (base_currency ~ '^[A-Z]{3}$'),
  default_language text not null default 'en' check (default_language in ('en', 'zh-CN', 'zh-TW', 'ms')),
  appearance_mode text not null default 'system' check (appearance_mode in ('system', 'light', 'dark')),
  primary_colour text not null default '#1d4ed8',
  secondary_colour text not null default '#0f172a',
  accent_colour text not null default '#f59e0b',
  system_font_size integer not null default 16 check (system_font_size between 10 and 30),
  table_font_size integer not null default 13 check (table_font_size between 8 and 24),
  table_row_height integer not null default 42 check (table_row_height between 24 and 80),
  document_font_size integer not null default 12 check (document_font_size between 7 and 30),
  logo_width integer not null default 180 check (logo_width between 50 and 400),
  screen_zoom integer not null default 100 check (screen_zoom between 50 and 200),
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists companies_name_lower_uidx on public.companies (lower(name));

create table if not exists public.user_company_access (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  company_id bigint not null references public.companies(id) on delete cascade,
  can_view boolean not null default true,
  can_create boolean not null default false,
  can_edit boolean not null default false,
  can_delete boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, company_id)
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles(id, full_name)
select id, coalesce(raw_user_meta_data ->> 'full_name', split_part(email, '@', 1))
from auth.users
on conflict (id) do nothing;

create or replace function public.is_app_administrator()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'administrator' and status = 'active'
  );
$$;

create or replace function public.bootstrap_first_admin()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    return false;
  end if;

  if exists (select 1 from public.profiles where role = 'administrator') then
    return exists (
      select 1 from public.profiles where id = auth.uid() and role = 'administrator'
    );
  end if;

  update public.profiles
  set role = 'administrator', status = 'active', updated_at = now()
  where id = auth.uid();

  return true;
end;
$$;

alter table public.profiles enable row level security;
alter table public.companies enable row level security;
alter table public.user_company_access enable row level security;

grant select on public.profiles to authenticated;
grant select, insert, update, delete on public.companies to authenticated;
grant select, insert, update, delete on public.user_company_access to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.bootstrap_first_admin() to authenticated;
grant execute on function public.is_app_administrator() to authenticated;

drop policy if exists profiles_select_own_or_admin on public.profiles;
create policy profiles_select_own_or_admin on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_app_administrator());

drop policy if exists companies_select_accessible on public.companies;
create policy companies_select_accessible on public.companies
for select to authenticated
using (
  public.is_app_administrator()
  or exists (
    select 1 from public.user_company_access access
    where access.company_id = companies.id
      and access.user_id = auth.uid()
      and access.can_view = true
  )
);

drop policy if exists companies_insert_admin on public.companies;
create policy companies_insert_admin on public.companies
for insert to authenticated
with check (public.is_app_administrator());

drop policy if exists companies_update_admin on public.companies;
create policy companies_update_admin on public.companies
for update to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

drop policy if exists companies_delete_admin on public.companies;
create policy companies_delete_admin on public.companies
for delete to authenticated
using (public.is_app_administrator());

drop policy if exists access_select_own_or_admin on public.user_company_access;
create policy access_select_own_or_admin on public.user_company_access
for select to authenticated
using (user_id = auth.uid() or public.is_app_administrator());

drop policy if exists access_insert_admin on public.user_company_access;
create policy access_insert_admin on public.user_company_access
for insert to authenticated
with check (public.is_app_administrator());

drop policy if exists access_update_admin on public.user_company_access;
create policy access_update_admin on public.user_company_access
for update to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

drop policy if exists access_delete_admin on public.user_company_access;
create policy access_delete_admin on public.user_company_access
for delete to authenticated
using (public.is_app_administrator());

notify pgrst, 'reload schema';
commit;
