-- A3 MANAGEMENT - PHASE 1 USER MANAGEMENT
-- Run after 000_phase0_foundation.sql and 001_active_company_selector.sql.
-- Safe to run more than once. Existing companies and users are not deleted.

begin;

alter table public.profiles
  add column if not exists email text,
  add column if not exists phone text,
  add column if not exists job_title text,
  add column if not exists notes text;

update public.profiles profile
set email = auth_user.email,
    updated_at = now()
from auth.users auth_user
where auth_user.id = profile.id
  and profile.email is distinct from auth_user.email;

create unique index if not exists profiles_email_lower_uidx
  on public.profiles (lower(email))
  where email is not null;

alter table public.user_company_access
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_table text,
  target_user_id uuid references public.profiles(id) on delete set null,
  target_record_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_actor_user_id_idx
  on public.audit_logs(actor_user_id);
create index if not exists audit_logs_target_user_id_idx
  on public.audit_logs(target_user_id);
create index if not exists audit_logs_created_at_idx
  on public.audit_logs(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists user_company_access_set_updated_at on public.user_company_access;
create trigger user_company_access_set_updated_at
before update on public.user_company_access
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1))
  )
  on conflict (id) do update
  set email = excluded.email,
      updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update on auth.users
for each row execute function public.handle_new_user();

alter table public.audit_logs enable row level security;

grant select on public.audit_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists audit_logs_select_administrator on public.audit_logs;
create policy audit_logs_select_administrator on public.audit_logs
for select to authenticated
using (public.is_app_administrator());

notify pgrst, 'reload schema';
commit;

select
  profile.id,
  profile.email,
  profile.full_name,
  profile.role,
  profile.status,
  count(access.company_id) as assigned_companies
from public.profiles profile
left join public.user_company_access access on access.user_id = profile.id
group by profile.id, profile.email, profile.full_name, profile.role, profile.status
order by profile.created_at;
