-- A3 MANAGEMENT - PHASE 1.8 CUSTOMER & CRM
-- Run after 007_phase1_customer_invoices.sql.
begin;

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete restrict,
  customer_no text,
  customer_type text not null default 'company' check (customer_type in ('company','individual')),
  customer_name text not null,
  contact_person text,
  phone text,
  email text,
  billing_address text,
  uen_tax_id text,
  payment_terms_days integer not null default 0 check (payment_terms_days >= 0),
  credit_limit numeric(14,2) not null default 0 check (credit_limit >= 0),
  preferred_language text not null default 'en' check (preferred_language in ('en','zh')),
  status text not null default 'active' check (status in ('active','inactive')),
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists customers_company_no_uidx on public.customers(company_id, lower(customer_no)) where customer_no is not null;
create index if not exists customers_company_name_idx on public.customers(company_id, customer_name);

create or replace function public.assign_customer_no() returns trigger language plpgsql set search_path=public as $$
begin
  if new.customer_no is null or btrim(new.customer_no)='' then
    new.customer_no := 'CUS-' || lpad(new.id::text, 6, '0');
  end if;
  new.updated_at := now();
  return new;
end $$;
drop trigger if exists customers_assign_no on public.customers;
create trigger customers_assign_no before insert or update on public.customers for each row execute function public.assign_customer_no();

create table if not exists public.quotations (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete restrict,
  customer_id bigint not null references public.customers(id) on delete restrict,
  quotation_no text,
  quotation_date date not null default current_date,
  valid_until date,
  status text not null default 'draft' check (status in ('draft','sent','accepted','rejected','expired','converted','cancelled')),
  currency text not null default 'SGD',
  subtotal numeric(14,2) not null default 0,
  service_charge_rate numeric(7,4) not null default 0,
  gst_rate numeric(7,4) not null default 0,
  service_charge numeric(14,2) not null default 0,
  gst_amount numeric(14,2) not null default 0,
  total_amount numeric(14,2) not null default 0,
  notes text,
  terms text,
  converted_job_id bigint references public.driver_jobs(id) on delete set null,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quotation_items (
  id bigint generated by default as identity primary key,
  quotation_id bigint not null references public.quotations(id) on delete cascade,
  description text not null,
  quantity numeric(14,3) not null default 1 check (quantity > 0),
  unit_price numeric(14,2) not null default 0 check (unit_price >= 0),
  line_total numeric(14,2) generated always as (round(quantity * unit_price, 2)) stored,
  sort_order integer not null default 0
);

create unique index if not exists quotations_company_no_uidx on public.quotations(company_id, lower(quotation_no)) where quotation_no is not null;
create index if not exists quotations_company_date_idx on public.quotations(company_id, quotation_date desc);

create or replace function public.assign_quotation_no() returns trigger language plpgsql set search_path=public as $$
begin
  if new.quotation_no is null or btrim(new.quotation_no)='' then
    new.quotation_no := 'QT-' || to_char(coalesce(new.quotation_date,current_date),'YYYYMM') || '-' || lpad(new.id::text,5,'0');
  end if;
  new.updated_at := now();
  return new;
end $$;
drop trigger if exists quotations_assign_no on public.quotations;
create trigger quotations_assign_no before insert or update on public.quotations for each row execute function public.assign_quotation_no();

grant select,insert,update,delete on public.customers,public.quotations,public.quotation_items to authenticated;
grant usage,select on sequence public.customers_id_seq,public.quotations_id_seq,public.quotation_items_id_seq to authenticated;
commit;
