-- A3 MANAGEMENT FINANCE - UPGRADE 1
-- LIMOUSINE RATE MANAGEMENT
-- Run after migrations 000 through 009.
-- Safe to rerun. Existing jobs and finance records are preserved.

begin;

create table if not exists public.limousine_vehicle_types (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  code text not null,
  name text not null,
  passenger_capacity integer not null default 4 check (passenger_capacity between 1 and 100),
  luggage_capacity integer not null default 2 check (luggage_capacity between 0 and 100),
  is_active boolean not null default true,
  sort_order integer not null default 100,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Backward compatibility: an earlier A3 Finance database may already have
-- public.limousine_vehicle_types without the Upgrade 1 columns. CREATE TABLE IF
-- NOT EXISTS does not add missing columns, so add and normalise them before any
-- index, foreign key or API operation uses them.
alter table public.limousine_vehicle_types
  add column if not exists code text,
  add column if not exists name text,
  add column if not exists passenger_capacity integer not null default 4,
  add column if not exists luggage_capacity integer not null default 2,
  add column if not exists is_active boolean not null default true,
  add column if not exists sort_order integer not null default 100,
  add column if not exists notes text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- Copy values from common legacy column names when they are present.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'limousine_vehicle_types'
      and column_name = 'vehicle_code'
  ) then
    execute $sql$
      update public.limousine_vehicle_types
      set code = coalesce(nullif(btrim(code), ''), nullif(btrim(vehicle_code::text), ''))
      where code is null or btrim(code) = ''
    $sql$;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'limousine_vehicle_types'
      and column_name = 'vehicle_type_name'
  ) then
    execute $sql$
      update public.limousine_vehicle_types
      set name = coalesce(nullif(btrim(name), ''), nullif(btrim(vehicle_type_name::text), ''))
      where name is null or btrim(name) = ''
    $sql$;
  elsif exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'limousine_vehicle_types'
      and column_name = 'type_name'
  ) then
    execute $sql$
      update public.limousine_vehicle_types
      set name = coalesce(nullif(btrim(name), ''), nullif(btrim(type_name::text), ''))
      where name is null or btrim(name) = ''
    $sql$;
  end if;
end;
$$;

update public.limousine_vehicle_types
set code = 'VT-' || id::text
where code is null or btrim(code) = '';

update public.limousine_vehicle_types
set name = 'Vehicle Type ' || id::text
where name is null or btrim(name) = '';

update public.limousine_vehicle_types
set passenger_capacity = greatest(coalesce(passenger_capacity, 4), 1),
    luggage_capacity = greatest(coalesce(luggage_capacity, 2), 0),
    is_active = coalesce(is_active, true),
    sort_order = coalesce(sort_order, 100),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

-- Existing legacy rows may contain duplicate blank/default values. Make them
-- unique deterministically before creating the case-insensitive indexes.
with ranked as (
  select id,
         row_number() over (
           partition by company_id, lower(btrim(code))
           order by id
         ) as duplicate_no
  from public.limousine_vehicle_types
)
update public.limousine_vehicle_types vehicle_type
set code = btrim(vehicle_type.code) || '-' || vehicle_type.id::text
from ranked
where ranked.id = vehicle_type.id
  and ranked.duplicate_no > 1;

with ranked as (
  select id,
         row_number() over (
           partition by company_id, lower(btrim(name))
           order by id
         ) as duplicate_no
  from public.limousine_vehicle_types
)
update public.limousine_vehicle_types vehicle_type
set name = btrim(vehicle_type.name) || ' (' || vehicle_type.id::text || ')'
from ranked
where ranked.id = vehicle_type.id
  and ranked.duplicate_no > 1;

alter table public.limousine_vehicle_types
  alter column code set not null,
  alter column name set not null,
  alter column passenger_capacity set default 4,
  alter column passenger_capacity set not null,
  alter column luggage_capacity set default 2,
  alter column luggage_capacity set not null,
  alter column is_active set default true,
  alter column is_active set not null,
  alter column sort_order set default 100,
  alter column sort_order set not null,
  alter column created_at set default now(),
  alter column created_at set not null,
  alter column updated_at set default now(),
  alter column updated_at set not null;

create unique index if not exists limousine_vehicle_types_company_code_uidx
  on public.limousine_vehicle_types(company_id, lower(code));
create unique index if not exists limousine_vehicle_types_company_name_uidx
  on public.limousine_vehicle_types(company_id, lower(name));
create index if not exists limousine_vehicle_types_company_active_idx
  on public.limousine_vehicle_types(company_id, is_active, sort_order, name);

create table if not exists public.limousine_rate_cards (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  vehicle_type_id bigint not null references public.limousine_vehicle_types(id) on delete cascade,
  name text not null,
  service_type text not null,
  pricing_method text not null default 'fixed'
    check (pricing_method in ('fixed', 'per_hour')),
  base_amount numeric(14,2) not null default 0 check (base_amount >= 0),
  currency text not null default 'SGD' check (currency ~ '^[A-Z]{3}$'),
  minimum_hours numeric(8,2) not null default 1 check (minimum_hours >= 0),
  included_hours numeric(8,2) not null default 0 check (included_hours >= 0),
  additional_hour_amount numeric(14,2) not null default 0 check (additional_hour_amount >= 0),
  valid_from date not null default current_date,
  valid_to date,
  days_of_week smallint[] not null default '{}'::smallint[],
  start_time time,
  end_time time,
  pickup_pattern text,
  dropoff_pattern text,
  min_passengers integer not null default 0 check (min_passengers >= 0),
  max_passengers integer check (max_passengers is null or max_passengers >= 0),
  min_luggage integer not null default 0 check (min_luggage >= 0),
  max_luggage integer check (max_luggage is null or max_luggage >= 0),
  priority integer not null default 100,
  is_active boolean not null default true,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (valid_to is null or valid_to >= valid_from),
  check (max_passengers is null or max_passengers >= min_passengers),
  check (max_luggage is null or max_luggage >= min_luggage),
  check (days_of_week <@ array[1,2,3,4,5,6,7]::smallint[])
);

-- Backward compatibility for an existing rate-card table. Every column used by
-- indexes, the API and match_limousine_rate is created before those objects.
alter table public.limousine_rate_cards
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists vehicle_type_id bigint references public.limousine_vehicle_types(id) on delete cascade,
  add column if not exists name text,
  add column if not exists service_type text,
  add column if not exists pricing_method text default 'fixed',
  add column if not exists base_amount numeric(14,2) default 0,
  add column if not exists currency text default 'SGD',
  add column if not exists minimum_hours numeric(8,2) default 1,
  add column if not exists included_hours numeric(8,2) default 0,
  add column if not exists additional_hour_amount numeric(14,2) default 0,
  add column if not exists valid_from date default current_date,
  add column if not exists valid_to date,
  add column if not exists days_of_week smallint[] default '{}'::smallint[],
  add column if not exists start_time time,
  add column if not exists end_time time,
  add column if not exists pickup_pattern text,
  add column if not exists dropoff_pattern text,
  add column if not exists min_passengers integer default 0,
  add column if not exists max_passengers integer,
  add column if not exists min_luggage integer default 0,
  add column if not exists max_luggage integer,
  add column if not exists priority integer default 100,
  add column if not exists is_active boolean default true,
  add column if not exists notes text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

-- Copy common legacy names when available.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'limousine_rate_cards' and column_name = 'rate_name'
  ) then
    execute $sql$
      update public.limousine_rate_cards
      set name = coalesce(nullif(btrim(name), ''), nullif(btrim(rate_name::text), ''))
      where name is null or btrim(name) = ''
    $sql$;
  end if;end;
$$;

update public.limousine_rate_cards
set name = coalesce(nullif(btrim(name), ''), 'Rate Card ' || id::text),
    service_type = coalesce(nullif(btrim(service_type), ''), 'Point-to-Point'),
    pricing_method = case when lower(coalesce(pricing_method, 'fixed')) in ('fixed', 'per_hour')
      then lower(coalesce(pricing_method, 'fixed')) else 'fixed' end,
    base_amount = greatest(coalesce(base_amount, 0), 0),
    currency = case when upper(coalesce(currency, 'SGD')) ~ '^[A-Z]{3}$'
      then upper(coalesce(currency, 'SGD')) else 'SGD' end,
    minimum_hours = greatest(coalesce(minimum_hours, 1), 0),
    included_hours = greatest(coalesce(included_hours, 0), 0),
    additional_hour_amount = greatest(coalesce(additional_hour_amount, 0), 0),
    valid_from = coalesce(valid_from, current_date),
    days_of_week = coalesce(days_of_week, '{}'::smallint[]),
    min_passengers = greatest(coalesce(min_passengers, 0), 0),
    min_luggage = greatest(coalesce(min_luggage, 0), 0),
    priority = coalesce(priority, 100),
    is_active = coalesce(is_active, true),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

alter table public.limousine_rate_cards
  alter column name set not null,
  alter column service_type set not null,
  alter column pricing_method set default 'fixed',
  alter column pricing_method set not null,
  alter column base_amount set default 0,
  alter column base_amount set not null,
  alter column currency set default 'SGD',
  alter column currency set not null,
  alter column minimum_hours set default 1,
  alter column minimum_hours set not null,
  alter column included_hours set default 0,
  alter column included_hours set not null,
  alter column additional_hour_amount set default 0,
  alter column additional_hour_amount set not null,
  alter column valid_from set default current_date,
  alter column valid_from set not null,
  alter column days_of_week set default '{}'::smallint[],
  alter column days_of_week set not null,
  alter column min_passengers set default 0,
  alter column min_passengers set not null,
  alter column min_luggage set default 0,
  alter column min_luggage set not null,
  alter column priority set default 100,
  alter column priority set not null,
  alter column is_active set default true,
  alter column is_active set not null,
  alter column created_at set default now(),
  alter column created_at set not null,
  alter column updated_at set default now(),
  alter column updated_at set not null;

create index if not exists limousine_rate_cards_match_idx
  on public.limousine_rate_cards(
    company_id, vehicle_type_id, service_type, is_active,
    valid_from, valid_to, priority desc, base_amount
  );
create index if not exists limousine_rate_cards_company_idx
  on public.limousine_rate_cards(company_id, vehicle_type_id, name);

create table if not exists public.limousine_extra_charge_rules (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  vehicle_type_id bigint references public.limousine_vehicle_types(id) on delete cascade,
  service_type text,
  name text not null,
  rule_basis text not null default 'always'
    check (rule_basis in (
      'always', 'time_window', 'pickup_contains', 'dropoff_contains',
      'extra_stop', 'additional_hour', 'passenger_count', 'luggage_count'
    )),
  match_text text,
  threshold numeric(10,2) not null default 0 check (threshold >= 0),
  charge_type text not null default 'fixed'
    check (charge_type in ('fixed', 'percentage', 'per_unit')),
  amount numeric(14,2) not null default 0 check (amount >= 0),
  valid_from date not null default current_date,
  valid_to date,
  days_of_week smallint[] not null default '{}'::smallint[],
  start_time time,
  end_time time,
  is_stackable boolean not null default true,
  priority integer not null default 100,
  is_active boolean not null default true,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (valid_to is null or valid_to >= valid_from),
  check (days_of_week <@ array[1,2,3,4,5,6,7]::smallint[])
);

-- Backward compatibility for an existing extra-charge table. Every column used
-- by indexes, the API and match_limousine_rate is created first.
alter table public.limousine_extra_charge_rules
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists vehicle_type_id bigint references public.limousine_vehicle_types(id) on delete cascade,
  add column if not exists service_type text,
  add column if not exists name text,
  add column if not exists rule_basis text default 'always',
  add column if not exists match_text text,
  add column if not exists threshold numeric(10,2) default 0,
  add column if not exists charge_type text default 'fixed',
  add column if not exists amount numeric(14,2) default 0,
  add column if not exists valid_from date default current_date,
  add column if not exists valid_to date,
  add column if not exists days_of_week smallint[] default '{}'::smallint[],
  add column if not exists start_time time,
  add column if not exists end_time time,
  add column if not exists is_stackable boolean default true,
  add column if not exists priority integer default 100,
  add column if not exists is_active boolean default true,
  add column if not exists notes text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'limousine_extra_charge_rules' and column_name = 'rule_name'
  ) then
    execute $sql$
      update public.limousine_extra_charge_rules
      set name = coalesce(nullif(btrim(name), ''), nullif(btrim(rule_name::text), ''))
      where name is null or btrim(name) = ''
    $sql$;
  end if;end;
$$;

update public.limousine_extra_charge_rules
set name = coalesce(nullif(btrim(name), ''), 'Extra Charge ' || id::text),
    rule_basis = case when lower(coalesce(rule_basis, 'always')) in (
      'always', 'time_window', 'pickup_contains', 'dropoff_contains',
      'extra_stop', 'additional_hour', 'passenger_count', 'luggage_count'
    ) then lower(coalesce(rule_basis, 'always')) else 'always' end,
    threshold = greatest(coalesce(threshold, 0), 0),
    charge_type = case when lower(coalesce(charge_type, 'fixed')) in ('fixed', 'percentage', 'per_unit')
      then lower(coalesce(charge_type, 'fixed')) else 'fixed' end,
    amount = greatest(coalesce(amount, 0), 0),
    valid_from = coalesce(valid_from, current_date),
    days_of_week = coalesce(days_of_week, '{}'::smallint[]),
    is_stackable = coalesce(is_stackable, true),
    priority = coalesce(priority, 100),
    is_active = coalesce(is_active, true),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

-- Keep the modern `name` column compatible with an older required
-- `rule_name` column. The trigger runs before NOT NULL checks and supports
-- both new and legacy application versions.
do $compatibility$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'limousine_extra_charge_rules'
      and column_name = 'rule_name'
  ) then
    execute $sql$
      update public.limousine_extra_charge_rules
      set rule_name = coalesce(
        nullif(btrim(rule_name::text), ''),
        nullif(btrim(name), ''),
        'Extra Charge ' || id::text
      )
    $sql$;

    execute $function$
      create or replace function public.a3_sync_limousine_extra_charge_rule_names()
      returns trigger
      language plpgsql
      set search_path = public
      as $body$
      begin
        new.name := coalesce(
          nullif(btrim(new.name), ''),
          nullif(btrim(new.rule_name::text), '')
        );
        new.rule_name := coalesce(
          nullif(btrim(new.rule_name::text), ''),
          new.name
        );
        if new.name is null or btrim(new.name) = '' then
          raise exception 'Extra-charge rule name is required.';
        end if;
        return new;
      end;
      $body$
    $function$;

    execute 'drop trigger if exists limousine_extra_charge_rules_sync_names on public.limousine_extra_charge_rules';
    execute $trigger$
      create trigger limousine_extra_charge_rules_sync_names
      before insert or update of name, rule_name
      on public.limousine_extra_charge_rules
      for each row
      execute function public.a3_sync_limousine_extra_charge_rule_names()
    $trigger$;
  end if;
end
$compatibility$;

alter table public.limousine_extra_charge_rules
  alter column name set not null,
  alter column rule_basis set default 'always',
  alter column rule_basis set not null,
  alter column threshold set default 0,
  alter column threshold set not null,
  alter column charge_type set default 'fixed',
  alter column charge_type set not null,
  alter column amount set default 0,
  alter column amount set not null,
  alter column valid_from set default current_date,
  alter column valid_from set not null,
  alter column days_of_week set default '{}'::smallint[],
  alter column days_of_week set not null,
  alter column is_stackable set default true,
  alter column is_stackable set not null,
  alter column priority set default 100,
  alter column priority set not null,
  alter column is_active set default true,
  alter column is_active set not null,
  alter column created_at set default now(),
  alter column created_at set not null,
  alter column updated_at set default now(),
  alter column updated_at set not null;

create index if not exists limousine_extra_charge_rules_match_idx
  on public.limousine_extra_charge_rules(
    company_id, vehicle_type_id, service_type, is_active,
    valid_from, valid_to, priority desc
  );

-- Keep the existing Jobs table compatible while recording matched pricing details.
alter table public.driver_jobs
  add column if not exists limousine_vehicle_type_id bigint
    references public.limousine_vehicle_types(id) on delete set null,
  add column if not exists passenger_count integer not null default 0,
  add column if not exists luggage_count integer not null default 0,
  add column if not exists duration_hours numeric(8,2) not null default 1,
  add column if not exists extra_stops integer not null default 0,
  add column if not exists matched_rate_card_id bigint
    references public.limousine_rate_cards(id) on delete set null,
  add column if not exists matched_rate_name text,
  add column if not exists matched_base_amount numeric(14,2) not null default 0,
  add column if not exists matched_extra_amount numeric(14,2) not null default 0,
  add column if not exists rate_match_details jsonb;

alter table public.driver_jobs
  alter column rate_match_details drop not null,
  alter column rate_match_details drop default;

update public.driver_jobs
set rate_match_details = null
where rate_match_details = '{}'::jsonb;

create index if not exists driver_jobs_limousine_vehicle_type_idx
  on public.driver_jobs(limousine_vehicle_type_id);
create index if not exists driver_jobs_matched_rate_card_idx
  on public.driver_jobs(matched_rate_card_id);

-- Reuse the foundation updated-at trigger function from migration 002.
drop trigger if exists limousine_vehicle_types_set_updated_at on public.limousine_vehicle_types;
create trigger limousine_vehicle_types_set_updated_at
before update on public.limousine_vehicle_types
for each row execute function public.set_updated_at();

drop trigger if exists limousine_rate_cards_set_updated_at on public.limousine_rate_cards;
create trigger limousine_rate_cards_set_updated_at
before update on public.limousine_rate_cards
for each row execute function public.set_updated_at();

drop trigger if exists limousine_extra_charge_rules_set_updated_at on public.limousine_extra_charge_rules;
create trigger limousine_extra_charge_rules_set_updated_at
before update on public.limousine_extra_charge_rules
for each row execute function public.set_updated_at();

create or replace function public.a3_time_in_window(
  p_value time,
  p_start time,
  p_end time
)
returns boolean
language sql
immutable
set search_path = public
as $$
  select case
    when p_start is null and p_end is null then true
    when p_value is null then false
    when p_start is null then p_value <= p_end
    when p_end is null then p_value >= p_start
    when p_start <= p_end then p_value between p_start and p_end
    else p_value >= p_start or p_value <= p_end
  end;
$$;

create or replace function public.match_limousine_rate(
  p_company_id bigint,
  p_vehicle_type_id bigint,
  p_service_type text,
  p_service_date date default current_date,
  p_pickup_time time default null,
  p_pickup_location text default null,
  p_dropoff_location text default null,
  p_passengers integer default 0,
  p_luggage integer default 0,
  p_hours numeric default 1,
  p_extra_stops integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_rate public.limousine_rate_cards%rowtype;
  v_rule public.limousine_extra_charge_rules%rowtype;
  v_hours numeric := greatest(coalesce(p_hours, 1), 0);
  v_base numeric(14,2) := 0;
  v_extra numeric(14,2) := 0;
  v_charge numeric(14,2) := 0;
  v_charges jsonb := '[]'::jsonb;
  v_non_stackable_used boolean := false;
begin
  if auth.uid() is null then
    return jsonb_build_object(
      'matched', false,
      'message', 'Authentication is required.'
    );
  end if;

  if not public.is_app_administrator() and not exists (
    select 1
    from public.user_company_access access
    where access.user_id = auth.uid()
      and access.company_id = p_company_id
      and access.can_view = true
  ) then
    return jsonb_build_object(
      'matched', false,
      'message', 'You do not have access to this company.'
    );
  end if;

  if p_company_id is null or p_vehicle_type_id is null or btrim(coalesce(p_service_type, '')) = '' then
    return jsonb_build_object(
      'matched', false,
      'message', 'Company, vehicle type and service type are required.'
    );
  end if;

  select rate.*
    into v_rate
  from public.limousine_rate_cards rate
  where rate.company_id = p_company_id
    and rate.vehicle_type_id = p_vehicle_type_id
    and rate.is_active = true
    and lower(rate.service_type) = lower(btrim(p_service_type))
    and coalesce(p_service_date, current_date) >= rate.valid_from
    and (rate.valid_to is null or coalesce(p_service_date, current_date) <= rate.valid_to)
    and (
      cardinality(rate.days_of_week) = 0
      or extract(isodow from coalesce(p_service_date, current_date))::smallint = any(rate.days_of_week)
    )
    and public.a3_time_in_window(p_pickup_time, rate.start_time, rate.end_time)
    and (
      rate.pickup_pattern is null or btrim(rate.pickup_pattern) = ''
      or coalesce(p_pickup_location, '') ilike '%' || rate.pickup_pattern || '%'
    )
    and (
      rate.dropoff_pattern is null or btrim(rate.dropoff_pattern) = ''
      or coalesce(p_dropoff_location, '') ilike '%' || rate.dropoff_pattern || '%'
    )
    and greatest(coalesce(p_passengers, 0), 0) >= rate.min_passengers
    and (rate.max_passengers is null or greatest(coalesce(p_passengers, 0), 0) <= rate.max_passengers)
    and greatest(coalesce(p_luggage, 0), 0) >= rate.min_luggage
    and (rate.max_luggage is null or greatest(coalesce(p_luggage, 0), 0) <= rate.max_luggage)
  order by
    (
      (case when nullif(btrim(rate.pickup_pattern), '') is not null then 1 else 0 end) +
      (case when nullif(btrim(rate.dropoff_pattern), '') is not null then 1 else 0 end) +
      (case when rate.start_time is not null or rate.end_time is not null then 1 else 0 end) +
      (case when rate.max_passengers is not null then 1 else 0 end) +
      (case when rate.max_luggage is not null then 1 else 0 end)
    ) desc,
    rate.priority desc,
    rate.base_amount asc,
    rate.id asc
  limit 1;

  if not found then
    return jsonb_build_object(
      'matched', false,
      'message', 'No active rate card matched the supplied trip details.'
    );
  end if;

  if v_rate.pricing_method = 'per_hour' then
    v_base := round(
      v_rate.base_amount * greatest(ceil(v_hours), ceil(v_rate.minimum_hours)),
      2
    );
  else
    v_base := v_rate.base_amount + round(
      v_rate.additional_hour_amount * greatest(ceil(v_hours - v_rate.included_hours), 0),
      2
    );
  end if;

  for v_rule in
    select rule.*
    from public.limousine_extra_charge_rules rule
    where rule.company_id = p_company_id
      and rule.is_active = true
      and (rule.vehicle_type_id is null or rule.vehicle_type_id = p_vehicle_type_id)
      and (rule.service_type is null or btrim(rule.service_type) = '' or lower(rule.service_type) = lower(btrim(p_service_type)))
      and coalesce(p_service_date, current_date) >= rule.valid_from
      and (rule.valid_to is null or coalesce(p_service_date, current_date) <= rule.valid_to)
      and (
        cardinality(rule.days_of_week) = 0
        or extract(isodow from coalesce(p_service_date, current_date))::smallint = any(rule.days_of_week)
      )
      and public.a3_time_in_window(p_pickup_time, rule.start_time, rule.end_time)
      and case rule.rule_basis
        when 'always' then true
        when 'time_window' then public.a3_time_in_window(p_pickup_time, rule.start_time, rule.end_time)
        when 'pickup_contains' then btrim(coalesce(rule.match_text, '')) <> ''
          and coalesce(p_pickup_location, '') ilike '%' || rule.match_text || '%'
        when 'dropoff_contains' then btrim(coalesce(rule.match_text, '')) <> ''
          and coalesce(p_dropoff_location, '') ilike '%' || rule.match_text || '%'
        when 'extra_stop' then greatest(coalesce(p_extra_stops, 0), 0) >= rule.threshold
        when 'additional_hour' then v_hours > rule.threshold
        when 'passenger_count' then greatest(coalesce(p_passengers, 0), 0) >= rule.threshold
        when 'luggage_count' then greatest(coalesce(p_luggage, 0), 0) >= rule.threshold
        else false
      end
    order by rule.priority desc, rule.id asc
  loop
    if not v_rule.is_stackable then
      if v_non_stackable_used then
        continue;
      end if;
      v_non_stackable_used := true;
    end if;

    v_charge := case v_rule.charge_type
      when 'percentage' then round(v_base * v_rule.amount / 100, 2)
      when 'per_unit' then round(
        v_rule.amount * case v_rule.rule_basis
          when 'extra_stop' then greatest(coalesce(p_extra_stops, 0) - v_rule.threshold + 1, 0)
          when 'additional_hour' then greatest(ceil(v_hours - v_rule.threshold), 0)
          when 'passenger_count' then greatest(coalesce(p_passengers, 0) - v_rule.threshold + 1, 0)
          when 'luggage_count' then greatest(coalesce(p_luggage, 0) - v_rule.threshold + 1, 0)
          else 1
        end,
        2
      )
      else v_rule.amount
    end;

    v_extra := v_extra + v_charge;
    v_charges := v_charges || jsonb_build_array(jsonb_build_object(
      'rule_id', v_rule.id,
      'name', v_rule.name,
      'charge_type', v_rule.charge_type,
      'amount', v_charge,
      'stackable', v_rule.is_stackable
    ));
  end loop;

  return jsonb_build_object(
    'matched', true,
    'rate_card_id', v_rate.id,
    'rate_name', v_rate.name,
    'vehicle_type_id', v_rate.vehicle_type_id,
    'service_type', v_rate.service_type,
    'pricing_method', v_rate.pricing_method,
    'currency', v_rate.currency,
    'base_amount', round(v_base, 2),
    'extra_amount', round(v_extra, 2),
    'total_amount', round(v_base + v_extra, 2),
    'charges', v_charges
  );
end;
$$;

alter table public.limousine_vehicle_types enable row level security;
alter table public.limousine_rate_cards enable row level security;
alter table public.limousine_extra_charge_rules enable row level security;

grant select, insert, update, delete on public.limousine_vehicle_types to authenticated;
grant select, insert, update, delete on public.limousine_rate_cards to authenticated;
grant select, insert, update, delete on public.limousine_extra_charge_rules to authenticated;
grant usage, select on all sequences in schema public to authenticated;
revoke all on function public.match_limousine_rate(
  bigint, bigint, text, date, time, text, text, integer, integer, numeric, integer
) from public, anon;
grant execute on function public.match_limousine_rate(
  bigint, bigint, text, date, time, text, text, integer, integer, numeric, integer
) to authenticated;

drop policy if exists limousine_vehicle_types_select_accessible on public.limousine_vehicle_types;
create policy limousine_vehicle_types_select_accessible
on public.limousine_vehicle_types for select to authenticated
using (
  public.is_app_administrator()
  or exists (
    select 1 from public.user_company_access access
    where access.company_id = limousine_vehicle_types.company_id
      and access.user_id = auth.uid()
      and access.can_view = true
  )
);

drop policy if exists limousine_vehicle_types_write_administrator on public.limousine_vehicle_types;
create policy limousine_vehicle_types_write_administrator
on public.limousine_vehicle_types for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

drop policy if exists limousine_rate_cards_select_accessible on public.limousine_rate_cards;
create policy limousine_rate_cards_select_accessible
on public.limousine_rate_cards for select to authenticated
using (
  public.is_app_administrator()
  or exists (
    select 1 from public.user_company_access access
    where access.company_id = limousine_rate_cards.company_id
      and access.user_id = auth.uid()
      and access.can_view = true
  )
);

drop policy if exists limousine_rate_cards_write_administrator on public.limousine_rate_cards;
create policy limousine_rate_cards_write_administrator
on public.limousine_rate_cards for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

drop policy if exists limousine_extra_charge_rules_select_accessible on public.limousine_extra_charge_rules;
create policy limousine_extra_charge_rules_select_accessible
on public.limousine_extra_charge_rules for select to authenticated
using (
  public.is_app_administrator()
  or exists (
    select 1 from public.user_company_access access
    where access.company_id = limousine_extra_charge_rules.company_id
      and access.user_id = auth.uid()
      and access.can_view = true
  )
);

drop policy if exists limousine_extra_charge_rules_write_administrator on public.limousine_extra_charge_rules;
create policy limousine_extra_charge_rules_write_administrator
on public.limousine_extra_charge_rules for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

notify pgrst, 'reload schema';
commit;
