-- A3 MANAGEMENT FINANCE - UPGRADE 2
-- CUSTOMER PROFILES & CONTRACT LIMOUSINE RATES
-- Run after 010_limousine_rate_management.sql.
-- Safe to rerun. Existing customers, jobs, quotations and finance records are preserved.

begin;

alter table public.customers
  add column if not exists default_currency text not null default 'SGD',
  add column if not exists contract_reference text,
  add column if not exists contract_start_date date,
  add column if not exists contract_end_date date;

update public.customers
set default_currency = upper(coalesce(nullif(btrim(default_currency), ''), 'SGD'));

alter table public.customers
  alter column default_currency set default 'SGD',
  alter column default_currency set not null;

create table if not exists public.customer_limousine_rates (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  customer_id bigint not null references public.customers(id) on delete cascade,
  rate_card_id bigint not null references public.limousine_rate_cards(id) on delete cascade,
  contract_name text not null,
  override_base_amount numeric(14,2) not null default 0 check (override_base_amount >= 0),
  currency text not null default 'SGD' check (currency ~ '^[A-Z]{3}$'),
  pricing_method text check (pricing_method is null or pricing_method in ('fixed','per_hour')),
  minimum_hours numeric(8,2) check (minimum_hours is null or minimum_hours >= 0),
  included_hours numeric(8,2) check (included_hours is null or included_hours >= 0),
  additional_hour_amount numeric(14,2) check (additional_hour_amount is null or additional_hour_amount >= 0),
  valid_from date not null default current_date,
  valid_to date,
  priority integer not null default 100,
  is_active boolean not null default true,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (valid_to is null or valid_to >= valid_from)
);

-- Schema-safe compatibility if a partial table already exists.
alter table public.customer_limousine_rates
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists customer_id bigint references public.customers(id) on delete cascade,
  add column if not exists rate_card_id bigint references public.limousine_rate_cards(id) on delete cascade,
  add column if not exists contract_name text,
  add column if not exists override_base_amount numeric(14,2) default 0,
  add column if not exists currency text default 'SGD',
  add column if not exists pricing_method text,
  add column if not exists minimum_hours numeric(8,2),
  add column if not exists included_hours numeric(8,2),
  add column if not exists additional_hour_amount numeric(14,2),
  add column if not exists valid_from date default current_date,
  add column if not exists valid_to date,
  add column if not exists priority integer default 100,
  add column if not exists is_active boolean default true,
  add column if not exists notes text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.customer_limousine_rates contract_rate
set contract_name = coalesce(
      nullif(btrim(contract_rate.contract_name), ''),
      'Customer Contract ' || contract_rate.id::text
    ),
    override_base_amount = greatest(coalesce(contract_rate.override_base_amount, 0), 0),
    currency = upper(coalesce(nullif(btrim(contract_rate.currency), ''), 'SGD')),
    valid_from = coalesce(contract_rate.valid_from, current_date),
    priority = coalesce(contract_rate.priority, 100),
    is_active = coalesce(contract_rate.is_active, true),
    created_at = coalesce(contract_rate.created_at, now()),
    updated_at = coalesce(contract_rate.updated_at, now());

alter table public.customer_limousine_rates
  alter column contract_name set not null,
  alter column override_base_amount set default 0,
  alter column override_base_amount set not null,
  alter column currency set default 'SGD',
  alter column currency set not null,
  alter column valid_from set default current_date,
  alter column valid_from set not null,
  alter column priority set default 100,
  alter column priority set not null,
  alter column is_active set default true,
  alter column is_active set not null,
  alter column created_at set default now(),
  alter column created_at set not null,
  alter column updated_at set default now(),
  alter column updated_at set not null;

create index if not exists customer_limousine_rates_customer_idx
  on public.customer_limousine_rates(company_id, customer_id, is_active, valid_from, valid_to);
create index if not exists customer_limousine_rates_match_idx
  on public.customer_limousine_rates(customer_id, rate_card_id, is_active, priority desc);

alter table public.driver_jobs
  add column if not exists customer_id bigint references public.customers(id) on delete set null,
  add column if not exists matched_customer_rate_id bigint references public.customer_limousine_rates(id) on delete set null,
  add column if not exists pricing_source text default 'standard';

update public.driver_jobs
set pricing_source = case
  when matched_customer_rate_id is not null then 'customer_contract'
  when matched_rate_card_id is not null then 'standard'
  else 'manual'
end
where pricing_source is null or btrim(pricing_source) = '';

alter table public.driver_jobs
  alter column pricing_source set default 'standard',
  alter column pricing_source set not null;

alter table public.quotations
  add column if not exists limousine_vehicle_type_id bigint references public.limousine_vehicle_types(id) on delete set null,
  add column if not exists service_type text,
  add column if not exists service_date date,
  add column if not exists pickup_time time,
  add column if not exists pickup_location text,
  add column if not exists dropoff_location text,
  add column if not exists passenger_count integer not null default 1,
  add column if not exists luggage_count integer not null default 0,
  add column if not exists duration_hours numeric(8,2) not null default 1,
  add column if not exists extra_stops integer not null default 0,
  add column if not exists matched_rate_card_id bigint references public.limousine_rate_cards(id) on delete set null,
  add column if not exists matched_customer_rate_id bigint references public.customer_limousine_rates(id) on delete set null,
  add column if not exists pricing_source text default 'manual',
  add column if not exists rate_match_details jsonb;

update public.quotations
set pricing_source = case
  when matched_customer_rate_id is not null then 'customer_contract'
  when matched_rate_card_id is not null then 'standard'
  else 'manual'
end
where pricing_source is null or btrim(pricing_source) = '';

alter table public.quotations
  alter column pricing_source set default 'manual',
  alter column pricing_source set not null;

create index if not exists driver_jobs_customer_idx on public.driver_jobs(company_id, customer_id, job_date desc);
create index if not exists quotations_customer_rate_idx on public.quotations(company_id, customer_id, matched_customer_rate_id);

-- Customer-aware matcher. It inherits route, timing, capacity and surcharge rules
-- from Upgrade 1, then replaces the base fare with the active negotiated rate.
create or replace function public.match_limousine_rate_for_customer(
  p_company_id bigint,
  p_customer_id bigint,
  p_vehicle_type_id bigint,
  p_service_type text,
  p_service_date date default current_date,
  p_pickup_time time default null,
  p_pickup_location text default null,
  p_dropoff_location text default null,
  p_passengers integer default 0,
  p_luggage integer default 0,
  p_hours numeric default 1,
  p_extra_stops integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_standard jsonb;
  v_contract public.customer_limousine_rates%rowtype;
  v_rate public.limousine_rate_cards%rowtype;
  v_customer public.customers%rowtype;
  v_hours numeric := greatest(coalesce(p_hours, 1), 0);
  v_base numeric(14,2) := 0;
  v_extra numeric(14,2) := 0;
  v_charge_amount numeric(14,2) := 0;
  v_percentage numeric(14,4) := 0;
  v_charge jsonb;
  v_charges jsonb := '[]'::jsonb;
  v_rate_card_id bigint;
  v_pricing_method text;
  v_minimum_hours numeric;
  v_included_hours numeric;
  v_additional_hour_amount numeric;
begin
  if auth.uid() is null then
    return jsonb_build_object('matched', false, 'message', 'Authentication is required.');
  end if;

  if not public.is_app_administrator()
     and not exists (
       select 1
       from public.user_company_access access
       where access.user_id = auth.uid()
         and access.company_id = p_company_id
         and access.can_view = true
     ) then
    return jsonb_build_object('matched', false, 'message', 'Company access is required.');
  end if;

  v_standard := public.match_limousine_rate(
    p_company_id,
    p_vehicle_type_id,
    p_service_type,
    p_service_date,
    p_pickup_time,
    p_pickup_location,
    p_dropoff_location,
    p_passengers,
    p_luggage,
    p_hours,
    p_extra_stops
  );

  if not coalesce((v_standard ->> 'matched')::boolean, false) then
    return v_standard;
  end if;

  if p_customer_id is null then
    return v_standard || jsonb_build_object(
      'pricing_source', 'standard',
      'customer_id', null,
      'customer_rate_id', null
    );
  end if;

  select customer.* into v_customer
  from public.customers customer
  where customer.id = p_customer_id
    and customer.company_id = p_company_id
    and customer.status = 'active';

  if not found then
    return jsonb_build_object(
      'matched', false,
      'message', 'The selected active customer does not belong to this company.'
    );
  end if;

  v_rate_card_id := (v_standard ->> 'rate_card_id')::bigint;

  select contract_rate.* into v_contract
  from public.customer_limousine_rates contract_rate
  where contract_rate.company_id = p_company_id
    and contract_rate.customer_id = p_customer_id
    and contract_rate.rate_card_id = v_rate_card_id
    and contract_rate.is_active = true
    and coalesce(p_service_date, current_date) >= contract_rate.valid_from
    and (contract_rate.valid_to is null or coalesce(p_service_date, current_date) <= contract_rate.valid_to)
  order by contract_rate.priority desc, contract_rate.valid_from desc, contract_rate.id desc
  limit 1;

  if not found then
    return v_standard || jsonb_build_object(
      'pricing_source', 'standard',
      'customer_id', p_customer_id,
      'customer_name', v_customer.customer_name,
      'customer_rate_id', null
    );
  end if;

  select rate.* into strict v_rate
  from public.limousine_rate_cards rate
  where rate.id = v_rate_card_id;

  v_pricing_method := coalesce(v_contract.pricing_method, v_rate.pricing_method);
  v_minimum_hours := coalesce(v_contract.minimum_hours, v_rate.minimum_hours, 1);
  v_included_hours := coalesce(v_contract.included_hours, v_rate.included_hours, 0);
  v_additional_hour_amount := coalesce(
    v_contract.additional_hour_amount,
    v_rate.additional_hour_amount,
    0
  );

  if v_pricing_method = 'per_hour' then
    v_base := round(
      v_contract.override_base_amount * greatest(ceil(v_hours), ceil(v_minimum_hours)),
      2
    );
  else
    v_base := v_contract.override_base_amount + round(
      v_additional_hour_amount * greatest(ceil(v_hours - v_included_hours), 0),
      2
    );
  end if;

  for v_charge in
    select value from jsonb_array_elements(coalesce(v_standard -> 'charges', '[]'::jsonb))
  loop
    v_charge_amount := coalesce((v_charge ->> 'amount')::numeric, 0);

    if v_charge ->> 'charge_type' = 'percentage' then
      select rule.amount into v_percentage
      from public.limousine_extra_charge_rules rule
      where rule.id = (v_charge ->> 'rule_id')::bigint;
      v_charge_amount := round(v_base * coalesce(v_percentage, 0) / 100, 2);
    end if;

    v_extra := v_extra + v_charge_amount;
    v_charges := v_charges || jsonb_build_array(
      v_charge || jsonb_build_object('amount', v_charge_amount)
    );
  end loop;

  return v_standard || jsonb_build_object(
    'pricing_source', 'customer_contract',
    'customer_id', p_customer_id,
    'customer_name', v_customer.customer_name,
    'customer_rate_id', v_contract.id,
    'customer_rate_name', v_contract.contract_name,
    'standard_rate_name', v_rate.name,
    'rate_name', v_contract.contract_name,
    'pricing_method', v_pricing_method,
    'currency', v_contract.currency,
    'base_amount', round(v_base, 2),
    'extra_amount', round(v_extra, 2),
    'total_amount', round(v_base + v_extra, 2),
    'charges', v_charges
  );
end;
$$;

create or replace function public.validate_customer_limousine_rate()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer_company_id bigint;
  v_rate_company_id bigint;
  v_rate_currency text;
begin
  select customer.company_id
  into v_customer_company_id
  from public.customers customer
  where customer.id = new.customer_id;

  if v_customer_company_id is null or v_customer_company_id <> new.company_id then
    raise exception 'Customer contract rate company does not match the selected customer.';
  end if;

  select rate.company_id, upper(rate.currency)
  into v_rate_company_id, v_rate_currency
  from public.limousine_rate_cards rate
  where rate.id = new.rate_card_id;

  if v_rate_company_id is null or v_rate_company_id <> new.company_id then
    raise exception 'Customer contract rate company does not match the standard rate card.';
  end if;

  new.currency := upper(coalesce(nullif(btrim(new.currency), ''), v_rate_currency));
  if new.currency <> v_rate_currency then
    raise exception 'Customer contract currency must match the standard rate card currency (%).', v_rate_currency;
  end if;

  if new.valid_to is not null and new.valid_to < new.valid_from then
    raise exception 'Customer contract valid-to date cannot be earlier than valid-from date.';
  end if;

  new.override_base_amount := greatest(coalesce(new.override_base_amount, 0), 0);
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists customer_limousine_rates_validate on public.customer_limousine_rates;
create trigger customer_limousine_rates_validate
before insert or update on public.customer_limousine_rates
for each row execute function public.validate_customer_limousine_rate();

alter table public.customer_limousine_rates enable row level security;

grant select, insert, update, delete on public.customer_limousine_rates to authenticated;
grant usage, select on all sequences in schema public to authenticated;
revoke all on function public.match_limousine_rate_for_customer(
  bigint, bigint, bigint, text, date, time, text, text, integer, integer, numeric, integer
) from public, anon;
grant execute on function public.match_limousine_rate_for_customer(
  bigint, bigint, bigint, text, date, time, text, text, integer, integer, numeric, integer
) to authenticated;

drop policy if exists customer_limousine_rates_select_accessible on public.customer_limousine_rates;
create policy customer_limousine_rates_select_accessible
on public.customer_limousine_rates for select to authenticated
using (
  public.is_app_administrator()
  or exists (
    select 1 from public.user_company_access access
    where access.company_id = customer_limousine_rates.company_id
      and access.user_id = auth.uid()
      and access.can_view = true
  )
);

drop policy if exists customer_limousine_rates_write_administrator on public.customer_limousine_rates;
create policy customer_limousine_rates_write_administrator
on public.customer_limousine_rates for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

drop trigger if exists customer_limousine_rates_set_updated_at on public.customer_limousine_rates;
create trigger customer_limousine_rates_set_updated_at
before update on public.customer_limousine_rates
for each row execute function public.set_updated_at();

notify pgrst, 'reload schema';
commit;
