-- A3 MANAGEMENT FINANCE - UPGRADE 3
-- ACCOUNTS RECEIVABLE & PAYMENT COLLECTION
-- Run after 011_customer_contract_rates.sql.
-- Safe to rerun. Existing invoices and legacy amount-paid values are preserved.

begin;

alter table public.customer_invoices
  add column if not exists customer_id bigint references public.customers(id) on delete set null,
  add column if not exists currency text not null default 'SGD',
  add column if not exists payment_ledger_opening_amount numeric(14,2) not null default 0;

update public.customer_invoices
set currency = upper(coalesce(nullif(btrim(currency), ''), 'SGD'));

alter table public.customer_invoices
  alter column currency set default 'SGD',
  alter column currency set not null,
  alter column payment_ledger_opening_amount set default 0,
  alter column payment_ledger_opening_amount set not null;

create table if not exists public.customer_payments (
  id bigint generated by default as identity primary key,
  receipt_no text,
  company_id bigint not null references public.companies(id) on delete restrict,
  customer_id bigint references public.customers(id) on delete set null,
  customer_name text not null,
  payment_date date not null default current_date,
  currency text not null default 'SGD',
  amount numeric(14,2) not null check (amount > 0),
  allocated_amount numeric(14,2) not null default 0 check (allocated_amount >= 0),
  unallocated_amount numeric(14,2) not null default 0 check (unallocated_amount >= 0),
  payment_method text not null,
  payment_reference text,
  status text not null default 'posted' check (status in ('posted','void')),
  notes text,
  void_reason text,
  voided_by uuid references public.profiles(id) on delete set null,
  voided_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (currency ~ '^[A-Z]{3}$'),
  check (allocated_amount + unallocated_amount = amount)
);

-- Schema-safe compatibility for partial or earlier payment tables.
alter table public.customer_payments
  add column if not exists receipt_no text,
  add column if not exists company_id bigint references public.companies(id) on delete restrict,
  add column if not exists customer_id bigint references public.customers(id) on delete set null,
  add column if not exists customer_name text,
  add column if not exists payment_date date default current_date,
  add column if not exists currency text default 'SGD',
  add column if not exists amount numeric(14,2) default 0,
  add column if not exists allocated_amount numeric(14,2) default 0,
  add column if not exists unallocated_amount numeric(14,2) default 0,
  add column if not exists payment_method text,
  add column if not exists payment_reference text,
  add column if not exists status text default 'posted',
  add column if not exists notes text,
  add column if not exists void_reason text,
  add column if not exists voided_by uuid references public.profiles(id) on delete set null,
  add column if not exists voided_at timestamptz,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.customer_payments
set customer_name = coalesce(nullif(btrim(customer_name), ''), 'Customer'),
    payment_date = coalesce(payment_date, current_date),
    currency = upper(coalesce(nullif(btrim(currency), ''), 'SGD')),
    amount = greatest(coalesce(amount, 0), 0),
    allocated_amount = greatest(coalesce(allocated_amount, 0), 0),
    unallocated_amount = greatest(coalesce(unallocated_amount, amount - allocated_amount), 0),
    payment_method = coalesce(nullif(btrim(payment_method), ''), 'Other'),
    status = case when lower(coalesce(status, 'posted')) = 'void' then 'void' else 'posted' end,
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

create table if not exists public.customer_payment_allocations (
  id bigint generated by default as identity primary key,
  payment_id bigint not null references public.customer_payments(id) on delete cascade,
  invoice_id bigint not null references public.customer_invoices(id) on delete restrict,
  allocated_amount numeric(14,2) not null check (allocated_amount > 0),
  created_at timestamptz not null default now(),
  unique(payment_id, invoice_id)
);

alter table public.customer_payment_allocations
  add column if not exists payment_id bigint references public.customer_payments(id) on delete cascade,
  add column if not exists invoice_id bigint references public.customer_invoices(id) on delete restrict,
  add column if not exists allocated_amount numeric(14,2) default 0,
  add column if not exists created_at timestamptz default now();

update public.customer_payment_allocations
set allocated_amount = greatest(coalesce(allocated_amount, 0), 0),
    created_at = coalesce(created_at, now());

-- Preserve pre-upgrade amount-paid values exactly once as the opening ledger
-- balance. Do not copy ledger-calculated amounts again when this migration is rerun.
update public.customer_invoices invoice
set payment_ledger_opening_amount = greatest(coalesce(invoice.amount_paid, 0), 0)
where coalesce(invoice.payment_ledger_opening_amount, 0) = 0
  and coalesce(invoice.amount_paid, 0) > 0
  and not exists (
    select 1
    from public.customer_payment_allocations allocation
    where allocation.invoice_id = invoice.id
  );

create unique index if not exists customer_payments_receipt_no_uidx
  on public.customer_payments(lower(receipt_no))
  where receipt_no is not null;
create index if not exists customer_payments_company_date_idx
  on public.customer_payments(company_id, payment_date desc, id desc);
create index if not exists customer_payments_customer_idx
  on public.customer_payments(company_id, customer_id, status, payment_date desc);
create unique index if not exists customer_payment_allocations_payment_invoice_uidx
  on public.customer_payment_allocations(payment_id, invoice_id);
create index if not exists customer_payment_allocations_payment_idx
  on public.customer_payment_allocations(payment_id);
create index if not exists customer_payment_allocations_invoice_idx
  on public.customer_payment_allocations(invoice_id);
create index if not exists customer_invoices_receivable_idx
  on public.customer_invoices(company_id, status, due_date, invoice_date desc);

create or replace function public.assign_customer_payment_receipt_no()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.receipt_no is null or btrim(new.receipt_no) = '' then
    new.receipt_no := 'RCPT-' ||
      to_char(coalesce(new.payment_date, current_date), 'YYYYMMDD') || '-' ||
      lpad(new.id::text, 5, '0');
  end if;
  new.currency := upper(coalesce(nullif(btrim(new.currency), ''), 'SGD'));
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists customer_payments_assign_receipt_no on public.customer_payments;
create trigger customer_payments_assign_receipt_no
before insert or update on public.customer_payments
for each row execute function public.assign_customer_payment_receipt_no();

create or replace function public.refresh_customer_invoice_payment_state(p_invoice_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invoice public.customer_invoices%rowtype;
  v_allocated numeric(14,2) := 0;
  v_paid numeric(14,2) := 0;
  v_status text;
begin
  select * into v_invoice
  from public.customer_invoices
  where id = p_invoice_id
  for update;

  if not found then
    return;
  end if;

  select coalesce(sum(allocation.allocated_amount), 0)
  into v_allocated
  from public.customer_payment_allocations allocation
  join public.customer_payments payment on payment.id = allocation.payment_id
  where allocation.invoice_id = p_invoice_id
    and payment.status = 'posted';

  v_paid := least(
    greatest(coalesce(v_invoice.total_amount, 0), 0),
    greatest(coalesce(v_invoice.payment_ledger_opening_amount, 0), 0) + greatest(v_allocated, 0)
  );

  if v_invoice.status = 'cancelled' then
    v_status := 'cancelled';
  elsif v_paid >= coalesce(v_invoice.total_amount, 0) and coalesce(v_invoice.total_amount, 0) > 0 then
    v_status := 'paid';
  elsif v_paid > 0 then
    v_status := 'partial';
  elsif v_invoice.due_date is not null and v_invoice.due_date < current_date then
    v_status := 'overdue';
  elsif v_invoice.status = 'draft' then
    v_status := 'draft';
  else
    v_status := 'issued';
  end if;

  update public.customer_invoices
  set amount_paid = round(v_paid, 2),
      status = v_status,
      updated_at = now()
  where id = p_invoice_id;
end;
$$;

create or replace function public.protect_customer_invoice_ledger_amount()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_allocated numeric(14,2) := 0;
  v_has_allocations boolean := false;
begin
  if tg_op = 'INSERT' then
    new.payment_ledger_opening_amount := greatest(coalesce(new.amount_paid, 0), 0);
    return new;
  end if;

  select exists (
    select 1
    from public.customer_payment_allocations allocation
    join public.customer_payments payment on payment.id = allocation.payment_id
    where allocation.invoice_id = old.id
      and payment.status = 'posted'
  ) into v_has_allocations;

  if not v_has_allocations then
    if new.amount_paid is distinct from old.amount_paid then
      new.payment_ledger_opening_amount := greatest(coalesce(new.amount_paid, 0), 0);
    end if;
    return new;
  end if;

  select coalesce(sum(allocation.allocated_amount), 0)
  into v_allocated
  from public.customer_payment_allocations allocation
  join public.customer_payments payment on payment.id = allocation.payment_id
  where allocation.invoice_id = old.id
    and payment.status = 'posted';

  new.amount_paid := least(
    greatest(coalesce(new.total_amount, 0), 0),
    greatest(coalesce(old.payment_ledger_opening_amount, 0), 0) + greatest(v_allocated, 0)
  );

  if old.status = 'cancelled' or new.status = 'cancelled' then
    new.status := 'cancelled';
  elsif new.amount_paid >= coalesce(new.total_amount, 0) and coalesce(new.total_amount, 0) > 0 then
    new.status := 'paid';
  elsif new.amount_paid > 0 then
    new.status := 'partial';
  elsif new.due_date is not null and new.due_date < current_date then
    new.status := 'overdue';
  elsif old.status = 'draft' and new.status = 'draft' then
    new.status := 'draft';
  else
    new.status := 'issued';
  end if;

  return new;
end;
$$;

drop trigger if exists customer_invoices_protect_ledger_amount on public.customer_invoices;
create trigger customer_invoices_protect_ledger_amount
before insert or update of amount_paid, total_amount, due_date, status
on public.customer_invoices
for each row execute function public.protect_customer_invoice_ledger_amount();

create or replace function public.record_customer_payment(
  p_company_id bigint,
  p_customer_id bigint,
  p_customer_name text,
  p_payment_date date,
  p_currency text,
  p_amount numeric,
  p_payment_method text,
  p_payment_reference text default null,
  p_notes text default null,
  p_allocations jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_payment_id bigint;
  v_customer_name text := nullif(btrim(coalesce(p_customer_name, '')), '');
  v_customer public.customers%rowtype;
  v_allocation jsonb;
  v_invoice public.customer_invoices%rowtype;
  v_invoice_id bigint;
  v_amount numeric(14,2);
  v_allocated numeric(14,2) := 0;
  v_balance numeric(14,2);
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;
  if not public.is_app_administrator() then
    raise exception 'Administrator access is required.';
  end if;
  if p_company_id is null or not exists (
    select 1 from public.companies where id = p_company_id
  ) then
    raise exception 'A valid company is required.';
  end if;
  if coalesce(p_amount, 0) <= 0 then
    raise exception 'Payment amount must be greater than zero.';
  end if;
  if nullif(btrim(coalesce(p_payment_method, '')), '') is null then
    raise exception 'Payment method is required.';
  end if;
  if jsonb_typeof(coalesce(p_allocations, '[]'::jsonb)) <> 'array' then
    raise exception 'Payment allocations must be an array.';
  end if;

  if p_customer_id is not null then
    select * into v_customer
    from public.customers
    where id = p_customer_id
      and company_id = p_company_id;
    if not found then
      raise exception 'The selected customer does not belong to this company.';
    end if;
    v_customer_name := v_customer.customer_name;
  end if;

  if v_customer_name is null then
    raise exception 'Customer name is required.';
  end if;

  insert into public.customer_payments (
    company_id,
    customer_id,
    customer_name,
    payment_date,
    currency,
    amount,
    allocated_amount,
    unallocated_amount,
    payment_method,
    payment_reference,
    notes,
    created_by
  ) values (
    p_company_id,
    p_customer_id,
    v_customer_name,
    coalesce(p_payment_date, current_date),
    upper(coalesce(nullif(btrim(p_currency), ''), 'SGD')),
    round(p_amount, 2),
    0,
    round(p_amount, 2),
    btrim(p_payment_method),
    nullif(btrim(coalesce(p_payment_reference, '')), ''),
    nullif(btrim(coalesce(p_notes, '')), ''),
    v_user_id
  ) returning id into v_payment_id;

  for v_allocation in
    select value from jsonb_array_elements(coalesce(p_allocations, '[]'::jsonb))
  loop
    begin
      v_invoice_id := (v_allocation ->> 'invoice_id')::bigint;
      v_amount := round((v_allocation ->> 'amount')::numeric, 2);
    exception when others then
      raise exception 'Every allocation requires a valid invoice and amount.';
    end;

    if v_amount <= 0 then
      raise exception 'Every allocation amount must be greater than zero.';
    end if;

    select * into v_invoice
    from public.customer_invoices
    where id = v_invoice_id
    for update;

    if not found then
      raise exception 'Invoice % was not found.', v_invoice_id;
    end if;
    if v_invoice.company_id <> p_company_id then
      raise exception 'Invoice % belongs to another company.', coalesce(v_invoice.invoice_no, v_invoice.id::text);
    end if;
    if upper(coalesce(v_invoice.currency, 'SGD')) <> upper(coalesce(p_currency, 'SGD')) then
      raise exception 'Invoice % uses a different currency.', coalesce(v_invoice.invoice_no, v_invoice.id::text);
    end if;
    if v_invoice.status = 'cancelled' then
      raise exception 'Cancelled invoice % cannot receive payment.', coalesce(v_invoice.invoice_no, v_invoice.id::text);
    end if;
    if p_customer_id is not null and v_invoice.customer_id is not null and v_invoice.customer_id <> p_customer_id then
      raise exception 'Invoice % belongs to another customer.', coalesce(v_invoice.invoice_no, v_invoice.id::text);
    end if;

    v_balance := greatest(coalesce(v_invoice.total_amount, 0) - coalesce(v_invoice.amount_paid, 0), 0);
    if v_amount > v_balance then
      raise exception 'Allocation for invoice % exceeds its outstanding balance of %.',
        coalesce(v_invoice.invoice_no, v_invoice.id::text),
        to_char(v_balance, 'FM9999999990.00');
    end if;

    v_allocated := v_allocated + v_amount;
    if v_allocated > round(p_amount, 2) then
      raise exception 'Total invoice allocations exceed the payment amount.';
    end if;

    insert into public.customer_payment_allocations(payment_id, invoice_id, allocated_amount)
    values (v_payment_id, v_invoice_id, v_amount);
  end loop;

  update public.customer_payments
  set allocated_amount = round(v_allocated, 2),
      unallocated_amount = round(p_amount - v_allocated, 2),
      updated_at = now()
  where id = v_payment_id;

  for v_invoice_id in
    select distinct invoice_id
    from public.customer_payment_allocations
    where payment_id = v_payment_id
  loop
    perform public.refresh_customer_invoice_payment_state(v_invoice_id);
  end loop;

  return (
    select jsonb_build_object(
      'success', true,
      'payment_id', payment.id,
      'receipt_no', payment.receipt_no,
      'amount', payment.amount,
      'allocated_amount', payment.allocated_amount,
      'unallocated_amount', payment.unallocated_amount
    )
    from public.customer_payments payment
    where payment.id = v_payment_id
  );
end;
$$;

create or replace function public.allocate_customer_payment_credit(
  p_payment_id bigint,
  p_allocations jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_payment public.customer_payments%rowtype;
  v_allocation jsonb;
  v_invoice public.customer_invoices%rowtype;
  v_invoice_id bigint;
  v_amount numeric(14,2);
  v_applied numeric(14,2) := 0;
  v_balance numeric(14,2);
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;
  if not public.is_app_administrator() then
    raise exception 'Administrator access is required.';
  end if;
  if jsonb_typeof(coalesce(p_allocations, '[]'::jsonb)) <> 'array'
     or jsonb_array_length(coalesce(p_allocations, '[]'::jsonb)) = 0 then
    raise exception 'Select at least one invoice allocation.';
  end if;

  select * into v_payment
  from public.customer_payments
  where id = p_payment_id
  for update;

  if not found then
    raise exception 'Payment receipt was not found.';
  end if;
  if v_payment.status <> 'posted' then
    raise exception 'Only a posted payment can apply customer credit.';
  end if;
  if v_payment.unallocated_amount <= 0 then
    raise exception 'This payment has no unallocated customer credit.';
  end if;

  for v_allocation in
    select value from jsonb_array_elements(p_allocations)
  loop
    begin
      v_invoice_id := (v_allocation ->> 'invoice_id')::bigint;
      v_amount := round((v_allocation ->> 'amount')::numeric, 2);
    exception when others then
      raise exception 'Every allocation requires a valid invoice and amount.';
    end;

    if v_amount <= 0 then
      raise exception 'Every allocation amount must be greater than zero.';
    end if;

    select * into v_invoice
    from public.customer_invoices
    where id = v_invoice_id
    for update;

    if not found then
      raise exception 'Invoice % was not found.', v_invoice_id;
    end if;
    if v_invoice.company_id <> v_payment.company_id then
      raise exception 'Invoice % belongs to another company.', coalesce(v_invoice.invoice_no, v_invoice.id::text);
    end if;
    if upper(coalesce(v_invoice.currency, 'SGD')) <> upper(v_payment.currency) then
      raise exception 'Invoice % uses a different currency.', coalesce(v_invoice.invoice_no, v_invoice.id::text);
    end if;
    if v_invoice.status = 'cancelled' then
      raise exception 'Cancelled invoice % cannot receive payment.', coalesce(v_invoice.invoice_no, v_invoice.id::text);
    end if;
    if v_payment.customer_id is not null
       and v_invoice.customer_id is not null
       and v_invoice.customer_id <> v_payment.customer_id then
      raise exception 'Invoice % belongs to another customer.', coalesce(v_invoice.invoice_no, v_invoice.id::text);
    end if;

    v_balance := greatest(coalesce(v_invoice.total_amount, 0) - coalesce(v_invoice.amount_paid, 0), 0);
    if v_amount > v_balance then
      raise exception 'Allocation for invoice % exceeds its outstanding balance of %.',
        coalesce(v_invoice.invoice_no, v_invoice.id::text),
        to_char(v_balance, 'FM9999999990.00');
    end if;

    v_applied := v_applied + v_amount;
    if v_applied > v_payment.unallocated_amount then
      raise exception 'Allocations exceed the available customer credit of %.',
        to_char(v_payment.unallocated_amount, 'FM9999999990.00');
    end if;

    insert into public.customer_payment_allocations(payment_id, invoice_id, allocated_amount)
    values (v_payment.id, v_invoice_id, v_amount)
    on conflict(payment_id, invoice_id)
    do update set allocated_amount = public.customer_payment_allocations.allocated_amount + excluded.allocated_amount;
  end loop;

  update public.customer_payments
  set allocated_amount = round(allocated_amount + v_applied, 2),
      unallocated_amount = round(unallocated_amount - v_applied, 2),
      updated_at = now()
  where id = v_payment.id;

  for v_invoice_id in
    select distinct invoice_id
    from public.customer_payment_allocations
    where payment_id = v_payment.id
  loop
    perform public.refresh_customer_invoice_payment_state(v_invoice_id);
  end loop;

  return (
    select jsonb_build_object(
      'success', true,
      'payment_id', payment.id,
      'receipt_no', payment.receipt_no,
      'allocated_amount', payment.allocated_amount,
      'unallocated_amount', payment.unallocated_amount
    )
    from public.customer_payments payment
    where payment.id = v_payment.id
  );
end;
$$;

create or replace function public.void_customer_payment(
  p_payment_id bigint,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_payment public.customer_payments%rowtype;
  v_invoice_id bigint;
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;
  if not public.is_app_administrator() then
    raise exception 'Administrator access is required.';
  end if;
  if nullif(btrim(coalesce(p_reason, '')), '') is null then
    raise exception 'A reversal reason is required.';
  end if;

  select * into v_payment
  from public.customer_payments
  where id = p_payment_id
  for update;

  if not found then
    raise exception 'Payment receipt was not found.';
  end if;
  if v_payment.status = 'void' then
    return jsonb_build_object(
      'success', true,
      'payment_id', v_payment.id,
      'receipt_no', v_payment.receipt_no,
      'status', 'void'
    );
  end if;

  update public.customer_payments
  set status = 'void',
      void_reason = btrim(p_reason),
      voided_by = v_user_id,
      voided_at = now(),
      updated_at = now()
  where id = p_payment_id;

  for v_invoice_id in
    select distinct invoice_id
    from public.customer_payment_allocations
    where payment_id = p_payment_id
  loop
    perform public.refresh_customer_invoice_payment_state(v_invoice_id);
  end loop;

  return jsonb_build_object(
    'success', true,
    'payment_id', v_payment.id,
    'receipt_no', v_payment.receipt_no,
    'status', 'void'
  );
end;
$$;

alter table public.customer_payments enable row level security;
alter table public.customer_payment_allocations enable row level security;

grant select, insert, update, delete on public.customer_payments to authenticated;
grant select, insert, update, delete on public.customer_payment_allocations to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.record_customer_payment(bigint,bigint,text,date,text,numeric,text,text,text,jsonb) to authenticated;
grant execute on function public.allocate_customer_payment_credit(bigint,jsonb) to authenticated;
grant execute on function public.void_customer_payment(bigint,text) to authenticated;
grant execute on function public.refresh_customer_invoice_payment_state(bigint) to authenticated;

drop policy if exists customer_payments_administrator_all on public.customer_payments;
create policy customer_payments_administrator_all on public.customer_payments
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

drop policy if exists customer_payment_allocations_administrator_all on public.customer_payment_allocations;
create policy customer_payment_allocations_administrator_all on public.customer_payment_allocations
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

notify pgrst, 'reload schema';
commit;
