-- A3 MANAGEMENT FINANCE - UPGRADE 4
-- ACCOUNTS PAYABLE & SUPPLIER PAYMENTS
-- Run after 012_accounts_receivable_payment_collection.sql.
-- Safe to rerun. Existing finance, job and receivable records are preserved.

begin;

-- -----------------------------------------------------------------------------
-- 1. SUPPLIER MASTER
-- -----------------------------------------------------------------------------
create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete restrict,
  supplier_no text,
  supplier_name text not null,
  contact_person text,
  email text,
  phone text,
  billing_address text,
  uen text,
  default_currency text not null default 'SGD',
  payment_terms_days integer not null default 30,
  bank_name text,
  bank_account_name text,
  bank_account_no text,
  paynow_details text,
  status text not null default 'active',
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (default_currency ~ '^[A-Z]{3}$'),
  check (payment_terms_days between 0 and 3650),
  check (status in ('active','inactive'))
);

alter table public.suppliers
  add column if not exists company_id bigint references public.companies(id) on delete restrict,
  add column if not exists supplier_no text,
  add column if not exists supplier_name text,
  add column if not exists contact_person text,
  add column if not exists email text,
  add column if not exists phone text,
  add column if not exists billing_address text,
  add column if not exists uen text,
  add column if not exists default_currency text default 'SGD',
  add column if not exists payment_terms_days integer default 30,
  add column if not exists bank_name text,
  add column if not exists bank_account_name text,
  add column if not exists bank_account_no text,
  add column if not exists paynow_details text,
  add column if not exists status text default 'active',
  add column if not exists notes text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.suppliers
set supplier_name = coalesce(nullif(btrim(supplier_name), ''), 'Supplier ' || id::text),
    supplier_no = coalesce(nullif(btrim(supplier_no), ''), 'SUP-' || lpad(id::text, 5, '0')),
    default_currency = upper(coalesce(nullif(btrim(default_currency), ''), 'SGD')),
    payment_terms_days = greatest(coalesce(payment_terms_days, 30), 0),
    status = case when lower(coalesce(status, 'active')) = 'inactive' then 'inactive' else 'active' end,
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

update public.suppliers duplicate
set supplier_no = duplicate.supplier_no || '-DUP-' || duplicate.id::text
where duplicate.supplier_no is not null
  and exists (
    select 1 from public.suppliers original
    where original.company_id = duplicate.company_id
      and lower(original.supplier_no) = lower(duplicate.supplier_no)
      and original.id < duplicate.id
  );

create unique index if not exists suppliers_company_no_uidx
  on public.suppliers(company_id, lower(supplier_no))
  where supplier_no is not null;
create index if not exists suppliers_company_name_idx
  on public.suppliers(company_id, lower(supplier_name), status);

create or replace function public.prepare_supplier_record()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.supplier_name := coalesce(nullif(btrim(new.supplier_name), ''), 'Supplier');
  new.default_currency := upper(coalesce(nullif(btrim(new.default_currency), ''), 'SGD'));
  new.payment_terms_days := greatest(coalesce(new.payment_terms_days, 30), 0);
  new.status := case when lower(coalesce(new.status, 'active')) = 'inactive' then 'inactive' else 'active' end;
  if new.supplier_no is null or btrim(new.supplier_no) = '' then
    new.supplier_no := 'SUP-' || lpad(new.id::text, 5, '0');
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists suppliers_prepare_record on public.suppliers;
create trigger suppliers_prepare_record
before insert or update on public.suppliers
for each row execute function public.prepare_supplier_record();

-- -----------------------------------------------------------------------------
-- 2. SUPPLIER BILLS
-- -----------------------------------------------------------------------------
create table if not exists public.supplier_bills (
  id bigint generated by default as identity primary key,
  bill_no text,
  company_id bigint not null references public.companies(id) on delete restrict,
  supplier_id bigint not null references public.suppliers(id) on delete restrict,
  supplier_name text not null,
  supplier_invoice_no text,
  bill_date date not null default current_date,
  due_date date,
  currency text not null default 'SGD',
  subtotal numeric(14,2) not null default 0,
  gst_amount numeric(14,2) not null default 0,
  total_amount numeric(14,2) not null default 0,
  payment_ledger_opening_amount numeric(14,2) not null default 0,
  amount_paid numeric(14,2) not null default 0,
  credit_applied numeric(14,2) not null default 0,
  status text not null default 'open',
  expense_category text,
  reference text,
  description text,
  notes text,
  cancelled_reason text,
  cancelled_by uuid references public.profiles(id) on delete set null,
  cancelled_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (currency ~ '^[A-Z]{3}$'),
  check (subtotal >= 0 and gst_amount >= 0 and total_amount >= 0),
  check (payment_ledger_opening_amount >= 0 and amount_paid >= 0 and credit_applied >= 0),
  check (status in ('draft','open','partial','paid','overdue','cancelled'))
);

alter table public.supplier_bills
  add column if not exists bill_no text,
  add column if not exists company_id bigint references public.companies(id) on delete restrict,
  add column if not exists supplier_id bigint references public.suppliers(id) on delete restrict,
  add column if not exists supplier_name text,
  add column if not exists supplier_invoice_no text,
  add column if not exists bill_date date default current_date,
  add column if not exists due_date date,
  add column if not exists currency text default 'SGD',
  add column if not exists subtotal numeric(14,2) default 0,
  add column if not exists gst_amount numeric(14,2) default 0,
  add column if not exists total_amount numeric(14,2) default 0,
  add column if not exists payment_ledger_opening_amount numeric(14,2) default 0,
  add column if not exists amount_paid numeric(14,2) default 0,
  add column if not exists credit_applied numeric(14,2) default 0,
  add column if not exists status text default 'open',
  add column if not exists expense_category text,
  add column if not exists reference text,
  add column if not exists description text,
  add column if not exists notes text,
  add column if not exists cancelled_reason text,
  add column if not exists cancelled_by uuid references public.profiles(id) on delete set null,
  add column if not exists cancelled_at timestamptz,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.supplier_bills
set supplier_name = coalesce(nullif(btrim(supplier_name), ''), 'Supplier'),
    bill_date = coalesce(bill_date, current_date),
    currency = upper(coalesce(nullif(btrim(currency), ''), 'SGD')),
    subtotal = greatest(coalesce(subtotal, 0), 0),
    gst_amount = greatest(coalesce(gst_amount, 0), 0),
    total_amount = greatest(
      case when coalesce(total_amount, 0) > 0 then total_amount else coalesce(subtotal, 0) + coalesce(gst_amount, 0) end,
      0
    ),
    payment_ledger_opening_amount = greatest(coalesce(payment_ledger_opening_amount, 0), 0),
    amount_paid = greatest(coalesce(amount_paid, 0), 0),
    credit_applied = greatest(coalesce(credit_applied, 0), 0),
    status = case
      when lower(coalesce(status, 'open')) = 'cancelled' then 'cancelled'
      when lower(coalesce(status, 'open')) = 'paid' then 'paid'
      when lower(coalesce(status, 'open')) = 'partial' then 'partial'
      when lower(coalesce(status, 'open')) = 'draft' then 'draft'
      when due_date is not null and due_date < current_date then 'overdue'
      else 'open'
    end,
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

create table if not exists public.supplier_bill_items (
  id bigint generated by default as identity primary key,
  bill_id bigint not null references public.supplier_bills(id) on delete cascade,
  description text not null,
  quantity numeric(12,2) not null default 1,
  unit_price numeric(14,2) not null default 0,
  line_total numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  check (quantity > 0 and unit_price >= 0 and line_total >= 0)
);

alter table public.supplier_bill_items
  add column if not exists bill_id bigint references public.supplier_bills(id) on delete cascade,
  add column if not exists description text,
  add column if not exists quantity numeric(12,2) default 1,
  add column if not exists unit_price numeric(14,2) default 0,
  add column if not exists line_total numeric(14,2) default 0,
  add column if not exists created_at timestamptz default now();

update public.supplier_bills duplicate
set bill_no = duplicate.bill_no || '-DUP-' || duplicate.id::text
where duplicate.bill_no is not null
  and exists (
    select 1 from public.supplier_bills original
    where original.company_id = duplicate.company_id
      and lower(original.bill_no) = lower(duplicate.bill_no)
      and original.id < duplicate.id
  );

create unique index if not exists supplier_bills_company_no_uidx
  on public.supplier_bills(company_id, lower(bill_no))
  where bill_no is not null;
create index if not exists supplier_bills_supplier_due_idx
  on public.supplier_bills(company_id, supplier_id, status, due_date, bill_date desc);
create index if not exists supplier_bill_items_bill_idx
  on public.supplier_bill_items(bill_id);

create or replace function public.prepare_supplier_bill()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.currency := upper(coalesce(nullif(btrim(new.currency), ''), 'SGD'));
  new.subtotal := round(greatest(coalesce(new.subtotal, 0), 0), 2);
  new.gst_amount := round(greatest(coalesce(new.gst_amount, 0), 0), 2);
  new.total_amount := round(greatest(coalesce(new.total_amount, new.subtotal + new.gst_amount), 0), 2);
  if new.total_amount = 0 and new.subtotal + new.gst_amount > 0 then
    new.total_amount := round(new.subtotal + new.gst_amount, 2);
  end if;
  if new.bill_no is null or btrim(new.bill_no) = '' then
    new.bill_no := 'BILL-' || to_char(coalesce(new.bill_date, current_date), 'YYYYMMDD') || '-' || lpad(new.id::text, 5, '0');
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists supplier_bills_prepare_record on public.supplier_bills;
create trigger supplier_bills_prepare_record
before insert or update on public.supplier_bills
for each row execute function public.prepare_supplier_bill();

-- -----------------------------------------------------------------------------
-- 3. SUPPLIER PAYMENTS AND ALLOCATIONS
-- -----------------------------------------------------------------------------
create table if not exists public.supplier_payments (
  id bigint generated by default as identity primary key,
  voucher_no text,
  company_id bigint not null references public.companies(id) on delete restrict,
  supplier_id bigint not null references public.suppliers(id) on delete restrict,
  supplier_name text not null,
  payment_date date not null default current_date,
  currency text not null default 'SGD',
  amount numeric(14,2) not null,
  allocated_amount numeric(14,2) not null default 0,
  unallocated_amount numeric(14,2) not null default 0,
  payment_method text not null,
  payment_reference text,
  bank_account text,
  status text not null default 'posted',
  notes text,
  void_reason text,
  voided_by uuid references public.profiles(id) on delete set null,
  voided_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (currency ~ '^[A-Z]{3}$'),
  check (amount > 0 and allocated_amount >= 0 and unallocated_amount >= 0),
  check (status in ('posted','void')),
  check (allocated_amount + unallocated_amount = amount)
);

alter table public.supplier_payments
  add column if not exists voucher_no text,
  add column if not exists company_id bigint references public.companies(id) on delete restrict,
  add column if not exists supplier_id bigint references public.suppliers(id) on delete restrict,
  add column if not exists supplier_name text,
  add column if not exists payment_date date default current_date,
  add column if not exists currency text default 'SGD',
  add column if not exists amount numeric(14,2) default 0,
  add column if not exists allocated_amount numeric(14,2) default 0,
  add column if not exists unallocated_amount numeric(14,2) default 0,
  add column if not exists payment_method text,
  add column if not exists payment_reference text,
  add column if not exists bank_account text,
  add column if not exists status text default 'posted',
  add column if not exists notes text,
  add column if not exists void_reason text,
  add column if not exists voided_by uuid references public.profiles(id) on delete set null,
  add column if not exists voided_at timestamptz,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.supplier_payments
set supplier_name = coalesce(nullif(btrim(supplier_name), ''), 'Supplier'),
    payment_date = coalesce(payment_date, current_date),
    currency = upper(coalesce(nullif(btrim(currency), ''), 'SGD')),
    amount = greatest(coalesce(amount, 0), 0),
    allocated_amount = least(greatest(coalesce(allocated_amount, 0), 0), greatest(coalesce(amount, 0), 0)),
    unallocated_amount = greatest(
      greatest(coalesce(amount, 0), 0) - least(greatest(coalesce(allocated_amount, 0), 0), greatest(coalesce(amount, 0), 0)),
      0
    ),
    payment_method = coalesce(nullif(btrim(payment_method), ''), 'Other'),
    status = case when lower(coalesce(status, 'posted')) = 'void' then 'void' else 'posted' end,
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

create table if not exists public.supplier_payment_allocations (
  id bigint generated by default as identity primary key,
  payment_id bigint not null references public.supplier_payments(id) on delete cascade,
  bill_id bigint not null references public.supplier_bills(id) on delete restrict,
  allocated_amount numeric(14,2) not null,
  created_at timestamptz not null default now(),
  unique(payment_id, bill_id),
  check (allocated_amount > 0)
);

alter table public.supplier_payment_allocations
  add column if not exists payment_id bigint references public.supplier_payments(id) on delete cascade,
  add column if not exists bill_id bigint references public.supplier_bills(id) on delete restrict,
  add column if not exists allocated_amount numeric(14,2) default 0,
  add column if not exists created_at timestamptz default now();

update public.supplier_payments duplicate
set voucher_no = duplicate.voucher_no || '-DUP-' || duplicate.id::text
where duplicate.voucher_no is not null
  and exists (
    select 1 from public.supplier_payments original
    where lower(original.voucher_no) = lower(duplicate.voucher_no)
      and original.id < duplicate.id
  );

create unique index if not exists supplier_payments_voucher_no_uidx
  on public.supplier_payments(lower(voucher_no))
  where voucher_no is not null;
create index if not exists supplier_payments_company_date_idx
  on public.supplier_payments(company_id, payment_date desc, id desc);
create index if not exists supplier_payment_allocations_payment_idx
  on public.supplier_payment_allocations(payment_id);
create index if not exists supplier_payment_allocations_bill_idx
  on public.supplier_payment_allocations(bill_id);

create or replace function public.prepare_supplier_payment()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.voucher_no is null or btrim(new.voucher_no) = '' then
    new.voucher_no := 'PV-' || to_char(coalesce(new.payment_date, current_date), 'YYYYMMDD') || '-' || lpad(new.id::text, 5, '0');
  end if;
  new.currency := upper(coalesce(nullif(btrim(new.currency), ''), 'SGD'));
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists supplier_payments_prepare_record on public.supplier_payments;
create trigger supplier_payments_prepare_record
before insert or update on public.supplier_payments
for each row execute function public.prepare_supplier_payment();

-- -----------------------------------------------------------------------------
-- 4. SUPPLIER CREDIT NOTES
-- -----------------------------------------------------------------------------
create table if not exists public.supplier_credit_notes (
  id bigint generated by default as identity primary key,
  credit_note_no text,
  company_id bigint not null references public.companies(id) on delete restrict,
  supplier_id bigint not null references public.suppliers(id) on delete restrict,
  supplier_name text not null,
  credit_date date not null default current_date,
  currency text not null default 'SGD',
  amount numeric(14,2) not null,
  applied_amount numeric(14,2) not null default 0,
  unapplied_amount numeric(14,2) not null default 0,
  supplier_reference text,
  reason text not null,
  status text not null default 'posted',
  notes text,
  void_reason text,
  voided_by uuid references public.profiles(id) on delete set null,
  voided_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (currency ~ '^[A-Z]{3}$'),
  check (amount > 0 and applied_amount >= 0 and unapplied_amount >= 0),
  check (status in ('posted','void')),
  check (applied_amount + unapplied_amount = amount)
);

alter table public.supplier_credit_notes
  add column if not exists credit_note_no text,
  add column if not exists company_id bigint references public.companies(id) on delete restrict,
  add column if not exists supplier_id bigint references public.suppliers(id) on delete restrict,
  add column if not exists supplier_name text,
  add column if not exists credit_date date default current_date,
  add column if not exists currency text default 'SGD',
  add column if not exists amount numeric(14,2) default 0,
  add column if not exists applied_amount numeric(14,2) default 0,
  add column if not exists unapplied_amount numeric(14,2) default 0,
  add column if not exists supplier_reference text,
  add column if not exists reason text,
  add column if not exists status text default 'posted',
  add column if not exists notes text,
  add column if not exists void_reason text,
  add column if not exists voided_by uuid references public.profiles(id) on delete set null,
  add column if not exists voided_at timestamptz,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.supplier_credit_notes
set supplier_name = coalesce(nullif(btrim(supplier_name), ''), 'Supplier'),
    credit_date = coalesce(credit_date, current_date),
    currency = upper(coalesce(nullif(btrim(currency), ''), 'SGD')),
    amount = greatest(coalesce(amount, 0), 0),
    applied_amount = least(greatest(coalesce(applied_amount, 0), 0), greatest(coalesce(amount, 0), 0)),
    unapplied_amount = greatest(
      greatest(coalesce(amount, 0), 0) - least(greatest(coalesce(applied_amount, 0), 0), greatest(coalesce(amount, 0), 0)),
      0
    ),
    reason = coalesce(nullif(btrim(reason), ''), 'Supplier credit'),
    status = case when lower(coalesce(status, 'posted')) = 'void' then 'void' else 'posted' end,
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

create table if not exists public.supplier_credit_allocations (
  id bigint generated by default as identity primary key,
  credit_note_id bigint not null references public.supplier_credit_notes(id) on delete cascade,
  bill_id bigint not null references public.supplier_bills(id) on delete restrict,
  allocated_amount numeric(14,2) not null,
  created_at timestamptz not null default now(),
  unique(credit_note_id, bill_id),
  check (allocated_amount > 0)
);

alter table public.supplier_credit_allocations
  add column if not exists credit_note_id bigint references public.supplier_credit_notes(id) on delete cascade,
  add column if not exists bill_id bigint references public.supplier_bills(id) on delete restrict,
  add column if not exists allocated_amount numeric(14,2) default 0,
  add column if not exists created_at timestamptz default now();

update public.supplier_credit_notes duplicate
set credit_note_no = duplicate.credit_note_no || '-DUP-' || duplicate.id::text
where duplicate.credit_note_no is not null
  and exists (
    select 1 from public.supplier_credit_notes original
    where lower(original.credit_note_no) = lower(duplicate.credit_note_no)
      and original.id < duplicate.id
  );

create unique index if not exists supplier_credit_notes_no_uidx
  on public.supplier_credit_notes(lower(credit_note_no))
  where credit_note_no is not null;
create index if not exists supplier_credit_notes_company_date_idx
  on public.supplier_credit_notes(company_id, credit_date desc, id desc);
create index if not exists supplier_credit_allocations_credit_idx
  on public.supplier_credit_allocations(credit_note_id);
create index if not exists supplier_credit_allocations_bill_idx
  on public.supplier_credit_allocations(bill_id);

create or replace function public.prepare_supplier_credit_note()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.credit_note_no is null or btrim(new.credit_note_no) = '' then
    new.credit_note_no := 'SCN-' || to_char(coalesce(new.credit_date, current_date), 'YYYYMMDD') || '-' || lpad(new.id::text, 5, '0');
  end if;
  new.currency := upper(coalesce(nullif(btrim(new.currency), ''), 'SGD'));
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists supplier_credit_notes_prepare_record on public.supplier_credit_notes;
create trigger supplier_credit_notes_prepare_record
before insert or update on public.supplier_credit_notes
for each row execute function public.prepare_supplier_credit_note();

-- -----------------------------------------------------------------------------
-- 5. BILL BALANCE AND STATUS
-- -----------------------------------------------------------------------------
create or replace function public.refresh_supplier_bill_state(p_bill_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_bill public.supplier_bills%rowtype;
  v_payment_allocated numeric(14,2) := 0;
  v_credit_allocated numeric(14,2) := 0;
  v_paid numeric(14,2) := 0;
  v_credit numeric(14,2) := 0;
  v_balance numeric(14,2) := 0;
  v_status text;
begin
  select * into v_bill
  from public.supplier_bills
  where id = p_bill_id
  for update;

  if not found then return; end if;

  select coalesce(sum(allocation.allocated_amount), 0)
  into v_payment_allocated
  from public.supplier_payment_allocations allocation
  join public.supplier_payments payment on payment.id = allocation.payment_id
  where allocation.bill_id = p_bill_id and payment.status = 'posted';

  select coalesce(sum(allocation.allocated_amount), 0)
  into v_credit_allocated
  from public.supplier_credit_allocations allocation
  join public.supplier_credit_notes credit on credit.id = allocation.credit_note_id
  where allocation.bill_id = p_bill_id and credit.status = 'posted';

  v_paid := least(
    greatest(coalesce(v_bill.total_amount, 0), 0),
    greatest(coalesce(v_bill.payment_ledger_opening_amount, 0), 0) + greatest(v_payment_allocated, 0)
  );
  v_credit := least(
    greatest(coalesce(v_bill.total_amount, 0) - v_paid, 0),
    greatest(v_credit_allocated, 0)
  );
  v_balance := greatest(coalesce(v_bill.total_amount, 0) - v_paid - v_credit, 0);

  if v_bill.status = 'cancelled' then
    v_status := 'cancelled';
  elsif v_balance <= 0.004 and coalesce(v_bill.total_amount, 0) > 0 then
    v_status := 'paid';
  elsif v_paid + v_credit > 0 then
    v_status := 'partial';
  elsif v_bill.status = 'draft' then
    v_status := 'draft';
  elsif v_bill.due_date is not null and v_bill.due_date < current_date then
    v_status := 'overdue';
  else
    v_status := 'open';
  end if;

  update public.supplier_bills
  set amount_paid = round(v_paid, 2),
      credit_applied = round(v_credit, 2),
      status = v_status,
      updated_at = now()
  where id = p_bill_id;
end;
$$;

-- Preserve any pre-upgrade paid amount once as opening balance.
update public.supplier_bills bill
set payment_ledger_opening_amount = greatest(coalesce(bill.amount_paid, 0), 0)
where coalesce(bill.payment_ledger_opening_amount, 0) = 0
  and coalesce(bill.amount_paid, 0) > 0
  and not exists (
    select 1 from public.supplier_payment_allocations allocation where allocation.bill_id = bill.id
  );

-- -----------------------------------------------------------------------------
-- 6. ATOMIC PAYMENT FUNCTIONS
-- -----------------------------------------------------------------------------
create or replace function public.record_supplier_payment(
  p_company_id bigint,
  p_supplier_id bigint,
  p_payment_date date,
  p_currency text,
  p_amount numeric,
  p_payment_method text,
  p_payment_reference text,
  p_bank_account text,
  p_notes text,
  p_allocations jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_supplier public.suppliers%rowtype;
  v_payment_id bigint;
  v_allocation jsonb;
  v_bill public.supplier_bills%rowtype;
  v_bill_id bigint;
  v_amount numeric(14,2);
  v_allocated numeric(14,2) := 0;
  v_balance numeric(14,2);
begin
  if v_user_id is null then raise exception 'Authentication is required.'; end if;
  if not public.is_app_administrator() then raise exception 'Administrator access is required.'; end if;
  if p_amount is null or round(p_amount, 2) <= 0 then raise exception 'Payment amount must be greater than zero.'; end if;
  if nullif(btrim(coalesce(p_payment_method, '')), '') is null then raise exception 'Payment method is required.'; end if;

  select * into v_supplier from public.suppliers where id = p_supplier_id and company_id = p_company_id;
  if not found then raise exception 'Supplier was not found for the selected company.'; end if;

  insert into public.supplier_payments(
    company_id, supplier_id, supplier_name, payment_date, currency, amount,
    allocated_amount, unallocated_amount, payment_method, payment_reference,
    bank_account, notes, created_by
  ) values (
    p_company_id, p_supplier_id, v_supplier.supplier_name, coalesce(p_payment_date, current_date),
    upper(coalesce(nullif(btrim(p_currency), ''), v_supplier.default_currency, 'SGD')),
    round(p_amount, 2), 0, round(p_amount, 2), btrim(p_payment_method),
    nullif(btrim(coalesce(p_payment_reference, '')), ''),
    nullif(btrim(coalesce(p_bank_account, '')), ''),
    nullif(btrim(coalesce(p_notes, '')), ''), v_user_id
  ) returning id into v_payment_id;

  for v_allocation in select value from jsonb_array_elements(coalesce(p_allocations, '[]'::jsonb))
  loop
    begin
      v_bill_id := (v_allocation ->> 'bill_id')::bigint;
      v_amount := round((v_allocation ->> 'amount')::numeric, 2);
    exception when others then
      raise exception 'Every allocation requires a valid bill and amount.';
    end;
    if v_amount <= 0 then raise exception 'Every allocation amount must be greater than zero.'; end if;

    select * into v_bill from public.supplier_bills where id = v_bill_id for update;
    if not found then raise exception 'Supplier bill % was not found.', v_bill_id; end if;
    if v_bill.company_id <> p_company_id or v_bill.supplier_id <> p_supplier_id then
      raise exception 'Bill % belongs to another company or supplier.', coalesce(v_bill.bill_no, v_bill.id::text);
    end if;
    if upper(v_bill.currency) <> upper(coalesce(p_currency, v_supplier.default_currency, 'SGD')) then
      raise exception 'Bill % uses a different currency.', coalesce(v_bill.bill_no, v_bill.id::text);
    end if;
    if v_bill.status = 'cancelled' then raise exception 'Cancelled bill % cannot receive payment.', coalesce(v_bill.bill_no, v_bill.id::text); end if;

    v_balance := greatest(v_bill.total_amount - v_bill.amount_paid - v_bill.credit_applied, 0);
    if v_amount > v_balance + 0.004 then
      raise exception 'Allocation for bill % exceeds its outstanding balance of %.',
        coalesce(v_bill.bill_no, v_bill.id::text), to_char(v_balance, 'FM9999999990.00');
    end if;

    v_allocated := v_allocated + v_amount;
    if v_allocated > round(p_amount, 2) + 0.004 then raise exception 'Bill allocations exceed the payment amount.'; end if;

    insert into public.supplier_payment_allocations(payment_id, bill_id, allocated_amount)
    values (v_payment_id, v_bill_id, v_amount);
  end loop;

  update public.supplier_payments
  set allocated_amount = round(v_allocated, 2),
      unallocated_amount = round(p_amount - v_allocated, 2),
      updated_at = now()
  where id = v_payment_id;

  for v_bill_id in select distinct bill_id from public.supplier_payment_allocations where payment_id = v_payment_id
  loop perform public.refresh_supplier_bill_state(v_bill_id); end loop;

  return (
    select jsonb_build_object(
      'success', true, 'payment_id', payment.id, 'voucher_no', payment.voucher_no,
      'amount', payment.amount, 'allocated_amount', payment.allocated_amount,
      'unallocated_amount', payment.unallocated_amount
    ) from public.supplier_payments payment where payment.id = v_payment_id
  );
end;
$$;

create or replace function public.allocate_supplier_payment_credit(
  p_payment_id bigint,
  p_allocations jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_payment public.supplier_payments%rowtype;
  v_allocation jsonb;
  v_bill public.supplier_bills%rowtype;
  v_bill_id bigint;
  v_amount numeric(14,2);
  v_applied numeric(14,2) := 0;
  v_balance numeric(14,2);
begin
  if v_user_id is null then raise exception 'Authentication is required.'; end if;
  if not public.is_app_administrator() then raise exception 'Administrator access is required.'; end if;

  select * into v_payment from public.supplier_payments where id = p_payment_id for update;
  if not found then raise exception 'Supplier payment was not found.'; end if;
  if v_payment.status <> 'posted' then raise exception 'Only a posted payment can be allocated.'; end if;
  if v_payment.unallocated_amount <= 0 then raise exception 'This payment has no unallocated amount.'; end if;

  for v_allocation in select value from jsonb_array_elements(coalesce(p_allocations, '[]'::jsonb))
  loop
    v_bill_id := (v_allocation ->> 'bill_id')::bigint;
    v_amount := round((v_allocation ->> 'amount')::numeric, 2);
    if v_amount <= 0 then raise exception 'Every allocation amount must be greater than zero.'; end if;

    select * into v_bill from public.supplier_bills where id = v_bill_id for update;
    if not found then raise exception 'Supplier bill % was not found.', v_bill_id; end if;
    if v_bill.company_id <> v_payment.company_id or v_bill.supplier_id <> v_payment.supplier_id then
      raise exception 'Bill % belongs to another company or supplier.', coalesce(v_bill.bill_no, v_bill.id::text);
    end if;
    if upper(v_bill.currency) <> upper(v_payment.currency) then raise exception 'Bill % uses a different currency.', coalesce(v_bill.bill_no, v_bill.id::text); end if;
    if v_bill.status = 'cancelled' then raise exception 'Cancelled bill % cannot receive payment.', coalesce(v_bill.bill_no, v_bill.id::text); end if;

    v_balance := greatest(v_bill.total_amount - v_bill.amount_paid - v_bill.credit_applied, 0);
    if v_amount > v_balance + 0.004 then raise exception 'Allocation exceeds bill % balance.', coalesce(v_bill.bill_no, v_bill.id::text); end if;

    v_applied := v_applied + v_amount;
    if v_applied > v_payment.unallocated_amount + 0.004 then raise exception 'Allocations exceed available unallocated payment.'; end if;

    insert into public.supplier_payment_allocations(payment_id, bill_id, allocated_amount)
    values (v_payment.id, v_bill_id, v_amount)
    on conflict(payment_id, bill_id)
    do update set allocated_amount = public.supplier_payment_allocations.allocated_amount + excluded.allocated_amount;
  end loop;

  update public.supplier_payments
  set allocated_amount = round(allocated_amount + v_applied, 2),
      unallocated_amount = round(unallocated_amount - v_applied, 2),
      updated_at = now()
  where id = v_payment.id;

  for v_bill_id in select distinct bill_id from public.supplier_payment_allocations where payment_id = v_payment.id
  loop perform public.refresh_supplier_bill_state(v_bill_id); end loop;

  return jsonb_build_object('success', true, 'payment_id', v_payment.id, 'voucher_no', v_payment.voucher_no);
end;
$$;

create or replace function public.void_supplier_payment(p_payment_id bigint, p_reason text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_payment public.supplier_payments%rowtype;
  v_bill_id bigint;
begin
  if v_user_id is null then raise exception 'Authentication is required.'; end if;
  if not public.is_app_administrator() then raise exception 'Administrator access is required.'; end if;
  if nullif(btrim(coalesce(p_reason, '')), '') is null then raise exception 'A reversal reason is required.'; end if;

  select * into v_payment from public.supplier_payments where id = p_payment_id for update;
  if not found then raise exception 'Supplier payment was not found.'; end if;
  if v_payment.status = 'void' then return jsonb_build_object('success', true, 'payment_id', v_payment.id, 'status', 'void'); end if;

  update public.supplier_payments
  set status = 'void', void_reason = btrim(p_reason), voided_by = v_user_id,
      voided_at = now(), updated_at = now()
  where id = p_payment_id;

  for v_bill_id in select distinct bill_id from public.supplier_payment_allocations where payment_id = p_payment_id
  loop perform public.refresh_supplier_bill_state(v_bill_id); end loop;

  return jsonb_build_object('success', true, 'payment_id', v_payment.id, 'voucher_no', v_payment.voucher_no, 'status', 'void');
end;
$$;

-- -----------------------------------------------------------------------------
-- 7. ATOMIC CREDIT NOTE FUNCTIONS
-- -----------------------------------------------------------------------------
create or replace function public.record_supplier_credit_note(
  p_company_id bigint,
  p_supplier_id bigint,
  p_credit_date date,
  p_currency text,
  p_amount numeric,
  p_supplier_reference text,
  p_reason text,
  p_notes text,
  p_allocations jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_supplier public.suppliers%rowtype;
  v_credit_id bigint;
  v_allocation jsonb;
  v_bill public.supplier_bills%rowtype;
  v_bill_id bigint;
  v_amount numeric(14,2);
  v_applied numeric(14,2) := 0;
  v_balance numeric(14,2);
begin
  if v_user_id is null then raise exception 'Authentication is required.'; end if;
  if not public.is_app_administrator() then raise exception 'Administrator access is required.'; end if;
  if p_amount is null or round(p_amount, 2) <= 0 then raise exception 'Credit amount must be greater than zero.'; end if;
  if nullif(btrim(coalesce(p_reason, '')), '') is null then raise exception 'Credit reason is required.'; end if;

  select * into v_supplier from public.suppliers where id = p_supplier_id and company_id = p_company_id;
  if not found then raise exception 'Supplier was not found for the selected company.'; end if;

  insert into public.supplier_credit_notes(
    company_id, supplier_id, supplier_name, credit_date, currency, amount,
    applied_amount, unapplied_amount, supplier_reference, reason, notes, created_by
  ) values (
    p_company_id, p_supplier_id, v_supplier.supplier_name, coalesce(p_credit_date, current_date),
    upper(coalesce(nullif(btrim(p_currency), ''), v_supplier.default_currency, 'SGD')),
    round(p_amount, 2), 0, round(p_amount, 2),
    nullif(btrim(coalesce(p_supplier_reference, '')), ''), btrim(p_reason),
    nullif(btrim(coalesce(p_notes, '')), ''), v_user_id
  ) returning id into v_credit_id;

  for v_allocation in select value from jsonb_array_elements(coalesce(p_allocations, '[]'::jsonb))
  loop
    v_bill_id := (v_allocation ->> 'bill_id')::bigint;
    v_amount := round((v_allocation ->> 'amount')::numeric, 2);
    if v_amount <= 0 then raise exception 'Every allocation amount must be greater than zero.'; end if;

    select * into v_bill from public.supplier_bills where id = v_bill_id for update;
    if not found then raise exception 'Supplier bill % was not found.', v_bill_id; end if;
    if v_bill.company_id <> p_company_id or v_bill.supplier_id <> p_supplier_id then raise exception 'Bill belongs to another company or supplier.'; end if;
    if upper(v_bill.currency) <> upper(coalesce(p_currency, v_supplier.default_currency, 'SGD')) then raise exception 'Bill uses a different currency.'; end if;
    if v_bill.status = 'cancelled' then raise exception 'Cancelled bills cannot receive credit.'; end if;

    v_balance := greatest(v_bill.total_amount - v_bill.amount_paid - v_bill.credit_applied, 0);
    if v_amount > v_balance + 0.004 then raise exception 'Credit allocation exceeds bill balance.'; end if;

    v_applied := v_applied + v_amount;
    if v_applied > round(p_amount, 2) + 0.004 then raise exception 'Credit allocations exceed the credit amount.'; end if;

    insert into public.supplier_credit_allocations(credit_note_id, bill_id, allocated_amount)
    values (v_credit_id, v_bill_id, v_amount);
  end loop;

  update public.supplier_credit_notes
  set applied_amount = round(v_applied, 2), unapplied_amount = round(p_amount - v_applied, 2), updated_at = now()
  where id = v_credit_id;

  for v_bill_id in select distinct bill_id from public.supplier_credit_allocations where credit_note_id = v_credit_id
  loop perform public.refresh_supplier_bill_state(v_bill_id); end loop;

  return (
    select jsonb_build_object(
      'success', true, 'credit_note_id', credit.id, 'credit_note_no', credit.credit_note_no,
      'amount', credit.amount, 'applied_amount', credit.applied_amount, 'unapplied_amount', credit.unapplied_amount
    ) from public.supplier_credit_notes credit where credit.id = v_credit_id
  );
end;
$$;

create or replace function public.allocate_supplier_credit_note(
  p_credit_note_id bigint,
  p_allocations jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_credit public.supplier_credit_notes%rowtype;
  v_allocation jsonb;
  v_bill public.supplier_bills%rowtype;
  v_bill_id bigint;
  v_amount numeric(14,2);
  v_applied numeric(14,2) := 0;
  v_balance numeric(14,2);
begin
  if v_user_id is null then raise exception 'Authentication is required.'; end if;
  if not public.is_app_administrator() then raise exception 'Administrator access is required.'; end if;

  select * into v_credit from public.supplier_credit_notes where id = p_credit_note_id for update;
  if not found then raise exception 'Supplier credit note was not found.'; end if;
  if v_credit.status <> 'posted' then raise exception 'Only a posted credit note can be allocated.'; end if;
  if v_credit.unapplied_amount <= 0 then raise exception 'This credit note has no unapplied balance.'; end if;

  for v_allocation in select value from jsonb_array_elements(coalesce(p_allocations, '[]'::jsonb))
  loop
    v_bill_id := (v_allocation ->> 'bill_id')::bigint;
    v_amount := round((v_allocation ->> 'amount')::numeric, 2);
    if v_amount <= 0 then raise exception 'Every allocation amount must be greater than zero.'; end if;

    select * into v_bill from public.supplier_bills where id = v_bill_id for update;
    if not found then raise exception 'Supplier bill % was not found.', v_bill_id; end if;
    if v_bill.company_id <> v_credit.company_id or v_bill.supplier_id <> v_credit.supplier_id then raise exception 'Bill belongs to another company or supplier.'; end if;
    if upper(v_bill.currency) <> upper(v_credit.currency) then raise exception 'Bill uses a different currency.'; end if;
    if v_bill.status = 'cancelled' then raise exception 'Cancelled bills cannot receive credit.'; end if;

    v_balance := greatest(v_bill.total_amount - v_bill.amount_paid - v_bill.credit_applied, 0);
    if v_amount > v_balance + 0.004 then raise exception 'Credit allocation exceeds bill balance.'; end if;

    v_applied := v_applied + v_amount;
    if v_applied > v_credit.unapplied_amount + 0.004 then raise exception 'Allocations exceed unapplied credit.'; end if;

    insert into public.supplier_credit_allocations(credit_note_id, bill_id, allocated_amount)
    values (v_credit.id, v_bill_id, v_amount)
    on conflict(credit_note_id, bill_id)
    do update set allocated_amount = public.supplier_credit_allocations.allocated_amount + excluded.allocated_amount;
  end loop;

  update public.supplier_credit_notes
  set applied_amount = round(applied_amount + v_applied, 2),
      unapplied_amount = round(unapplied_amount - v_applied, 2),
      updated_at = now()
  where id = v_credit.id;

  for v_bill_id in select distinct bill_id from public.supplier_credit_allocations where credit_note_id = v_credit.id
  loop perform public.refresh_supplier_bill_state(v_bill_id); end loop;

  return jsonb_build_object('success', true, 'credit_note_id', v_credit.id, 'credit_note_no', v_credit.credit_note_no);
end;
$$;

create or replace function public.void_supplier_credit_note(p_credit_note_id bigint, p_reason text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_credit public.supplier_credit_notes%rowtype;
  v_bill_id bigint;
begin
  if v_user_id is null then raise exception 'Authentication is required.'; end if;
  if not public.is_app_administrator() then raise exception 'Administrator access is required.'; end if;
  if nullif(btrim(coalesce(p_reason, '')), '') is null then raise exception 'A reversal reason is required.'; end if;

  select * into v_credit from public.supplier_credit_notes where id = p_credit_note_id for update;
  if not found then raise exception 'Supplier credit note was not found.'; end if;
  if v_credit.status = 'void' then return jsonb_build_object('success', true, 'credit_note_id', v_credit.id, 'status', 'void'); end if;

  update public.supplier_credit_notes
  set status = 'void', void_reason = btrim(p_reason), voided_by = v_user_id,
      voided_at = now(), updated_at = now()
  where id = p_credit_note_id;

  for v_bill_id in select distinct bill_id from public.supplier_credit_allocations where credit_note_id = p_credit_note_id
  loop perform public.refresh_supplier_bill_state(v_bill_id); end loop;

  return jsonb_build_object('success', true, 'credit_note_id', v_credit.id, 'credit_note_no', v_credit.credit_note_no, 'status', 'void');
end;
$$;

-- -----------------------------------------------------------------------------
-- 8. SECURITY
-- -----------------------------------------------------------------------------
alter table public.suppliers enable row level security;
alter table public.supplier_bills enable row level security;
alter table public.supplier_bill_items enable row level security;
alter table public.supplier_payments enable row level security;
alter table public.supplier_payment_allocations enable row level security;
alter table public.supplier_credit_notes enable row level security;
alter table public.supplier_credit_allocations enable row level security;

grant select, insert, update, delete on public.suppliers to authenticated;
grant select, insert, update, delete on public.supplier_bills to authenticated;
grant select, insert, update, delete on public.supplier_bill_items to authenticated;
grant select, insert, update, delete on public.supplier_payments to authenticated;
grant select, insert, update, delete on public.supplier_payment_allocations to authenticated;
grant select, insert, update, delete on public.supplier_credit_notes to authenticated;
grant select, insert, update, delete on public.supplier_credit_allocations to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on function public.refresh_supplier_bill_state(bigint) from public, anon;
revoke all on function public.record_supplier_payment(bigint,bigint,date,text,numeric,text,text,text,text,jsonb) from public, anon;
revoke all on function public.allocate_supplier_payment_credit(bigint,jsonb) from public, anon;
revoke all on function public.void_supplier_payment(bigint,text) from public, anon;
revoke all on function public.record_supplier_credit_note(bigint,bigint,date,text,numeric,text,text,text,jsonb) from public, anon;
revoke all on function public.allocate_supplier_credit_note(bigint,jsonb) from public, anon;
revoke all on function public.void_supplier_credit_note(bigint,text) from public, anon;

grant execute on function public.refresh_supplier_bill_state(bigint) to authenticated;
grant execute on function public.record_supplier_payment(bigint,bigint,date,text,numeric,text,text,text,text,jsonb) to authenticated;
grant execute on function public.allocate_supplier_payment_credit(bigint,jsonb) to authenticated;
grant execute on function public.void_supplier_payment(bigint,text) to authenticated;
grant execute on function public.record_supplier_credit_note(bigint,bigint,date,text,numeric,text,text,text,jsonb) to authenticated;
grant execute on function public.allocate_supplier_credit_note(bigint,jsonb) to authenticated;
grant execute on function public.void_supplier_credit_note(bigint,text) to authenticated;

drop policy if exists suppliers_administrator_all on public.suppliers;
create policy suppliers_administrator_all on public.suppliers
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists supplier_bills_administrator_all on public.supplier_bills;
create policy supplier_bills_administrator_all on public.supplier_bills
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists supplier_bill_items_administrator_all on public.supplier_bill_items;
create policy supplier_bill_items_administrator_all on public.supplier_bill_items
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists supplier_payments_administrator_all on public.supplier_payments;
create policy supplier_payments_administrator_all on public.supplier_payments
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists supplier_payment_allocations_administrator_all on public.supplier_payment_allocations;
create policy supplier_payment_allocations_administrator_all on public.supplier_payment_allocations
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists supplier_credit_notes_administrator_all on public.supplier_credit_notes;
create policy supplier_credit_notes_administrator_all on public.supplier_credit_notes
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists supplier_credit_allocations_administrator_all on public.supplier_credit_allocations;
create policy supplier_credit_allocations_administrator_all on public.supplier_credit_allocations
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

notify pgrst, 'reload schema';
commit;
