-- A3 MANAGEMENT FINANCE - UPGRADE 5
-- BANK RECONCILIATION & CASH ACCOUNTS
-- Run after 013_accounts_payable_supplier_payments.sql.
-- Safe to rerun. Existing finance records are preserved.

begin;

-- -----------------------------------------------------------------------------
-- 1. BANK / CASH ACCOUNTS
-- -----------------------------------------------------------------------------
create table if not exists public.bank_accounts (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  account_code text,
  account_name text not null,
  bank_name text,
  account_no text,
  currency text not null default 'SGD',
  opening_balance numeric(16,2) not null default 0,
  opening_balance_date date,
  is_active boolean not null default true,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (currency ~ '^[A-Z]{3}$')
);

alter table public.bank_accounts
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists account_code text,
  add column if not exists account_name text,
  add column if not exists bank_name text,
  add column if not exists account_no text,
  add column if not exists currency text default 'SGD',
  add column if not exists opening_balance numeric(16,2) default 0,
  add column if not exists opening_balance_date date,
  add column if not exists is_active boolean default true,
  add column if not exists notes text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.bank_accounts
set account_name = coalesce(nullif(btrim(account_name), ''), nullif(btrim(bank_name), ''), 'Bank Account'),
    currency = upper(coalesce(nullif(btrim(currency), ''), 'SGD')),
    opening_balance = coalesce(opening_balance, 0),
    is_active = coalesce(is_active, true),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

update public.bank_accounts duplicate
set account_code = duplicate.account_code || '-DUP-' || duplicate.id::text
where duplicate.account_code is not null
  and exists (
    select 1 from public.bank_accounts original
    where original.company_id = duplicate.company_id
      and lower(original.account_code) = lower(duplicate.account_code)
      and original.id < duplicate.id
  );

create unique index if not exists bank_accounts_company_code_uidx
  on public.bank_accounts(company_id, lower(account_code))
  where account_code is not null;
create index if not exists bank_accounts_company_active_idx
  on public.bank_accounts(company_id, is_active, account_name);

-- -----------------------------------------------------------------------------
-- 2. BANK STATEMENT BATCHES AND LINES
-- -----------------------------------------------------------------------------
create table if not exists public.bank_statement_batches (
  id bigint generated by default as identity primary key,
  batch_no text,
  company_id bigint not null references public.companies(id) on delete cascade,
  bank_account_id bigint not null references public.bank_accounts(id) on delete restrict,
  statement_reference text,
  period_from date not null,
  period_to date not null,
  opening_balance numeric(16,2) not null default 0,
  closing_balance numeric(16,2) not null default 0,
  status text not null default 'draft',
  notes text,
  reconciled_by uuid references public.profiles(id) on delete set null,
  reconciled_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (period_to >= period_from),
  check (status in ('draft','reconciled'))
);

alter table public.bank_statement_batches
  add column if not exists batch_no text,
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists bank_account_id bigint references public.bank_accounts(id) on delete restrict,
  add column if not exists statement_reference text,
  add column if not exists period_from date,
  add column if not exists period_to date,
  add column if not exists opening_balance numeric(16,2) default 0,
  add column if not exists closing_balance numeric(16,2) default 0,
  add column if not exists status text default 'draft',
  add column if not exists notes text,
  add column if not exists reconciled_by uuid references public.profiles(id) on delete set null,
  add column if not exists reconciled_at timestamptz,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.bank_statement_batches
set period_from = coalesce(period_from, current_date),
    period_to = coalesce(period_to, period_from, current_date),
    opening_balance = coalesce(opening_balance, 0),
    closing_balance = coalesce(closing_balance, 0),
    status = case when lower(coalesce(status, 'draft')) = 'reconciled' then 'reconciled' else 'draft' end,
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

create table if not exists public.bank_statement_lines (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.bank_statement_batches(id) on delete cascade,
  company_id bigint not null references public.companies(id) on delete cascade,
  bank_account_id bigint not null references public.bank_accounts(id) on delete restrict,
  sequence_no integer not null,
  transaction_date date not null,
  value_date date,
  description text not null,
  reference text,
  amount numeric(16,2) not null,
  running_balance numeric(16,2),
  match_status text not null default 'unmatched',
  ignored_reason text,
  ignored_by uuid references public.profiles(id) on delete set null,
  ignored_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (amount <> 0),
  check (match_status in ('unmatched','partial','matched','ignored')),
  unique(batch_id, sequence_no)
);

alter table public.bank_statement_lines
  add column if not exists batch_id bigint references public.bank_statement_batches(id) on delete cascade,
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists bank_account_id bigint references public.bank_accounts(id) on delete restrict,
  add column if not exists sequence_no integer,
  add column if not exists transaction_date date,
  add column if not exists value_date date,
  add column if not exists description text,
  add column if not exists reference text,
  add column if not exists amount numeric(16,2) default 0,
  add column if not exists running_balance numeric(16,2),
  add column if not exists match_status text default 'unmatched',
  add column if not exists ignored_reason text,
  add column if not exists ignored_by uuid references public.profiles(id) on delete set null,
  add column if not exists ignored_at timestamptz,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.bank_statement_lines
set sequence_no = coalesce(sequence_no, id::integer),
    transaction_date = coalesce(transaction_date, current_date),
    description = coalesce(nullif(btrim(description), ''), 'Bank transaction'),
    amount = coalesce(amount, 0),
    match_status = case
      when lower(coalesce(match_status, 'unmatched')) = 'ignored' then 'ignored'
      when lower(coalesce(match_status, 'unmatched')) = 'matched' then 'matched'
      when lower(coalesce(match_status, 'unmatched')) = 'partial' then 'partial'
      else 'unmatched'
    end,
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

update public.bank_statement_batches duplicate
set batch_no = duplicate.batch_no || '-DUP-' || duplicate.id::text
where duplicate.batch_no is not null
  and exists (
    select 1 from public.bank_statement_batches original
    where lower(original.batch_no) = lower(duplicate.batch_no)
      and original.id < duplicate.id
  );

create unique index if not exists bank_statement_batches_no_uidx
  on public.bank_statement_batches(lower(batch_no)) where batch_no is not null;
create index if not exists bank_statement_batches_account_period_idx
  on public.bank_statement_batches(company_id, bank_account_id, period_to desc, id desc);
create unique index if not exists bank_statement_lines_batch_sequence_uidx
  on public.bank_statement_lines(batch_id, sequence_no);
create index if not exists bank_statement_lines_reconcile_idx
  on public.bank_statement_lines(bank_account_id, match_status, transaction_date, id);

-- -----------------------------------------------------------------------------
-- 3. CASH BOOK ENTRIES
-- Positive amount = receipt / inflow. Negative amount = payment / outflow.
-- -----------------------------------------------------------------------------
create table if not exists public.bank_cashbook_entries (
  id bigint generated by default as identity primary key,
  entry_no text,
  company_id bigint not null references public.companies(id) on delete cascade,
  bank_account_id bigint not null references public.bank_accounts(id) on delete restrict,
  entry_date date not null default current_date,
  value_date date,
  entry_type text not null default 'adjustment',
  source_type text,
  source_id bigint,
  reference text,
  description text not null,
  amount numeric(16,2) not null,
  status text not null default 'posted',
  notes text,
  void_reason text,
  voided_by uuid references public.profiles(id) on delete set null,
  voided_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (amount <> 0),
  check (entry_type in ('receipt','payment','bank_fee','interest','transfer','adjustment')),
  check (status in ('posted','void'))
);

alter table public.bank_cashbook_entries
  add column if not exists entry_no text,
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists bank_account_id bigint references public.bank_accounts(id) on delete restrict,
  add column if not exists entry_date date default current_date,
  add column if not exists value_date date,
  add column if not exists entry_type text default 'adjustment',
  add column if not exists source_type text,
  add column if not exists source_id bigint,
  add column if not exists reference text,
  add column if not exists description text,
  add column if not exists amount numeric(16,2) default 0,
  add column if not exists status text default 'posted',
  add column if not exists notes text,
  add column if not exists void_reason text,
  add column if not exists voided_by uuid references public.profiles(id) on delete set null,
  add column if not exists voided_at timestamptz,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.bank_cashbook_entries
set entry_date = coalesce(entry_date, current_date),
    entry_type = case
      when lower(coalesce(entry_type, 'adjustment')) in ('receipt','payment','bank_fee','interest','transfer','adjustment')
        then lower(entry_type)
      else 'adjustment'
    end,
    description = coalesce(nullif(btrim(description), ''), 'Cash-book entry'),
    amount = coalesce(amount, 0),
    status = case when lower(coalesce(status, 'posted')) = 'void' then 'void' else 'posted' end,
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

update public.bank_cashbook_entries duplicate
set entry_no = duplicate.entry_no || '-DUP-' || duplicate.id::text
where duplicate.entry_no is not null
  and exists (
    select 1 from public.bank_cashbook_entries original
    where lower(original.entry_no) = lower(duplicate.entry_no)
      and original.id < duplicate.id
  );

create unique index if not exists bank_cashbook_entries_no_uidx
  on public.bank_cashbook_entries(lower(entry_no)) where entry_no is not null;
create unique index if not exists bank_cashbook_entries_source_uidx
  on public.bank_cashbook_entries(source_type, source_id)
  where source_type is not null and source_id is not null;
create index if not exists bank_cashbook_entries_account_date_idx
  on public.bank_cashbook_entries(bank_account_id, status, entry_date, id);

-- -----------------------------------------------------------------------------
-- 4. RECONCILIATION MATCH ALLOCATIONS
-- -----------------------------------------------------------------------------
create table if not exists public.bank_reconciliation_matches (
  id bigint generated by default as identity primary key,
  statement_line_id bigint not null references public.bank_statement_lines(id) on delete cascade,
  cashbook_entry_id bigint not null references public.bank_cashbook_entries(id) on delete restrict,
  matched_amount numeric(16,2) not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  check (matched_amount > 0),
  unique(statement_line_id, cashbook_entry_id)
);

alter table public.bank_reconciliation_matches
  add column if not exists statement_line_id bigint references public.bank_statement_lines(id) on delete cascade,
  add column if not exists cashbook_entry_id bigint references public.bank_cashbook_entries(id) on delete restrict,
  add column if not exists matched_amount numeric(16,2) default 0,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now();

update public.bank_reconciliation_matches
set matched_amount = greatest(coalesce(matched_amount, 0), 0),
    created_at = coalesce(created_at, now());

create unique index if not exists bank_reconciliation_match_pair_uidx
  on public.bank_reconciliation_matches(statement_line_id, cashbook_entry_id);
create index if not exists bank_reconciliation_matches_line_idx
  on public.bank_reconciliation_matches(statement_line_id);
create index if not exists bank_reconciliation_matches_entry_idx
  on public.bank_reconciliation_matches(cashbook_entry_id);

-- -----------------------------------------------------------------------------
-- 5. NUMBERING AND STATE FUNCTIONS
-- -----------------------------------------------------------------------------
create or replace function public.prepare_bank_account()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.account_name := coalesce(nullif(btrim(new.account_name), ''), nullif(btrim(new.bank_name), ''), 'Bank Account');
  new.currency := upper(coalesce(nullif(btrim(new.currency), ''), 'SGD'));
  new.opening_balance := round(coalesce(new.opening_balance, 0), 2);
  new.is_active := coalesce(new.is_active, true);
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists bank_accounts_prepare_record on public.bank_accounts;
create trigger bank_accounts_prepare_record
before insert or update on public.bank_accounts
for each row execute function public.prepare_bank_account();

create or replace function public.prepare_bank_statement_batch()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.batch_no is null or btrim(new.batch_no) = '' then
    new.batch_no := 'BANK-' || to_char(coalesce(new.period_to, current_date), 'YYYYMMDD') || '-' || lpad(new.id::text, 5, '0');
  end if;
  new.opening_balance := round(coalesce(new.opening_balance, 0), 2);
  new.closing_balance := round(coalesce(new.closing_balance, 0), 2);
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists bank_statement_batches_prepare_record on public.bank_statement_batches;
create trigger bank_statement_batches_prepare_record
before insert or update on public.bank_statement_batches
for each row execute function public.prepare_bank_statement_batch();

create or replace function public.prepare_bank_cashbook_entry()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.entry_no is null or btrim(new.entry_no) = '' then
    new.entry_no := 'CB-' || to_char(coalesce(new.entry_date, current_date), 'YYYYMMDD') || '-' || lpad(new.id::text, 5, '0');
  end if;
  new.description := coalesce(nullif(btrim(new.description), ''), 'Cash-book entry');
  new.amount := round(coalesce(new.amount, 0), 2);
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists bank_cashbook_entries_prepare_record on public.bank_cashbook_entries;
create trigger bank_cashbook_entries_prepare_record
before insert or update on public.bank_cashbook_entries
for each row execute function public.prepare_bank_cashbook_entry();

create or replace function public.refresh_bank_statement_line_state(p_statement_line_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_line public.bank_statement_lines%rowtype;
  v_matched numeric(16,2) := 0;
begin
  select * into v_line
  from public.bank_statement_lines
  where id = p_statement_line_id
  for update;

  if not found or v_line.match_status = 'ignored' then
    return;
  end if;

  select coalesce(sum(match.matched_amount), 0)
  into v_matched
  from public.bank_reconciliation_matches match
  join public.bank_cashbook_entries entry on entry.id = match.cashbook_entry_id
  where match.statement_line_id = p_statement_line_id
    and entry.status = 'posted';

  update public.bank_statement_lines
  set match_status = case
        when v_matched <= 0 then 'unmatched'
        when v_matched + 0.005 >= abs(v_line.amount) then 'matched'
        else 'partial'
      end,
      updated_at = now()
  where id = p_statement_line_id;
end;
$$;

create or replace function public.a3_match_bank_transaction(
  p_actor uuid,
  p_statement_line_id bigint,
  p_cashbook_entry_id bigint,
  p_amount numeric default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_line public.bank_statement_lines%rowtype;
  v_entry public.bank_cashbook_entries%rowtype;
  v_batch public.bank_statement_batches%rowtype;
  v_line_used numeric(16,2) := 0;
  v_entry_used numeric(16,2) := 0;
  v_amount numeric(16,2);
  v_match_id bigint;
begin
  if not exists (
    select 1 from public.profiles
    where id = p_actor and role = 'administrator' and status = 'active'
  ) then
    raise exception 'Administrator access is required.';
  end if;

  select * into v_line from public.bank_statement_lines where id = p_statement_line_id for update;
  if not found then raise exception 'Bank statement line was not found.'; end if;

  select * into v_entry from public.bank_cashbook_entries where id = p_cashbook_entry_id for update;
  if not found then raise exception 'Cash-book entry was not found.'; end if;

  select * into v_batch from public.bank_statement_batches where id = v_line.batch_id for update;
  if v_batch.status = 'reconciled' then raise exception 'Reopen the reconciliation before changing matches.'; end if;
  if v_line.match_status = 'ignored' then raise exception 'Ignored statement lines cannot be matched.'; end if;
  if v_entry.status <> 'posted' then raise exception 'Only posted cash-book entries can be matched.'; end if;
  if v_line.company_id <> v_entry.company_id or v_line.bank_account_id <> v_entry.bank_account_id then
    raise exception 'The statement line and cash-book entry must use the same company and bank account.';
  end if;
  if sign(v_line.amount) <> sign(v_entry.amount) then
    raise exception 'Receipt and payment directions do not match.';
  end if;

  select coalesce(sum(matched_amount), 0) into v_line_used
  from public.bank_reconciliation_matches where statement_line_id = v_line.id;
  select coalesce(sum(matched_amount), 0) into v_entry_used
  from public.bank_reconciliation_matches where cashbook_entry_id = v_entry.id;

  v_amount := round(coalesce(
    p_amount,
    least(abs(v_line.amount) - v_line_used, abs(v_entry.amount) - v_entry_used)
  ), 2);

  if v_amount <= 0 then raise exception 'No unmatched amount remains.'; end if;
  if v_amount > abs(v_line.amount) - v_line_used + 0.005 then raise exception 'Match exceeds the remaining statement amount.'; end if;
  if v_amount > abs(v_entry.amount) - v_entry_used + 0.005 then raise exception 'Match exceeds the remaining cash-book amount.'; end if;

  insert into public.bank_reconciliation_matches(
    statement_line_id, cashbook_entry_id, matched_amount, created_by
  ) values (
    v_line.id, v_entry.id, v_amount, p_actor
  )
  on conflict (statement_line_id, cashbook_entry_id)
  do update set matched_amount = public.bank_reconciliation_matches.matched_amount + excluded.matched_amount
  returning id into v_match_id;

  perform public.refresh_bank_statement_line_state(v_line.id);
  return v_match_id;
end;
$$;

create or replace function public.a3_remove_bank_match(
  p_actor uuid,
  p_match_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_line_id bigint;
  v_batch_status text;
begin
  if not exists (
    select 1 from public.profiles
    where id = p_actor and role = 'administrator' and status = 'active'
  ) then raise exception 'Administrator access is required.'; end if;

  select match.statement_line_id, batch.status
  into v_line_id, v_batch_status
  from public.bank_reconciliation_matches match
  join public.bank_statement_lines line on line.id = match.statement_line_id
  join public.bank_statement_batches batch on batch.id = line.batch_id
  where match.id = p_match_id;

  if v_line_id is null then return false; end if;
  if v_batch_status = 'reconciled' then raise exception 'Reopen the reconciliation before removing matches.'; end if;

  delete from public.bank_reconciliation_matches where id = p_match_id;
  perform public.refresh_bank_statement_line_state(v_line_id);
  return true;
end;
$$;

create or replace function public.a3_close_bank_reconciliation(
  p_actor uuid,
  p_batch_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_batch public.bank_statement_batches%rowtype;
  v_statement_total numeric(16,2) := 0;
  v_calculated_closing numeric(16,2) := 0;
  v_unresolved integer := 0;
begin
  if not exists (
    select 1 from public.profiles
    where id = p_actor and role = 'administrator' and status = 'active'
  ) then raise exception 'Administrator access is required.'; end if;

  select * into v_batch from public.bank_statement_batches where id = p_batch_id for update;
  if not found then raise exception 'Reconciliation batch was not found.'; end if;

  select coalesce(sum(amount), 0),
         count(*) filter (where match_status not in ('matched','ignored'))
  into v_statement_total, v_unresolved
  from public.bank_statement_lines
  where batch_id = p_batch_id;

  v_calculated_closing := round(v_batch.opening_balance + v_statement_total, 2);

  if abs(v_calculated_closing - v_batch.closing_balance) > 0.02 then
    raise exception 'Statement opening balance plus transactions does not equal the closing balance.';
  end if;
  if v_unresolved > 0 then
    raise exception '% statement line(s) are still unmatched or partially matched.', v_unresolved;
  end if;

  update public.bank_statement_batches
  set status = 'reconciled', reconciled_by = p_actor, reconciled_at = now(), updated_at = now()
  where id = p_batch_id;

  return jsonb_build_object(
    'batch_id', p_batch_id,
    'calculated_closing_balance', v_calculated_closing,
    'statement_closing_balance', v_batch.closing_balance,
    'unresolved_lines', v_unresolved
  );
end;
$$;

create or replace function public.a3_reopen_bank_reconciliation(
  p_actor uuid,
  p_batch_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.profiles
    where id = p_actor and role = 'administrator' and status = 'active'
  ) then raise exception 'Administrator access is required.'; end if;

  update public.bank_statement_batches
  set status = 'draft', reconciled_by = null, reconciled_at = null, updated_at = now()
  where id = p_batch_id;
  return found;
end;
$$;

-- -----------------------------------------------------------------------------
-- 6. RLS AND GRANTS
-- -----------------------------------------------------------------------------
alter table public.bank_accounts enable row level security;
alter table public.bank_statement_batches enable row level security;
alter table public.bank_statement_lines enable row level security;
alter table public.bank_cashbook_entries enable row level security;
alter table public.bank_reconciliation_matches enable row level security;

grant select, insert, update, delete on public.bank_accounts to authenticated;
grant select, insert, update, delete on public.bank_statement_batches to authenticated;
grant select, insert, update, delete on public.bank_statement_lines to authenticated;
grant select, insert, update, delete on public.bank_cashbook_entries to authenticated;
grant select, insert, update, delete on public.bank_reconciliation_matches to authenticated;
grant usage, select on all sequences in schema public to authenticated;

grant execute on function public.refresh_bank_statement_line_state(bigint) to authenticated;
grant execute on function public.a3_match_bank_transaction(uuid,bigint,bigint,numeric) to authenticated;
grant execute on function public.a3_remove_bank_match(uuid,bigint) to authenticated;
grant execute on function public.a3_close_bank_reconciliation(uuid,bigint) to authenticated;
grant execute on function public.a3_reopen_bank_reconciliation(uuid,bigint) to authenticated;

-- Administrators operate this finance control module. The service-role API also
-- validates the administrator session before any write.
drop policy if exists bank_accounts_administrator_all on public.bank_accounts;
create policy bank_accounts_administrator_all on public.bank_accounts
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists bank_statement_batches_administrator_all on public.bank_statement_batches;
create policy bank_statement_batches_administrator_all on public.bank_statement_batches
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists bank_statement_lines_administrator_all on public.bank_statement_lines;
create policy bank_statement_lines_administrator_all on public.bank_statement_lines
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists bank_cashbook_entries_administrator_all on public.bank_cashbook_entries;
create policy bank_cashbook_entries_administrator_all on public.bank_cashbook_entries
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists bank_reconciliation_matches_administrator_all on public.bank_reconciliation_matches;
create policy bank_reconciliation_matches_administrator_all on public.bank_reconciliation_matches
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

commit;
