-- A3 MANAGEMENT FINANCE - UPGRADE 7
-- PROFIT & LOSS REPORTING
-- Run after 015_gst_reports_tax_control.sql.
-- Safe to rerun. Existing operational and finance records are preserved.

begin;

-- -----------------------------------------------------------------------------
-- 1. PROFIT & LOSS CHART OF ACCOUNTS
-- -----------------------------------------------------------------------------
create table if not exists public.pl_accounts (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  account_code text not null,
  account_name text not null,
  account_group text not null default 'operating_expense',
  normal_side text not null default 'debit',
  is_system boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 100,
  description text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (account_group in ('revenue','cost_of_sales','operating_expense','other_income','other_expense')),
  check (normal_side in ('debit','credit'))
);

alter table public.pl_accounts
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists account_code text,
  add column if not exists account_name text,
  add column if not exists account_group text default 'operating_expense',
  add column if not exists normal_side text default 'debit',
  add column if not exists is_system boolean default false,
  add column if not exists is_active boolean default true,
  add column if not exists sort_order integer default 100,
  add column if not exists description text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.pl_accounts
set account_code = upper(coalesce(nullif(btrim(account_code), ''), 'PL-' || id::text)),
    account_name = coalesce(nullif(btrim(account_name), ''), 'P&L Account ' || id::text),
    account_group = case
      when lower(coalesce(account_group, '')) in ('revenue','cost_of_sales','operating_expense','other_income','other_expense')
        then lower(account_group)
      else 'operating_expense'
    end,
    normal_side = case when lower(coalesce(normal_side, 'debit')) = 'credit' then 'credit' else 'debit' end,
    is_system = coalesce(is_system, false),
    is_active = coalesce(is_active, true),
    sort_order = coalesce(sort_order, 100),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

update public.pl_accounts duplicate
set account_code = duplicate.account_code || '-DUP-' || duplicate.id::text
where exists (
  select 1
  from public.pl_accounts original
  where original.company_id = duplicate.company_id
    and upper(original.account_code) = upper(duplicate.account_code)
    and original.id < duplicate.id
);

create unique index if not exists pl_accounts_company_code_uidx
  on public.pl_accounts(company_id, account_code);
create index if not exists pl_accounts_company_group_idx
  on public.pl_accounts(company_id, account_group, sort_order, account_code);

create or replace function public.prepare_pl_account()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.account_code := upper(coalesce(nullif(btrim(new.account_code), ''), 'PL'));
  new.account_name := coalesce(nullif(btrim(new.account_name), ''), 'P&L Account');
  new.account_group := lower(coalesce(nullif(btrim(new.account_group), ''), 'operating_expense'));
  if new.account_group not in ('revenue','cost_of_sales','operating_expense','other_income','other_expense') then
    raise exception 'Invalid P&L account group.';
  end if;
  new.normal_side := case
    when new.account_group in ('revenue','other_income') then 'credit'
    else 'debit'
  end;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists pl_accounts_prepare on public.pl_accounts;
create trigger pl_accounts_prepare
before insert or update on public.pl_accounts
for each row execute function public.prepare_pl_account();

-- -----------------------------------------------------------------------------
-- 2. SOURCE-TO-ACCOUNT MAPPINGS
-- -----------------------------------------------------------------------------
create table if not exists public.pl_source_mappings (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  source_type text not null,
  source_category text not null default '*',
  account_id bigint not null references public.pl_accounts(id) on delete restrict,
  priority integer not null default 100,
  is_active boolean not null default true,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (source_type in ('customer_invoice','supplier_bill','driver_payout','bank_cashbook','manual'))
);

alter table public.pl_source_mappings
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists source_type text,
  add column if not exists source_category text default '*',
  add column if not exists account_id bigint references public.pl_accounts(id) on delete restrict,
  add column if not exists priority integer default 100,
  add column if not exists is_active boolean default true,
  add column if not exists notes text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.pl_source_mappings
set source_type = case
      when lower(coalesce(source_type, '')) in ('customer_invoice','supplier_bill','driver_payout','bank_cashbook','manual')
        then lower(source_type)
      else 'manual'
    end,
    source_category = lower(coalesce(nullif(btrim(source_category), ''), '*')),
    priority = coalesce(priority, 100),
    is_active = coalesce(is_active, true),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

delete from public.pl_source_mappings duplicate
using public.pl_source_mappings original
where duplicate.company_id = original.company_id
  and duplicate.source_type = original.source_type
  and duplicate.source_category = original.source_category
  and duplicate.id > original.id;

create unique index if not exists pl_source_mappings_company_source_uidx
  on public.pl_source_mappings(company_id, source_type, source_category);
create index if not exists pl_source_mappings_lookup_idx
  on public.pl_source_mappings(company_id, source_type, is_active, priority, source_category);

create or replace function public.prepare_pl_source_mapping()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  account_company_id bigint;
begin
  new.source_type := lower(coalesce(nullif(btrim(new.source_type), ''), 'manual'));
  new.source_category := lower(coalesce(nullif(btrim(new.source_category), ''), '*'));
  select company_id into account_company_id from public.pl_accounts where id = new.account_id;
  if account_company_id is null or account_company_id <> new.company_id then
    raise exception 'The P&L account must belong to the same company as the mapping.';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists pl_source_mappings_prepare on public.pl_source_mappings;
create trigger pl_source_mappings_prepare
before insert or update on public.pl_source_mappings
for each row execute function public.prepare_pl_source_mapping();

-- -----------------------------------------------------------------------------
-- 3. MONTHLY BUDGETS
-- -----------------------------------------------------------------------------
create table if not exists public.pl_budgets (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  account_id bigint not null references public.pl_accounts(id) on delete cascade,
  budget_month date not null,
  amount numeric(16,2) not null default 0,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (amount >= 0),
  check (budget_month = date_trunc('month', budget_month)::date)
);

alter table public.pl_budgets
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists account_id bigint references public.pl_accounts(id) on delete cascade,
  add column if not exists budget_month date,
  add column if not exists amount numeric(16,2) default 0,
  add column if not exists notes text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.pl_budgets
set budget_month = date_trunc('month', coalesce(budget_month, current_date))::date,
    amount = greatest(coalesce(amount, 0), 0),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

delete from public.pl_budgets duplicate
using public.pl_budgets original
where duplicate.company_id = original.company_id
  and duplicate.account_id = original.account_id
  and duplicate.budget_month = original.budget_month
  and duplicate.id > original.id;

create unique index if not exists pl_budgets_account_month_uidx
  on public.pl_budgets(company_id, account_id, budget_month);
create index if not exists pl_budgets_company_month_idx
  on public.pl_budgets(company_id, budget_month, account_id);

create or replace function public.prepare_pl_budget()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  account_company_id bigint;
begin
  new.budget_month := date_trunc('month', coalesce(new.budget_month, current_date))::date;
  new.amount := greatest(coalesce(new.amount, 0), 0);
  select company_id into account_company_id from public.pl_accounts where id = new.account_id;
  if account_company_id is null or account_company_id <> new.company_id then
    raise exception 'The budget account must belong to the same company.';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists pl_budgets_prepare on public.pl_budgets;
create trigger pl_budgets_prepare
before insert or update on public.pl_budgets
for each row execute function public.prepare_pl_budget();

-- -----------------------------------------------------------------------------
-- 4. MANUAL PROFIT & LOSS ENTRIES
-- -----------------------------------------------------------------------------
create table if not exists public.pl_manual_entries (
  id bigint generated by default as identity primary key,
  entry_no text,
  company_id bigint not null references public.companies(id) on delete cascade,
  account_id bigint not null references public.pl_accounts(id) on delete restrict,
  entry_date date not null default current_date,
  description text not null,
  reference text,
  direction text not null default 'increase',
  amount numeric(16,2) not null,
  status text not null default 'posted',
  notes text,
  void_reason text,
  voided_by uuid references public.profiles(id) on delete set null,
  voided_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (direction in ('increase','decrease')),
  check (amount > 0),
  check (status in ('posted','void'))
);

alter table public.pl_manual_entries
  add column if not exists entry_no text,
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists account_id bigint references public.pl_accounts(id) on delete restrict,
  add column if not exists entry_date date default current_date,
  add column if not exists description text,
  add column if not exists reference text,
  add column if not exists direction text default 'increase',
  add column if not exists amount numeric(16,2) default 0,
  add column if not exists status text default 'posted',
  add column if not exists notes text,
  add column if not exists void_reason text,
  add column if not exists voided_by uuid references public.profiles(id) on delete set null,
  add column if not exists voided_at timestamptz,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.pl_manual_entries
set entry_no = coalesce(nullif(btrim(entry_no), ''), 'PLE-' || lpad(id::text, 6, '0')),
    entry_date = coalesce(entry_date, current_date),
    description = coalesce(nullif(btrim(description), ''), 'Manual P&L entry'),
    direction = case when lower(coalesce(direction, 'increase')) = 'decrease' then 'decrease' else 'increase' end,
    amount = greatest(abs(coalesce(amount, 0)), 0.01),
    status = case when lower(coalesce(status, 'posted')) = 'void' then 'void' else 'posted' end,
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

update public.pl_manual_entries duplicate
set entry_no = duplicate.entry_no || '-DUP-' || duplicate.id::text
where exists (
  select 1
  from public.pl_manual_entries original
  where original.company_id = duplicate.company_id
    and lower(original.entry_no) = lower(duplicate.entry_no)
    and original.id < duplicate.id
);

create unique index if not exists pl_manual_entries_company_no_uidx
  on public.pl_manual_entries(company_id, entry_no);
create index if not exists pl_manual_entries_company_date_idx
  on public.pl_manual_entries(company_id, status, entry_date desc, id desc);

create or replace function public.prepare_pl_manual_entry()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  account_company_id bigint;
begin
  new.entry_date := coalesce(new.entry_date, current_date);
  new.description := coalesce(nullif(btrim(new.description), ''), 'Manual P&L entry');
  new.direction := case when lower(coalesce(new.direction, 'increase')) = 'decrease' then 'decrease' else 'increase' end;
  new.amount := abs(coalesce(new.amount, 0));
  if new.amount <= 0 then raise exception 'Manual P&L amount must be greater than zero.'; end if;
  select company_id into account_company_id from public.pl_accounts where id = new.account_id;
  if account_company_id is null or account_company_id <> new.company_id then
    raise exception 'The manual-entry account must belong to the same company.';
  end if;
  if new.entry_no is null or btrim(new.entry_no) = '' then
    new.entry_no := 'PLE-' || to_char(new.entry_date, 'YYYYMMDD') || '-' || lpad(new.id::text, 5, '0');
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists pl_manual_entries_prepare on public.pl_manual_entries;
create trigger pl_manual_entries_prepare
before insert or update on public.pl_manual_entries
for each row execute function public.prepare_pl_manual_entry();

create or replace function public.void_pl_manual_entry(p_entry_id bigint, p_reason text)
returns public.pl_manual_entries
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.pl_manual_entries;
begin
  if not public.is_app_administrator() then raise exception 'Administrator access is required.'; end if;
  if nullif(btrim(p_reason), '') is null then raise exception 'A void reason is required.'; end if;
  update public.pl_manual_entries
  set status = 'void',
      void_reason = btrim(p_reason),
      voided_by = auth.uid(),
      voided_at = now(),
      updated_by = auth.uid(),
      updated_at = now()
  where id = p_entry_id and status = 'posted'
  returning * into result;
  if result.id is null then raise exception 'Posted P&L entry was not found.'; end if;
  return result;
end;
$$;

-- -----------------------------------------------------------------------------
-- 5. OPTIONAL ACCOUNT CLASSIFICATION ON SOURCE RECORDS
-- -----------------------------------------------------------------------------
alter table public.customer_invoices
  add column if not exists pl_account_id bigint references public.pl_accounts(id) on delete set null;
alter table public.supplier_bills
  add column if not exists pl_account_id bigint references public.pl_accounts(id) on delete set null;
alter table public.driver_payouts
  add column if not exists pl_account_id bigint references public.pl_accounts(id) on delete set null;
alter table public.bank_cashbook_entries
  add column if not exists pl_account_id bigint references public.pl_accounts(id) on delete set null;

create index if not exists customer_invoices_pl_account_idx on public.customer_invoices(company_id, pl_account_id);
create index if not exists supplier_bills_pl_account_idx on public.supplier_bills(company_id, pl_account_id);
create index if not exists driver_payouts_pl_account_idx on public.driver_payouts(company_id, pl_account_id);
create index if not exists bank_cashbook_entries_pl_account_idx on public.bank_cashbook_entries(company_id, pl_account_id);

-- -----------------------------------------------------------------------------
-- 6. DEFAULT ACCOUNTS AND MAPPINGS FOR EVERY COMPANY
-- -----------------------------------------------------------------------------
create or replace function public.seed_pl_defaults(p_company_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  sales_id bigint;
  service_id bigint;
  general_expense_id bigint;
  driver_cost_id bigint;
  bank_charge_id bigint;
  other_income_id bigint;
  interest_income_id bigint;
  other_expense_id bigint;
begin
  insert into public.pl_accounts(company_id, account_code, account_name, account_group, is_system, sort_order, description)
  values
    (p_company_id, '4000', 'Sales Revenue', 'revenue', true, 100, 'Core customer sales and service revenue.'),
    (p_company_id, '4100', 'Service Charge Revenue', 'revenue', true, 110, 'Service charge income before GST.'),
    (p_company_id, '5000', 'Cost of Sales', 'cost_of_sales', true, 200, 'Direct costs attributable to sales.'),
    (p_company_id, '5100', 'Driver Costs', 'cost_of_sales', true, 210, 'Approved driver payouts and related direct driver costs.'),
    (p_company_id, '6000', 'General Operating Expenses', 'operating_expense', true, 300, 'General supplier and operating expenses.'),
    (p_company_id, '6100', 'Vehicle Expenses', 'operating_expense', true, 310, 'Fuel, maintenance, parking, ERP and vehicle expenses.'),
    (p_company_id, '6200', 'Staff Costs', 'operating_expense', true, 320, 'Salary, CPF and employment costs.'),
    (p_company_id, '6300', 'Rent and Premises', 'operating_expense', true, 330, 'Rent, utilities and premises costs.'),
    (p_company_id, '6400', 'Marketing and Promotion', 'operating_expense', true, 340, 'Advertising, promotions and marketing costs.'),
    (p_company_id, '6500', 'Professional Fees', 'operating_expense', true, 350, 'Accounting, legal and professional services.'),
    (p_company_id, '6600', 'Bank Charges', 'operating_expense', true, 360, 'Bank fees and payment processing charges.'),
    (p_company_id, '7000', 'Other Income', 'other_income', true, 400, 'Non-core income and positive adjustments.'),
    (p_company_id, '7100', 'Interest Income', 'other_income', true, 410, 'Interest earned.'),
    (p_company_id, '8000', 'Other Expenses', 'other_expense', true, 500, 'Non-core expenses and negative adjustments.')
  on conflict (company_id, account_code) do update
    set account_name = excluded.account_name,
        account_group = excluded.account_group,
        is_system = true,
        sort_order = excluded.sort_order,
        description = excluded.description,
        updated_at = now();

  select id into sales_id from public.pl_accounts where company_id = p_company_id and account_code = '4000';
  select id into service_id from public.pl_accounts where company_id = p_company_id and account_code = '4100';
  select id into general_expense_id from public.pl_accounts where company_id = p_company_id and account_code = '6000';
  select id into driver_cost_id from public.pl_accounts where company_id = p_company_id and account_code = '5100';
  select id into bank_charge_id from public.pl_accounts where company_id = p_company_id and account_code = '6600';
  select id into other_income_id from public.pl_accounts where company_id = p_company_id and account_code = '7000';
  select id into interest_income_id from public.pl_accounts where company_id = p_company_id and account_code = '7100';
  select id into other_expense_id from public.pl_accounts where company_id = p_company_id and account_code = '8000';

  insert into public.pl_source_mappings(company_id, source_type, source_category, account_id, priority, is_active)
  values
    (p_company_id, 'customer_invoice', 'invoice_subtotal', sales_id, 10, true),
    (p_company_id, 'customer_invoice', 'service_charge', service_id, 10, true),
    (p_company_id, 'customer_invoice', '*', sales_id, 100, true),
    (p_company_id, 'supplier_bill', '*', general_expense_id, 100, true),
    (p_company_id, 'driver_payout', '*', driver_cost_id, 100, true),
    (p_company_id, 'bank_cashbook', 'bank_fee', bank_charge_id, 10, true),
    (p_company_id, 'bank_cashbook', 'interest_income', interest_income_id, 10, true),
    (p_company_id, 'bank_cashbook', 'interest_expense', other_expense_id, 10, true),
    (p_company_id, 'bank_cashbook', 'adjustment_income', other_income_id, 10, true),
    (p_company_id, 'bank_cashbook', 'adjustment_expense', other_expense_id, 10, true)
  on conflict (company_id, source_type, source_category) do update
    set account_id = excluded.account_id,
        priority = excluded.priority,
        is_active = true,
        updated_at = now();
end;
$$;

create or replace function public.seed_pl_defaults_for_new_company()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.seed_pl_defaults(new.id);
  return new;
end;
$$;

drop trigger if exists companies_seed_pl_defaults on public.companies;
create trigger companies_seed_pl_defaults
after insert on public.companies
for each row execute function public.seed_pl_defaults_for_new_company();

do $$
declare
  company_record record;
begin
  for company_record in select id from public.companies loop
    perform public.seed_pl_defaults(company_record.id);
  end loop;
end;
$$;

-- -----------------------------------------------------------------------------
-- 7. SECURITY
-- -----------------------------------------------------------------------------
alter table public.pl_accounts enable row level security;
alter table public.pl_source_mappings enable row level security;
alter table public.pl_budgets enable row level security;
alter table public.pl_manual_entries enable row level security;

grant select, insert, update, delete on public.pl_accounts to authenticated;
grant select, insert, update, delete on public.pl_source_mappings to authenticated;
grant select, insert, update, delete on public.pl_budgets to authenticated;
grant select, insert, update, delete on public.pl_manual_entries to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.seed_pl_defaults(bigint) to authenticated;
grant execute on function public.void_pl_manual_entry(bigint, text) to authenticated;

drop policy if exists pl_accounts_admin_all on public.pl_accounts;
create policy pl_accounts_admin_all on public.pl_accounts
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists pl_source_mappings_admin_all on public.pl_source_mappings;
create policy pl_source_mappings_admin_all on public.pl_source_mappings
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists pl_budgets_admin_all on public.pl_budgets;
create policy pl_budgets_admin_all on public.pl_budgets
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists pl_manual_entries_admin_all on public.pl_manual_entries;
create policy pl_manual_entries_admin_all on public.pl_manual_entries
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

notify pgrst, 'reload schema';
commit;
