-- A3 MANAGEMENT FINANCE
-- PHASES 8, 9 AND 10 - COMPLETE INSTALLATION
-- Generated from migrations 017, 018 and 019.
-- Run only after migrations 000 through 016 and the consolidated 010_z compatibility migration.
-- Each phase runs in its own transaction. Safe to rerun.



-- ============================================================================
-- FILE: 017_balance_sheet_reporting.sql
-- ============================================================================

-- A3 MANAGEMENT FINANCE - UPGRADE 8
-- BALANCE SHEET REPORTING
-- Run after 016_profit_and_loss_reporting.sql.
-- Safe to rerun. Existing operational and finance records are preserved.

begin;

-- -----------------------------------------------------------------------------
-- 1. BALANCE SHEET CHART OF ACCOUNTS
-- -----------------------------------------------------------------------------
create table if not exists public.bs_accounts (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  account_code text not null,
  account_name text not null,
  account_group text not null default 'current_asset',
  normal_side text not null default 'debit',
  is_contra boolean not null default false,
  is_system boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 100,
  description text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (account_group in ('current_asset','non_current_asset','current_liability','non_current_liability','equity')),
  check (normal_side in ('debit','credit'))
);

alter table public.bs_accounts
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists account_code text,
  add column if not exists account_name text,
  add column if not exists account_group text default 'current_asset',
  add column if not exists normal_side text default 'debit',
  add column if not exists is_contra boolean default false,
  add column if not exists is_system boolean default false,
  add column if not exists is_active boolean default true,
  add column if not exists sort_order integer default 100,
  add column if not exists description text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.bs_accounts
set account_code = upper(coalesce(nullif(btrim(account_code), ''), 'BS-' || id::text)),
    account_name = coalesce(nullif(btrim(account_name), ''), 'Balance Sheet Account ' || id::text),
    account_group = case
      when lower(coalesce(account_group, '')) in ('current_asset','non_current_asset','current_liability','non_current_liability','equity')
        then lower(account_group)
      else 'current_asset'
    end,
    normal_side = case when lower(coalesce(normal_side, 'debit')) = 'credit' then 'credit' else 'debit' end,
    is_contra = coalesce(is_contra, false),
    is_system = coalesce(is_system, false),
    is_active = coalesce(is_active, true),
    sort_order = coalesce(sort_order, 100),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

update public.bs_accounts duplicate
set account_code = duplicate.account_code || '-DUP-' || duplicate.id::text
where exists (
  select 1 from public.bs_accounts original
  where original.company_id = duplicate.company_id
    and upper(original.account_code) = upper(duplicate.account_code)
    and original.id < duplicate.id
);

create unique index if not exists bs_accounts_company_code_uidx
  on public.bs_accounts(company_id, account_code);
create index if not exists bs_accounts_company_group_idx
  on public.bs_accounts(company_id, account_group, sort_order, account_code);

create or replace function public.prepare_bs_account()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.account_code := upper(coalesce(nullif(btrim(new.account_code), ''), 'BS'));
  new.account_name := coalesce(nullif(btrim(new.account_name), ''), 'Balance Sheet Account');
  new.account_group := lower(coalesce(nullif(btrim(new.account_group), ''), 'current_asset'));
  if new.account_group not in ('current_asset','non_current_asset','current_liability','non_current_liability','equity') then
    raise exception 'Invalid Balance Sheet account group.';
  end if;
  new.is_contra := coalesce(new.is_contra, false);
  new.normal_side := case
    when new.account_group in ('current_liability','non_current_liability','equity')
      then case when new.is_contra then 'debit' else 'credit' end
    else case when new.is_contra then 'credit' else 'debit' end
  end;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists bs_accounts_prepare on public.bs_accounts;
create trigger bs_accounts_prepare
before insert or update on public.bs_accounts
for each row execute function public.prepare_bs_account();

-- -----------------------------------------------------------------------------
-- 2. MANUAL BALANCE SHEET ENTRIES
-- Used for capital, loans, fixed assets, depreciation, accruals and opening items.
-- -----------------------------------------------------------------------------
create table if not exists public.bs_manual_entries (
  id bigint generated by default as identity primary key,
  entry_no text,
  company_id bigint not null references public.companies(id) on delete cascade,
  account_id bigint not null references public.bs_accounts(id) on delete restrict,
  entry_date date not null default current_date,
  description text not null,
  reference text,
  entry_side text not null default 'debit',
  amount numeric(16,2) not null,
  status text not null default 'posted',
  notes text,
  void_reason text,
  voided_by uuid references public.profiles(id) on delete set null,
  voided_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (entry_side in ('debit','credit')),
  check (amount > 0),
  check (status in ('posted','void'))
);

alter table public.bs_manual_entries
  add column if not exists entry_no text,
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists account_id bigint references public.bs_accounts(id) on delete restrict,
  add column if not exists entry_date date default current_date,
  add column if not exists description text,
  add column if not exists reference text,
  add column if not exists entry_side text default 'debit',
  add column if not exists amount numeric(16,2) default 0,
  add column if not exists status text default 'posted',
  add column if not exists notes text,
  add column if not exists void_reason text,
  add column if not exists voided_by uuid references public.profiles(id) on delete set null,
  add column if not exists voided_at timestamptz,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.bs_manual_entries
set entry_no = coalesce(nullif(btrim(entry_no), ''), 'BSE-' || lpad(id::text, 6, '0')),
    entry_date = coalesce(entry_date, current_date),
    description = coalesce(nullif(btrim(description), ''), 'Balance Sheet entry'),
    entry_side = case when lower(coalesce(entry_side, 'debit')) = 'credit' then 'credit' else 'debit' end,
    amount = greatest(abs(coalesce(amount, 0)), 0.01),
    status = case when lower(coalesce(status, 'posted')) = 'void' then 'void' else 'posted' end,
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

update public.bs_manual_entries duplicate
set entry_no = duplicate.entry_no || '-DUP-' || duplicate.id::text
where exists (
  select 1 from public.bs_manual_entries original
  where original.company_id = duplicate.company_id
    and lower(original.entry_no) = lower(duplicate.entry_no)
    and original.id < duplicate.id
);

create unique index if not exists bs_manual_entries_company_no_uidx
  on public.bs_manual_entries(company_id, entry_no);
create index if not exists bs_manual_entries_company_date_idx
  on public.bs_manual_entries(company_id, status, entry_date desc, id desc);

create or replace function public.prepare_bs_manual_entry()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  account_company_id bigint;
begin
  new.entry_date := coalesce(new.entry_date, current_date);
  new.description := coalesce(nullif(btrim(new.description), ''), 'Balance Sheet entry');
  new.entry_side := case when lower(coalesce(new.entry_side, 'debit')) = 'credit' then 'credit' else 'debit' end;
  new.amount := abs(coalesce(new.amount, 0));
  if new.amount <= 0 then raise exception 'Balance Sheet entry amount must be greater than zero.'; end if;
  select company_id into account_company_id from public.bs_accounts where id = new.account_id;
  if account_company_id is null or account_company_id <> new.company_id then
    raise exception 'The Balance Sheet account must belong to the same company.';
  end if;
  if new.entry_no is null or btrim(new.entry_no) = '' then
    new.entry_no := 'BSE-' || to_char(new.entry_date, 'YYYYMMDD') || '-' || lpad(new.id::text, 5, '0');
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists bs_manual_entries_prepare on public.bs_manual_entries;
create trigger bs_manual_entries_prepare
before insert or update on public.bs_manual_entries
for each row execute function public.prepare_bs_manual_entry();

create or replace function public.void_bs_manual_entry(p_entry_id bigint, p_reason text)
returns public.bs_manual_entries
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.bs_manual_entries;
begin
  if not public.is_app_administrator() then raise exception 'Administrator access is required.'; end if;
  if nullif(btrim(p_reason), '') is null then raise exception 'A void reason is required.'; end if;
  update public.bs_manual_entries
  set status = 'void', void_reason = btrim(p_reason), voided_by = auth.uid(), voided_at = now(),
      updated_by = auth.uid(), updated_at = now()
  where id = p_entry_id and status = 'posted'
  returning * into result;
  if result.id is null then raise exception 'Posted Balance Sheet entry was not found.'; end if;
  return result;
end;
$$;

-- -----------------------------------------------------------------------------
-- 3. REPORT SNAPSHOTS
-- -----------------------------------------------------------------------------
create table if not exists public.bs_report_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_no text,
  company_id bigint not null references public.companies(id) on delete cascade,
  as_of_date date not null,
  status text not null default 'draft',
  total_assets numeric(16,2) not null default 0,
  total_liabilities numeric(16,2) not null default 0,
  total_equity numeric(16,2) not null default 0,
  variance numeric(16,2) not null default 0,
  report_data jsonb not null default '{}'::jsonb,
  notes text,
  finalised_by uuid references public.profiles(id) on delete set null,
  finalised_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('draft','final')),
  unique(company_id, as_of_date)
);

alter table public.bs_report_snapshots
  add column if not exists snapshot_no text,
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists as_of_date date,
  add column if not exists status text default 'draft',
  add column if not exists total_assets numeric(16,2) default 0,
  add column if not exists total_liabilities numeric(16,2) default 0,
  add column if not exists total_equity numeric(16,2) default 0,
  add column if not exists variance numeric(16,2) default 0,
  add column if not exists report_data jsonb default '{}'::jsonb,
  add column if not exists notes text,
  add column if not exists finalised_by uuid references public.profiles(id) on delete set null,
  add column if not exists finalised_at timestamptz,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create unique index if not exists bs_report_snapshots_company_date_uidx
  on public.bs_report_snapshots(company_id, as_of_date);
create index if not exists bs_report_snapshots_company_idx
  on public.bs_report_snapshots(company_id, as_of_date desc, id desc);

create or replace function public.prepare_bs_snapshot()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.snapshot_no is null or btrim(new.snapshot_no) = '' then
    new.snapshot_no := 'BS-' || to_char(new.as_of_date, 'YYYYMMDD') || '-' || lpad(new.id::text, 4, '0');
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists bs_report_snapshots_prepare on public.bs_report_snapshots;
create trigger bs_report_snapshots_prepare
before insert or update on public.bs_report_snapshots
for each row execute function public.prepare_bs_snapshot();

-- -----------------------------------------------------------------------------
-- 4. DEFAULT ACCOUNTS
-- -----------------------------------------------------------------------------
create or replace function public.seed_bs_defaults(p_company_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.bs_accounts(company_id, account_code, account_name, account_group, normal_side, is_contra, is_system, sort_order, description)
  values
    (p_company_id, '1000', 'Cash and Bank', 'current_asset', 'debit', false, true, 100, 'Bank and cash-book balances.'),
    (p_company_id, '1100', 'Accounts Receivable', 'current_asset', 'debit', false, true, 110, 'Outstanding customer invoices.'),
    (p_company_id, '1200', 'Supplier Advances and Credits', 'current_asset', 'debit', false, true, 120, 'Unallocated supplier payments and credits.'),
    (p_company_id, '1300', 'GST Receivable', 'current_asset', 'debit', false, true, 130, 'Net recoverable GST.'),
    (p_company_id, '1500', 'Property, Plant and Equipment', 'non_current_asset', 'debit', false, true, 200, 'Vehicles, equipment and fixed assets.'),
    (p_company_id, '1590', 'Accumulated Depreciation', 'non_current_asset', 'credit', true, true, 210, 'Contra asset for accumulated depreciation.'),
    (p_company_id, '1900', 'Other Assets', 'non_current_asset', 'debit', false, true, 290, 'Other non-current assets.'),
    (p_company_id, '2000', 'Accounts Payable', 'current_liability', 'credit', false, true, 300, 'Outstanding supplier bills.'),
    (p_company_id, '2100', 'Customer Deposits and Credits', 'current_liability', 'credit', false, true, 310, 'Unallocated customer payments.'),
    (p_company_id, '2200', 'GST Payable', 'current_liability', 'credit', false, true, 320, 'Net GST payable.'),
    (p_company_id, '2300', 'Accrued Expenses', 'current_liability', 'credit', false, true, 330, 'Accrued operating expenses.'),
    (p_company_id, '2400', 'Driver Payouts Payable', 'current_liability', 'credit', false, true, 340, 'Approved driver payouts not yet settled.'),
    (p_company_id, '2500', 'Loans and Borrowings', 'non_current_liability', 'credit', false, true, 400, 'Long-term loans and borrowings.'),
    (p_company_id, '3000', 'Capital', 'equity', 'credit', false, true, 500, 'Shareholder or owner capital.'),
    (p_company_id, '3100', 'Drawings and Dividends', 'equity', 'debit', true, true, 510, 'Contra equity for drawings and dividends.'),
    (p_company_id, '3200', 'Retained Earnings', 'equity', 'credit', false, true, 520, 'Cumulative profit or loss.'),
    (p_company_id, '3900', 'Other Equity', 'equity', 'credit', false, true, 590, 'Other reserves and equity balances.')
  on conflict (company_id, account_code) do update
    set account_name = excluded.account_name,
        account_group = excluded.account_group,
        normal_side = excluded.normal_side,
        is_contra = excluded.is_contra,
        is_system = true,
        sort_order = excluded.sort_order,
        description = excluded.description,
        updated_at = now();
end;
$$;

do $$ declare company_record record; begin
  for company_record in select id from public.companies loop
    perform public.seed_bs_defaults(company_record.id);
  end loop;
end $$;

create or replace function public.seed_bs_defaults_for_new_company()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.seed_bs_defaults(new.id);
  return new;
end;
$$;

drop trigger if exists companies_seed_bs_defaults on public.companies;
create trigger companies_seed_bs_defaults
after insert on public.companies
for each row execute function public.seed_bs_defaults_for_new_company();

-- -----------------------------------------------------------------------------
-- 5. SECURITY
-- -----------------------------------------------------------------------------
alter table public.bs_accounts enable row level security;
alter table public.bs_manual_entries enable row level security;
alter table public.bs_report_snapshots enable row level security;

grant select, insert, update, delete on public.bs_accounts to authenticated;
grant select, insert, update, delete on public.bs_manual_entries to authenticated;
grant select, insert, update, delete on public.bs_report_snapshots to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.seed_bs_defaults(bigint) to authenticated;
grant execute on function public.void_bs_manual_entry(bigint,text) to authenticated;

do $$
declare table_name text;
begin
  for table_name in select unnest(array['bs_accounts','bs_manual_entries','bs_report_snapshots']) loop
    execute format('drop policy if exists %I on public.%I', table_name || '_administrator_all', table_name);
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator())',
      table_name || '_administrator_all', table_name
    );
  end loop;
end $$;

commit;

notify pgrst, 'reload schema';


-- ============================================================================
-- FILE: 018_cash_flow_statement.sql
-- ============================================================================

-- A3 MANAGEMENT FINANCE - UPGRADE 9
-- CASH FLOW STATEMENT
-- Run after 017_balance_sheet_reporting.sql.
-- Safe to rerun. Existing bank and cash-book records are preserved.

begin;

-- -----------------------------------------------------------------------------
-- 1. EXPLICIT CASH-FLOW CLASSIFICATION ON CASH-BOOK ENTRIES
-- -----------------------------------------------------------------------------
alter table public.bank_cashbook_entries
  add column if not exists cash_flow_activity text,
  add column if not exists cash_flow_line text;

-- Remove only older checks on these two columns before installing current rules.
do $$
declare constraint_record record;
begin
  for constraint_record in
    select conname
    from pg_constraint
    where conrelid = 'public.bank_cashbook_entries'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%cash_flow_activity%'
  loop
    execute format('alter table public.bank_cashbook_entries drop constraint %I', constraint_record.conname);
  end loop;
end $$;

update public.bank_cashbook_entries
set cash_flow_activity = case
      when lower(coalesce(cash_flow_activity, '')) in ('operating','investing','financing','excluded')
        then lower(cash_flow_activity)
      else null
    end,
    cash_flow_line = nullif(btrim(cash_flow_line), '');

alter table public.bank_cashbook_entries
  add constraint bank_cashbook_entries_cash_flow_activity_check
  check (cash_flow_activity is null or cash_flow_activity in ('operating','investing','financing','excluded'));

create index if not exists bank_cashbook_entries_cash_flow_idx
  on public.bank_cashbook_entries(company_id, cash_flow_activity, entry_date, status);

-- -----------------------------------------------------------------------------
-- 2. DEFAULT CLASSIFICATION MAPPINGS
-- -----------------------------------------------------------------------------
create table if not exists public.cash_flow_mappings (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  source_type text not null default '*',
  entry_type text not null default '*',
  activity text not null default 'operating',
  line_name text not null,
  priority integer not null default 100,
  is_active boolean not null default true,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (activity in ('operating','investing','financing','excluded'))
);

alter table public.cash_flow_mappings
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists source_type text default '*',
  add column if not exists entry_type text default '*',
  add column if not exists activity text default 'operating',
  add column if not exists line_name text,
  add column if not exists priority integer default 100,
  add column if not exists is_active boolean default true,
  add column if not exists notes text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.cash_flow_mappings
set source_type = lower(coalesce(nullif(btrim(source_type), ''), '*')),
    entry_type = lower(coalesce(nullif(btrim(entry_type), ''), '*')),
    activity = case
      when lower(coalesce(activity, 'operating')) in ('operating','investing','financing','excluded')
        then lower(activity)
      else 'operating'
    end,
    line_name = coalesce(nullif(btrim(line_name), ''), 'Other cash movement'),
    priority = coalesce(priority, 100),
    is_active = coalesce(is_active, true),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

update public.cash_flow_mappings duplicate
set source_type = duplicate.source_type || '-duplicate-' || duplicate.id::text
where exists (
  select 1 from public.cash_flow_mappings original
  where original.company_id = duplicate.company_id
    and original.source_type = duplicate.source_type
    and original.entry_type = duplicate.entry_type
    and original.id < duplicate.id
);

create unique index if not exists cash_flow_mappings_company_source_uidx
  on public.cash_flow_mappings(company_id, source_type, entry_type);
create index if not exists cash_flow_mappings_company_priority_idx
  on public.cash_flow_mappings(company_id, is_active, priority, id);

create or replace function public.prepare_cash_flow_mapping()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.source_type := lower(coalesce(nullif(btrim(new.source_type), ''), '*'));
  new.entry_type := lower(coalesce(nullif(btrim(new.entry_type), ''), '*'));
  new.activity := lower(coalesce(nullif(btrim(new.activity), ''), 'operating'));
  if new.activity not in ('operating','investing','financing','excluded') then
    raise exception 'Invalid cash-flow activity.';
  end if;
  new.line_name := coalesce(nullif(btrim(new.line_name), ''), 'Other cash movement');
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists cash_flow_mappings_prepare on public.cash_flow_mappings;
create trigger cash_flow_mappings_prepare
before insert or update on public.cash_flow_mappings
for each row execute function public.prepare_cash_flow_mapping();

-- -----------------------------------------------------------------------------
-- 3. REPORT SNAPSHOTS
-- -----------------------------------------------------------------------------
create table if not exists public.cash_flow_report_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_no text,
  company_id bigint not null references public.companies(id) on delete cascade,
  period_from date not null,
  period_to date not null,
  status text not null default 'draft',
  operating_cash numeric(16,2) not null default 0,
  investing_cash numeric(16,2) not null default 0,
  financing_cash numeric(16,2) not null default 0,
  net_cash_change numeric(16,2) not null default 0,
  opening_cash numeric(16,2) not null default 0,
  closing_cash numeric(16,2) not null default 0,
  reconciliation_difference numeric(16,2) not null default 0,
  report_data jsonb not null default '{}'::jsonb,
  notes text,
  finalised_by uuid references public.profiles(id) on delete set null,
  finalised_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (period_to >= period_from),
  check (status in ('draft','final')),
  unique(company_id, period_from, period_to)
);

alter table public.cash_flow_report_snapshots
  add column if not exists snapshot_no text,
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists period_from date,
  add column if not exists period_to date,
  add column if not exists status text default 'draft',
  add column if not exists operating_cash numeric(16,2) default 0,
  add column if not exists investing_cash numeric(16,2) default 0,
  add column if not exists financing_cash numeric(16,2) default 0,
  add column if not exists net_cash_change numeric(16,2) default 0,
  add column if not exists opening_cash numeric(16,2) default 0,
  add column if not exists closing_cash numeric(16,2) default 0,
  add column if not exists reconciliation_difference numeric(16,2) default 0,
  add column if not exists report_data jsonb default '{}'::jsonb,
  add column if not exists notes text,
  add column if not exists finalised_by uuid references public.profiles(id) on delete set null,
  add column if not exists finalised_at timestamptz,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create unique index if not exists cash_flow_snapshots_company_period_uidx
  on public.cash_flow_report_snapshots(company_id, period_from, period_to);
create index if not exists cash_flow_snapshots_company_idx
  on public.cash_flow_report_snapshots(company_id, period_to desc, id desc);

create or replace function public.prepare_cash_flow_snapshot()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.snapshot_no is null or btrim(new.snapshot_no) = '' then
    new.snapshot_no := 'CF-' || to_char(new.period_from, 'YYYYMMDD') || '-' || to_char(new.period_to, 'YYYYMMDD');
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists cash_flow_snapshots_prepare on public.cash_flow_report_snapshots;
create trigger cash_flow_snapshots_prepare
before insert or update on public.cash_flow_report_snapshots
for each row execute function public.prepare_cash_flow_snapshot();

-- -----------------------------------------------------------------------------
-- 4. DEFAULT MAPPINGS
-- -----------------------------------------------------------------------------
create or replace function public.seed_cash_flow_defaults(p_company_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.cash_flow_mappings(company_id, source_type, entry_type, activity, line_name, priority, notes)
  values
    (p_company_id, 'customer_payment', 'receipt', 'operating', 'Receipts from customers', 10, 'Posted customer receipts.'),
    (p_company_id, 'supplier_payment', 'payment', 'operating', 'Payments to suppliers', 20, 'Posted supplier payments.'),
    (p_company_id, 'driver_payout', 'payment', 'operating', 'Payments to drivers', 30, 'Driver payout settlement.'),
    (p_company_id, '*', 'bank_fee', 'operating', 'Bank and payment charges', 40, 'Bank charges and processing fees.'),
    (p_company_id, '*', 'interest', 'operating', 'Interest received or paid', 50, 'Interest cash movement.'),
    (p_company_id, '*', 'transfer', 'excluded', 'Transfers between own accounts', 60, 'Excluded from the cash-flow statement to avoid double counting.'),
    (p_company_id, '*', 'receipt', 'operating', 'Other operating receipts', 70, 'Other cash receipts.'),
    (p_company_id, '*', 'payment', 'operating', 'Other operating payments', 80, 'Other cash payments.'),
    (p_company_id, '*', 'adjustment', 'operating', 'Other operating cash movements', 90, 'Manual cash-book adjustment.')
  on conflict (company_id, source_type, entry_type) do update
    set activity = excluded.activity,
        line_name = excluded.line_name,
        priority = excluded.priority,
        notes = excluded.notes,
        updated_at = now();
end;
$$;

do $$ declare company_record record; begin
  for company_record in select id from public.companies loop
    perform public.seed_cash_flow_defaults(company_record.id);
  end loop;
end $$;

create or replace function public.seed_cash_flow_defaults_for_new_company()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.seed_cash_flow_defaults(new.id);
  return new;
end;
$$;

drop trigger if exists companies_seed_cash_flow_defaults on public.companies;
create trigger companies_seed_cash_flow_defaults
after insert on public.companies
for each row execute function public.seed_cash_flow_defaults_for_new_company();

-- -----------------------------------------------------------------------------
-- 5. SECURITY
-- -----------------------------------------------------------------------------
alter table public.cash_flow_mappings enable row level security;
alter table public.cash_flow_report_snapshots enable row level security;

grant select, insert, update, delete on public.cash_flow_mappings to authenticated;
grant select, insert, update, delete on public.cash_flow_report_snapshots to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.seed_cash_flow_defaults(bigint) to authenticated;

do $$
declare table_name text;
begin
  for table_name in select unnest(array['cash_flow_mappings','cash_flow_report_snapshots']) loop
    execute format('drop policy if exists %I on public.%I', table_name || '_administrator_all', table_name);
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator())',
      table_name || '_administrator_all', table_name
    );
  end loop;
end $$;

commit;

notify pgrst, 'reload schema';


-- ============================================================================
-- FILE: 019_final_consolidation_control.sql
-- ============================================================================

-- A3 MANAGEMENT FINANCE - UPGRADE 10
-- FINAL CONSOLIDATION, PERIOD CONTROL, PERMISSIONS AND AUDIT
-- Run after 018_cash_flow_statement.sql.
-- Safe to rerun. Existing finance records are preserved.

begin;

-- -----------------------------------------------------------------------------
-- 1. FINANCIAL PERIOD CLOSE CONTROL
-- -----------------------------------------------------------------------------
create table if not exists public.finance_periods (
  id bigint generated by default as identity primary key,
  period_no text,
  company_id bigint not null references public.companies(id) on delete cascade,
  period_name text not null,
  period_from date not null,
  period_to date not null,
  status text not null default 'open',
  close_notes text,
  closed_by uuid references public.profiles(id) on delete set null,
  closed_at timestamptz,
  reopened_by uuid references public.profiles(id) on delete set null,
  reopened_at timestamptz,
  reopened_reason text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (period_to >= period_from),
  check (status in ('open','closed')),
  unique(company_id, period_from, period_to)
);

alter table public.finance_periods
  add column if not exists period_no text,
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists period_name text,
  add column if not exists period_from date,
  add column if not exists period_to date,
  add column if not exists status text default 'open',
  add column if not exists close_notes text,
  add column if not exists closed_by uuid references public.profiles(id) on delete set null,
  add column if not exists closed_at timestamptz,
  add column if not exists reopened_by uuid references public.profiles(id) on delete set null,
  add column if not exists reopened_at timestamptz,
  add column if not exists reopened_reason text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create unique index if not exists finance_periods_company_range_uidx
  on public.finance_periods(company_id, period_from, period_to);
create index if not exists finance_periods_company_status_idx
  on public.finance_periods(company_id, status, period_to desc, id desc);

create or replace function public.prepare_finance_period()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.period_from is null or new.period_to is null then
    raise exception 'Financial period start and end dates are required.';
  end if;
  if new.period_to < new.period_from then
    raise exception 'Financial period end date cannot be earlier than the start date.';
  end if;
  if exists (
    select 1
    from public.finance_periods existing
    where existing.company_id = new.company_id
      and existing.id <> coalesce(new.id, 0)
      and daterange(existing.period_from, existing.period_to, '[]')
          && daterange(new.period_from, new.period_to, '[]')
  ) then
    raise exception 'The financial period overlaps an existing period for this company.';
  end if;
  if new.period_no is null or btrim(new.period_no) = '' then
    new.period_no := 'FP-' || to_char(new.period_from, 'YYYYMMDD') || '-' || to_char(new.period_to, 'YYYYMMDD');
  end if;
  new.period_name := coalesce(nullif(btrim(new.period_name), ''), to_char(new.period_from, 'Mon YYYY'));
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists finance_periods_prepare on public.finance_periods;
create trigger finance_periods_prepare
before insert or update on public.finance_periods
for each row execute function public.prepare_finance_period();

create or replace function public.is_finance_period_locked(p_company_id bigint, p_transaction_date date)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.finance_periods
    where company_id = p_company_id
      and status = 'closed'
      and p_transaction_date between period_from and period_to
  );
$$;

-- Generic period lock guard. The date-column name is supplied as trigger argument.
create or replace function public.guard_finance_period_lock()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  old_data jsonb;
  new_data jsonb;
  old_company bigint;
  new_company bigint;
  old_date date;
  new_date date;
begin
  if tg_op in ('UPDATE', 'DELETE') then
    old_data := to_jsonb(old);
    old_company := nullif(old_data ->> 'company_id', '')::bigint;
    old_date := nullif(old_data ->> tg_argv[0], '')::date;
    if old_company is not null and old_date is not null
       and public.is_finance_period_locked(old_company, old_date) then
      raise exception 'The financial period containing % is closed. Reopen the period before changing this record.', old_date;
    end if;
  end if;

  if tg_op in ('INSERT', 'UPDATE') then
    new_data := to_jsonb(new);
    new_company := nullif(new_data ->> 'company_id', '')::bigint;
    new_date := nullif(new_data ->> tg_argv[0], '')::date;
    if new_company is not null and new_date is not null
       and public.is_finance_period_locked(new_company, new_date) then
      raise exception 'The financial period containing % is closed. Reopen the period before changing this record.', new_date;
    end if;
  end if;

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

-- Install period lock guards only when the expected table/date column exists.
do $$
declare
  item record;
  trigger_name text;
begin
  for item in
    select * from (values
      ('customer_invoices','invoice_date'),
      ('customer_payments','payment_date'),
      ('supplier_bills','bill_date'),
      ('supplier_payments','payment_date'),
      ('supplier_credit_notes','credit_date'),
      ('driver_payouts','period_end'),
      ('bank_cashbook_entries','entry_date'),
      ('gst_adjustments','adjustment_date'),
      ('pl_manual_entries','entry_date'),
      ('bs_manual_entries','entry_date')
    ) as source(table_name, date_column)
  loop
    if to_regclass('public.' || item.table_name) is not null and exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = item.table_name and column_name = item.date_column
    ) then
      trigger_name := item.table_name || '_finance_period_guard';
      execute format('drop trigger if exists %I on public.%I', trigger_name, item.table_name);
      execute format(
        'create trigger %I before insert or update or delete on public.%I for each row execute function public.guard_finance_period_lock(%L)',
        trigger_name, item.table_name, item.date_column
      );
    end if;
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- 2. MODULE PERMISSIONS
-- -----------------------------------------------------------------------------
create table if not exists public.finance_module_permissions (
  id bigint generated by default as identity primary key,
  role_name text not null,
  module_name text not null,
  can_view boolean not null default false,
  can_create boolean not null default false,
  can_edit boolean not null default false,
  can_approve boolean not null default false,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique(role_name, module_name),
  check (role_name in ('administrator','finance','viewer','user'))
);

alter table public.finance_module_permissions
  add column if not exists role_name text,
  add column if not exists module_name text,
  add column if not exists can_view boolean default false,
  add column if not exists can_create boolean default false,
  add column if not exists can_edit boolean default false,
  add column if not exists can_approve boolean default false,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_at timestamptz default now();

insert into public.finance_module_permissions(role_name, module_name, can_view, can_create, can_edit, can_approve)
select role_name, module_name,
  role_name in ('administrator','finance','viewer'),
  role_name in ('administrator','finance'),
  role_name in ('administrator','finance'),
  role_name = 'administrator'
from unnest(array['administrator','finance','viewer','user']) as roles(role_name)
cross join unnest(array[
  'dashboard','invoices','receivables','payables','bank_reconciliation','gst_reports',
  'profit_loss','balance_sheet','cash_flow','financial_control'
]) as modules(module_name)
on conflict (role_name, module_name) do nothing;

update public.finance_module_permissions
set can_view = true, can_create = true, can_edit = true, can_approve = true, updated_at = now()
where role_name = 'administrator';

create or replace function public.finance_role_can(p_module_name text, p_action text default 'view')
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((
    select case lower(p_action)
      when 'view' then permission.can_view
      when 'create' then permission.can_create
      when 'edit' then permission.can_edit
      when 'approve' then permission.can_approve
      else false
    end
    from public.profiles profile
    join public.finance_module_permissions permission
      on permission.role_name = profile.role
     and permission.module_name = lower(p_module_name)
    where profile.id = auth.uid() and profile.status = 'active'
    limit 1
  ), false);
$$;

-- -----------------------------------------------------------------------------
-- 3. FINANCE AUDIT EVENTS
-- -----------------------------------------------------------------------------
create table if not exists public.finance_audit_events (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete set null,
  event_type text not null,
  module_name text not null,
  target_table text,
  target_id text,
  description text not null,
  details jsonb not null default '{}'::jsonb,
  actor_user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.finance_audit_events
  add column if not exists company_id bigint references public.companies(id) on delete set null,
  add column if not exists event_type text,
  add column if not exists module_name text,
  add column if not exists target_table text,
  add column if not exists target_id text,
  add column if not exists description text,
  add column if not exists details jsonb default '{}'::jsonb,
  add column if not exists actor_user_id uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now();

create index if not exists finance_audit_events_company_date_idx
  on public.finance_audit_events(company_id, created_at desc, id desc);
create index if not exists finance_audit_events_module_idx
  on public.finance_audit_events(module_name, created_at desc, id desc);

create or replace function public.close_finance_period(
  p_period_id bigint,
  p_notes text default null
)
returns public.finance_periods
language plpgsql
security definer
set search_path = public
as $$
declare result public.finance_periods;
begin
  if not public.is_app_administrator() then raise exception 'Administrator access is required.'; end if;
  update public.finance_periods
  set status = 'closed', close_notes = nullif(btrim(p_notes), ''), closed_by = auth.uid(), closed_at = now(),
      reopened_by = null, reopened_at = null, reopened_reason = null, updated_at = now()
  where id = p_period_id and status = 'open'
  returning * into result;
  if result.id is null then raise exception 'Open finance period was not found.'; end if;
  insert into public.finance_audit_events(company_id,event_type,module_name,target_table,target_id,description,actor_user_id)
  values(result.company_id,'period_closed','financial_control','finance_periods',result.id::text,'Financial period closed.',auth.uid());
  return result;
end;
$$;

create or replace function public.reopen_finance_period(
  p_period_id bigint,
  p_reason text
)
returns public.finance_periods
language plpgsql
security definer
set search_path = public
as $$
declare result public.finance_periods;
begin
  if not public.is_app_administrator() then raise exception 'Administrator access is required.'; end if;
  if nullif(btrim(p_reason), '') is null then raise exception 'A reopen reason is required.'; end if;
  update public.finance_periods
  set status = 'open', reopened_by = auth.uid(), reopened_at = now(), reopened_reason = btrim(p_reason), updated_at = now()
  where id = p_period_id and status = 'closed'
  returning * into result;
  if result.id is null then raise exception 'Closed finance period was not found.'; end if;
  insert into public.finance_audit_events(company_id,event_type,module_name,target_table,target_id,description,details,actor_user_id)
  values(result.company_id,'period_reopened','financial_control','finance_periods',result.id::text,'Financial period reopened.',jsonb_build_object('reason',btrim(p_reason)),auth.uid());
  return result;
end;
$$;

-- -----------------------------------------------------------------------------
-- 4. SECURITY
-- -----------------------------------------------------------------------------
alter table public.finance_periods enable row level security;
alter table public.finance_module_permissions enable row level security;
alter table public.finance_audit_events enable row level security;

grant select, insert, update, delete on public.finance_periods to authenticated;
grant select, insert, update, delete on public.finance_module_permissions to authenticated;
grant select, insert on public.finance_audit_events to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.is_finance_period_locked(bigint,date) to authenticated;
grant execute on function public.finance_role_can(text,text) to authenticated;
grant execute on function public.close_finance_period(bigint,text) to authenticated;
grant execute on function public.reopen_finance_period(bigint,text) to authenticated;

do $$
declare table_name text;
begin
  for table_name in select unnest(array['finance_periods','finance_module_permissions','finance_audit_events']) loop
    execute format('drop policy if exists %I on public.%I', table_name || '_administrator_all', table_name);
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator())',
      table_name || '_administrator_all', table_name
    );
  end loop;
end $$;

commit;

notify pgrst, 'reload schema';
