-- A3 MANAGEMENT FINANCE - UPGRADE 10
-- FINAL CONSOLIDATION, PERIOD CONTROL, PERMISSIONS AND AUDIT
-- Run after 018_cash_flow_statement.sql.
-- Safe to rerun. Existing finance records are preserved.

begin;

-- -----------------------------------------------------------------------------
-- 1. FINANCIAL PERIOD CLOSE CONTROL
-- -----------------------------------------------------------------------------
create table if not exists public.finance_periods (
  id bigint generated by default as identity primary key,
  period_no text,
  company_id bigint not null references public.companies(id) on delete cascade,
  period_name text not null,
  period_from date not null,
  period_to date not null,
  status text not null default 'open',
  close_notes text,
  closed_by uuid references public.profiles(id) on delete set null,
  closed_at timestamptz,
  reopened_by uuid references public.profiles(id) on delete set null,
  reopened_at timestamptz,
  reopened_reason text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (period_to >= period_from),
  check (status in ('open','closed')),
  unique(company_id, period_from, period_to)
);

alter table public.finance_periods
  add column if not exists period_no text,
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists period_name text,
  add column if not exists period_from date,
  add column if not exists period_to date,
  add column if not exists status text default 'open',
  add column if not exists close_notes text,
  add column if not exists closed_by uuid references public.profiles(id) on delete set null,
  add column if not exists closed_at timestamptz,
  add column if not exists reopened_by uuid references public.profiles(id) on delete set null,
  add column if not exists reopened_at timestamptz,
  add column if not exists reopened_reason text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create unique index if not exists finance_periods_company_range_uidx
  on public.finance_periods(company_id, period_from, period_to);
create index if not exists finance_periods_company_status_idx
  on public.finance_periods(company_id, status, period_to desc, id desc);

create or replace function public.prepare_finance_period()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.period_from is null or new.period_to is null then
    raise exception 'Financial period start and end dates are required.';
  end if;
  if new.period_to < new.period_from then
    raise exception 'Financial period end date cannot be earlier than the start date.';
  end if;
  if exists (
    select 1
    from public.finance_periods existing
    where existing.company_id = new.company_id
      and existing.id <> coalesce(new.id, 0)
      and daterange(existing.period_from, existing.period_to, '[]')
          && daterange(new.period_from, new.period_to, '[]')
  ) then
    raise exception 'The financial period overlaps an existing period for this company.';
  end if;
  if new.period_no is null or btrim(new.period_no) = '' then
    new.period_no := 'FP-' || to_char(new.period_from, 'YYYYMMDD') || '-' || to_char(new.period_to, 'YYYYMMDD');
  end if;
  new.period_name := coalesce(nullif(btrim(new.period_name), ''), to_char(new.period_from, 'Mon YYYY'));
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists finance_periods_prepare on public.finance_periods;
create trigger finance_periods_prepare
before insert or update on public.finance_periods
for each row execute function public.prepare_finance_period();

create or replace function public.is_finance_period_locked(p_company_id bigint, p_transaction_date date)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.finance_periods
    where company_id = p_company_id
      and status = 'closed'
      and p_transaction_date between period_from and period_to
  );
$$;

-- Generic period lock guard. The date-column name is supplied as trigger argument.
create or replace function public.guard_finance_period_lock()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  old_data jsonb;
  new_data jsonb;
  old_company bigint;
  new_company bigint;
  old_date date;
  new_date date;
begin
  if tg_op in ('UPDATE', 'DELETE') then
    old_data := to_jsonb(old);
    old_company := nullif(old_data ->> 'company_id', '')::bigint;
    old_date := nullif(old_data ->> tg_argv[0], '')::date;
    if old_company is not null and old_date is not null
       and public.is_finance_period_locked(old_company, old_date) then
      raise exception 'The financial period containing % is closed. Reopen the period before changing this record.', old_date;
    end if;
  end if;

  if tg_op in ('INSERT', 'UPDATE') then
    new_data := to_jsonb(new);
    new_company := nullif(new_data ->> 'company_id', '')::bigint;
    new_date := nullif(new_data ->> tg_argv[0], '')::date;
    if new_company is not null and new_date is not null
       and public.is_finance_period_locked(new_company, new_date) then
      raise exception 'The financial period containing % is closed. Reopen the period before changing this record.', new_date;
    end if;
  end if;

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

-- Install period lock guards only when the expected table/date column exists.
do $$
declare
  item record;
  trigger_name text;
begin
  for item in
    select * from (values
      ('customer_invoices','invoice_date'),
      ('customer_payments','payment_date'),
      ('supplier_bills','bill_date'),
      ('supplier_payments','payment_date'),
      ('supplier_credit_notes','credit_date'),
      ('driver_payouts','period_end'),
      ('bank_cashbook_entries','entry_date'),
      ('gst_adjustments','adjustment_date'),
      ('pl_manual_entries','entry_date'),
      ('bs_manual_entries','entry_date')
    ) as source(table_name, date_column)
  loop
    if to_regclass('public.' || item.table_name) is not null and exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = item.table_name and column_name = item.date_column
    ) then
      trigger_name := item.table_name || '_finance_period_guard';
      execute format('drop trigger if exists %I on public.%I', trigger_name, item.table_name);
      execute format(
        'create trigger %I before insert or update or delete on public.%I for each row execute function public.guard_finance_period_lock(%L)',
        trigger_name, item.table_name, item.date_column
      );
    end if;
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- 2. MODULE PERMISSIONS
-- -----------------------------------------------------------------------------
create table if not exists public.finance_module_permissions (
  id bigint generated by default as identity primary key,
  role_name text not null,
  module_name text not null,
  can_view boolean not null default false,
  can_create boolean not null default false,
  can_edit boolean not null default false,
  can_approve boolean not null default false,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique(role_name, module_name),
  check (role_name in ('administrator','finance','viewer','user'))
);

alter table public.finance_module_permissions
  add column if not exists role_name text,
  add column if not exists module_name text,
  add column if not exists can_view boolean default false,
  add column if not exists can_create boolean default false,
  add column if not exists can_edit boolean default false,
  add column if not exists can_approve boolean default false,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_at timestamptz default now();

insert into public.finance_module_permissions(role_name, module_name, can_view, can_create, can_edit, can_approve)
select role_name, module_name,
  role_name in ('administrator','finance','viewer'),
  role_name in ('administrator','finance'),
  role_name in ('administrator','finance'),
  role_name = 'administrator'
from unnest(array['administrator','finance','viewer','user']) as roles(role_name)
cross join unnest(array[
  'dashboard','invoices','receivables','payables','bank_reconciliation','gst_reports',
  'profit_loss','balance_sheet','cash_flow','financial_control'
]) as modules(module_name)
on conflict (role_name, module_name) do nothing;

update public.finance_module_permissions
set can_view = true, can_create = true, can_edit = true, can_approve = true, updated_at = now()
where role_name = 'administrator';

create or replace function public.finance_role_can(p_module_name text, p_action text default 'view')
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((
    select case lower(p_action)
      when 'view' then permission.can_view
      when 'create' then permission.can_create
      when 'edit' then permission.can_edit
      when 'approve' then permission.can_approve
      else false
    end
    from public.profiles profile
    join public.finance_module_permissions permission
      on permission.role_name = profile.role
     and permission.module_name = lower(p_module_name)
    where profile.id = auth.uid() and profile.status = 'active'
    limit 1
  ), false);
$$;

-- -----------------------------------------------------------------------------
-- 3. FINANCE AUDIT EVENTS
-- -----------------------------------------------------------------------------
create table if not exists public.finance_audit_events (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete set null,
  event_type text not null,
  module_name text not null,
  target_table text,
  target_id text,
  description text not null,
  details jsonb not null default '{}'::jsonb,
  actor_user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.finance_audit_events
  add column if not exists company_id bigint references public.companies(id) on delete set null,
  add column if not exists event_type text,
  add column if not exists module_name text,
  add column if not exists target_table text,
  add column if not exists target_id text,
  add column if not exists description text,
  add column if not exists details jsonb default '{}'::jsonb,
  add column if not exists actor_user_id uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now();

create index if not exists finance_audit_events_company_date_idx
  on public.finance_audit_events(company_id, created_at desc, id desc);
create index if not exists finance_audit_events_module_idx
  on public.finance_audit_events(module_name, created_at desc, id desc);

create or replace function public.close_finance_period(
  p_period_id bigint,
  p_notes text default null
)
returns public.finance_periods
language plpgsql
security definer
set search_path = public
as $$
declare result public.finance_periods;
begin
  if not public.is_app_administrator() then raise exception 'Administrator access is required.'; end if;
  update public.finance_periods
  set status = 'closed', close_notes = nullif(btrim(p_notes), ''), closed_by = auth.uid(), closed_at = now(),
      reopened_by = null, reopened_at = null, reopened_reason = null, updated_at = now()
  where id = p_period_id and status = 'open'
  returning * into result;
  if result.id is null then raise exception 'Open finance period was not found.'; end if;
  insert into public.finance_audit_events(company_id,event_type,module_name,target_table,target_id,description,actor_user_id)
  values(result.company_id,'period_closed','financial_control','finance_periods',result.id::text,'Financial period closed.',auth.uid());
  return result;
end;
$$;

create or replace function public.reopen_finance_period(
  p_period_id bigint,
  p_reason text
)
returns public.finance_periods
language plpgsql
security definer
set search_path = public
as $$
declare result public.finance_periods;
begin
  if not public.is_app_administrator() then raise exception 'Administrator access is required.'; end if;
  if nullif(btrim(p_reason), '') is null then raise exception 'A reopen reason is required.'; end if;
  update public.finance_periods
  set status = 'open', reopened_by = auth.uid(), reopened_at = now(), reopened_reason = btrim(p_reason), updated_at = now()
  where id = p_period_id and status = 'closed'
  returning * into result;
  if result.id is null then raise exception 'Closed finance period was not found.'; end if;
  insert into public.finance_audit_events(company_id,event_type,module_name,target_table,target_id,description,details,actor_user_id)
  values(result.company_id,'period_reopened','financial_control','finance_periods',result.id::text,'Financial period reopened.',jsonb_build_object('reason',btrim(p_reason)),auth.uid());
  return result;
end;
$$;

-- -----------------------------------------------------------------------------
-- 4. SECURITY
-- -----------------------------------------------------------------------------
alter table public.finance_periods enable row level security;
alter table public.finance_module_permissions enable row level security;
alter table public.finance_audit_events enable row level security;

grant select, insert, update, delete on public.finance_periods to authenticated;
grant select, insert, update, delete on public.finance_module_permissions to authenticated;
grant select, insert on public.finance_audit_events to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.is_finance_period_locked(bigint,date) to authenticated;
grant execute on function public.finance_role_can(text,text) to authenticated;
grant execute on function public.close_finance_period(bigint,text) to authenticated;
grant execute on function public.reopen_finance_period(bigint,text) to authenticated;

do $$
declare table_name text;
begin
  for table_name in select unnest(array['finance_periods','finance_module_permissions','finance_audit_events']) loop
    execute format('drop policy if exists %I on public.%I', table_name || '_administrator_all', table_name);
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator())',
      table_name || '_administrator_all', table_name
    );
  end loop;
end $$;

commit;

notify pgrst, 'reload schema';
