-- A3 MANAGEMENT - PHASE 11
-- DRIVER NETWORK, MULTI-COMPANY LINKS, CLIENT/CUSTOMER LINKS AND COMPANY-LOCKED SIGNUP
-- Run after migration 019. Safe to run more than once.

begin;

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- 1. DRIVER TO LIMOUSINE COMPANY NETWORK
-- ------------------------------------------------------------
create table if not exists public.driver_company_links (
  id bigint generated by default as identity primary key,
  driver_id bigint not null references public.drivers(id) on delete cascade,
  company_id bigint not null references public.companies(id) on delete restrict,
  is_primary boolean not null default false,
  membership_status text not null default 'active'
    check (membership_status in ('active', 'inactive', 'suspended')),
  joined_at date not null default current_date,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (driver_id, company_id)
);

create index if not exists driver_company_links_company_idx
  on public.driver_company_links(company_id, membership_status, driver_id);
create index if not exists driver_company_links_driver_idx
  on public.driver_company_links(driver_id, membership_status, company_id);
create unique index if not exists driver_company_links_one_primary_uidx
  on public.driver_company_links(driver_id)
  where is_primary = true and membership_status = 'active';

create or replace function public.validate_driver_company_link()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  selected_company_type text;
  selected_company_status text;
begin
  select company_type, status
    into selected_company_type, selected_company_status
  from public.companies
  where id = new.company_id;

  if selected_company_type is null then
    raise exception 'Selected company was not found.';
  end if;

  if selected_company_type <> 'limousine' then
    raise exception 'Drivers can only be linked through the Driver Network to limousine companies.';
  end if;

  if selected_company_status <> 'active' then
    raise exception 'The selected limousine company is inactive.';
  end if;

  if new.is_primary and new.membership_status = 'active' then
    update public.driver_company_links
       set is_primary = false,
           updated_at = now()
     where driver_id = new.driver_id
       and id <> coalesce(new.id, 0)
       and is_primary = true;
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists driver_company_links_validate on public.driver_company_links;
create trigger driver_company_links_validate
before insert or update on public.driver_company_links
for each row execute function public.validate_driver_company_link();

create or replace function public.sync_primary_driver_company()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.is_primary and new.membership_status = 'active' then
    update public.drivers
       set company_id = new.company_id,
           updated_at = now()
     where id = new.driver_id
       and company_id is distinct from new.company_id;
  end if;
  return new;
end;
$$;

drop trigger if exists driver_company_links_sync_primary on public.driver_company_links;
create trigger driver_company_links_sync_primary
after insert or update on public.driver_company_links
for each row execute function public.sync_primary_driver_company();

drop trigger if exists driver_company_links_set_updated_at on public.driver_company_links;
create trigger driver_company_links_set_updated_at
before update on public.driver_company_links
for each row execute function public.set_updated_at();

-- Backfill each existing driver whose current company is a limousine company.
-- Update existing links first, then insert only missing links. This avoids
-- PostgreSQL cardinality errors from a multi-row ON CONFLICT update.
update public.driver_company_links link
set is_primary = true,
    membership_status = case when driver.status = 'active' then 'active' else 'inactive' end,
    joined_at = coalesce(driver.created_at::date, link.joined_at, current_date),
    notes = coalesce(link.notes, 'Migrated from the original driver company assignment.'),
    updated_at = now()
from public.drivers driver
join public.companies company on company.id = driver.company_id
where company.company_type = 'limousine'
  and link.driver_id = driver.id
  and link.company_id = driver.company_id;

insert into public.driver_company_links (
  driver_id,
  company_id,
  is_primary,
  membership_status,
  joined_at,
  notes
)
select
  driver.id,
  driver.company_id,
  true,
  case when driver.status = 'active' then 'active' else 'inactive' end,
  coalesce(driver.created_at::date, current_date),
  'Migrated from the original driver company assignment.'
from public.drivers driver
join public.companies company on company.id = driver.company_id
where company.company_type = 'limousine'
  and not exists (
    select 1
    from public.driver_company_links link
    where link.driver_id = driver.id
      and link.company_id = driver.company_id
  );

-- ------------------------------------------------------------
-- 2. DRIVER TO CLIENT / CUSTOMER LINKS
-- Company-type customers are shown as Clients. Individual customers are
-- shown as Customers. The relationship type is assigned automatically.
-- ------------------------------------------------------------
create table if not exists public.driver_customer_links (
  id bigint generated by default as identity primary key,
  driver_id bigint not null references public.drivers(id) on delete cascade,
  company_id bigint not null references public.companies(id) on delete restrict,
  customer_id bigint not null references public.customers(id) on delete cascade,
  relationship_type text not null default 'client'
    check (relationship_type in ('client', 'customer')),
  link_status text not null default 'active'
    check (link_status in ('active', 'inactive')),
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (driver_id, customer_id)
);

create index if not exists driver_customer_links_driver_idx
  on public.driver_customer_links(driver_id, link_status, company_id);
create index if not exists driver_customer_links_customer_idx
  on public.driver_customer_links(customer_id, link_status, driver_id);
create index if not exists driver_customer_links_company_idx
  on public.driver_customer_links(company_id, link_status, driver_id);

create or replace function public.validate_driver_customer_link()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  selected_customer_company bigint;
  selected_customer_type text;
begin
  select company_id, customer_type
    into selected_customer_company, selected_customer_type
  from public.customers
  where id = new.customer_id;

  if selected_customer_company is null then
    raise exception 'Selected client or customer was not found.';
  end if;

  if selected_customer_company <> new.company_id then
    raise exception 'The selected client or customer does not belong to this company.';
  end if;

  if not exists (
    select 1
    from public.driver_company_links link
    where link.driver_id = new.driver_id
      and link.company_id = new.company_id
      and link.membership_status = 'active'
  ) then
    raise exception 'The driver must first be linked to this limousine company.';
  end if;

  new.relationship_type := case
    when selected_customer_type = 'individual' then 'customer'
    else 'client'
  end;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists driver_customer_links_validate on public.driver_customer_links;
create trigger driver_customer_links_validate
before insert or update on public.driver_customer_links
for each row execute function public.validate_driver_customer_link();

drop trigger if exists driver_customer_links_set_updated_at on public.driver_customer_links;
create trigger driver_customer_links_set_updated_at
before update on public.driver_customer_links
for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- 3. COMPANY-SPECIFIC PUBLIC DRIVER SIGNUP LINKS
-- The public token determines the company. Applicants cannot choose or alter it.
-- ------------------------------------------------------------
create table if not exists public.driver_signup_links (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public.companies(id) on delete cascade,
  public_token uuid not null default gen_random_uuid() unique,
  link_name text not null default 'Driver Recruitment',
  status text not null default 'active'
    check (status in ('active', 'inactive')),
  expires_at timestamptz,
  max_applications integer check (max_applications is null or max_applications > 0),
  application_count integer not null default 0 check (application_count >= 0),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists driver_signup_links_company_idx
  on public.driver_signup_links(company_id, status, created_at desc);
create index if not exists driver_signup_links_token_idx
  on public.driver_signup_links(public_token);

create or replace function public.validate_driver_signup_link()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  selected_company_type text;
  selected_company_status text;
begin
  select company_type, status
    into selected_company_type, selected_company_status
  from public.companies
  where id = new.company_id;

  if selected_company_type is null then
    raise exception 'Selected company was not found.';
  end if;
  if selected_company_type <> 'limousine' then
    raise exception 'Driver signup links can only be created for limousine companies.';
  end if;
  if (tg_op = 'INSERT' or new.company_id is distinct from old.company_id)
     and selected_company_status <> 'active' then
    raise exception 'Driver signup links require an active limousine company.';
  end if;

  new.link_name := coalesce(nullif(btrim(new.link_name), ''), 'Driver Recruitment');
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists driver_signup_links_validate on public.driver_signup_links;
create trigger driver_signup_links_validate
before insert or update on public.driver_signup_links
for each row execute function public.validate_driver_signup_link();

drop trigger if exists driver_signup_links_set_updated_at on public.driver_signup_links;
create trigger driver_signup_links_set_updated_at
before update on public.driver_signup_links
for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- 4. DRIVER SIGNUP APPLICATIONS
-- ------------------------------------------------------------
create table if not exists public.driver_signup_applications (
  id bigint generated by default as identity primary key,
  application_no text unique,
  signup_link_id uuid not null references public.driver_signup_links(id) on delete restrict,
  company_id bigint not null references public.companies(id) on delete restrict,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'withdrawn')),
  driver_id bigint references public.drivers(id) on delete set null,

  full_name text not null,
  phone text not null,
  contact_email text not null,
  address text,
  nric_passport text,
  nationality text,
  date_of_birth date,
  licence_no text,
  licence_class text,
  licence_expiry date,
  emergency_contact_name text,
  emergency_contact_phone text,
  vehicle_make text,
  vehicle_model text,
  vehicle_plate text,
  vehicle_type text,
  bank_name text,
  bank_account_name text,
  bank_account_no text,
  paynow_type text check (paynow_type is null or paynow_type in ('mobile', 'nric', 'uen', 'other')),
  paynow_no text,
  notes text,
  consent_confirmed boolean not null default false,

  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  review_notes text,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists driver_signup_applications_company_idx
  on public.driver_signup_applications(company_id, status, submitted_at desc);
create index if not exists driver_signup_applications_link_idx
  on public.driver_signup_applications(signup_link_id, status, submitted_at desc);
create unique index if not exists driver_signup_applications_pending_email_uidx
  on public.driver_signup_applications(company_id, lower(contact_email))
  where status = 'pending';

create or replace function public.prepare_driver_signup_application()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  selected_link public.driver_signup_links%rowtype;
begin
  select * into selected_link
  from public.driver_signup_links
  where id = new.signup_link_id;

  if selected_link.id is null then
    raise exception 'Driver signup link was not found.';
  end if;

  if tg_op = 'INSERT' then
    if selected_link.status <> 'active' then
      raise exception 'This driver signup link is inactive.';
    end if;
    if selected_link.expires_at is not null and selected_link.expires_at <= now() then
      raise exception 'This driver signup link has expired.';
    end if;
    if selected_link.max_applications is not null
       and selected_link.application_count >= selected_link.max_applications then
      raise exception 'This driver signup link has reached its application limit.';
    end if;
  end if;

  new.company_id := selected_link.company_id;
  new.full_name := btrim(new.full_name);
  new.phone := btrim(new.phone);
  new.contact_email := lower(btrim(new.contact_email));
  new.vehicle_plate := nullif(upper(btrim(coalesce(new.vehicle_plate, ''))), '');
  new.updated_at := now();

  if new.full_name = '' or new.phone = '' or new.contact_email = '' then
    raise exception 'Name, phone and email are required.';
  end if;
  if not new.consent_confirmed then
    raise exception 'Consent confirmation is required.';
  end if;

  return new;
end;
$$;

drop trigger if exists driver_signup_applications_prepare on public.driver_signup_applications;
create trigger driver_signup_applications_prepare
before insert or update on public.driver_signup_applications
for each row execute function public.prepare_driver_signup_application();

create or replace function public.assign_driver_application_number()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.application_no is null or btrim(new.application_no) = '' then
    new.application_no := 'DRVAPP-' || lpad(new.id::text, 6, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists driver_signup_applications_assign_number on public.driver_signup_applications;
create trigger driver_signup_applications_assign_number
before insert on public.driver_signup_applications
for each row execute function public.assign_driver_application_number();

create or replace function public.count_driver_signup_application()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  update public.driver_signup_links
     set application_count = application_count + 1,
         updated_at = now()
   where id = new.signup_link_id;
  return new;
end;
$$;

drop trigger if exists driver_signup_applications_count on public.driver_signup_applications;
create trigger driver_signup_applications_count
after insert on public.driver_signup_applications
for each row execute function public.count_driver_signup_application();

drop trigger if exists driver_signup_applications_set_updated_at on public.driver_signup_applications;
create trigger driver_signup_applications_set_updated_at
before update on public.driver_signup_applications
for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- 5. SECURITY
-- Public signup is handled only through the server API using the service role.
-- No anonymous table access is granted.
-- ------------------------------------------------------------
alter table public.driver_company_links enable row level security;
alter table public.driver_customer_links enable row level security;
alter table public.driver_signup_links enable row level security;
alter table public.driver_signup_applications enable row level security;

grant select, insert, update, delete on
  public.driver_company_links,
  public.driver_customer_links,
  public.driver_signup_links,
  public.driver_signup_applications
  to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Driver company links: administrators manage; drivers can see their own network.
drop policy if exists driver_company_links_select_admin_or_self on public.driver_company_links;
create policy driver_company_links_select_admin_or_self on public.driver_company_links
for select to authenticated
using (
  public.is_app_administrator()
  or exists (
    select 1 from public.drivers driver
    where driver.id = driver_company_links.driver_id
      and driver.auth_user_id = auth.uid()
  )
);

drop policy if exists driver_company_links_manage_admin on public.driver_company_links;
create policy driver_company_links_manage_admin on public.driver_company_links
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

-- Driver customer links: administrators manage; drivers can see their own links.
drop policy if exists driver_customer_links_select_admin_or_self on public.driver_customer_links;
create policy driver_customer_links_select_admin_or_self on public.driver_customer_links
for select to authenticated
using (
  public.is_app_administrator()
  or exists (
    select 1 from public.drivers driver
    where driver.id = driver_customer_links.driver_id
      and driver.auth_user_id = auth.uid()
  )
);

drop policy if exists driver_customer_links_manage_admin on public.driver_customer_links;
create policy driver_customer_links_manage_admin on public.driver_customer_links
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

-- Signup links and applications are administrator-only inside the authenticated app.
drop policy if exists driver_signup_links_admin on public.driver_signup_links;
create policy driver_signup_links_admin on public.driver_signup_links
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

drop policy if exists driver_signup_applications_admin on public.driver_signup_applications;
create policy driver_signup_applications_admin on public.driver_signup_applications
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());


-- Phase 10 permission matrix extension for the new administrator module.
with desired(role_name, module_name, can_view, can_create, can_edit, can_approve) as (
  values
    ('administrator', 'driver_network', true, true, true, true),
    ('finance',       'driver_network', false, false, false, false),
    ('viewer',        'driver_network', false, false, false, false),
    ('user',          'driver_network', false, false, false, false)
)
update public.finance_module_permissions permission
set can_view = desired.can_view,
    can_create = desired.can_create,
    can_edit = desired.can_edit,
    can_approve = desired.can_approve,
    updated_at = now()
from desired
where permission.role_name = desired.role_name
  and permission.module_name = desired.module_name;

insert into public.finance_module_permissions(
  role_name,
  module_name,
  can_view,
  can_create,
  can_edit,
  can_approve
)
select
  desired.role_name,
  desired.module_name,
  desired.can_view,
  desired.can_create,
  desired.can_edit,
  desired.can_approve
from (
  values
    ('administrator', 'driver_network', true, true, true, true),
    ('finance',       'driver_network', false, false, false, false),
    ('viewer',        'driver_network', false, false, false, false),
    ('user',          'driver_network', false, false, false, false)
) as desired(role_name, module_name, can_view, can_create, can_edit, can_approve)
where not exists (
  select 1
  from public.finance_module_permissions permission
  where permission.role_name = desired.role_name
    and permission.module_name = desired.module_name
);

notify pgrst, 'reload schema';
commit;
