-- A3 MANAGEMENT - PHASE 1 STEP 3
-- DRIVER MANAGEMENT, DRIVER LOGIN, DOCUMENTS, JOB/PAYOUT FOUNDATION
-- Run after migrations 000, 001, 002 and 003.
-- Safe to run more than once. Existing companies, users and drivers are not deleted.

begin;

-- ------------------------------------------------------------
-- 1. ALLOW THE DRIVER LOGIN ROLE
-- ------------------------------------------------------------
do $$
declare
  constraint_name text;
begin
  for constraint_name in
    select conname
    from pg_constraint
    where conrelid = 'public.profiles'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%role%'
  loop
    execute format('alter table public.profiles drop constraint %I', constraint_name);
  end loop;
end
$$;

alter table public.profiles
  add constraint profiles_role_check
  check (role in ('administrator', 'finance', 'viewer', 'user', 'driver'))
  not valid;

alter table public.profiles validate constraint profiles_role_check;

-- ------------------------------------------------------------
-- 2. DRIVER MASTER
-- ------------------------------------------------------------
create table if not exists public.drivers (
  id bigint generated by default as identity primary key,
  driver_no text unique,
  company_id bigint not null references public.companies(id) on delete restrict,
  auth_user_id uuid unique references auth.users(id) on delete set null,

  full_name text not null,
  phone text,
  contact_email text,
  login_email text,
  address text,
  nric_passport text,
  nationality text,
  date_of_birth date,

  licence_no text,
  licence_class text,
  licence_expiry date,

  emergency_contact_name text,
  emergency_contact_phone text,

  vehicle_make text,
  vehicle_model text,
  vehicle_plate text,
  vehicle_type text,

  bank_name text,
  bank_account_name text,
  bank_account_no text,
  paynow_type text check (paynow_type is null or paynow_type in ('mobile', 'nric', 'uen', 'other')),
  paynow_no text,

  profile_photo_path text,
  licence_front_path text,
  licence_back_path text,
  identity_document_path text,

  login_enabled boolean not null default false,
  status text not null default 'active' check (status in ('active', 'inactive')),
  notes text,

  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists drivers_login_email_lower_uidx
  on public.drivers(lower(login_email))
  where login_email is not null;
create index if not exists drivers_company_id_idx on public.drivers(company_id);
create index if not exists drivers_auth_user_id_idx on public.drivers(auth_user_id);
create index if not exists drivers_status_idx on public.drivers(status);
create index if not exists drivers_vehicle_plate_lower_idx on public.drivers(lower(vehicle_plate));

create or replace function public.assign_driver_number()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.driver_no is null or btrim(new.driver_no) = '' then
    new.driver_no := 'DRV-' || lpad(new.id::text, 5, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists drivers_assign_number on public.drivers;
create trigger drivers_assign_number
before insert on public.drivers
for each row execute function public.assign_driver_number();

drop trigger if exists drivers_set_updated_at on public.drivers;
create trigger drivers_set_updated_at
before update on public.drivers
for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- 3. DRIVER JOB FOUNDATION
-- ------------------------------------------------------------
create table if not exists public.driver_jobs (
  id bigint generated by default as identity primary key,
  driver_id bigint not null references public.drivers(id) on delete cascade,
  company_id bigint not null references public.companies(id) on delete restrict,
  job_reference text,
  job_date date not null default current_date,
  service_type text,
  pickup_location text,
  dropoff_location text,
  gross_amount numeric(14,2) not null default 0,
  driver_amount numeric(14,2) not null default 0,
  status text not null default 'completed'
    check (status in ('scheduled', 'in_progress', 'completed', 'cancelled')),
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists driver_jobs_driver_date_idx
  on public.driver_jobs(driver_id, job_date desc);
create index if not exists driver_jobs_company_date_idx
  on public.driver_jobs(company_id, job_date desc);

drop trigger if exists driver_jobs_set_updated_at on public.driver_jobs;
create trigger driver_jobs_set_updated_at
before update on public.driver_jobs
for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- 4. DRIVER PAYOUT FOUNDATION
-- ------------------------------------------------------------
create table if not exists public.driver_payouts (
  id bigint generated by default as identity primary key,
  driver_id bigint not null references public.drivers(id) on delete cascade,
  company_id bigint not null references public.companies(id) on delete restrict,
  payout_no text unique,
  period_start date,
  period_end date,
  gross_earnings numeric(14,2) not null default 0,
  deductions numeric(14,2) not null default 0,
  advances numeric(14,2) not null default 0,
  amount_paid numeric(14,2) not null default 0,
  net_payout numeric(14,2) generated always as
    (gross_earnings - deductions - advances) stored,
  outstanding_amount numeric(14,2) generated always as
    (greatest(gross_earnings - deductions - advances - amount_paid, 0)) stored,
  payment_date date,
  payment_method text,
  status text not null default 'draft'
    check (status in ('draft', 'approved', 'partial', 'paid', 'cancelled')),
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists driver_payouts_driver_period_idx
  on public.driver_payouts(driver_id, period_end desc);
create index if not exists driver_payouts_company_period_idx
  on public.driver_payouts(company_id, period_end desc);

drop trigger if exists driver_payouts_set_updated_at on public.driver_payouts;
create trigger driver_payouts_set_updated_at
before update on public.driver_payouts
for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- 5. DRIVER SELF-SERVICE RPC
-- Only the editable fields are accepted by this function.
-- ------------------------------------------------------------
create or replace function public.update_own_driver_profile(
  p_phone text,
  p_contact_email text,
  p_address text,
  p_emergency_contact_name text,
  p_emergency_contact_phone text,
  p_vehicle_make text,
  p_vehicle_model text,
  p_vehicle_plate text,
  p_vehicle_type text,
  p_bank_name text,
  p_bank_account_name text,
  p_bank_account_no text,
  p_paynow_type text,
  p_paynow_no text,
  p_notes text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_driver_id bigint;
begin
  if auth.uid() is null then
    raise exception 'You must be signed in.';
  end if;

  update public.drivers
  set phone = nullif(btrim(p_phone), ''),
      contact_email = nullif(lower(btrim(p_contact_email)), ''),
      address = nullif(btrim(p_address), ''),
      emergency_contact_name = nullif(btrim(p_emergency_contact_name), ''),
      emergency_contact_phone = nullif(btrim(p_emergency_contact_phone), ''),
      vehicle_make = nullif(btrim(p_vehicle_make), ''),
      vehicle_model = nullif(btrim(p_vehicle_model), ''),
      vehicle_plate = nullif(upper(btrim(p_vehicle_plate)), ''),
      vehicle_type = nullif(btrim(p_vehicle_type), ''),
      bank_name = nullif(btrim(p_bank_name), ''),
      bank_account_name = nullif(btrim(p_bank_account_name), ''),
      bank_account_no = nullif(btrim(p_bank_account_no), ''),
      paynow_type = case
        when nullif(btrim(p_paynow_type), '') is null then null
        when p_paynow_type in ('mobile', 'nric', 'uen', 'other') then p_paynow_type
        else null
      end,
      paynow_no = nullif(btrim(p_paynow_no), ''),
      notes = nullif(btrim(p_notes), ''),
      updated_by = auth.uid(),
      updated_at = now()
  where auth_user_id = auth.uid()
    and status = 'active'
  returning id into updated_driver_id;

  if updated_driver_id is null then
    raise exception 'Active driver profile was not found.';
  end if;

  return updated_driver_id;
end;
$$;

-- ------------------------------------------------------------
-- 6. ROW LEVEL SECURITY
-- ------------------------------------------------------------
alter table public.drivers enable row level security;
alter table public.driver_jobs enable row level security;
alter table public.driver_payouts enable row level security;

grant select, insert, update, delete on public.drivers to authenticated;
grant select, insert, update, delete on public.driver_jobs to authenticated;
grant select, insert, update, delete on public.driver_payouts to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.update_own_driver_profile(
  text,text,text,text,text,text,text,text,text,text,text,text,text,text,text
) to authenticated;

-- Drivers: administrators manage all; linked driver reads their own record.
drop policy if exists drivers_select_admin_or_self on public.drivers;
create policy drivers_select_admin_or_self on public.drivers
for select to authenticated
using (
  public.is_app_administrator()
  or auth_user_id = auth.uid()
);

drop policy if exists drivers_insert_administrator on public.drivers;
create policy drivers_insert_administrator on public.drivers
for insert to authenticated
with check (public.is_app_administrator());

drop policy if exists drivers_update_administrator on public.drivers;
create policy drivers_update_administrator on public.drivers
for update to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

drop policy if exists drivers_delete_administrator on public.drivers;
create policy drivers_delete_administrator on public.drivers
for delete to authenticated
using (public.is_app_administrator());

-- Jobs: administrators manage; linked drivers can view their own jobs.
drop policy if exists driver_jobs_select_admin_or_self on public.driver_jobs;
create policy driver_jobs_select_admin_or_self on public.driver_jobs
for select to authenticated
using (
  public.is_app_administrator()
  or exists (
    select 1 from public.drivers driver
    where driver.id = driver_jobs.driver_id
      and driver.auth_user_id = auth.uid()
  )
);

drop policy if exists driver_jobs_write_administrator on public.driver_jobs;
create policy driver_jobs_write_administrator on public.driver_jobs
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

-- Payouts: administrators manage; linked drivers can view their own payouts.
drop policy if exists driver_payouts_select_admin_or_self on public.driver_payouts;
create policy driver_payouts_select_admin_or_self on public.driver_payouts
for select to authenticated
using (
  public.is_app_administrator()
  or exists (
    select 1 from public.drivers driver
    where driver.id = driver_payouts.driver_id
      and driver.auth_user_id = auth.uid()
  )
);

drop policy if exists driver_payouts_write_administrator on public.driver_payouts;
create policy driver_payouts_write_administrator on public.driver_payouts
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

-- ------------------------------------------------------------
-- 7. PRIVATE DRIVER DOCUMENT STORAGE
-- ------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'driver-documents',
  'driver-documents',
  false,
  10485760,
  array['image/png', 'image/jpeg', 'image/webp', 'application/pdf']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

-- Administrators and the linked driver can read a driver's own folder.
drop policy if exists driver_documents_select_admin_or_self on storage.objects;
create policy driver_documents_select_admin_or_self
on storage.objects
for select
to authenticated
using (
  bucket_id = 'driver-documents'
  and (
    public.is_app_administrator()
    or exists (
      select 1 from public.drivers driver
      where driver.auth_user_id = auth.uid()
        and driver.id::text = (storage.foldername(name))[2]
    )
  )
);

drop policy if exists driver_documents_insert_administrator on storage.objects;
create policy driver_documents_insert_administrator
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'driver-documents'
  and public.is_app_administrator()
);

drop policy if exists driver_documents_update_administrator on storage.objects;
create policy driver_documents_update_administrator
on storage.objects
for update
to authenticated
using (
  bucket_id = 'driver-documents'
  and public.is_app_administrator()
)
with check (
  bucket_id = 'driver-documents'
  and public.is_app_administrator()
);

drop policy if exists driver_documents_delete_administrator on storage.objects;
create policy driver_documents_delete_administrator
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'driver-documents'
  and public.is_app_administrator()
);

notify pgrst, 'reload schema';
commit;

select
  id,
  driver_no,
  full_name,
  company_id,
  login_email,
  login_enabled,
  status
from public.drivers
order by created_at;
