-- A3 MANAGEMENT - PHASE 1 STEP 5
-- DRIVER PAYOUTS & PAYMENT TRACKING
-- Run after 005_phase1_jobs_booking_management.sql.

begin;

create table if not exists public.driver_payout_items (
  id bigint generated by default as identity primary key,
  payout_id bigint not null references public.driver_payouts(id) on delete cascade,
  job_id bigint not null references public.driver_jobs(id) on delete restrict,
  amount numeric(14,2) not null default 0 check (amount >= 0),
  created_at timestamptz not null default now(),
  unique(job_id)
);

create index if not exists driver_payout_items_payout_idx
  on public.driver_payout_items(payout_id);

create or replace function public.assign_driver_payout_no()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.payout_no is null or btrim(new.payout_no) = '' then
    new.payout_no := 'PAY-' || to_char(coalesce(new.period_end, current_date), 'YYYYMMDD') || '-' || lpad(new.id::text, 5, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists driver_payouts_assign_no on public.driver_payouts;
create trigger driver_payouts_assign_no
before insert on public.driver_payouts
for each row execute function public.assign_driver_payout_no();

alter table public.driver_payout_items enable row level security;
grant select, insert, update, delete on public.driver_payout_items to authenticated;
grant usage, select on sequence public.driver_payout_items_id_seq to authenticated;

drop policy if exists driver_payout_items_select_admin_or_self on public.driver_payout_items;
create policy driver_payout_items_select_admin_or_self on public.driver_payout_items
for select to authenticated
using (
  public.is_app_administrator()
  or exists (
    select 1
    from public.driver_payouts payout
    join public.drivers driver on driver.id = payout.driver_id
    where payout.id = driver_payout_items.payout_id
      and driver.auth_user_id = auth.uid()
  )
);

drop policy if exists driver_payout_items_write_administrator on public.driver_payout_items;
create policy driver_payout_items_write_administrator on public.driver_payout_items
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

commit;
