-- A3 MANAGEMENT - PHASE 1 STEP 6
-- CUSTOMER INVOICES & PAYMENT COLLECTION
-- Run after 006_phase1_driver_payouts.sql.

begin;

create table if not exists public.customer_invoices (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete restrict,
  invoice_no text,
  invoice_date date not null default current_date,
  due_date date,
  customer_name text not null,
  customer_phone text,
  customer_email text,
  billing_address text,
  subtotal numeric(14,2) not null default 0 check (subtotal >= 0),
  service_charge_rate numeric(7,4) not null default 0 check (service_charge_rate >= 0),
  service_charge_amount numeric(14,2) not null default 0 check (service_charge_amount >= 0),
  gst_rate numeric(7,4) not null default 0 check (gst_rate >= 0),
  gst_amount numeric(14,2) not null default 0 check (gst_amount >= 0),
  total_amount numeric(14,2) not null default 0 check (total_amount >= 0),
  amount_paid numeric(14,2) not null default 0 check (amount_paid >= 0),
  status text not null default 'draft' check (status in ('draft','issued','partial','paid','overdue','cancelled')),
  payment_method text,
  payment_reference text,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_invoice_items (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.customer_invoices(id) on delete cascade,
  job_id bigint references public.driver_jobs(id) on delete restrict,
  description text not null,
  quantity numeric(12,2) not null default 1 check (quantity > 0),
  unit_price numeric(14,2) not null default 0 check (unit_price >= 0),
  line_total numeric(14,2) not null default 0 check (line_total >= 0),
  created_at timestamptz not null default now(),
  unique(job_id)
);

create unique index if not exists customer_invoices_company_no_uidx
  on public.customer_invoices(company_id, lower(invoice_no))
  where invoice_no is not null;
create index if not exists customer_invoices_company_date_idx on public.customer_invoices(company_id, invoice_date desc);
create index if not exists customer_invoice_items_invoice_idx on public.customer_invoice_items(invoice_id);

create or replace function public.assign_customer_invoice_no()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.invoice_no is null or btrim(new.invoice_no) = '' then
    new.invoice_no := 'INV-' || to_char(coalesce(new.invoice_date, current_date), 'YYYYMMDD') || '-' || lpad(new.id::text, 5, '0');
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists customer_invoices_assign_no on public.customer_invoices;
create trigger customer_invoices_assign_no
before insert or update on public.customer_invoices
for each row execute function public.assign_customer_invoice_no();

alter table public.customer_invoices enable row level security;
alter table public.customer_invoice_items enable row level security;

grant select, insert, update, delete on public.customer_invoices to authenticated;
grant select, insert, update, delete on public.customer_invoice_items to authenticated;
grant usage, select on sequence public.customer_invoices_id_seq to authenticated;
grant usage, select on sequence public.customer_invoice_items_id_seq to authenticated;

drop policy if exists customer_invoices_administrator_all on public.customer_invoices;
create policy customer_invoices_administrator_all on public.customer_invoices
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

drop policy if exists customer_invoice_items_administrator_all on public.customer_invoice_items;
create policy customer_invoice_items_administrator_all on public.customer_invoice_items
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

commit;
