-- A3 MANAGEMENT - PHASE 1.9
-- Quotation PDF, company GST rules and payment gateway/admin fees.
-- Run once after 008_phase1_customer_crm.sql.
begin;

alter table public.companies
  add column if not exists gst_registered boolean not null default false,
  add column if not exists gst_no text,
  add column if not exists gst_rate numeric(7,4) not null default 9,
  add column if not exists company_email text,
  add column if not exists company_phone text,
  add column if not exists company_address text,
  add column if not exists bank_details text;

create table if not exists public.company_payment_gateways (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  gateway_code text not null check (gateway_code in ('kpay','fomopay','hitpay','stripe')),
  display_name text not null,
  enabled boolean not null default false,
  fee_type text not null default 'percentage' check (fee_type in ('percentage','fixed')),
  fee_value numeric(14,4) not null default 0 check (fee_value >= 0),
  fee_borne_by text not null default 'customer' check (fee_borne_by in ('customer','company')),
  minimum_amount numeric(14,2) not null default 0 check (minimum_amount >= 0),
  qr_image_url text,
  payment_instructions text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(company_id,gateway_code)
);

alter table public.quotations
  add column if not exists payment_gateway_code text,
  add column if not exists payment_fee_type text,
  add column if not exists payment_fee_rate numeric(14,4) not null default 0,
  add column if not exists payment_admin_fee numeric(14,2) not null default 0,
  add column if not exists payment_fee_borne_by text not null default 'customer',
  add column if not exists gst_registered_snapshot boolean not null default false,
  add column if not exists gst_no_snapshot text;

create index if not exists company_payment_gateways_company_idx
  on public.company_payment_gateways(company_id, enabled);

grant select,insert,update,delete on public.company_payment_gateways to authenticated;
grant usage,select on sequence public.company_payment_gateways_id_seq to authenticated;

insert into public.company_payment_gateways(company_id,gateway_code,display_name,enabled)
select c.id, g.code, g.name, false
from public.companies c
cross join (values
 ('kpay','KPay'),('fomopay','FOMO Pay'),('hitpay','HitPay'),('stripe','Stripe')
) as g(code,name)
on conflict(company_id,gateway_code) do nothing;

commit;
