-- A3 MANAGEMENT FINANCE - UPGRADE 6
-- GST REPORTS & TAX CONTROL
-- Run after 014_bank_reconciliation_cash_accounts.sql.
-- Safe to rerun. Existing invoices, supplier bills and payment records are preserved.

begin;

-- -----------------------------------------------------------------------------
-- 1. COMPANY GST CONTROL SETTINGS
-- -----------------------------------------------------------------------------
alter table public.companies
  add column if not exists gst_reporting_frequency text default 'quarterly',
  add column if not exists gst_accounting_basis text default 'invoice',
  add column if not exists gst_effective_from date,
  add column if not exists gst_deregistered_on date,
  add column if not exists gst_submission_due_days integer default 30,
  add column if not exists gst_financial_year_start_month integer default 1;

update public.companies
set gst_reporting_frequency = case
      when lower(coalesce(gst_reporting_frequency, 'quarterly')) in ('monthly','quarterly','half_yearly','annual')
        then lower(gst_reporting_frequency)
      else 'quarterly'
    end,
    gst_accounting_basis = case
      when lower(coalesce(gst_accounting_basis, 'invoice')) in ('invoice','payment')
        then lower(gst_accounting_basis)
      else 'invoice'
    end,
    gst_submission_due_days = greatest(coalesce(gst_submission_due_days, 30), 0),
    gst_financial_year_start_month = least(greatest(coalesce(gst_financial_year_start_month, 1), 1), 12);

-- -----------------------------------------------------------------------------
-- 2. GST TAX CODES
-- -----------------------------------------------------------------------------
create table if not exists public.gst_tax_codes (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  code text not null,
  name text not null,
  transaction_type text not null default 'both',
  treatment text not null default 'standard_rated',
  rate numeric(7,4) not null default 0,
  recoverable_percentage numeric(7,4) not null default 100,
  box_no integer,
  is_default_sales boolean not null default false,
  is_default_purchase boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 100,
  description text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (transaction_type in ('sales','purchase','both')),
  check (treatment in ('standard_rated','zero_rated','exempt','out_of_scope','blocked_input')),
  check (rate between 0 and 100),
  check (recoverable_percentage between 0 and 100),
  check (box_no is null or box_no between 1 and 8)
);

alter table public.gst_tax_codes
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists code text,
  add column if not exists name text,
  add column if not exists transaction_type text default 'both',
  add column if not exists treatment text default 'standard_rated',
  add column if not exists rate numeric(7,4) default 0,
  add column if not exists recoverable_percentage numeric(7,4) default 100,
  add column if not exists box_no integer,
  add column if not exists is_default_sales boolean default false,
  add column if not exists is_default_purchase boolean default false,
  add column if not exists is_active boolean default true,
  add column if not exists sort_order integer default 100,
  add column if not exists description text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.gst_tax_codes
set code = upper(coalesce(nullif(btrim(code), ''), 'GST-' || id::text)),
    name = coalesce(nullif(btrim(name), ''), 'GST Code'),
    transaction_type = case when lower(coalesce(transaction_type, 'both')) in ('sales','purchase','both') then lower(transaction_type) else 'both' end,
    treatment = case when lower(coalesce(treatment, 'standard_rated')) in ('standard_rated','zero_rated','exempt','out_of_scope','blocked_input') then lower(treatment) else 'standard_rated' end,
    rate = least(greatest(coalesce(rate, 0), 0), 100),
    recoverable_percentage = least(greatest(coalesce(recoverable_percentage, 100), 0), 100),
    is_default_sales = coalesce(is_default_sales, false),
    is_default_purchase = coalesce(is_default_purchase, false),
    is_active = coalesce(is_active, true),
    sort_order = coalesce(sort_order, 100),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

-- Normalise duplicate legacy codes before enforcing uniqueness.
update public.gst_tax_codes duplicate
set code = duplicate.code || '-DUP-' || duplicate.id::text
where exists (
  select 1 from public.gst_tax_codes original
  where original.company_id = duplicate.company_id
    and lower(original.code) = lower(duplicate.code)
    and original.id < duplicate.id
);

-- Keep only the first legacy default in each direction.
update public.gst_tax_codes duplicate
set is_default_sales = false
where duplicate.is_default_sales = true
  and exists (
    select 1 from public.gst_tax_codes original
    where original.company_id = duplicate.company_id
      and original.is_default_sales = true
      and original.id < duplicate.id
  );

update public.gst_tax_codes duplicate
set is_default_purchase = false
where duplicate.is_default_purchase = true
  and exists (
    select 1 from public.gst_tax_codes original
    where original.company_id = duplicate.company_id
      and original.is_default_purchase = true
      and original.id < duplicate.id
  );

create unique index if not exists gst_tax_codes_company_code_uidx
  on public.gst_tax_codes(company_id, lower(code));
create index if not exists gst_tax_codes_company_active_idx
  on public.gst_tax_codes(company_id, is_active, sort_order, code);
create unique index if not exists gst_tax_codes_default_sales_uidx
  on public.gst_tax_codes(company_id)
  where is_default_sales = true;
create unique index if not exists gst_tax_codes_default_purchase_uidx
  on public.gst_tax_codes(company_id)
  where is_default_purchase = true;

create or replace function public.prepare_gst_tax_code()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.code := upper(coalesce(nullif(btrim(new.code), ''), 'GST'));
  new.name := coalesce(nullif(btrim(new.name), ''), new.code);
  new.transaction_type := case when lower(coalesce(new.transaction_type, 'both')) in ('sales','purchase','both') then lower(new.transaction_type) else 'both' end;
  new.treatment := case when lower(coalesce(new.treatment, 'standard_rated')) in ('standard_rated','zero_rated','exempt','out_of_scope','blocked_input') then lower(new.treatment) else 'standard_rated' end;
  new.rate := least(greatest(coalesce(new.rate, 0), 0), 100);
  new.recoverable_percentage := least(greatest(coalesce(new.recoverable_percentage, 100), 0), 100);
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists gst_tax_codes_prepare_record on public.gst_tax_codes;
create trigger gst_tax_codes_prepare_record
before insert or update on public.gst_tax_codes
for each row execute function public.prepare_gst_tax_code();

-- Seed a complete starter set for every company.
insert into public.gst_tax_codes(
  company_id, code, name, transaction_type, treatment, rate,
  recoverable_percentage, box_no, is_default_sales, is_default_purchase,
  sort_order, description
)
select company.id, seed.code, seed.name, seed.transaction_type, seed.treatment,
       case when seed.use_company_rate then coalesce(company.gst_rate, 9) else seed.rate end,
       seed.recoverable_percentage, seed.box_no,
       seed.is_default_sales, seed.is_default_purchase, seed.sort_order, seed.description
from public.companies company
cross join (
  values
    ('SR-S', 'Standard-Rated Sales', 'sales', 'standard_rated', 0::numeric, true, 100::numeric, 1, true, false, 10, 'Taxable local sales at the company GST rate.'),
    ('ZR-S', 'Zero-Rated Sales', 'sales', 'zero_rated', 0::numeric, false, 100::numeric, 2, false, false, 20, 'Zero-rated supplies.'),
    ('ES-S', 'Exempt Sales', 'sales', 'exempt', 0::numeric, false, 100::numeric, 3, false, false, 30, 'Exempt supplies.'),
    ('OS-S', 'Out-of-Scope Sales', 'sales', 'out_of_scope', 0::numeric, false, 100::numeric, null::integer, false, false, 40, 'Transactions outside the GST return.'),
    ('TX-P', 'Taxable Purchase', 'purchase', 'standard_rated', 0::numeric, true, 100::numeric, 5, false, true, 50, 'Purchase with recoverable input tax.'),
    ('BL-P', 'Blocked Input Tax', 'purchase', 'blocked_input', 0::numeric, true, 0::numeric, 5, false, false, 60, 'Purchase where input tax is not recoverable.'),
    ('NR-P', 'Non-Taxable Purchase', 'purchase', 'out_of_scope', 0::numeric, false, 0::numeric, null::integer, false, false, 70, 'Purchase without claimable GST.')
) as seed(code,name,transaction_type,treatment,rate,use_company_rate,recoverable_percentage,box_no,is_default_sales,is_default_purchase,sort_order,description)
on conflict do nothing;

-- -----------------------------------------------------------------------------
-- 3. DOCUMENT TAX CLASSIFICATION
-- -----------------------------------------------------------------------------
alter table public.customer_invoices
  add column if not exists gst_tax_code_id bigint references public.gst_tax_codes(id) on delete set null,
  add column if not exists gst_treatment text default 'standard_rated',
  add column if not exists gst_reportable boolean default true,
  add column if not exists gst_review_status text default 'pending',
  add column if not exists gst_review_notes text,
  add column if not exists gst_reviewed_by uuid references public.profiles(id) on delete set null,
  add column if not exists gst_reviewed_at timestamptz;

update public.customer_invoices
set gst_treatment = case
      when lower(coalesce(gst_treatment, '')) in ('standard_rated','zero_rated','exempt','out_of_scope') then lower(gst_treatment)
      when coalesce(gst_amount, 0) > 0 then 'standard_rated'
      else 'out_of_scope'
    end,
    gst_reportable = coalesce(gst_reportable, true),
    gst_review_status = case when lower(coalesce(gst_review_status, 'pending')) in ('pending','reviewed','excluded') then lower(gst_review_status) else 'pending' end;

update public.customer_invoices invoice
set gst_tax_code_id = code.id
from public.gst_tax_codes code
where invoice.gst_tax_code_id is null
  and code.company_id = invoice.company_id
  and code.is_default_sales = true;

alter table public.supplier_bills
  add column if not exists gst_tax_code_id bigint references public.gst_tax_codes(id) on delete set null,
  add column if not exists gst_treatment text default 'standard_rated',
  add column if not exists gst_reportable boolean default true,
  add column if not exists gst_review_status text default 'pending',
  add column if not exists gst_review_notes text,
  add column if not exists input_tax_recoverable_percentage numeric(7,4) default 100,
  add column if not exists recoverable_gst_amount numeric(14,2) default 0,
  add column if not exists gst_reviewed_by uuid references public.profiles(id) on delete set null,
  add column if not exists gst_reviewed_at timestamptz;

update public.supplier_bills
set gst_treatment = case
      when lower(coalesce(gst_treatment, '')) in ('standard_rated','zero_rated','exempt','out_of_scope','blocked_input') then lower(gst_treatment)
      when coalesce(gst_amount, 0) > 0 then 'standard_rated'
      else 'out_of_scope'
    end,
    gst_reportable = coalesce(gst_reportable, true),
    gst_review_status = case when lower(coalesce(gst_review_status, 'pending')) in ('pending','reviewed','excluded') then lower(gst_review_status) else 'pending' end,
    input_tax_recoverable_percentage = least(greatest(coalesce(input_tax_recoverable_percentage, 100), 0), 100),
    recoverable_gst_amount = round(
      greatest(coalesce(gst_amount, 0), 0) * least(greatest(coalesce(input_tax_recoverable_percentage, 100), 0), 100) / 100,
      2
    );

update public.supplier_bills bill
set gst_tax_code_id = code.id
from public.gst_tax_codes code
where bill.gst_tax_code_id is null
  and code.company_id = bill.company_id
  and code.is_default_purchase = true;

create index if not exists customer_invoices_gst_review_idx
  on public.customer_invoices(company_id, invoice_date, gst_review_status, gst_reportable);
create index if not exists supplier_bills_gst_review_idx
  on public.supplier_bills(company_id, bill_date, gst_review_status, gst_reportable);

create or replace function public.prepare_supplier_bill_gst_control()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.input_tax_recoverable_percentage := least(greatest(coalesce(new.input_tax_recoverable_percentage, 100), 0), 100);
  new.recoverable_gst_amount := round(greatest(coalesce(new.gst_amount, 0), 0) * new.input_tax_recoverable_percentage / 100, 2);
  new.gst_reportable := coalesce(new.gst_reportable, true);
  new.gst_review_status := case when lower(coalesce(new.gst_review_status, 'pending')) in ('pending','reviewed','excluded') then lower(new.gst_review_status) else 'pending' end;
  return new;
end;
$$;

drop trigger if exists supplier_bills_prepare_gst_control on public.supplier_bills;
create trigger supplier_bills_prepare_gst_control
before insert or update of gst_amount, input_tax_recoverable_percentage, gst_review_status, gst_reportable
on public.supplier_bills
for each row execute function public.prepare_supplier_bill_gst_control();

-- -----------------------------------------------------------------------------
-- 4. GST ADJUSTMENTS AND FILING PERIODS
-- -----------------------------------------------------------------------------
create table if not exists public.gst_adjustments (
  id bigint generated by default as identity primary key,
  adjustment_no text,
  company_id bigint not null references public.companies(id) on delete restrict,
  adjustment_date date not null default current_date,
  adjustment_type text not null,
  treatment text not null default 'standard_rated',
  taxable_amount numeric(14,2) not null default 0,
  gst_amount numeric(14,2) not null default 0,
  reference text,
  reason text not null,
  status text not null default 'posted',
  notes text,
  void_reason text,
  voided_by uuid references public.profiles(id) on delete set null,
  voided_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (adjustment_type in ('output_tax','input_tax')),
  check (treatment in ('standard_rated','zero_rated','exempt','out_of_scope','blocked_input')),
  check (status in ('posted','void'))
);

alter table public.gst_adjustments
  add column if not exists adjustment_no text,
  add column if not exists company_id bigint references public.companies(id) on delete restrict,
  add column if not exists adjustment_date date default current_date,
  add column if not exists adjustment_type text,
  add column if not exists treatment text default 'standard_rated',
  add column if not exists taxable_amount numeric(14,2) default 0,
  add column if not exists gst_amount numeric(14,2) default 0,
  add column if not exists reference text,
  add column if not exists reason text,
  add column if not exists status text default 'posted',
  add column if not exists notes text,
  add column if not exists void_reason text,
  add column if not exists voided_by uuid references public.profiles(id) on delete set null,
  add column if not exists voided_at timestamptz,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.gst_adjustments
set adjustment_date = coalesce(adjustment_date, current_date),
    adjustment_type = case when lower(coalesce(adjustment_type, 'output_tax')) = 'input_tax' then 'input_tax' else 'output_tax' end,
    treatment = case when lower(coalesce(treatment, 'standard_rated')) in ('standard_rated','zero_rated','exempt','out_of_scope','blocked_input') then lower(treatment) else 'standard_rated' end,
    taxable_amount = coalesce(taxable_amount, 0),
    gst_amount = coalesce(gst_amount, 0),
    reason = coalesce(nullif(btrim(reason), ''), 'GST adjustment'),
    status = case when lower(coalesce(status, 'posted')) = 'void' then 'void' else 'posted' end,
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

create unique index if not exists gst_adjustments_no_uidx
  on public.gst_adjustments(lower(adjustment_no))
  where adjustment_no is not null;
create index if not exists gst_adjustments_company_date_idx
  on public.gst_adjustments(company_id, adjustment_date desc, status);

create or replace function public.prepare_gst_adjustment()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.adjustment_no is null or btrim(new.adjustment_no) = '' then
    new.adjustment_no := 'GSTA-' || to_char(coalesce(new.adjustment_date, current_date), 'YYYYMMDD') || '-' || lpad(new.id::text, 5, '0');
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists gst_adjustments_prepare_record on public.gst_adjustments;
create trigger gst_adjustments_prepare_record
before insert or update on public.gst_adjustments
for each row execute function public.prepare_gst_adjustment();

create table if not exists public.gst_filing_periods (
  id bigint generated by default as identity primary key,
  period_no text,
  company_id bigint not null references public.companies(id) on delete restrict,
  period_label text not null,
  period_from date not null,
  period_to date not null,
  due_date date,
  status text not null default 'draft',
  box1_standard_rated_supplies numeric(14,2) not null default 0,
  box2_zero_rated_supplies numeric(14,2) not null default 0,
  box3_exempt_supplies numeric(14,2) not null default 0,
  box4_total_supplies numeric(14,2) not null default 0,
  box5_taxable_purchases numeric(14,2) not null default 0,
  box6_output_tax numeric(14,2) not null default 0,
  box7_input_tax numeric(14,2) not null default 0,
  box8_net_gst numeric(14,2) not null default 0,
  source_snapshot_at timestamptz,
  notes text,
  filed_reference text,
  filed_at timestamptz,
  filed_by uuid references public.profiles(id) on delete set null,
  reopened_reason text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(company_id, period_from, period_to),
  check (period_to >= period_from),
  check (status in ('draft','reviewed','filed'))
);

alter table public.gst_filing_periods
  add column if not exists period_no text,
  add column if not exists company_id bigint references public.companies(id) on delete restrict,
  add column if not exists period_label text,
  add column if not exists period_from date,
  add column if not exists period_to date,
  add column if not exists due_date date,
  add column if not exists status text default 'draft',
  add column if not exists box1_standard_rated_supplies numeric(14,2) default 0,
  add column if not exists box2_zero_rated_supplies numeric(14,2) default 0,
  add column if not exists box3_exempt_supplies numeric(14,2) default 0,
  add column if not exists box4_total_supplies numeric(14,2) default 0,
  add column if not exists box5_taxable_purchases numeric(14,2) default 0,
  add column if not exists box6_output_tax numeric(14,2) default 0,
  add column if not exists box7_input_tax numeric(14,2) default 0,
  add column if not exists box8_net_gst numeric(14,2) default 0,
  add column if not exists source_snapshot_at timestamptz,
  add column if not exists notes text,
  add column if not exists filed_reference text,
  add column if not exists filed_at timestamptz,
  add column if not exists filed_by uuid references public.profiles(id) on delete set null,
  add column if not exists reopened_reason text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create unique index if not exists gst_filing_periods_no_uidx
  on public.gst_filing_periods(lower(period_no))
  where period_no is not null;
create index if not exists gst_filing_periods_company_idx
  on public.gst_filing_periods(company_id, period_from desc, period_to desc);

create or replace function public.prepare_gst_filing_period()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.period_no is null or btrim(new.period_no) = '' then
    new.period_no := 'GST-' || to_char(new.period_from, 'YYYYMMDD') || '-' || lpad(new.id::text, 4, '0');
  end if;
  new.period_label := coalesce(nullif(btrim(new.period_label), ''), to_char(new.period_from, 'DD Mon YYYY') || ' to ' || to_char(new.period_to, 'DD Mon YYYY'));
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists gst_filing_periods_prepare_record on public.gst_filing_periods;
create trigger gst_filing_periods_prepare_record
before insert or update on public.gst_filing_periods
for each row execute function public.prepare_gst_filing_period();

create table if not exists public.gst_period_entries (
  id bigint generated by default as identity primary key,
  period_id bigint not null references public.gst_filing_periods(id) on delete cascade,
  company_id bigint not null references public.companies(id) on delete restrict,
  source_type text not null,
  source_id bigint not null,
  source_no text,
  source_date date not null,
  counterparty text,
  direction text not null,
  treatment text not null,
  taxable_amount numeric(14,2) not null default 0,
  gst_amount numeric(14,2) not null default 0,
  recoverable_gst_amount numeric(14,2) not null default 0,
  box_no integer,
  description text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(period_id, source_type, source_id),
  check (source_type in ('customer_invoice','supplier_bill','adjustment')),
  check (direction in ('output','input')),
  check (treatment in ('standard_rated','zero_rated','exempt','out_of_scope','blocked_input'))
);

alter table public.gst_period_entries
  add column if not exists period_id bigint references public.gst_filing_periods(id) on delete cascade,
  add column if not exists company_id bigint references public.companies(id) on delete restrict,
  add column if not exists source_type text,
  add column if not exists source_id bigint,
  add column if not exists source_no text,
  add column if not exists source_date date,
  add column if not exists counterparty text,
  add column if not exists direction text,
  add column if not exists treatment text,
  add column if not exists taxable_amount numeric(14,2) default 0,
  add column if not exists gst_amount numeric(14,2) default 0,
  add column if not exists recoverable_gst_amount numeric(14,2) default 0,
  add column if not exists box_no integer,
  add column if not exists description text,
  add column if not exists details jsonb default '{}'::jsonb,
  add column if not exists created_at timestamptz default now();

create unique index if not exists gst_period_entries_source_uidx
  on public.gst_period_entries(period_id, source_type, source_id);
create index if not exists gst_period_entries_period_idx
  on public.gst_period_entries(period_id, box_no, source_date, id);

-- -----------------------------------------------------------------------------
-- 5. PERIOD REFRESH / SNAPSHOT ENGINE
-- -----------------------------------------------------------------------------
create or replace function public.refresh_gst_filing_period(p_period_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_period public.gst_filing_periods%rowtype;
  v_box1 numeric(14,2) := 0;
  v_box2 numeric(14,2) := 0;
  v_box3 numeric(14,2) := 0;
  v_box4 numeric(14,2) := 0;
  v_box5 numeric(14,2) := 0;
  v_box6 numeric(14,2) := 0;
  v_box7 numeric(14,2) := 0;
  v_box8 numeric(14,2) := 0;
begin
  if auth.uid() is null or not public.is_app_administrator() then
    raise exception 'Administrator access is required.';
  end if;

  select * into v_period
  from public.gst_filing_periods
  where id = p_period_id
  for update;

  if not found then
    raise exception 'GST filing period was not found.';
  end if;
  if v_period.status = 'filed' then
    raise exception 'Reopen the filed period before refreshing it.';
  end if;

  delete from public.gst_period_entries where period_id = p_period_id;

  insert into public.gst_period_entries(
    period_id, company_id, source_type, source_id, source_no, source_date,
    counterparty, direction, treatment, taxable_amount, gst_amount,
    recoverable_gst_amount, box_no, description, details
  )
  select v_period.id, invoice.company_id, 'customer_invoice', invoice.id,
         invoice.invoice_no, invoice.invoice_date, invoice.customer_name,
         'output', invoice.gst_treatment,
         round(greatest(coalesce(invoice.subtotal, 0) + coalesce(invoice.service_charge_amount, 0), 0), 2),
         round(greatest(coalesce(invoice.gst_amount, 0), 0), 2),
         0,
         case invoice.gst_treatment
           when 'standard_rated' then 1
           when 'zero_rated' then 2
           when 'exempt' then 3
           else null
         end,
         'Customer invoice',
         jsonb_build_object('status', invoice.status, 'gst_rate', invoice.gst_rate, 'review_status', invoice.gst_review_status)
  from public.customer_invoices invoice
  where invoice.company_id = v_period.company_id
    and invoice.invoice_date between v_period.period_from and v_period.period_to
    and invoice.status not in ('draft','cancelled')
    and coalesce(invoice.gst_reportable, true) = true
    and coalesce(invoice.gst_review_status, 'pending') <> 'excluded';

  insert into public.gst_period_entries(
    period_id, company_id, source_type, source_id, source_no, source_date,
    counterparty, direction, treatment, taxable_amount, gst_amount,
    recoverable_gst_amount, box_no, description, details
  )
  select v_period.id, bill.company_id, 'supplier_bill', bill.id,
         bill.bill_no, bill.bill_date, bill.supplier_name,
         'input', bill.gst_treatment,
         round(greatest(coalesce(bill.subtotal, 0), 0), 2),
         round(greatest(coalesce(bill.gst_amount, 0), 0), 2),
         round(greatest(coalesce(bill.recoverable_gst_amount, 0), 0), 2),
         case when bill.gst_treatment in ('standard_rated','blocked_input') then 5 else null end,
         'Supplier bill',
         jsonb_build_object('status', bill.status, 'recoverable_percentage', bill.input_tax_recoverable_percentage, 'review_status', bill.gst_review_status)
  from public.supplier_bills bill
  where bill.company_id = v_period.company_id
    and bill.bill_date between v_period.period_from and v_period.period_to
    and bill.status not in ('draft','cancelled')
    and coalesce(bill.gst_reportable, true) = true
    and coalesce(bill.gst_review_status, 'pending') <> 'excluded';

  insert into public.gst_period_entries(
    period_id, company_id, source_type, source_id, source_no, source_date,
    counterparty, direction, treatment, taxable_amount, gst_amount,
    recoverable_gst_amount, box_no, description, details
  )
  select v_period.id, adjustment.company_id, 'adjustment', adjustment.id,
         adjustment.adjustment_no, adjustment.adjustment_date, null,
         case when adjustment.adjustment_type = 'input_tax' then 'input' else 'output' end,
         adjustment.treatment,
         round(coalesce(adjustment.taxable_amount, 0), 2),
         round(coalesce(adjustment.gst_amount, 0), 2),
         case when adjustment.adjustment_type = 'input_tax' then round(coalesce(adjustment.gst_amount, 0), 2) else 0 end,
         case
           when adjustment.adjustment_type = 'input_tax' then 5
           when adjustment.treatment = 'standard_rated' then 1
           when adjustment.treatment = 'zero_rated' then 2
           when adjustment.treatment = 'exempt' then 3
           else null
         end,
         adjustment.reason,
         jsonb_build_object('reference', adjustment.reference, 'notes', adjustment.notes)
  from public.gst_adjustments adjustment
  where adjustment.company_id = v_period.company_id
    and adjustment.adjustment_date between v_period.period_from and v_period.period_to
    and adjustment.status = 'posted';

  select
    coalesce(sum(case when direction = 'output' and treatment = 'standard_rated' then taxable_amount else 0 end), 0),
    coalesce(sum(case when direction = 'output' and treatment = 'zero_rated' then taxable_amount else 0 end), 0),
    coalesce(sum(case when direction = 'output' and treatment = 'exempt' then taxable_amount else 0 end), 0),
    coalesce(sum(case when direction = 'input' and treatment in ('standard_rated','blocked_input') then taxable_amount else 0 end), 0),
    coalesce(sum(case when direction = 'output' then gst_amount else 0 end), 0),
    coalesce(sum(case when direction = 'input' then recoverable_gst_amount else 0 end), 0)
  into v_box1, v_box2, v_box3, v_box5, v_box6, v_box7
  from public.gst_period_entries
  where period_id = p_period_id;

  v_box4 := round(v_box1 + v_box2 + v_box3, 2);
  v_box8 := round(v_box6 - v_box7, 2);

  update public.gst_filing_periods
  set box1_standard_rated_supplies = round(v_box1, 2),
      box2_zero_rated_supplies = round(v_box2, 2),
      box3_exempt_supplies = round(v_box3, 2),
      box4_total_supplies = round(v_box4, 2),
      box5_taxable_purchases = round(v_box5, 2),
      box6_output_tax = round(v_box6, 2),
      box7_input_tax = round(v_box7, 2),
      box8_net_gst = round(v_box8, 2),
      source_snapshot_at = now(),
      updated_at = now()
  where id = p_period_id;

  return jsonb_build_object(
    'period_id', p_period_id,
    'box1', round(v_box1, 2), 'box2', round(v_box2, 2),
    'box3', round(v_box3, 2), 'box4', round(v_box4, 2),
    'box5', round(v_box5, 2), 'box6', round(v_box6, 2),
    'box7', round(v_box7, 2), 'box8', round(v_box8, 2)
  );
end;
$$;

-- -----------------------------------------------------------------------------
-- 6. SECURITY
-- -----------------------------------------------------------------------------
alter table public.gst_tax_codes enable row level security;
alter table public.gst_adjustments enable row level security;
alter table public.gst_filing_periods enable row level security;
alter table public.gst_period_entries enable row level security;

grant select, insert, update, delete on public.gst_tax_codes to authenticated;
grant select, insert, update, delete on public.gst_adjustments to authenticated;
grant select, insert, update, delete on public.gst_filing_periods to authenticated;
grant select, insert, update, delete on public.gst_period_entries to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.refresh_gst_filing_period(bigint) to authenticated;

drop policy if exists gst_tax_codes_admin_all on public.gst_tax_codes;
create policy gst_tax_codes_admin_all on public.gst_tax_codes
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists gst_adjustments_admin_all on public.gst_adjustments;
create policy gst_adjustments_admin_all on public.gst_adjustments
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists gst_filing_periods_admin_all on public.gst_filing_periods;
create policy gst_filing_periods_admin_all on public.gst_filing_periods
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

drop policy if exists gst_period_entries_admin_all on public.gst_period_entries;
create policy gst_period_entries_admin_all on public.gst_period_entries
for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator());

notify pgrst, 'reload schema';
commit;
