-- A3 MANAGEMENT FINANCE - UPGRADE 8
-- BALANCE SHEET REPORTING
-- Run after 016_profit_and_loss_reporting.sql.
-- Safe to rerun. Existing operational and finance records are preserved.

begin;

-- -----------------------------------------------------------------------------
-- 1. BALANCE SHEET CHART OF ACCOUNTS
-- -----------------------------------------------------------------------------
create table if not exists public.bs_accounts (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  account_code text not null,
  account_name text not null,
  account_group text not null default 'current_asset',
  normal_side text not null default 'debit',
  is_contra boolean not null default false,
  is_system boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 100,
  description text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (account_group in ('current_asset','non_current_asset','current_liability','non_current_liability','equity')),
  check (normal_side in ('debit','credit'))
);

alter table public.bs_accounts
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists account_code text,
  add column if not exists account_name text,
  add column if not exists account_group text default 'current_asset',
  add column if not exists normal_side text default 'debit',
  add column if not exists is_contra boolean default false,
  add column if not exists is_system boolean default false,
  add column if not exists is_active boolean default true,
  add column if not exists sort_order integer default 100,
  add column if not exists description text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.bs_accounts
set account_code = upper(coalesce(nullif(btrim(account_code), ''), 'BS-' || id::text)),
    account_name = coalesce(nullif(btrim(account_name), ''), 'Balance Sheet Account ' || id::text),
    account_group = case
      when lower(coalesce(account_group, '')) in ('current_asset','non_current_asset','current_liability','non_current_liability','equity')
        then lower(account_group)
      else 'current_asset'
    end,
    normal_side = case when lower(coalesce(normal_side, 'debit')) = 'credit' then 'credit' else 'debit' end,
    is_contra = coalesce(is_contra, false),
    is_system = coalesce(is_system, false),
    is_active = coalesce(is_active, true),
    sort_order = coalesce(sort_order, 100),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

update public.bs_accounts duplicate
set account_code = duplicate.account_code || '-DUP-' || duplicate.id::text
where exists (
  select 1 from public.bs_accounts original
  where original.company_id = duplicate.company_id
    and upper(original.account_code) = upper(duplicate.account_code)
    and original.id < duplicate.id
);

create unique index if not exists bs_accounts_company_code_uidx
  on public.bs_accounts(company_id, account_code);
create index if not exists bs_accounts_company_group_idx
  on public.bs_accounts(company_id, account_group, sort_order, account_code);

create or replace function public.prepare_bs_account()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.account_code := upper(coalesce(nullif(btrim(new.account_code), ''), 'BS'));
  new.account_name := coalesce(nullif(btrim(new.account_name), ''), 'Balance Sheet Account');
  new.account_group := lower(coalesce(nullif(btrim(new.account_group), ''), 'current_asset'));
  if new.account_group not in ('current_asset','non_current_asset','current_liability','non_current_liability','equity') then
    raise exception 'Invalid Balance Sheet account group.';
  end if;
  new.is_contra := coalesce(new.is_contra, false);
  new.normal_side := case
    when new.account_group in ('current_liability','non_current_liability','equity')
      then case when new.is_contra then 'debit' else 'credit' end
    else case when new.is_contra then 'credit' else 'debit' end
  end;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists bs_accounts_prepare on public.bs_accounts;
create trigger bs_accounts_prepare
before insert or update on public.bs_accounts
for each row execute function public.prepare_bs_account();

-- -----------------------------------------------------------------------------
-- 2. MANUAL BALANCE SHEET ENTRIES
-- Used for capital, loans, fixed assets, depreciation, accruals and opening items.
-- -----------------------------------------------------------------------------
create table if not exists public.bs_manual_entries (
  id bigint generated by default as identity primary key,
  entry_no text,
  company_id bigint not null references public.companies(id) on delete cascade,
  account_id bigint not null references public.bs_accounts(id) on delete restrict,
  entry_date date not null default current_date,
  description text not null,
  reference text,
  entry_side text not null default 'debit',
  amount numeric(16,2) not null,
  status text not null default 'posted',
  notes text,
  void_reason text,
  voided_by uuid references public.profiles(id) on delete set null,
  voided_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (entry_side in ('debit','credit')),
  check (amount > 0),
  check (status in ('posted','void'))
);

alter table public.bs_manual_entries
  add column if not exists entry_no text,
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists account_id bigint references public.bs_accounts(id) on delete restrict,
  add column if not exists entry_date date default current_date,
  add column if not exists description text,
  add column if not exists reference text,
  add column if not exists entry_side text default 'debit',
  add column if not exists amount numeric(16,2) default 0,
  add column if not exists status text default 'posted',
  add column if not exists notes text,
  add column if not exists void_reason text,
  add column if not exists voided_by uuid references public.profiles(id) on delete set null,
  add column if not exists voided_at timestamptz,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.bs_manual_entries
set entry_no = coalesce(nullif(btrim(entry_no), ''), 'BSE-' || lpad(id::text, 6, '0')),
    entry_date = coalesce(entry_date, current_date),
    description = coalesce(nullif(btrim(description), ''), 'Balance Sheet entry'),
    entry_side = case when lower(coalesce(entry_side, 'debit')) = 'credit' then 'credit' else 'debit' end,
    amount = greatest(abs(coalesce(amount, 0)), 0.01),
    status = case when lower(coalesce(status, 'posted')) = 'void' then 'void' else 'posted' end,
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

update public.bs_manual_entries duplicate
set entry_no = duplicate.entry_no || '-DUP-' || duplicate.id::text
where exists (
  select 1 from public.bs_manual_entries original
  where original.company_id = duplicate.company_id
    and lower(original.entry_no) = lower(duplicate.entry_no)
    and original.id < duplicate.id
);

create unique index if not exists bs_manual_entries_company_no_uidx
  on public.bs_manual_entries(company_id, entry_no);
create index if not exists bs_manual_entries_company_date_idx
  on public.bs_manual_entries(company_id, status, entry_date desc, id desc);

create or replace function public.prepare_bs_manual_entry()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  account_company_id bigint;
begin
  new.entry_date := coalesce(new.entry_date, current_date);
  new.description := coalesce(nullif(btrim(new.description), ''), 'Balance Sheet entry');
  new.entry_side := case when lower(coalesce(new.entry_side, 'debit')) = 'credit' then 'credit' else 'debit' end;
  new.amount := abs(coalesce(new.amount, 0));
  if new.amount <= 0 then raise exception 'Balance Sheet entry amount must be greater than zero.'; end if;
  select company_id into account_company_id from public.bs_accounts where id = new.account_id;
  if account_company_id is null or account_company_id <> new.company_id then
    raise exception 'The Balance Sheet account must belong to the same company.';
  end if;
  if new.entry_no is null or btrim(new.entry_no) = '' then
    new.entry_no := 'BSE-' || to_char(new.entry_date, 'YYYYMMDD') || '-' || lpad(new.id::text, 5, '0');
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists bs_manual_entries_prepare on public.bs_manual_entries;
create trigger bs_manual_entries_prepare
before insert or update on public.bs_manual_entries
for each row execute function public.prepare_bs_manual_entry();

create or replace function public.void_bs_manual_entry(p_entry_id bigint, p_reason text)
returns public.bs_manual_entries
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.bs_manual_entries;
begin
  if not public.is_app_administrator() then raise exception 'Administrator access is required.'; end if;
  if nullif(btrim(p_reason), '') is null then raise exception 'A void reason is required.'; end if;
  update public.bs_manual_entries
  set status = 'void', void_reason = btrim(p_reason), voided_by = auth.uid(), voided_at = now(),
      updated_by = auth.uid(), updated_at = now()
  where id = p_entry_id and status = 'posted'
  returning * into result;
  if result.id is null then raise exception 'Posted Balance Sheet entry was not found.'; end if;
  return result;
end;
$$;

-- -----------------------------------------------------------------------------
-- 3. REPORT SNAPSHOTS
-- -----------------------------------------------------------------------------
create table if not exists public.bs_report_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_no text,
  company_id bigint not null references public.companies(id) on delete cascade,
  as_of_date date not null,
  status text not null default 'draft',
  total_assets numeric(16,2) not null default 0,
  total_liabilities numeric(16,2) not null default 0,
  total_equity numeric(16,2) not null default 0,
  variance numeric(16,2) not null default 0,
  report_data jsonb not null default '{}'::jsonb,
  notes text,
  finalised_by uuid references public.profiles(id) on delete set null,
  finalised_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (status in ('draft','final')),
  unique(company_id, as_of_date)
);

alter table public.bs_report_snapshots
  add column if not exists snapshot_no text,
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists as_of_date date,
  add column if not exists status text default 'draft',
  add column if not exists total_assets numeric(16,2) default 0,
  add column if not exists total_liabilities numeric(16,2) default 0,
  add column if not exists total_equity numeric(16,2) default 0,
  add column if not exists variance numeric(16,2) default 0,
  add column if not exists report_data jsonb default '{}'::jsonb,
  add column if not exists notes text,
  add column if not exists finalised_by uuid references public.profiles(id) on delete set null,
  add column if not exists finalised_at timestamptz,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create unique index if not exists bs_report_snapshots_company_date_uidx
  on public.bs_report_snapshots(company_id, as_of_date);
create index if not exists bs_report_snapshots_company_idx
  on public.bs_report_snapshots(company_id, as_of_date desc, id desc);

create or replace function public.prepare_bs_snapshot()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.snapshot_no is null or btrim(new.snapshot_no) = '' then
    new.snapshot_no := 'BS-' || to_char(new.as_of_date, 'YYYYMMDD') || '-' || lpad(new.id::text, 4, '0');
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists bs_report_snapshots_prepare on public.bs_report_snapshots;
create trigger bs_report_snapshots_prepare
before insert or update on public.bs_report_snapshots
for each row execute function public.prepare_bs_snapshot();

-- -----------------------------------------------------------------------------
-- 4. DEFAULT ACCOUNTS
-- -----------------------------------------------------------------------------
create or replace function public.seed_bs_defaults(p_company_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.bs_accounts(company_id, account_code, account_name, account_group, normal_side, is_contra, is_system, sort_order, description)
  values
    (p_company_id, '1000', 'Cash and Bank', 'current_asset', 'debit', false, true, 100, 'Bank and cash-book balances.'),
    (p_company_id, '1100', 'Accounts Receivable', 'current_asset', 'debit', false, true, 110, 'Outstanding customer invoices.'),
    (p_company_id, '1200', 'Supplier Advances and Credits', 'current_asset', 'debit', false, true, 120, 'Unallocated supplier payments and credits.'),
    (p_company_id, '1300', 'GST Receivable', 'current_asset', 'debit', false, true, 130, 'Net recoverable GST.'),
    (p_company_id, '1500', 'Property, Plant and Equipment', 'non_current_asset', 'debit', false, true, 200, 'Vehicles, equipment and fixed assets.'),
    (p_company_id, '1590', 'Accumulated Depreciation', 'non_current_asset', 'credit', true, true, 210, 'Contra asset for accumulated depreciation.'),
    (p_company_id, '1900', 'Other Assets', 'non_current_asset', 'debit', false, true, 290, 'Other non-current assets.'),
    (p_company_id, '2000', 'Accounts Payable', 'current_liability', 'credit', false, true, 300, 'Outstanding supplier bills.'),
    (p_company_id, '2100', 'Customer Deposits and Credits', 'current_liability', 'credit', false, true, 310, 'Unallocated customer payments.'),
    (p_company_id, '2200', 'GST Payable', 'current_liability', 'credit', false, true, 320, 'Net GST payable.'),
    (p_company_id, '2300', 'Accrued Expenses', 'current_liability', 'credit', false, true, 330, 'Accrued operating expenses.'),
    (p_company_id, '2400', 'Driver Payouts Payable', 'current_liability', 'credit', false, true, 340, 'Approved driver payouts not yet settled.'),
    (p_company_id, '2500', 'Loans and Borrowings', 'non_current_liability', 'credit', false, true, 400, 'Long-term loans and borrowings.'),
    (p_company_id, '3000', 'Capital', 'equity', 'credit', false, true, 500, 'Shareholder or owner capital.'),
    (p_company_id, '3100', 'Drawings and Dividends', 'equity', 'debit', true, true, 510, 'Contra equity for drawings and dividends.'),
    (p_company_id, '3200', 'Retained Earnings', 'equity', 'credit', false, true, 520, 'Cumulative profit or loss.'),
    (p_company_id, '3900', 'Other Equity', 'equity', 'credit', false, true, 590, 'Other reserves and equity balances.')
  on conflict (company_id, account_code) do update
    set account_name = excluded.account_name,
        account_group = excluded.account_group,
        normal_side = excluded.normal_side,
        is_contra = excluded.is_contra,
        is_system = true,
        sort_order = excluded.sort_order,
        description = excluded.description,
        updated_at = now();
end;
$$;

do $$ declare company_record record; begin
  for company_record in select id from public.companies loop
    perform public.seed_bs_defaults(company_record.id);
  end loop;
end $$;

create or replace function public.seed_bs_defaults_for_new_company()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.seed_bs_defaults(new.id);
  return new;
end;
$$;

drop trigger if exists companies_seed_bs_defaults on public.companies;
create trigger companies_seed_bs_defaults
after insert on public.companies
for each row execute function public.seed_bs_defaults_for_new_company();

-- -----------------------------------------------------------------------------
-- 5. SECURITY
-- -----------------------------------------------------------------------------
alter table public.bs_accounts enable row level security;
alter table public.bs_manual_entries enable row level security;
alter table public.bs_report_snapshots enable row level security;

grant select, insert, update, delete on public.bs_accounts to authenticated;
grant select, insert, update, delete on public.bs_manual_entries to authenticated;
grant select, insert, update, delete on public.bs_report_snapshots to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.seed_bs_defaults(bigint) to authenticated;
grant execute on function public.void_bs_manual_entry(bigint,text) to authenticated;

do $$
declare table_name text;
begin
  for table_name in select unnest(array['bs_accounts','bs_manual_entries','bs_report_snapshots']) loop
    execute format('drop policy if exists %I on public.%I', table_name || '_administrator_all', table_name);
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator())',
      table_name || '_administrator_all', table_name
    );
  end loop;
end $$;

commit;

notify pgrst, 'reload schema';
