-- A3 MANAGEMENT FINANCE - UPGRADE 9
-- CASH FLOW STATEMENT
-- Run after 017_balance_sheet_reporting.sql.
-- Safe to rerun. Existing bank and cash-book records are preserved.

begin;

-- -----------------------------------------------------------------------------
-- 1. EXPLICIT CASH-FLOW CLASSIFICATION ON CASH-BOOK ENTRIES
-- -----------------------------------------------------------------------------
alter table public.bank_cashbook_entries
  add column if not exists cash_flow_activity text,
  add column if not exists cash_flow_line text;

-- Remove only older checks on these two columns before installing current rules.
do $$
declare constraint_record record;
begin
  for constraint_record in
    select conname
    from pg_constraint
    where conrelid = 'public.bank_cashbook_entries'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%cash_flow_activity%'
  loop
    execute format('alter table public.bank_cashbook_entries drop constraint %I', constraint_record.conname);
  end loop;
end $$;

update public.bank_cashbook_entries
set cash_flow_activity = case
      when lower(coalesce(cash_flow_activity, '')) in ('operating','investing','financing','excluded')
        then lower(cash_flow_activity)
      else null
    end,
    cash_flow_line = nullif(btrim(cash_flow_line), '');

alter table public.bank_cashbook_entries
  add constraint bank_cashbook_entries_cash_flow_activity_check
  check (cash_flow_activity is null or cash_flow_activity in ('operating','investing','financing','excluded'));

create index if not exists bank_cashbook_entries_cash_flow_idx
  on public.bank_cashbook_entries(company_id, cash_flow_activity, entry_date, status);

-- -----------------------------------------------------------------------------
-- 2. DEFAULT CLASSIFICATION MAPPINGS
-- -----------------------------------------------------------------------------
create table if not exists public.cash_flow_mappings (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  source_type text not null default '*',
  entry_type text not null default '*',
  activity text not null default 'operating',
  line_name text not null,
  priority integer not null default 100,
  is_active boolean not null default true,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (activity in ('operating','investing','financing','excluded'))
);

alter table public.cash_flow_mappings
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists source_type text default '*',
  add column if not exists entry_type text default '*',
  add column if not exists activity text default 'operating',
  add column if not exists line_name text,
  add column if not exists priority integer default 100,
  add column if not exists is_active boolean default true,
  add column if not exists notes text,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists updated_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.cash_flow_mappings
set source_type = lower(coalesce(nullif(btrim(source_type), ''), '*')),
    entry_type = lower(coalesce(nullif(btrim(entry_type), ''), '*')),
    activity = case
      when lower(coalesce(activity, 'operating')) in ('operating','investing','financing','excluded')
        then lower(activity)
      else 'operating'
    end,
    line_name = coalesce(nullif(btrim(line_name), ''), 'Other cash movement'),
    priority = coalesce(priority, 100),
    is_active = coalesce(is_active, true),
    created_at = coalesce(created_at, now()),
    updated_at = coalesce(updated_at, now());

update public.cash_flow_mappings duplicate
set source_type = duplicate.source_type || '-duplicate-' || duplicate.id::text
where exists (
  select 1 from public.cash_flow_mappings original
  where original.company_id = duplicate.company_id
    and original.source_type = duplicate.source_type
    and original.entry_type = duplicate.entry_type
    and original.id < duplicate.id
);

create unique index if not exists cash_flow_mappings_company_source_uidx
  on public.cash_flow_mappings(company_id, source_type, entry_type);
create index if not exists cash_flow_mappings_company_priority_idx
  on public.cash_flow_mappings(company_id, is_active, priority, id);

create or replace function public.prepare_cash_flow_mapping()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.source_type := lower(coalesce(nullif(btrim(new.source_type), ''), '*'));
  new.entry_type := lower(coalesce(nullif(btrim(new.entry_type), ''), '*'));
  new.activity := lower(coalesce(nullif(btrim(new.activity), ''), 'operating'));
  if new.activity not in ('operating','investing','financing','excluded') then
    raise exception 'Invalid cash-flow activity.';
  end if;
  new.line_name := coalesce(nullif(btrim(new.line_name), ''), 'Other cash movement');
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists cash_flow_mappings_prepare on public.cash_flow_mappings;
create trigger cash_flow_mappings_prepare
before insert or update on public.cash_flow_mappings
for each row execute function public.prepare_cash_flow_mapping();

-- -----------------------------------------------------------------------------
-- 3. REPORT SNAPSHOTS
-- -----------------------------------------------------------------------------
create table if not exists public.cash_flow_report_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_no text,
  company_id bigint not null references public.companies(id) on delete cascade,
  period_from date not null,
  period_to date not null,
  status text not null default 'draft',
  operating_cash numeric(16,2) not null default 0,
  investing_cash numeric(16,2) not null default 0,
  financing_cash numeric(16,2) not null default 0,
  net_cash_change numeric(16,2) not null default 0,
  opening_cash numeric(16,2) not null default 0,
  closing_cash numeric(16,2) not null default 0,
  reconciliation_difference numeric(16,2) not null default 0,
  report_data jsonb not null default '{}'::jsonb,
  notes text,
  finalised_by uuid references public.profiles(id) on delete set null,
  finalised_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (period_to >= period_from),
  check (status in ('draft','final')),
  unique(company_id, period_from, period_to)
);

alter table public.cash_flow_report_snapshots
  add column if not exists snapshot_no text,
  add column if not exists company_id bigint references public.companies(id) on delete cascade,
  add column if not exists period_from date,
  add column if not exists period_to date,
  add column if not exists status text default 'draft',
  add column if not exists operating_cash numeric(16,2) default 0,
  add column if not exists investing_cash numeric(16,2) default 0,
  add column if not exists financing_cash numeric(16,2) default 0,
  add column if not exists net_cash_change numeric(16,2) default 0,
  add column if not exists opening_cash numeric(16,2) default 0,
  add column if not exists closing_cash numeric(16,2) default 0,
  add column if not exists reconciliation_difference numeric(16,2) default 0,
  add column if not exists report_data jsonb default '{}'::jsonb,
  add column if not exists notes text,
  add column if not exists finalised_by uuid references public.profiles(id) on delete set null,
  add column if not exists finalised_at timestamptz,
  add column if not exists created_by uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create unique index if not exists cash_flow_snapshots_company_period_uidx
  on public.cash_flow_report_snapshots(company_id, period_from, period_to);
create index if not exists cash_flow_snapshots_company_idx
  on public.cash_flow_report_snapshots(company_id, period_to desc, id desc);

create or replace function public.prepare_cash_flow_snapshot()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.snapshot_no is null or btrim(new.snapshot_no) = '' then
    new.snapshot_no := 'CF-' || to_char(new.period_from, 'YYYYMMDD') || '-' || to_char(new.period_to, 'YYYYMMDD');
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists cash_flow_snapshots_prepare on public.cash_flow_report_snapshots;
create trigger cash_flow_snapshots_prepare
before insert or update on public.cash_flow_report_snapshots
for each row execute function public.prepare_cash_flow_snapshot();

-- -----------------------------------------------------------------------------
-- 4. DEFAULT MAPPINGS
-- -----------------------------------------------------------------------------
create or replace function public.seed_cash_flow_defaults(p_company_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.cash_flow_mappings(company_id, source_type, entry_type, activity, line_name, priority, notes)
  values
    (p_company_id, 'customer_payment', 'receipt', 'operating', 'Receipts from customers', 10, 'Posted customer receipts.'),
    (p_company_id, 'supplier_payment', 'payment', 'operating', 'Payments to suppliers', 20, 'Posted supplier payments.'),
    (p_company_id, 'driver_payout', 'payment', 'operating', 'Payments to drivers', 30, 'Driver payout settlement.'),
    (p_company_id, '*', 'bank_fee', 'operating', 'Bank and payment charges', 40, 'Bank charges and processing fees.'),
    (p_company_id, '*', 'interest', 'operating', 'Interest received or paid', 50, 'Interest cash movement.'),
    (p_company_id, '*', 'transfer', 'excluded', 'Transfers between own accounts', 60, 'Excluded from the cash-flow statement to avoid double counting.'),
    (p_company_id, '*', 'receipt', 'operating', 'Other operating receipts', 70, 'Other cash receipts.'),
    (p_company_id, '*', 'payment', 'operating', 'Other operating payments', 80, 'Other cash payments.'),
    (p_company_id, '*', 'adjustment', 'operating', 'Other operating cash movements', 90, 'Manual cash-book adjustment.')
  on conflict (company_id, source_type, entry_type) do update
    set activity = excluded.activity,
        line_name = excluded.line_name,
        priority = excluded.priority,
        notes = excluded.notes,
        updated_at = now();
end;
$$;

do $$ declare company_record record; begin
  for company_record in select id from public.companies loop
    perform public.seed_cash_flow_defaults(company_record.id);
  end loop;
end $$;

create or replace function public.seed_cash_flow_defaults_for_new_company()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.seed_cash_flow_defaults(new.id);
  return new;
end;
$$;

drop trigger if exists companies_seed_cash_flow_defaults on public.companies;
create trigger companies_seed_cash_flow_defaults
after insert on public.companies
for each row execute function public.seed_cash_flow_defaults_for_new_company();

-- -----------------------------------------------------------------------------
-- 5. SECURITY
-- -----------------------------------------------------------------------------
alter table public.cash_flow_mappings enable row level security;
alter table public.cash_flow_report_snapshots enable row level security;

grant select, insert, update, delete on public.cash_flow_mappings to authenticated;
grant select, insert, update, delete on public.cash_flow_report_snapshots to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.seed_cash_flow_defaults(bigint) to authenticated;

do $$
declare table_name text;
begin
  for table_name in select unnest(array['cash_flow_mappings','cash_flow_report_snapshots']) loop
    execute format('drop policy if exists %I on public.%I', table_name || '_administrator_all', table_name);
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_app_administrator()) with check (public.is_app_administrator())',
      table_name || '_administrator_all', table_name
    );
  end loop;
end $$;

commit;

notify pgrst, 'reload schema';
