-- A3 FINANCE 1.2 — AEJKY PUBLIC LIMOUSINE WEBSITE
-- Run once after migration 021.
-- Adds secure public quotation lead storage. Public website requests are inserted
-- only through the server-side API using the Supabase service role.

begin;

create table if not exists public.limousine_quote_requests (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete restrict,
  public_reference text,
  customer_name text not null,
  phone text not null,
  email text,
  preferred_contact text not null default 'whatsapp'
    check (preferred_contact in ('whatsapp','telegram','wechat','phone')),
  service_type text not null
    check (service_type in ('airport_transfer','point_to_point','hourly_disposal','charter','sg_jb','jb_sg')),
  trip_date date not null,
  pickup_time time,
  pickup_location text not null,
  dropoff_location text not null,
  return_trip boolean not null default false,
  passengers integer not null default 1 check (passengers between 1 and 100),
  luggage integer not null default 0 check (luggage between 0 and 100),
  vehicle_type_id bigint references public.limousine_vehicle_types(id) on delete set null,
  rate_card_id bigint references public.limousine_rate_cards(id) on delete set null,
  estimated_amount numeric(14,2) check (estimated_amount is null or estimated_amount >= 0),
  currency text not null default 'SGD' check (currency ~ '^[A-Z]{3}$'),
  special_requests text,
  consent_accepted boolean not null default false,
  consented_at timestamptz,
  source text not null default 'public_website',
  status text not null default 'new'
    check (status in ('new','contacted','quoted','accepted','declined','cancelled')),
  internal_notes text,
  assigned_to uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.limousine_quote_requests
  add column if not exists public_reference text,
  add column if not exists preferred_contact text not null default 'whatsapp',
  add column if not exists return_trip boolean not null default false,
  add column if not exists vehicle_type_id bigint references public.limousine_vehicle_types(id) on delete set null,
  add column if not exists rate_card_id bigint references public.limousine_rate_cards(id) on delete set null,
  add column if not exists estimated_amount numeric(14,2),
  add column if not exists currency text not null default 'SGD',
  add column if not exists consent_accepted boolean not null default false,
  add column if not exists consented_at timestamptz,
  add column if not exists source text not null default 'public_website',
  add column if not exists status text not null default 'new',
  add column if not exists internal_notes text,
  add column if not exists assigned_to uuid references public.profiles(id) on delete set null,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create or replace function public.assign_limousine_quote_reference()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.public_reference is null or btrim(new.public_reference) = '' then
    new.public_reference :=
      'AEJ-' || to_char(coalesce(new.created_at, now()), 'YYYYMMDD') || '-' || lpad(new.id::text, 5, '0');
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists limousine_quote_requests_assign_reference on public.limousine_quote_requests;
create trigger limousine_quote_requests_assign_reference
before insert or update on public.limousine_quote_requests
for each row execute function public.assign_limousine_quote_reference();

create unique index if not exists limousine_quote_requests_reference_uidx
  on public.limousine_quote_requests(lower(public_reference))
  where public_reference is not null;
create index if not exists limousine_quote_requests_company_created_idx
  on public.limousine_quote_requests(company_id, created_at desc);
create index if not exists limousine_quote_requests_company_status_idx
  on public.limousine_quote_requests(company_id, status, trip_date);

alter table public.limousine_quote_requests enable row level security;

grant select, insert, update, delete on public.limousine_quote_requests to authenticated;
grant usage, select on sequence public.limousine_quote_requests_id_seq to authenticated;

drop policy if exists limousine_quote_requests_admin_all on public.limousine_quote_requests;
create policy limousine_quote_requests_admin_all on public.limousine_quote_requests
for all to authenticated
using (public.is_app_administrator())
with check (public.is_app_administrator());

notify pgrst, 'reload schema';
commit;
