"use client";
import { useMemo, useState } from "react";

type UploadKey="licence"|"pdvl"|"vehicleFront"|"phvDecal"|"vehicleBack"|"vehicleLeft"|"vehicleRight"|"interior"|"insurance"|"roadTax"|"logCard";
const uploads:{key:UploadKey;label:string;required:boolean;example?:string}[]=[
 {key:"licence",label:"Singapore Driving Licence",required:true,example:"/examples/singapore-driving-licence-example.svg"},
 {key:"pdvl",label:"Vocational Licence (PDVL)",required:true},
 {key:"vehicleFront",label:"Vehicle Front",required:true,example:"/examples/vehicle-front-example.svg"},
 {key:"phvDecal",label:"PHV Decal",required:true,example:"/examples/phv-decal-example.svg"},
 {key:"vehicleBack",label:"Vehicle Back",required:false},{key:"vehicleLeft",label:"Vehicle Left",required:false},{key:"vehicleRight",label:"Vehicle Right",required:false},{key:"interior",label:"Interior",required:false},{key:"insurance",label:"Insurance",required:false},{key:"roadTax",label:"Road Tax",required:false},{key:"logCard",label:"Vehicle Log Card",required:false},
];
function readFile(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||""));r.onerror=()=>reject(new Error("Unable to read file"));r.readAsDataURL(file)})}
export default function DriverSignupPage(){
 const [form,setForm]=useState<any>({name:"",mobile:"",email:"",nric:"",dob:"",address:"",carModel:"",vehicleType:"",carPlate:"",phvCompany:"",bankName:"",bankAccount:"",paynow:"",consent:false,documents:{}});
 const [busy,setBusy]=useState(false); const [result,setResult]=useState<any>(null); const [error,setError]=useState("");
 const missing=useMemo(()=>uploads.filter(x=>x.required&&!form.documents[x.key]?.data).map(x=>x.label),[form.documents]);
 async function choose(key:UploadKey,file?:File){if(!file)return;if(file.size>8*1024*1024){setError("Each file must be 8 MB or smaller.");return}const data=await readFile(file);setForm((f:any)=>({...f,documents:{...f.documents,[key]:{name:file.name,type:file.type,data}}}))}
 async function submit(){setError("");if(!form.name.trim()||!form.mobile.trim()||!form.carPlate.trim()){setError("Name, mobile number and vehicle plate are required.");return}if(missing.length){setError(`Please upload: ${missing.join(", ")}.`);return}if(!form.consent){setError("Please accept the declaration before submitting.");return}setBusy(true);try{const r=await fetch("/api/public/driver-applications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const data=await r.json();if(!r.ok||!data.ok)throw new Error(data.message||"Submission failed");setResult(data)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 if(result)return <main className="signup-shell"><section className="signup-card success"><h1>Application submitted</h1><p>Your application reference is <strong>{result.applicationId}</strong>.</p><p>Status: <strong>Pending Review</strong>. After approval, Finance will automatically create your driver account.</p></section></main>;
 return <main className="signup-shell"><section className="signup-hero"><span>A3 GROUP · DRIVER ONBOARDING</span><h1>Driver Sign-Up</h1><p>Complete the form and upload the required documents. Your account will be created automatically after approval.</p></section>
 <section className="signup-card"><h2>1. Personal information</h2><div className="signup-grid">{[["Full name","name"],["Mobile number","mobile"],["Email","email"],["NRIC / FIN","nric"],["Date of birth","dob","date"],["Residential address","address"]].map(([label,key,type])=><label key={key}>{label}<input type={type||"text"} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div></section>
 <section className="signup-card"><h2>2. Vehicle information</h2><div className="signup-grid">{[["Vehicle model","carModel"],["Vehicle type","vehicleType"],["Vehicle plate","carPlate"],["PHV company","phvCompany"]].map(([label,key])=><label key={key}>{label}<input value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value.toUpperCase()})}/></label>)}</div></section>
 <section className="signup-card"><h2>3. Documents</h2><p className="muted">Required documents are marked with *. Optional documents may be added now or later.</p><div className="upload-grid">{uploads.map(u=><article className="upload-box" key={u.key}><div><strong>{u.label}{u.required?" *":" (optional)"}</strong>{u.example&&<img src={u.example} alt={`${u.label} example`}/>}<small>{form.documents[u.key]?.name||"No file selected"}</small></div><label className="upload-button">{form.documents[u.key]?"Replace":"Upload"}<input type="file" accept="image/*,.pdf" onChange={e=>choose(u.key,e.target.files?.[0])}/></label>{form.documents[u.key]&&<button type="button" onClick={()=>setForm((f:any)=>({...f,documents:{...f.documents,[u.key]:undefined}}))}>Remove</button>}</article>)}</div></section>
 <section className="signup-card"><h2>4. Payment information</h2><div className="signup-grid">{[["Bank name","bankName"],["Bank account name / number","bankAccount"],["PayNow number","paynow"]].map(([label,key])=><label key={key}>{label}<input value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><label className="consent"><input type="checkbox" checked={form.consent} onChange={e=>setForm({...form,consent:e.target.checked})}/> I confirm that the information and documents submitted are accurate.</label>{error&&<p className="error-box">{error}</p>}<button className="submit-button" disabled={busy} onClick={submit}>{busy?"Submitting…":"Submit application"}</button></section>
 <style jsx global>{`body{margin:0;background:#f3f5f8;color:#17212b;font-family:Inter,Arial,sans-serif}.signup-shell{max-width:980px;margin:auto;padding:24px 16px 60px}.signup-hero{padding:24px 4px}.signup-hero span{font-size:12px;font-weight:800;letter-spacing:.12em;color:#087f5b}.signup-hero h1{font-size:clamp(32px,7vw,54px);margin:8px 0}.signup-hero p{color:#667085;max-width:680px}.signup-card{background:#fff;border:1px solid #e4e7ec;border-radius:18px;padding:20px;margin:16px 0;box-shadow:0 6px 24px rgba(16,24,40,.05)}.signup-card h2{margin-top:0}.signup-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.signup-grid label{font-weight:700;font-size:14px}.signup-grid input{box-sizing:border-box;width:100%;margin-top:7px;border:1px solid #d0d5dd;border-radius:10px;padding:13px;font-size:16px}.upload-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.upload-box{border:1px solid #dce1e8;border-radius:14px;padding:14px;display:flex;gap:10px;align-items:center;justify-content:space-between}.upload-box div{min-width:0}.upload-box img{display:block;width:130px;max-height:90px;object-fit:contain;margin:10px 0;background:#f8fafc;border-radius:8px}.upload-box small{display:block;color:#667085;overflow:hidden;text-overflow:ellipsis}.upload-button{background:#087f5b;color:#fff;padding:10px 13px;border-radius:10px;font-weight:800;white-space:nowrap}.upload-button input{display:none}.upload-box button{border:0;background:#fff0f0;color:#c92a2a;padding:8px;border-radius:8px}.consent{display:flex;gap:10px;margin:18px 0;align-items:flex-start}.submit-button{width:100%;border:0;border-radius:12px;background:#087f5b;color:white;font-weight:900;font-size:17px;padding:15px}.submit-button:disabled{opacity:.6}.error-box{background:#fff4e6;color:#c92a2a;padding:12px;border-radius:10px}.muted{color:#667085}.success{text-align:center;margin-top:15vh}@media(max-width:680px){.signup-grid,.upload-grid{grid-template-columns:1fr}.signup-card{padding:16px}.upload-box{align-items:flex-start;flex-wrap:wrap}.upload-box div{width:100%}.upload-box img{width:100%;max-height:150px}.submit-button{position:sticky;bottom:12px}}`}</style></main>
}
