"use client";
import { useEffect, useMemo, useState } from "react";

type UploadKey="licence"|"pdvl"|"vehicleFront"|"phvDecal"|"vehicleBack"|"vehicleLeft"|"vehicleRight"|"interior"|"insurance"|"roadTax"|"logCard";
type VehicleModel={id:string;model:string;vehicleType:string;active:boolean};
type DocumentValue={name:string;type:string;data:string};
type FormState={name:string;mobile:string;email:string;address:string;carModel:string;vehicleType:string;carPlate:string;modelNotListed:boolean;manualModel:string;manualVehicleType:string;bankName:string;accountName:string;bankAccount:string;paynow:string;emergencyName:string;emergencyRelationship:string;emergencyMobile:string;consent:boolean;documents:Partial<Record<UploadKey,DocumentValue>>};
const fallbackModels:VehicleModel[]=[
 {id:"VM-018",model:"Toyota Alphard",vehicleType:"7 Seater Premium",active:true},{id:"VM-019",model:"Toyota Vellfire",vehicleType:"7 Seater Premium",active:true},{id:"VM-017",model:"Hyundai Staria",vehicleType:"7 Seater",active:true},{id:"VM-020",model:"Mercedes-Benz V-Class",vehicleType:"7 Seater Premium",active:true},{id:"VM-011",model:"Toyota Noah",vehicleType:"7 Seater",active:true},{id:"VM-012",model:"Toyota Voxy",vehicleType:"7 Seater",active:true},{id:"VM-013",model:"Toyota Sienta",vehicleType:"7 Seater",active:true},{id:"VM-015",model:"Honda Freed",vehicleType:"7 Seater",active:true},{id:"VM-007",model:"Mercedes-Benz E-Class",vehicleType:"5 Seater Premium",active:true},{id:"VM-001",model:"Toyota Camry",vehicleType:"5 Seater",active:true}
];
const uploads:{key:UploadKey;label:string;required:boolean;example?:string}[]=[
 {key:"licence",label:"Singapore Driving Licence",required:true,example:"/examples/singapore-driving-licence-example.svg"},{key:"pdvl",label:"Vocational Licence (PDVL)",required:true},{key:"vehicleFront",label:"Vehicle Front",required:true,example:"/examples/vehicle-front-example.svg"},{key:"phvDecal",label:"PHV Decal",required:true,example:"/examples/phv-decal-example.svg"},{key:"vehicleBack",label:"Vehicle Back",required:false},{key:"vehicleLeft",label:"Vehicle Left",required:false},{key:"vehicleRight",label:"Vehicle Right",required:false},{key:"interior",label:"Interior",required:false},{key:"insurance",label:"Insurance",required:false},{key:"roadTax",label:"Road Tax",required:false},{key:"logCard",label:"Vehicle Log Card",required:false}
];
const initialForm:FormState={name:"",mobile:"",email:"",address:"",carModel:"",vehicleType:"",carPlate:"",modelNotListed:false,manualModel:"",manualVehicleType:"",bankName:"",accountName:"",bankAccount:"",paynow:"",emergencyName:"",emergencyRelationship:"",emergencyMobile:"",consent:false,documents:{}};
function readFile(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||""));reader.onerror=()=>reject(new Error("Unable to read file"));reader.readAsDataURL(file)})}
export default function DriverSignupPage(){
 const [form,setForm]=useState<FormState>(initialForm);const [models,setModels]=useState<VehicleModel[]>(fallbackModels);const [query,setQuery]=useState("");const [openResults,setOpenResults]=useState(false);const [busy,setBusy]=useState(false);const [result,setResult]=useState<{applicationId:string}|null>(null);const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/public/driver-applications").then(response=>response.ok?response.json():Promise.reject()).then(data=>{if(Array.isArray(data.models)&&data.models.length)setModels(data.models.filter((item:VehicleModel)=>item.active!==false))}).catch(()=>{})},[]);
 const matches=useMemo(()=>{const term=query.trim().toLowerCase();if(!term)return models.slice(0,8);return models.filter(item=>`${item.model} ${item.vehicleType}`.toLowerCase().includes(term)).slice(0,10)},[models,query]);
 const missing=useMemo(()=>uploads.filter(item=>item.required&&!form.documents[item.key]?.data).map(item=>item.label),[form.documents]);
 function chooseModel(model:VehicleModel){setForm(current=>({...current,carModel:model.model,vehicleType:model.vehicleType,modelNotListed:false,manualModel:"",manualVehicleType:""}));setQuery(model.model);setOpenResults(false)}
 async function choose(key:UploadKey,file?:File){if(!file)return;if(file.size>8*1024*1024){setError("Each file must be 8 MB or smaller.");return}const data=await readFile(file);setForm(current=>({...current,documents:{...current.documents,[key]:{name:file.name,type:file.type,data}}}))}
 async function submit(){setError("");const finalModel=form.modelNotListed?form.manualModel.trim():form.carModel.trim();const finalType=form.modelNotListed?form.manualVehicleType.trim():form.vehicleType.trim();if(!form.name.trim()||!form.mobile.trim()||!form.address.trim()||!form.carPlate.trim()){setError("Full name, mobile number, address and vehicle plate are required.");return}if(!finalModel||!finalType){setError("Select a vehicle model or enter the unlisted model and vehicle type.");return}if(missing.length){setError(`Please upload: ${missing.join(", ")}.`);return}if(!form.consent){setError("Please accept the declaration before submitting.");return}setBusy(true);try{const payload={...form,carModel:finalModel,vehicleType:finalType};const response=await fetch("/api/public/driver-applications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message||"Submission failed");setResult(data)}catch(caught){setError(caught instanceof Error?caught.message:String(caught))}finally{setBusy(false)}}
 if(result)return <main className="signup-shell"><section className="signup-card success"><h1>Application submitted</h1><p>Your application reference is <strong>{result.applicationId}</strong>.</p><p>Status: <strong>Pending Review</strong>. After approval, the administrator will create your account and provide the login details manually.</p></section></main>;
 return <main className="signup-shell"><section className="signup-hero"><span>A3 GROUP · DRIVER ONBOARDING</span><h1>Driver Sign-Up</h1><p>Complete the form and upload the required documents. No NRIC, birthday or PHV company information is requested.</p></section>
 <section className="signup-card"><h2>1. Personal information</h2><div className="signup-grid"><label>Full name *<input value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>Mobile number *<input inputMode="tel" value={form.mobile} onChange={event=>setForm({...form,mobile:event.target.value})}/></label><label>Email (optional)<input type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label><label>Residential address *<input value={form.address} onChange={event=>setForm({...form,address:event.target.value})}/></label></div></section>
 <section className="signup-card"><h2>2. Vehicle information</h2><div className="signup-grid"><label className="model-search">Search vehicle model *<input value={query} disabled={form.modelNotListed} placeholder="Example: Toyota Alphard" onFocus={()=>setOpenResults(true)} onChange={event=>{setQuery(event.target.value);setOpenResults(true);setForm(current=>({...current,carModel:"",vehicleType:""}))}}/>{openResults&&!form.modelNotListed&&<div className="model-results">{matches.length?matches.map(model=><button type="button" key={model.id} onClick={()=>chooseModel(model)}><strong>{model.model}</strong><span>{model.vehicleType}</span></button>):<div>No matching model. Select “Model not listed” below.</div>}</div>}</label><label>Vehicle type<input value={form.modelNotListed?form.manualVehicleType:form.vehicleType} readOnly={!form.modelNotListed} onChange={event=>setForm({...form,manualVehicleType:event.target.value})} placeholder="Automatically filled"/></label><label>Vehicle plate *<input value={form.carPlate} onChange={event=>setForm({...form,carPlate:event.target.value.toUpperCase()})}/></label><label className="checkline"><input type="checkbox" checked={form.modelNotListed} onChange={event=>{const checked=event.target.checked;setForm({...form,modelNotListed:checked,carModel:checked?"":form.carModel,vehicleType:checked?"":form.vehicleType});setOpenResults(false)}}/> My vehicle model is not listed</label>{form.modelNotListed&&<><label>Vehicle make and model *<input value={form.manualModel} onChange={event=>setForm({...form,manualModel:event.target.value})} placeholder="Enter make and model"/></label><label>Vehicle type *<input value={form.manualVehicleType} onChange={event=>setForm({...form,manualVehicleType:event.target.value})} placeholder="Example: 7 Seater"/></label></>}</div></section>
 <section className="signup-card"><h2>3. Documents</h2><p className="muted">Required documents are marked with *. Optional documents may be added now or later.</p><div className="upload-grid">{uploads.map(upload=><article className="upload-box" key={upload.key}><div><strong>{upload.label}{upload.required?" *":" (optional)"}</strong>{upload.example&&<img src={upload.example} alt={`${upload.label} example`}/>}<small>{form.documents[upload.key]?.name||"No file selected"}</small></div><label className="upload-button">{form.documents[upload.key]?"Replace":"Upload"}<input type="file" accept="image/*,.pdf" onChange={event=>choose(upload.key,event.target.files?.[0])}/></label>{form.documents[upload.key]&&<button type="button" onClick={()=>setForm(current=>({...current,documents:{...current.documents,[upload.key]:undefined}}))}>Remove</button>}</article>)}</div></section>
 <section className="signup-card"><h2>4. Payment information</h2><div className="signup-grid"><label>Bank name<input value={form.bankName} onChange={event=>setForm({...form,bankName:event.target.value})}/></label><label>Account name<input value={form.accountName} onChange={event=>setForm({...form,accountName:event.target.value})}/></label><label>Bank account number<input value={form.bankAccount} onChange={event=>setForm({...form,bankAccount:event.target.value})}/></label><label>PayNow (optional)<input value={form.paynow} onChange={event=>setForm({...form,paynow:event.target.value})}/></label></div></section>
 <section className="signup-card"><h2>5. Emergency contact</h2><div className="signup-grid"><label>Contact name<input value={form.emergencyName} onChange={event=>setForm({...form,emergencyName:event.target.value})}/></label><label>Relationship<input value={form.emergencyRelationship} onChange={event=>setForm({...form,emergencyRelationship:event.target.value})}/></label><label>Mobile number<input inputMode="tel" value={form.emergencyMobile} onChange={event=>setForm({...form,emergencyMobile:event.target.value})}/></label></div><label className="consent"><input type="checkbox" checked={form.consent} onChange={event=>setForm({...form,consent:event.target.checked})}/> I confirm that the information and documents submitted are accurate and consent to their use for driver onboarding.</label>{error&&<p className="error-box">{error}</p>}<button className="submit-button" disabled={busy} onClick={submit}>{busy?"Submitting…":"Submit application"}</button></section>
 <style jsx global>{`body{margin:0;background:#f3f5f8;color:#17212b;font-family:Inter,Arial,sans-serif}.signup-shell{max-width:980px;margin:auto;padding:24px 16px 60px}.signup-hero{padding:24px 4px}.signup-hero span{font-size:12px;font-weight:800;letter-spacing:.12em;color:#087f5b}.signup-hero h1{font-size:clamp(32px,7vw,54px);margin:8px 0}.signup-hero p{color:#667085;max-width:680px}.signup-card{background:#fff;border:1px solid #e4e7ec;border-radius:18px;padding:20px;margin:16px 0;box-shadow:0 6px 24px rgba(16,24,40,.05)}.signup-card h2{margin-top:0}.signup-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.signup-grid label{font-weight:700;font-size:14px;position:relative}.signup-grid input{box-sizing:border-box;width:100%;margin-top:7px;border:1px solid #d0d5dd;border-radius:10px;padding:13px;font-size:16px}.signup-grid input[readonly]{background:#f2f4f7;color:#475467}.model-results{position:absolute;z-index:10;left:0;right:0;top:100%;background:#fff;border:1px solid #d0d5dd;border-radius:12px;box-shadow:0 12px 24px rgba(16,24,40,.16);max-height:310px;overflow:auto}.model-results button{display:flex;width:100%;justify-content:space-between;gap:15px;border:0;border-bottom:1px solid #eef0f3;background:white;padding:13px;text-align:left}.model-results button:hover{background:#f0fdf4}.model-results span{color:#667085}.model-results div{padding:14px;color:#667085}.checkline{display:flex;gap:10px;align-items:center}.checkline input{width:auto;margin:0}.upload-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.upload-box{border:1px solid #dce1e8;border-radius:14px;padding:14px;display:flex;gap:10px;align-items:center;justify-content:space-between}.upload-box div{min-width:0}.upload-box img{display:block;width:130px;max-height:90px;object-fit:contain;margin:10px 0;background:#f8fafc;border-radius:8px}.upload-box small{display:block;color:#667085;overflow:hidden;text-overflow:ellipsis}.upload-button{background:#087f5b;color:#fff;padding:10px 13px;border-radius:10px;font-weight:800;white-space:nowrap}.upload-button input{display:none}.upload-box button{border:0;background:#fff0f0;color:#c92a2a;padding:8px;border-radius:8px}.consent{display:flex;gap:10px;margin:18px 0;align-items:flex-start}.submit-button{width:100%;border:0;border-radius:12px;background:#087f5b;color:white;font-weight:900;font-size:17px;padding:15px}.submit-button:disabled{opacity:.6}.error-box{background:#fff4e6;color:#c92a2a;padding:12px;border-radius:10px}.muted{color:#667085}.success{text-align:center;margin-top:15vh}@media(max-width:680px){.signup-grid,.upload-grid{grid-template-columns:1fr}.signup-card{padding:16px}.upload-box{align-items:flex-start;flex-wrap:wrap}.upload-box div{width:100%}.upload-box img{width:100%;max-height:150px}.submit-button{position:sticky;bottom:12px}}`}</style></main>
}
